### PR TITLE
Update WW3 for fix for MPI reproducibility 

### LINKED ISSUE #427: WW3 not reproducing for different number of pets
## Description
If you change the number of pets the WW3 model is using, the results do not reproduce the same answers as before.  For the wav-atm cases, just the restart file is different however, for the fully coupled case the output from the wave model, and the restarts are different.   This was discovered when trying to make a PR to put in the fix for the thread-safe issue, which is why that PR has not yet been submitted.  Details of the fixing this issue, since they are in WW3 will be in the WW3 issue that is related to this: https://github.com/NOAA-EMC/WW3/issues/317 

### To Reproduce:
Change the number of pets in a test with waves, the results will be different than before.

### LINKED ISSUE #822: WW3 1 deg grid update
## Description
Reduce the spectral resolution in the 1 deg and coarser grids for WW3 test cases.  

## Solution
Need new input directory with update grid inputs to reduce spectral resolution and we need to re-balance tests with these wave grids since fewer resources should then be required. 

## Alternatives
- none so far

## Related to
- no other issues as of now

### LINKED ISSUE #913: cpld_control_wave test does not have waves turned on -> OCN; run fails if waves->OCN is on
## Description

The ``cpld_control_wave`` test was added in PR #379 (6a4c307). At that time, it did not use the setting ``MOM6_USE_WAVES=True``. The basic test remained unchanged at PR #765 (4e7a72e) when it was updated to the P7 configuration and renamed ``cpld_control_wave_p7``.
 
Setting ``MOM6_USE_WAVES=True`` causes the ``cpld_control_wave_p7`` test to fail with a seg fault.

### To Reproduce:

Run the ``cpld_control_wave_p7`` from the current develop branch. The run succeeds. Examining the PET logs for the Ocn (eg. PET160) shows that none of the partitioned stokes drift components are connected as imports to the ocean. The ``INPUT/MOM_input`` setting for ``USE_WAVES`` is set to False.

Copy the run directory into a test directory and change the variable ``USE_WAVES`` to True. Submit the job. The PET160 log shows that Ocn is expecting the stokes drift components as imports (they are connected). However, the run fails with the following:

```
199: forrtl: severe (174): SIGSEGV, segmentation fault occurred
199: Image              PC                Routine            Line        Source
199: fv3.exe            000000000512812C  Unknown               Unknown  Unknown
199: libpthread-2.17.s  00002AC257F50630  Unknown               Unknown  Unknown
199: fv3.exe            0000000001D54926  w3iogomd_mp_calc_        4017  w3iogomd.F90
199: libiomp5.so        00002AC256660A43  __kmp_invoke_micr     Unknown  Unknown
199: libiomp5.so        00002AC2566242C6  __kmp_fork_call       Unknown  Unknown
199: libiomp5.so        00002AC2565E3BB0  __kmpc_fork_call      Unknown  Unknown
```

Run directories are located ```/scratch1/NCEPDEV/stmp2/Denise.Worthen/FV3_RT/wave_test_bug/turn_waves_on```

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [x] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

This PR updates WW3 for a fix to the MPI reproducibility issue (#427 https://github.com/NOAA-EMC/WW3/pull/518).  The issue was that if ice is updated throughout the run and you are using IC0 (which we are in UFS) points that become ice covered beyond a threshold are "deactivated" however, when using MPI, these points values were not being properly zero'd out as expected.  This has been fixed along with two other bug fixes (https://github.com/NOAA-EMC/WW3/pull/512 https://github.com/NOAA-EMC/WW3/pull/519) needed to run WW3 in debug mode (not completely finished or included in this PR, but these two required bug fixes are).  Answers will therefore change for wave tests which were effected by this bug (S2SW tests, HAFS tests with waves did not change answers).  The "cpld_bmark_mpi_p7" test was added to show that this bug was fixed as it is not apparent in the "cpld_control_wave_p7" test.  In addition to continue to test that WW3 is thread safe and passes some of the other tests, cpld_decomp_wave_p7, cpld_mpi_wave_p7, and cpld_2threads_wave_p7 were added.  

This PR also uses a new WW3 input directory which reduced the number of spectral points used in WW3 low resolution 1 deg grid  (#822) which in turn reduces the computational requirements for tests using the 1 deg grid.  Tests using this grid were profiled using ESMF on hera and resources were adjusted.  Additionally the ATMW tests were set-up to have machine dependent resources.   Any test using the 1 deg wave grid will have answer changes.   

A 5 deg grid and it's documentation is included in the new WW3 input that can be used for future low resolution tests. 
Lastly, the 1deg, 2deg and 5 deg tests have been updated to work for MOM6 coupling (issue #913), by making sure the namelist option: 
&OUTS USSP = 1, IUSSP = 3, STK_WN = 0.04, 0.110, 0.3305 /
was included in the appropriate ww3_grid.inp files. 

The new input that its required is currently staged on hera at: /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/input-data-20210930/WW3_input_data_20211113 (updated from original PR)

Co-authors: @aliabdolali @MatthewMasarik-NOAA

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
- fixes #427
- fixes #822
- fixes #913

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

This was tested in earlier versions on multiple platforms (dell, orion, gaea, hera.intel), with the most recent code a baseline was created and shown to match using hera.intel

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature: skip until oRTs can be updated to use S2SW
- [ ] CI: skip due to changes in this PR

## Dependencies

- waiting on https://github.com/NOAA-EMC/WW3/pull/521

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
The number of tests in this PR needs to be reduced. The current default cpld P7 test suite is for 3-components only because we could not turn waves on for the tested features (decomp, threading, restart). With the fixes for WW3, the existing cpld P7 test suite needs to be updated to include all 4 components. 

A separate 3-component test pair will need to be maintained only for restart reproducibility. The default_vars for the cpld_dflt should reflect the 4-component configuration, with only the 3-component c96mx100 configuration requiring a separate "non-wave" setting.

**Comment by JessicaMeixner-NOAA** [comment]
Would an acceptable alternative be to turn off the tests that the new tests could replace instead of changing the defaults, etc?

**Comment by DeniseWorthen** [comment]
The problem w/ that solution is that it implies the "default" is something other than a 4-component configuration.

**Comment by JessicaMeixner-NOAA** [comment]
If "cpld_control_wave_p7" becomes the default with all the default settings I'm assuming we rename this test to then be "cpld_control_p7" but "cpld_control_p7" still needs to be run as part of "cpld_restart_p7" what does "cpld_control_p7" then become?  

Or am I just changing the values within the tests and replacing "cpld_2threads_wave_p7" with "cpld_2threads_p7" (same for decomp)?

**Comment by DeniseWorthen** [comment]
I would suggest that, like the c192 and c384 test pairs, the non-wave, c96mx100 test that will be used for restart testing would be ``cpld_control_c96_p7`` and ``cpld_restart_c96_p7``. 

The default vars used for those tests would also be named in the same way as for the c192 and c384 cases: eg ``TASKS_cpl_c96`` 

All the tests currently in the ``cpld_control_p7`` set (decomp, etc) would keep the same name, but they would now have waves-on. 

The default vars should also be updated to make waves "on" to be the default. Those settings would then need to be explictly turned off in the test/restart pairs.

**Comment by junwang-noaa** [comment]
cpld_control_wave_p7 will become cpld_control_p7 with 4 components, and the cpld_control_p7 becomes the cpld_control_p7_nowav, the restart test cpld_restart_p7_nowav (current cpld_restart_p7) is associated with it.

File: tests/default_vars.sh [hunk 1]
```diff
@@ -23,13 +23,35 @@ elif [[ $MACHINE_ID = wcoss_dell_p3 ]]; then
...
-  TASKS_cpl_dflt_wwav=212; TPN_cpl_dflt_wwav=28; INPES_cpl_dflt_wwav=3; JNPES_cpl_dflt_wwav=8
+  TASKS_cpl_dflt_wwav=196; TPN_cpl_dflt_wwav=28; INPES_cpl_dflt_wwav=3; JNPES_cpl_dflt_wwav=8
   THRD_cpl_dflt_wwav=1; WPG_cpl_dflt_wwav=6;  MPB_cpl_dflt_wwav="0 143"; APB_cpl_dflt_wwav="0 149"
-  OPB_cpl_dflt_wwav="150 179"; IPB_cpl_dflt_wwav="180 191";  WPB_cpl_dflt_wwav="192 211"
+  OPB_cpl_dflt_wwav="150 169"; IPB_cpl_dflt_wwav="170 177"; WPB_cpl_dflt_wwav="178 195"  
+  NPROC_ICE_cpl_dflt_wwav=8
+
+  TASKS_cpl_thrd_wwav=120; TPN_cpl_thrd_wwav=14; INPES_cpl_thrd_wwav=3; JNPES_cpl_thrd_wwav=4
+  THRD_cpl_thrd_wwav=2; WPG_cpl_thrd_wwav=6;  MPB_cpl_thrd_wwav="0 71"; APB_cpl_thrd_wwav="0 77"
+  OPB_cpl_thrd_wwav="78 97"; IPB_cpl_thrd_wwav="98 107"; WPB_cpl_thrd_wwav="108 119"
```
Comment (junwang-noaa) [inline tests/default_vars.sh]: OCN is still taking 20 tasks, does this mean OCN does not have threading turned on?

Comment (JessicaMeixner-NOAA) [reply tests/default_vars.sh]: @jiandewang can you comment on this question from Jun about MOM6 threading. 

@junwang-noaa there is about to be a fairly large update to this PR based on requests for changes, FYI.  Just doing the final testing now.

Comment (jiandewang) [reply tests/default_vars.sh]: @junwang-noaa threading in OCN won't gain speed, thus we are not using this

**Comment by JessicaMeixner-NOAA** [comment]
This PR has now been updated to reduce the number of tests and have waves included in the coupled defaults.   @DeniseWorthen and @junwang-noaa I believe this is to your specifications.  Let me know if I misunderstood anything. 

We will also be updating the WW3 submodule pointer here soon to include an update for jet compilation flags.

**Comment by DeniseWorthen** [comment]
Why are all the ``NPROC_ICE_ice`` settings required in ``default_vars``? They all look identical except for two settings on dell-p3.

**Comment by JessicaMeixner-NOAA** [comment]
> Why are all the `NPROC_ICE_ice` settings required in `default_vars`? They all look identical except for two settings on dell-p3.

By explicitly setting this value it can 1. be different for different platforms and 2. can be straightforward for updating that number of pets in the future.   I think I had originally updated this value a little more than in this end product, but I think keeping it and that future flexibility could be nice.

**Comment by DeniseWorthen** [comment]
If the desire is flexibility (different on different platforms), that argument could be made for any component. Ice actually seems like the least likely component to want to vary in this way, since it is generally thought to be the "cheapest". 

We have talked about setting a default tasks for each resolution and having the PE bounds calculated automatically. But setting nproc_ice still requires you to manually edit the PE bounds so I don't think I see the usefulness. It just means you have to change two things instead of one for each platform and test.

**Comment by JessicaMeixner-NOAA** [comment]
Yes, the ice component is generally the cheapest, which is why it was also used at times to take a few processors from to make the full pet count use an entire node and not just a few more pets on an additional node.   If these extra NPROC_ICE variables are desired to be removed, it will take me another day or so to re-do the profiling on hera with the desired number of tasks for ice and then based on that re-do the counts for other components to either keep the same total number of tasks, etc.  Just let me know if that work is required.

**Comment by DeniseWorthen** [comment]
I can see the point of using it to make up a full node. 

In ``cpld_bmark_p7`` ,  you are still setting NPROC_ICE to 48; there is no ``NPROC_ICE_cpl_bmrk`` in default_vars.

File: tests/tests/cpld_control_c192_p7 [hunk 2]
```diff
@@ -122,4 +122,11 @@ export FNVMXC="'C192.vegetation_greenness.tileX.nc'"
 export FNSLPC="'C192.slope_type.tileX.nc'"
 export FNABSC="'C192.maximum_snow_albedo.tileX.nc'"
 
+export CPLWAV=.false.
+export CPLWAV2ATM=.false.
+export MOM6_USE_WAVES=False
+
+export NEMS_CONFIGURE=nems.configure.cpld.IN
+
+
```
Comment (DeniseWorthen) [inline tests/tests/cpld_control_c192_p7]: remove extra blank line

File: tests/tests/cpld_control_c96_p7 [hunk 3]
```diff
@@ -0,0 +1,89 @@
+#
+#  cpld_control C96 restart P7 test
```
Comment (DeniseWorthen) [inline tests/tests/cpld_control_c96_p7]: remove 'restart'. This is the control test.

File: tests/tests/cpld_debug_p7 [hunk 4]
```diff
@@ -63,4 +63,28 @@ export FHMAX=6
...
+export ocn_petlist_bounds=$OPB_cpl_c96
+export ice_petlist_bounds=$IPB_cpl_c96
+
+export CPLWAV=.false.
+export CPLWAV2ATM=.false.
+export MOM6_USE_WAVES=False
+
+export NEMS_CONFIGURE=nems.configure.cpld.IN
+
+
```
Comment (DeniseWorthen) [inline tests/tests/cpld_debug_p7]: another extra blank line

File: tests/rt.conf [hunk 5]
```diff
@@ -3,23 +3,25 @@
...
 RUN     | cpld_2threads_p7                                                                                                        | - wcoss_cray                            |     |
 RUN     | cpld_decomp_p7                                                                                                          | - wcoss_cray jet.intel                  |     |
-# Waves on
-RUN     | cpld_control_wave_p7                                                                                                    | - wcoss_cray                            | fv3 |
+RUN     | cpld_mpi_p7                                                                                                             | - wcoss_cray                            |     |
+
+RUN     | cpld_bmark_p7                                                                                                           | - wcoss_cray                            | fv3 |
+RUN     | cpld_bmark_mpi_p7                                                                                                       | - wcoss_cray                            |     |
```
Comment (DeniseWorthen) [inline tests/rt.conf:12]: Why do we need an mpi test for both the default and bmark resolutions?

File: tests/tests/control_c384gdas_wav [hunk 6]
```diff
@@ -54,33 +54,23 @@ export LIST_FILES="sfcf000.nc \
...
-export INPES=6
-export JNPES=8
-export WRITE_GROUP=1
-export WRTTASK_PER_GROUP=24
 export FHMAX=9
 export NPZ=127
 export NPZP=128
 export NPX=385
 export NPY=385
 export DT_ATMOS=225
```
Comment (DeniseWorthen) [inline tests/tests/control_c384gdas_wav:62]: Does dt_atmos need to be 225 for this test? I know it is the current value but I wonder if it is actually required to be smaller than what we use for the coupled model.

File: tests/tests/cpld_mpi_p7 [hunk 7]
```diff
@@ -62,23 +62,25 @@ export_cpl
...
+export atm_petlist_bounds=$APB_cpl_mpi
+export ocn_petlist_bounds=$OPB_cpl_mpi
+export ice_petlist_bounds=$IPB_cpl_mpi
+export wav_petlist_bounds=$WPB_cpl_mpi
 
-export CPLWAV=.true.
-export CPLWAV2ATM=.true.
-export eps_imesh=2.5e-1
+export NPROC_ICE=$NPROC_ICE_cpl_mpi
+
```
Comment (DeniseWorthen) [inline tests/tests/cpld_mpi_p7]: extra line

File: tests/rt.conf (hunk 5 above)
Comment (JessicaMeixner-NOAA) [reply tests/rt.conf:12]: The "cpld_bmark_mpi_p7" test was added to show that this bug was fixed as it is not apparent in the "cpld_control_wave_p7" test.  Without this test we could not debug the stated issue or catch the problem.  That being said, it's not typical to have this test.  It can be removed if deemed necessary for the final PR.

File: tests/tests/control_c384gdas_wav (hunk 6 above)
Comment (JessicaMeixner-NOAA) [reply tests/tests/control_c384gdas_wav:62]: This is the same DT_ATMOS as in the atm-only case, which this test is based on: https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/tests/control_c384gdas#L64

**Comment by JessicaMeixner-NOAA** [comment]
> I can see the point of using it to make up a full node.
> 
> In `cpld_bmark_p7` , you are still setting NPROC_ICE to 48; there is no `NPROC_ICE_cpl_bmrk` in default_vars.

Updated!

File: tests/tests/cpld_2threads_p7 [hunk 8]
```diff
@@ -51,11 +51,16 @@ export LIST_FILES="sfcf024.tile1.nc \
...
-                   RESTART/ufs.cpld.cpl.r.2021-03-23-21600.nc"
+                   RESTART/iced.2021-03-22-64800.nc \
+                   RESTART/ufs.cpld.cpl.r.2021-03-22-64800.nc \
+                   20210322.180000.out_grd.glo_1deg \
+                   20210322.180000.out_pnt.points \
+                   20210322.180000.restart.glo_1deg"
 
 export_fv3
 export_cpl
+export FHMAX=12
```
Comment (junwang-noaa) [inline tests/tests/cpld_2threads_p7]: Is there any issue with 24 hr forecast length?

Comment (JessicaMeixner-NOAA) [reply tests/tests/cpld_2threads_p7]: The FHMAX=12 was in the old cpld_control_wave_p7 test and therefore carried over in the new cpld_control_p7 (with waves) and the associated tests.  This could certainly be changed if needed.

File: tests/default_vars.sh [hunk 9]
```diff
@@ -42,6 +61,12 @@ elif [[ $MACHINE_ID = wcoss_dell_p3 ]]; then
   TASKS_cpl_bmrk=560; TPN_cpl_bmrk=28; INPES_cpl_bmrk=6; JNPES_cpl_bmrk=8
   THRD_cpl_bmrk=1; WPG_cpl_bmrk=24; MPB_cpl_bmrk="0 287"; APB_cpl_bmrk="0 311"
   OPB_cpl_bmrk="312 431"; IPB_cpl_bmrk="432 479"; WPB_cpl_bmrk="480 559"
+  NPROC_ICE_cpl_bmrk=48
+
+  TASKS_cpl_bmrk_mpi=600; TPN_cpl_bmrk_mpi=40; INPES_cpl_bmrk_mpi=6; JNPES_cpl_bmrk_mpi=8
```
Comment (junwang-noaa) [inline tests/default_vars.sh]: The cpl_bmrk_mpi test only has wave tasks changed. I am wondering which test, cpld_bmark_p7 or cpld_bmark_mpi_p7, has better load balance?

Comment (JessicaMeixner-NOAA) [reply tests/default_vars.sh]: In the end, I was simplifying the changes to narrow them to just WW3 --- as that was the focus of the debug.  If this test is left in, I can change other pet tasks if desired. 

I did not do any load balancing on the cpl benchmark test as the wave grid did not change.  I assumed it was load-balanced as is and the other was just for testing the wave MPI issues.

File: tests/tests/cpld_2threads_p7 (hunk 8 above)
Comment (DeniseWorthen) [reply tests/tests/cpld_2threads_p7]: I thought you had perhaps changed FHMAX for timing reasons. Shorter tests are generally better, but 24h is our standard length. What do you think @junwang-noaa ?

Comment (JessicaMeixner-NOAA) [reply tests/tests/cpld_2threads_p7]: I think it was shortened in the cpld_control_wave_p7 test  a while ago for timing reasons; however, with the lighter WW3 grid, I don't think you'll have the timing issues for the reason it was changed to 12 (assuming my memory is correct, I didn't go back and look up the commit histories to confirm).

File: tests/rt.conf (hunk 5 above)
Comment (DeniseWorthen) [reply tests/rt.conf:12]: I read through the issue [317](https://github.com/NOAA-EMC/WW3/issues/317) and it isn't clear to me whether the explanation for why this didn't impact the low-resolution test but did impact the bmark configuration was found. I'm wondering if testing at low-resolution will be adequate?

Comment (JessicaMeixner-NOAA) [reply tests/rt.conf:12]: I believe we just got lucky that we do not see it on the C96 test case, essentially during the forecast time, we do not have a point that has enough ice growth during the forecast to become a "deactivated" sea-point and therefore trigger the issue. It was either a little luck, forecast length, IC date or function of resolution or all of the above.

File: tests/default_vars.sh [hunk 10]
```diff
@@ -42,6 +61,12 @@ elif [[ $MACHINE_ID = wcoss_dell_p3 ]]; then
...
+  THRD_cpl_bmrk_mpi=1; WPG_cpl_bmrk_mpi=24; MPB_cpl_bmrk_mpi="0 287"; APB_cpl_bmrk_mpi="0 311"
+  OPB_cpl_bmrk_mpi="312 431"; IPB_cpl_bmrk_mpi="432 479"; WPB_cpl_bmrk_mpi="480 599"
+  NPROC_ICE_cpl_bmrk_mpi=48
 
   TASKS_cpl_c192=288; TPN_cpl_c192=28; INPES_cpl_c192=4; JNPES_cpl_c192=8
   THRD_cpl_c192=1; WPG_cpl_c192=12;  MPB_cpl_c192="0 191"; APB_cpl_c192="0 203"
```
Comment (DeniseWorthen) [inline tests/default_vars.sh:73]: There are no settings for NPROC_ICE for any coupled c192 test or c384 test. If we're setting this in default_vars, we should be consistent.

Actually, I think that the issue of setting tasking in default_vars is out of control. It think we need to address it, but that is beyond the scope of this PR (Issue [320](https://github.com/ufs-community/ufs-weather-model/issues/320)).

File: tests/rt.conf (hunk 5 above)
Comment (DeniseWorthen) [reply tests/rt.conf:12]: So is the MPI test for both resolutions required, in your opinion?

File: tests/default_vars.sh (hunk 1 above)
Comment (junwang-noaa) [reply tests/default_vars.sh]: @jiandewang Do you mean using threads in OCN does not speed up the OCN computation or it does not speed up the total run time for the test?

File: tests/tests/cpld_2threads_p7 (hunk 8 above)
Comment (junwang-noaa) [reply tests/tests/cpld_2threads_p7]: Let's change it back to 24hrs, the 12hr forecast with the lighter ww3 grid now takes 2mins, so I don't think it would be an issue.

File: tests/rt.conf (hunk 5 above)
Comment (JessicaMeixner-NOAA) [reply tests/rt.conf:12]: I assumed I'd be asked to delete this test, but wanted to include it in the initial PR at the minimum to show we accomplished our goal and on the off-chance others thought it should stay.  Testings non C96 low resolution for the operational requirements is not a part of the regression tests and I understand we have to draw the line of when/where to add the tests.  I also think that if the operational requirements test was expanded to support running the higher resolution cases, that could be sufficient.   I think the biggest argument for inclusion of this would be that different physics are used in the ocean model, but that's never been enough to add one in the past, so I don't see the wave model's situation would pass that threshold either.

File: tests/default_vars.sh (hunk 10 above)
Comment (JessicaMeixner-NOAA) [reply tests/default_vars.sh:73]: I added NPROC_ICE for c192/c384 for consistency.

**Comment by JessicaMeixner-NOAA** [comment]
I believe I have addressed all the existing reviewers comments.  I'm recreating a baseline for the cpld tests that I changed to 24 hours and then will do another check to make sure I can replicate that baseline and do not have any other typos. I'll report back.

**Comment by JessicaMeixner-NOAA** [comment]
I believe I have addressed all the existing reviewers comments.  I'm recreating a baseline for the cpld tests that I changed to  FHMAX=24 hours and then will do another check to make sure I can replicate that baseline and do not have any other typos. I'll report back.

File: tests/rt.conf (hunk 5 above)
Comment (DeniseWorthen) [reply tests/rt.conf:12]: OK, thanks. I have the same feeling about the longer c192 test; we initially created a long test for a specific issue that Moorthi had reported, but we've continued to carry it. It is hard to drop a test once it has been added. 

I think it might beIt useful in this case to commit the test just to mark a place where we knew something was working.

**Comment by DeniseWorthen** [comment]
Thanks Jessica for all the changes.  I've been over them again and I see no remaining issues. Hopefully we can start the baselines/commit tomorrow after your final testing.

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA Thanks for addressing all the issues. The code changes look good to me. Please let us know how the hera testing is going, we will then sync the input data and start RT.

**Comment by junwang-noaa** [comment]
@MinsukJi-NOAA The cpld_control_p7 test is updated to include wave in this PR, CI test may need to be updated too.

**Comment by JessicaMeixner-NOAA** [comment]
The input data should be fine to sync...  Before running the full tests I'm trying to figure out one error, which I can't seem to  make sense of for cpld_control_p7: 

```
 Comparing RESTART/ufs.cpld.cpl.r.2021-03-23-21600.nc .........OK
 Comparing \ ............MISSING file
 Comparing 20210323.060000.out_grd.glo_1deg .........OK
```

The cpld_bmark_mpi_p7 test also just failed in my last round of testing but that was an srun hang error not actual model error.

**Comment by junwang-noaa** [comment]
It seems to me there might be some extra space in the file list for
comparison in cpld_control_p7 test?

**Comment by junwang-noaa** [comment]
Input data directory WW3_input_data_20211113 has been synced to all the platforms except Cheyenne. @aliabdolali Do we still need the WW3_input_data_20211112, if not, would you please delete it on Orion? Thanks.

**Comment by aliabdolali** [comment]
> Input data directory WW3_input_data_20211113 has been synced to all the platforms except Cheyenne. @aliabdolali Do we still need the WW3_input_data_20211112, if not, would you please delete it on Orion? Thanks.

Done,

**Comment by DeniseWorthen** [comment]
The WW3_input_data_20211113 has been added to input-data-20210930 on Cheyenne. 

On Hera, what is input-data-directory-20211115? Was that directory and/or develop-202112XX created in association with this PR?

**Comment by JessicaMeixner-NOAA** [comment]
I did not create the input-data-directory-20211115 or  develop-202112XX  directory.  I only created: 
/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/input-data-20210930/WW3_input_data_20211112 (Which is no longer needed, and Ali deleted the copy he made on orion)  and
/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/input-data-20210930/WW3_input_data_20211113

I do have a baseline on hera for intel here: /scratch1/NCEPDEV/stmp4/Jessica.Meixner/FV3_RT/Baseline20111115 if we want to copy that instead of re-creating. 

The regression tests passed last night after deleting an extra space in the cpld_control_p7 list of files to compare.

**Comment by JessicaMeixner-NOAA** [comment]
I updated the baseline date to today's date.

**Comment by junwang-noaa** [comment]
I created the input-data-20211015 on hera to remove the
diag_table/field_table in the input directory and use a central version of
CO2 data for all the RT tests

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
Repo location: /scratch1/NCEPDEV/nems/emc.nemspara/autort/pr/779412862/20211116144510/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/emc.nemspara/FV3_RT/rt_10187
Test cpld_control_p7 031 failed failed 
Test cpld_control_p7 031 failed in run_test failed 
Please make changes and add the following label back:
hera-gnu-BL

**Comment by JessicaMeixner-NOAA** [comment]
The failure for the gnu test is because I did not change to use the non-wave control test. That fix was pushed.

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA Will this PR also close Issue #427 ?

(EDIT) Sorry--I was confused by the two different titles on the issues vs PR. No answer required.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/779412862/20211116094511/ufs-weather-model
Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_16213
Baseline creation and move successful
Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/779412862/20211116105416/ufs-weather-model
Please manually delete: /glade/scratch/dtcufsrt/FV3_RT/rt_59390
Test cpld_bmark_mpi_p7 006 failed failed 
Test cpld_bmark_mpi_p7 006 failed in run_test failed 
Please make changes and add the following label back:
cheyenne-intel-BL

**Comment by DeniseWorthen** [comment]
I can't spot any obvious reason why the mpi_p7 test failed. I will try running separately.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: gaea
Compiler: intel
Job: BL
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/779412862/20211116163017/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_18590
Baseline creation and move successful
Repo location: /lustre/f2/pdata/ncep/emc.nemspara/autort/pr/779412862/20211116181538/ufs-weather-model
Please manually delete: /lustre/f2/scratch/emc.nemspara/FV3_RT/rt_47060
Test cpld_bmark_mpi_p7 006 failed in run_test failed 
Please make changes and add the following label back:
gaea-intel-BL

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen I think the Cheyenne and gaea test failed for the same reason gaea did: 
TPN_cpl_bmrk_mpi=40 not TPN_cpl_bmrk_mpi=36 for each.

**Comment by JessicaMeixner-NOAA** [comment]
> @DeniseWorthen I think the Cheyenne and gaea test failed for the same reason gaea did:
> TPN_cpl_bmrk_mpi=40 not TPN_cpl_bmrk_mpi=36 for each.

Although I just saw you pushed the Cheyenne log.  Should I make this change or not?

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA Please make the change for gaea only while I think about what to do w/ Cheyenne.

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen I made the update for gaea, sorry about the issue on both machines for this test.

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA This sort of error is all too easy w/ the number of platforms and number of tasking options w/ the coupled model. 

Please go ahead and update the Cheyenne tasks. I will re-run that test and make an empty commit that tests passes a second time.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/779412862/20211116163015/ufs-weather-model
Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_168928
Baseline creation and move successful
Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/779412862/20211116182248/ufs-weather-model
Please manually delete: /lfs4/HFIP/h-nems/emc.nemspara/RT_RUNDIRS/emc.nemspara/FV3_RT/rt_224474
Test cpld_bmark_mpi_p7 005 failed in run_test failed 
Please make changes and add the following label back:
jet-intel-BL

**Review by junwang-noaa — APPROVED** [review]

**Comment by JessicaMeixner-NOAA** [comment]
Are we waiting on the CI or should we go ahead and start the process of merging the WW3 submodule?

**Comment by DeniseWorthen** [comment]
@MinsukJi-NOAA CI will need an update in the next PR, is that right?

**Comment by MinsukJi-NOAA** [comment]
> @MinsukJi-NOAA CI will need an update in the next PR, is that right?

I suggest we skip CI for this PR; it will be fixed in the next PR.

**Comment by junwang-noaa** [comment]
Thanks, Minsuk. Let's start the commit process.

**Review by DeniseWorthen — APPROVED** [review]

**Review by jiandewang — APPROVED** [review]

**Comment by aliabdolali** [comment]
thank you all for doing this.
