### PR TITLE
Eliminate computational instability in the datm_cdeps_mx025_cfsr test on gaea, orion and wcoss_dell_p3

### LINKED ISSUE #621: Test "datm_cdeps_mx025_cfsr" cannot be run on 3 platforms
## Description
The regression test "datm_cdeps_mx025_cfsr" cannot be run successfully on gaea, orion, and wcoss_dell_p3. due to computational instability.

Error messages:
 47: WARNING from PE     7: Extreme surface sfc_state detected: i= 891 j=  79 lon= -77.375 lat= -73.088 x= -77.005 y= -73.088 D= 9.5000E+00 SSH= 1.2348E+02 SST=-1.2187E+00 SSS= 3.3722E+01 U-=-2.0210E+00 U+= 0.0000E+00 V-= 2.8061E+00 V+= 0.0000E+00
140: FATAL from PE   100: There were a total of         4 locations detected with extreme surface values!

## Solution
The dynamics time step in MOM6 needs to be reduced for this test.

### LINKED ISSUE #640: Update CDEPS to the latest develop branch
## Description

The develop branch of CDEPS has been updated to change the data component module names for UFS applications.
The develop branch also include the latest updates from NCAR.

## Solution
The CDEPS submodule in ufs-weather-model will be updated to use the latest develop branch of CDEPS.

### PR DESCRIPTION
**Pull request by binli2337**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] If new or updated input data is required by this PR, it is clearly stated in the text of the PR.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Eliminate computational instability in the datm_cdeps_mx025_cfsr test on Gaea, Orion and WCOSS_dell_p3. This PR also uses the latest develop branch of CDEPS and reduces the forecast time to 12 hours for the "datm_cdeps_mx025_cfsr" and "datm_cdeps_mx025_gefs" tests, so that the two tests can be done within 30 minutes.

### Issue(s) addressed

- fixes #621 
- fixes #640 

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [x] CI: b91a740

### CODE REVIEW

**Comment by junwang-noaa** [comment]
@binli2337 @uturuncoglu @aerorahul I am wondering if we can have PR#611 and PR#615 in Bin's PR so that he can test the CDEPS in UFS, Also Ufuk, can you confirm the HAFS is working with PR#611 and PR#615 and the latest CDEPS code?

**Comment by aerorahul** [comment]
@junwang-noaa 
I have no issues with merging #611 and #615 into #642.
Please let me know what I need to do.

**Comment by junwang-noaa** [comment]
@uturuncoglu  Can you confirm if HAFS is working with PR #611 and #615? Once you confirm, we will combine the #611/#615 with this PR and plan to get it committed in the next two weeks. If we did not hear from you, we have to assume you need more time to test PR #611 and #615 within HAFS, we will not put the two PRs in the commit queue planned for the next two weeks. Please let us know. Thanks

**Comment by uturuncoglu** [comment]
@junwang-noaa let me check. I am still trying to update HAFS and RTs for recent changes. I'll update you.

**Review by uturuncoglu — APPROVED** [review]
These changes seem fine. I am trying to test https://github.com/ufs-community/ufs-weather-model/pull/615 and https://github.com/ufs-community/ufs-weather-model/pull/611 at this point. I'll let you know when I run HAFS related configuration with the combination of those PRs.

**Comment by uturuncoglu** [comment]
@aerorahul Are you also plaining to merge `aerorahul:feature/link_full_cdeps` to this branch also? Then, I could only test this branch with HAFS data components.

**Comment by binli2337** [comment]
@junwang-noaa Should I also reduce the length of run from 24 hours to 12 hours for the following two runs in this PR?
1) datm_mx025_cfsr
2) datm_mx025_gefs

**Comment by junwang-noaa** [comment]
Yes, it looks to me it takes too long (40mins) to run.

File: tests/tests/datm_cdeps_mx025_cfsr [hunk 1]
```diff
@@ -10,15 +10,18 @@ export LIST_FILES="RESTART/MOM.res.nc \
...
+                   RESTART/iced.2011-10-01-43200.nc \
+                   RESTART/DATM_CFSR.cpl.r.2011-10-01-43200.nc"
 
 export_datm_cdeps
-export WLCLK=40
 export DATM_SRC="CFSR"
 export FILENAME_BASE='cfsr.'
 export IATM=1760
 export JATM=880
+export DT_DYNAM_MOM6='900'
```
Comment (DeniseWorthen) [inline tests/tests/datm_cdeps_mx025_cfsr]: I don't quite understand why the two tests aren't using the same configuration as the cpld_control_c384. In that case, the default timesteps are set for the 1deg case in default_vars. But for the 1/4deg case, we re-set the timesteps like so:

export DT_DYNAM_MOM6='900'
export DT_THERM_MOM6='1800'
export CPL_SLOW=${DT_THERM_MOM6}
export CPL_FAST=${DT_ATMOS} 

It seems you'd still be using the 1deg settings (3600s) for the CPL_SLOW and the DT_THERM_MOM6.

Comment (binli2337) [reply tests/tests/datm_cdeps_mx025_cfsr]: @DeniseWorthen @junwang-noaa:  I will update the following 4 tests so that the same DT_THERM_MOM6 (=900) and DT_DYNAM_MOM6(=1800) are used:

1. datm_mx025_cfsr
2. datm_mx025_gefs
3. datm_cdeps_mx025_cfsr
4. datm_cdeps_mx025_gefs

**Comment by uturuncoglu** [comment]
@junwang-noaa @binli2337 I run the data ocean RTs under HAFS and both of them is failed. I am not sure the root of the failure at this point but something is causing answer change in those configurations. I'll keep you updated if I find anything.

**Comment by uturuncoglu** [comment]
BTW, I check the cases of the components FV3, HYCOM, CMEPS and CDEPS and they seems fine. I could checkout those components again and try.

**Comment by junwang-noaa** [comment]
@uturuncoglu Thanks for the testing. @binli2337 have you run RT with your branch? Is there any issue with it?

**Comment by uturuncoglu** [comment]
@junwang-noaa I tested again by using exact version of CMEPS, CDEPS, FV3 and HYCOM that works under new model and it is still failing. I also checked the files with NCAR's cprnc command and files are still different.

```
SUMMARY of cprnc:
 A total number of    147 fields were compared
          of which    133 had non-zero differences
               and     11 had differences in fill patterns
               and      0 had different dimension sizes
 A total number of      0 fields could not be analyzed
 A total number of      0 fields on file 1 were not found on file 2.
 A total number of      0 fields on file 2 were not found on file 1.
  diff_test: the two files seem to be DIFFERENT 
```

Maybe 32bit option is not passing correctly to the FV3. I could not see any CPP flag related with 32bit that is passed to FV3. I am not sure this is the issue or not but it might worth to check it.

**Comment by binli2337** [comment]
@junwang-noaa There are no issues in my RT runs.

File: tests/compile.sh [hunk 2]
```diff
@@ -109,51 +89,40 @@ fi
...
 set +ex
-TEST=$( echo $MAKE_OPT | grep -e "SUITES=" )
+TEST=$( echo $MAKE_OPT | grep -e "-DCCPP_SUITES=" )
 if [[ $? -eq 0 ]]; then
-  CCPP_SUITES=$( echo $MAKE_OPT | sed 's/.*SUITES=//' | sed 's/ .*//' )
-  echo "Compiling suites ${CCPP_SUITES}"
+  SUITES=$( echo $MAKE_OPT | sed 's/.*-DCCPP_SUITES=//' | sed 's/ .*//' )
+  echo "Compiling suites ${SUITES}"
 fi
 set -ex
```
Comment (DusanJovic-NOAA) [inline tests/compile.sh:112]: I do not see where `SUITES` is used, other than in `echo`.

File: tests/compile.sh [hunk 3]
```diff
@@ -162,13 +131,12 @@ fi
 export BUILD_VERBOSE=1
 export BUILD_DIR
 export BUILD_JOBS
-export CCPP_SUITES
```
Comment (DusanJovic-NOAA) [inline tests/compile.sh:165]: If `CCPP_SUITES` is removed here it should also be removed from `build.sh`, and documentation (wiki) updated.

**Comment by uturuncoglu** [comment]
@binli2337 @junwang-noaa i am still investigating the issue in HAFS. I'll let you know when I have any clue.

**Comment by MinsukJi-NOAA** [comment]
@binli2337 could you please make these changes to tests/utest.bld to address the failed CI tests?
```
diff --git a/tests/utest.bld b/tests/utest.bld
index 7a8eade..9f868ee 100644
--- a/tests/utest.bld
+++ b/tests/utest.bld
@@ -1,10 +1,9 @@
-control                           | APP=ATM SUITES=FV3_GFS_v16
-control_wrtGauss_netcdf_parallel  | APP=ATM SUITES=FV3_GFS_v16
-control_stochy                    | APP=ATM SUITES=FV3_GFS_v16
-control_ca                        | APP=ATM SUITES=FV3_GFS_v16
-control_lheatstrg                 | APP=ATM SUITES=FV3_GFS_v16
-control_multigases                | APP=ATM SUITES=FV3_GFS_v16_fv3wam 32BIT=Y MULTI_GASES=Y REPRO=Y
-control_csawmg                    | APP=ATM SUITES=FV3_GFS_v16_csawmg
-control_flake                     | APP=ATM SUITES=FV3_GFS_v16_flake
-regional_control                  | APP=ATM SUITES=FV3_GFS_v15_thompson_mynn 32BIT=Y
-cpld_control                      | APP=S2S SUITES=FV3_GFS_2017_coupled,FV3_GFS_2017_satmedmf_coupled,FV3_GFS_v15p2_coupled,FV3_GFS_v16_coupled,FV3_GFS_v16_couplednsst
+control                           | -DAPP=ATM -DCCPP_SUITES=FV3_GFS_v16
+control_wrtGauss_netcdf_parallel  | -DAPP=ATM -DCCPP_SUITES=FV3_GFS_v16
+control_stochy                    | -DAPP=ATM -DCCPP_SUITES=FV3_GFS_v16
+control_ca                        | -DAPP=ATM -DCCPP_SUITES=FV3_GFS_v16
+control_lheatstrg                 | -DAPP=ATM -DCCPP_SUITES=FV3_GFS_v16
+control_csawmg                    | -DAPP=ATM -DCCPP_SUITES=FV3_GFS_v16_csawmg
+control_flake                     | -DAPP=ATM -DCCPP_SUITES=FV3_GFS_v16_flake
+regional_control                  | -DAPP=ATM -DCCPP_SUITES=FV3_GFS_v15_thompson_mynn,FV3_GFS_v15_thompson_mynn_RRTMGP -D32BIT=ON
+cpld_control                      | -DAPP=S2S -DCCPP_SUITES=FV3_GFS_2017_coupled,FV3_GFS_v15p2_coupled,FV3_GFS_v16_coupled,FV3_GFS_v16_couplednsst
```

**Comment by uturuncoglu** [comment]
@junwang-noaa @binli2337 i tested the modifications. The DATM (ERA5) configuration under HAFS passes without any issue.  I also tested DOCN configurations and they are not bit-to-bit and tests are failing. So, maybe the issue is in FV3 side. I am seeing `Baseline Change` tag in this PR. What is the source of the baseline change? @binli2337 you said that RTs are fine but since there is a baseline change comment in this PR, you need to create baselines from scratch. Right? So, RT could not be fine unless you create the baselines. Anyway, maybe it is fine to see baseline change but I need to know the source of it.

**Comment by DeniseWorthen** [comment]
@uturuncoglu I believe the baselines will change in this case for two reasons. One, the forecast hour is shorter (to reduce the wall clock time) but also the timesteps for MOM6 have changed.

**Comment by uturuncoglu** [comment]
@DeniseWorthen i am not expecting any change since I am testing it under hafs without mom6. Also, I kept fv3 version same since hafs has specific ccpp suites that is not exist in Ufs develop. At this point I am not sure about this PR and needs to be delayed until we know the underlying issue

**Comment by uturuncoglu** [comment]
@DeniseWorthen the fv3 configuration is also same in my case

**Comment by DeniseWorthen** [comment]
@binli2337 Would you please confirm that this PR can be merged w/o harm to the hafs project? I am not sure of what the issues are but I assume you are in communication w/ Ufuk about this PR.

**Review by uturuncoglu — CHANGES_REQUESTED** [review]
@binli2337 @junwang-noaa I also run RT for HAFS standalone regional FV3 configuration and that also did not pass. So, it seems that the issue related with the FV3 not coupling and since the FV3 version is fixed (i am using same version with feature/hafs_couplehycom_cdeps branch under HAFS) and it was passing without any issue. I am suspecting a build time issue at this point. So, we need to investigate it further. Please let me know if you know anything that could lead to answer change such as change in compiler version etc.

**Comment by BinLiu-NOAA** [comment]
> @binli2337 @junwang-noaa I also run RT for HAFS standalone regional FV3 configuration and that also did not pass. So, it seems that the issue related with the FV3 not coupling and since the FV3 version is fixed (i am using same version with feature/hafs_couplehycom_cdeps branch under HAFS) and it was passing without any issue. I am suspecting a build time issue at this point. So, we need to investigate it further. Please let me know if you know anything that could lead to answer change such as change in compiler version etc.

@uturuncoglu When you say FV3 standalone RT did not pass here, did the build fail, the run fail to run, or just the forecast produce different results? If it is the last situation (producing different results), then that might not be a big concern here, since the fetaure/hafs_couplehycom_cdeps is somewhat (~2 months) behind the develop branch.

**Comment by MinsukJi-NOAA** [comment]
@binli2337 , please replace 32BIT=Y with -D32BIT=ON in utest.bld
```
+regional_control | -DAPP=ATM -DCCPP_SUITES=FV3_GFS_v15_thompson_mynn,FV3_GFS_v15_thompson_mynn_RRTMGP -D32BIT=ON
```

**Comment by binli2337** [comment]
New baseline directories need to be created for the following 4 data atmosphere tests due to shorter forecast time and reduced ocean dynamics time step:
datm_mx025_cfsr
datm_mx025_gefs
datm_cdeps_mx025_cfsr
datm_cdeps_mx025_gefs

New baseline directories also need to be created for the following tests on wcoss_phase3:
control_wrtGauss_netcdf_parallel_debug
control_wrtGauss_netcdf_parallel
regional_quilt_netcdf_parallel
regional_control
regional_restart
regional_control_debug
regional_quilt_hafs
regional_quilt
regional_quilt_RRTMGP

After new baseline results are created on wcoss_phase3, the following 3 RT tests cannot reproduce the baseline results:
control_wrtGauss_netcdf_parallel_debug
control_wrtGauss_netcdf_parallel
regional_quilt_netcdf_parallel

**Comment by binli2337** [comment]
@MinsukJi-NOAA It is done. Thanks!

**Comment by binli2337** [comment]
@uturuncoglu @junwang-noaa The following tests failed only on wcoss_phase3. The issue might be related to how netcdf library is installed on different platforms:
control_wrtGauss_netcdf_parallel_debug
control_wrtGauss_netcdf_parallel
regional_quilt_netcdf_parallel

**Comment by uturuncoglu** [comment]
@binli2337 HAFS stand-alone regional fv3 test runs but answer changes.

**Comment by uturuncoglu** [comment]
@binli2337 I am not sure netcdf change could lead to answer change. I could compare the module files and try to run the case again with old modules to see what happens.

**Comment by uturuncoglu** [comment]
@binli2337 @junwang-noaa i think having HAFS related RTS in UFS level needs to be priority to catch these issues quickly. Since model is enclosing too fast it is hard to test it with HAFS with this way.

**Comment by binli2337** [comment]
@uturuncoglu The plan is to merge the updates from this PR to the develop branch today. Please let @junwang-noaa and @DusanJovic-NOAA know if you have any questions or concerns.

**Review by DusanJovic-NOAA — APPROVED** [review]

File: tests/compile.sh (hunk 3 above)
Comment (aerorahul) [reply tests/compile.sh:165]: @binli2337 
Please update `build.sh` and remove any and all references to `CCPP_SUITES` from `build.sh`.

**Comment by uturuncoglu** [comment]
@binli2337 @junwang-noaa @DusanJovic-NOAA @BinLiu-NOAA My main concern is to have answer change in HAFS side without knowing the source of it. At this point, the decision is yours. If you still plain to merge it, that is fine but we need to create baselines in HAFS side again. @BinLiu-NOAA let me know what do you think? We were plaining to sync support/HAFS before Friday after all PRs merged. Are you fine with the possible answer change that is caused with this PR?

File: tests/compile.sh [hunk 4]
```diff
@@ -109,51 +89,40 @@ fi
...
-    echo "MAKE_OPT = ${MAKE_OPT}"
-    CMAKE_FLAGS="${CMAKE_FLAGS} -DAPP=ATM"
-fi
 
-if [[ "${MAKE_OPT}" == *"APP=S2SW"* ]]; then
-    CMAKE_FLAGS="${CMAKE_FLAGS} -DAPP=S2SW -DMOM6SOLO=ON"
-elif [[ "${MAKE_OPT}" == *"APP=S2S"* ]]; then
-    CMAKE_FLAGS="${CMAKE_FLAGS} -DAPP=S2S -DMOM6SOLO=ON"
+if [[ "${MAKE_OPT}" == *"-DAPP=S2S"* ]]; then
+    CMAKE_FLAGS="${CMAKE_FLAGS} -DMOM6SOLO=ON"
```
Comment (aerorahul) [inline tests/compile.sh]:
```suggestion
    CMAKE_FLAGS+=" -DMOM6SOLO=ON"
```

File: tests/compile.sh [hunk 5]
```diff
@@ -109,51 +89,40 @@ fi
...
 fi
 
-if [[ "${MAKE_OPT}" == *"APP=NG-GODAS-NEMSDATM"* ]]; then
-    CMAKE_FLAGS="${CMAKE_FLAGS} -DAPP=NG-GODAS-NEMSDATM"
-elif [[ "${MAKE_OPT}" == *"APP=NG-GODAS"* ]]; then
-    CMAKE_FLAGS="${CMAKE_FLAGS} -DAPP=NG-GODAS"
+if [[ "${MAKE_OPT}" == *"-DAPP=NG-GODAS"* ]]; then
+    CMAKE_FLAGS="${CMAKE_FLAGS} -DMOM6SOLO=ON"
```
Comment (aerorahul) [inline tests/compile.sh]:
```suggestion
    CMAKE_FLAGS+=" -DMOM6SOLO=ON"
```

File: tests/compile.sh (hunk 2 above)
Comment (aerorahul) [reply tests/compile.sh:112]: I don't see this posing an issue.

**Review by aerorahul — DISMISSED** [review]
A few minor cosmetic changes.
I don't see a need to rerun the regression tests.

File: tests/tests/datm_cdeps_mx025_cfsr [hunk 6]
```diff
@@ -10,15 +10,20 @@ export LIST_FILES="RESTART/MOM.res.nc \
...
 export DATM_SRC="CFSR"
 export FILENAME_BASE='cfsr.'
 export IATM=1760
 export JATM=880
+export DAYS="0.5"
+export FHMAX=12
+export RESTART_N=${FHMAX}
+export DT_DYNAM_MOM6='900'
+export DT_THERM_MOM6='1800'
+export CPL_SLOW=${DT_THERM_MOM6}
```
Comment (DeniseWorthen) [inline tests/tests/datm_cdeps_mx025_cfsr]: Since you've reset the variable ``CPL_SLOW``, you also need to reset the variable ``export coupling_interval_slow_sec=${CPL_SLOW}`` in the test to have it take effect in ``nems.configure.datm.IN``, otherwise it the original (default=3600s) value will be used. This will impact all the mx025 tests where you changed the MOM timesteps.

I just tested this on Cheyenne in the ``datm_mx025_cfsr`` test;  the nems.configure for it shows:

```
runSeq::
@3600
   MED med_phases_prep_ocn_avg
   MED -> OCN :remapMethod=redist
   OCN
   @900
     MED med_phases_prep_ice
     MED -> ICE :remapMethod=redist
```

**Review by DeniseWorthen — APPROVED** [review]

File: tests/tests/datm_cdeps_mx025_cfsr (hunk 6 above)
Comment (binli2337) [reply tests/tests/datm_cdeps_mx025_cfsr]: @DeniseWorthen The line "export CPL_SLOW=${DT_THERM_MOM6}" will be removed from the following 4 tests:
datm_mx025_cfsr
datm_mx025_gefs
datm_cdeps_mx025_cfsr
datm_cdeps_mx025_gefs

In above 4 tests, 
coupling_interval_slow_sec=3600 seconds
coupling_interval_fast_sec=900 seconds
DT_DYNAM_MOM6=900 seconds (ocean dynamics time step)
DT_THERM_MOM6=1800 seconds (ocean thermodynamic time step)

After the changes, the 4 tests passed RT tests on wcoss_phase3. Thanks for discovering the issues.

Comment (DeniseWorthen) [reply tests/tests/datm_cdeps_mx025_cfsr]: I don't believe that is the correct solution. If the slow coupling only occurs every hour, then MOM6 will take two internal thermodynamic timesteps before it gets "updated" forcing from the atm/ice.

Comment (binli2337) [reply tests/tests/datm_cdeps_mx025_cfsr]: A better solution will be used in a future PR. An issue will be submitted. Thanks!

Comment (DeniseWorthen) [reply tests/tests/datm_cdeps_mx025_cfsr]: OK, thanks. I think I mis-understood your original comment then.

File: tests/compile.sh (hunk 4 above)
Comment (binli2337) [reply tests/compile.sh]: Done.

File: tests/compile.sh (hunk 5 above)
Comment (binli2337) [reply tests/compile.sh]: Done.

File: tests/compile.sh (hunk 3 above)
Comment (binli2337) [reply tests/compile.sh:165]: Done.
