### PR TITLE
CMAKE for WW3 

### LINKED ISSUE #550: WW3 does not support concurrent builds
## Description

PR https://github.com/ufs-community/ufs-weather-model/pull/527 moved the coupled tests to the top of `rt.conf`, since the coupled tests take longest to wait tin the queue and to run.

This meant that both the CLDP+WAV compile job was running concurrently with the ATMW compile job - which led to compile errors.

Before this move, we were "lucky" in a sense that only ten builds can happen at the same time, and the two builds that involve WW3 are sufficiently far apart to not overlap.

### To Reproduce:

Run the two compile jobs that use WW3 at the same time.

## Solution

Improve the WW3 build to support clean out of source builds.

### LINKED ISSUE #1074: Integrate WW3 CMake build
## Description

A CMake build was recently added to WW3 and this build should be integrated in the UFS. This will significantly simplify the build because it will integrate directly into UFS with `add_subdirectory`.

This block of code:

https://github.com/ufs-community/ufs-weather-model/blob/34a5895b847f276335bd40f03321011d05d1b328/CMakeLists.txt#L157-L179

becomes:

```
  set(SWITCH "multi_esmf")
  set(MULTI_ESMF ON)
  add_subdirectory(WW3)
```

And linking the library is:

```
target_link_libraries(ufs PUBLIC WW3::WW3)
```

A working branch can be found here:  https://github.com/jessicameixner-noaa/ufs-weather-model/tree/feature/ww3-cmake

@JessicaMeixner-NOAA did some Initial testing and tests pass, but there is an error on WCOSS-Dell related to #1072

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ ] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

This updates WW3 and it's build to be using CMAKE and also now allows for concurrent builds.  Note this is just updating the existing tests.  Any other added capabilities that CMAKE will allow for (such as debug) will be addressed in subsequent PRs.  No answers are expected to change.   

A description of the WW3 CMake build can be found at https://github.com/NOAA-EMC/WW3/pull/533 and in the [documentation](https://github.com/kgerheiser/WW3/blob/feature/cmake/model/README.md)

author: @kgerheiser   
- Huge thanks to Kyle for bringing this great capability to WW3! 

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes #550 
- fixes #1074

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

The wave tests were run on hera, orion, gaea and wcoss-dell. 

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on https://github.com/NOAA-EMC/WW3/pull/638

### CODE REVIEW

File: tests/rt_utils.sh [hunk 1]
```diff
@@ -514,11 +514,11 @@ EOF
...
-  if [[ ${MAKE_OPT^^} =~ "-DAPP=ATMW" ]] || [[ ${MAKE_OPT^^} =~ "-DAPP=S2SW" ]] || [[ ${MAKE_OPT^^} =~ "-DAPP=HAFSW" ]] || [[ ${MAKE_OPT^^} =~ "-DAPP=HAFS-ALL" ]] ; then
-    if [[ ${COMPILE_PREV_WW3_NR} != '' ]]; then
-      echo "    trigger compile_${COMPILE_PREV_WW3_NR} == complete"  >> ${ECFLOW_RUN}/${ECFLOW_SUITE}.def
-    fi
-  fi
+  #if [[ ${MAKE_OPT^^} =~ "-DAPP=ATMW" ]] || [[ ${MAKE_OPT^^} =~ "-DAPP=S2SW" ]] || [[ ${MAKE_OPT^^} =~ "-DAPP=HAFSW" ]] || [[ ${MAKE_OPT^^} =~ "-DAPP=HAFS-ALL" ]] ; then
+  #  if [[ ${COMPILE_PREV_WW3_NR} != '' ]]; then
+  #    echo "    trigger compile_${COMPILE_PREV_WW3_NR} == complete"  >> ${ECFLOW_RUN}/${ECFLOW_SUITE}.def
+  #  fi
+  #fi
```
Comment (DusanJovic-NOAA) [inline tests/rt_utils.sh]: Remove this entire block of commented code

File: tests/rt_utils.sh [hunk 2]
```diff
@@ -387,13 +387,13 @@ rocoto_create_compile_task() {
...
-  if [[ ${COMPILE_PREV_WW3_NR} != '' ]]; then
-      if [[ ${MAKE_OPT^^} =~ "-DAPP=ATMW" ]] || [[ ${MAKE_OPT^^} =~ "-DAPP=S2SW" ]] || [[ ${MAKE_OPT^^} =~ "-DAPP=HAFSW" ]] || [[ ${MAKE_OPT^^} =~ "-DAPP=HAFS-ALL" ]] ; then
-          DEP_STRING="<dependency><taskdep task=\"compile_${COMPILE_PREV_WW3_NR}\"/></dependency>"
-      fi
-  fi
+  #if [[ ${COMPILE_PREV_WW3_NR} != '' ]]; then
+  #    if [[ ${MAKE_OPT^^} =~ "-DAPP=ATMW" ]] || [[ ${MAKE_OPT^^} =~ "-DAPP=S2SW" ]] || [[ ${MAKE_OPT^^} =~ "-DAPP=HAFSW" ]] || [[ ${MAKE_OPT^^} =~ "-DAPP=HAFS-ALL" ]] ; then
+  #        DEP_STRING="<dependency><taskdep task=\"compile_${COMPILE_PREV_WW3_NR}\"/></dependency>"
+  #    fi
+  #fi
```
Comment (DusanJovic-NOAA) [inline tests/rt_utils.sh]: Delete commented code. `DEP_STRING` can also be removed from lines 391 and 422

File: CMakeLists.txt [hunk 3]
```diff
@@ -155,27 +155,10 @@ endif()
...
-  message("")
-
-  add_custom_target(ww3_nems
-    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/WW3/model/esmf
-    COMMAND ${CMAKE_BUILD_TOOL} WW3_PARCOMPN=4 WW3_COMP=${WW3_COMP} ww3_nemslibonly > ${CMAKE_CURRENT_BINARY_DIR}/ww3_make.log 2>&1)
-
-  set(WW3_LIBS ${CMAKE_CURRENT_SOURCE_DIR}/WW3/model/obj/libww3_multi_esmf.a)
+  # Set options for WW3 build
+  set(SWITCH "multi_esmf" CACHE STRING "Default to switch_multi_esmf")
+  set(MULTI_ESMF ON CACHE BOOL "Enable ESMF for WW3")
```
Comment (DusanJovic-NOAA) [inline CMakeLists.txt:160]: Why are these two variables cache variables? Are users allowed to change the value of `SWITCH` or turn `MULTI_ESMF` OFF?

Comment (kgerheiser) [reply CMakeLists.txt:160]: I put that there. I thought because they are CACHE options in WW3 that it should be cache here, but maybe that's not needed.

Comment (JessicaMeixner-NOAA) [reply CMakeLists.txt:160]: Yes, the value of switch could change.   Also, there will be a different cap so the MULTI_ESMF might be changed to a different option at some point in the near future.

File: tests/rt_utils.sh (hunk 2 above)
Comment (JessicaMeixner-NOAA) [reply tests/rt_utils.sh]: done

File: tests/rt_utils.sh (hunk 1 above)
Comment (JessicaMeixner-NOAA) [reply tests/rt_utils.sh]: done

File: CMakeLists.txt (hunk 3 above)
Comment (kgerheiser) [reply CMakeLists.txt:160]: It needs to be cache because in WW3 because the option is defined like 

`set(MULTI_ESMF OFF CACHE BOOL "Build ww3_multi_esmf library")`. 

If you just use `set(MULTI_ESMF ON)` then in WW3 the value will be overridden to off. If you set it as cache the value won't be overridden because there is no `FORCE`.

Comment (DusanJovic-NOAA) [reply CMakeLists.txt:160]: Thank you both for checking.

File: modulefiles/ufs_orion.intel [hunk 4]
```diff
@@ -8,7 +8,7 @@ module-whatis "loads UFS Model prerequisites for Orion/Intel"
 
 module load contrib noaatools
 
-module load cmake/3.18.1
+module load cmake/3.22.1
```
Comment (DeniseWorthen) [inline modulefiles/ufs_orion.intel:11]: Is there a minimum cmake version required? Cheyenne.gnu/intel is loading cmake/3.18.2. Are changes required there?

Comment (kgerheiser) [reply modulefiles/ufs_orion.intel:11]: WW3 requires 3.19

Comment (JessicaMeixner-NOAA) [reply modulefiles/ufs_orion.intel:11]: @DeniseWorthen is Cheyenne cmake/3.22.0  the correct version to switch to for the Cheyenne modules?  (That was the version you mentioned on the WW3 PR, I forgot to update it here).

Comment (DeniseWorthen) [reply modulefiles/ufs_orion.intel:11]: Cheyenne has cmake/3.22.0. Thanks.

Comment (JessicaMeixner-NOAA) [reply modulefiles/ufs_orion.intel:11]: Updated for Cheyenne

File: tests/rt_utils.sh [hunk 5]
```diff
@@ -387,13 +387,7 @@ rocoto_create_compile_task() {
...
   fi
 
-  # serialize WW3 builds. FIXME
-  DEP_STRING=""
-  if [[ ${COMPILE_PREV_WW3_NR} != '' ]]; then
-      if [[ ${MAKE_OPT^^} =~ "-DAPP=ATMW" ]] || [[ ${MAKE_OPT^^} =~ "-DAPP=S2SW" ]] || [[ ${MAKE_OPT^^} =~ "-DAPP=HAFSW" ]] || [[ ${MAKE_OPT^^} =~ "-DAPP=HAFS-ALL" ]] ; then
-          DEP_STRING="<dependency><taskdep task=\"compile_${COMPILE_PREV_WW3_NR}\"/></dependency>"
-      fi
-  fi
+  ## serialize WW3 builds. FIXME
```
Comment (DeniseWorthen) [inline tests/rt_utils.sh]: Can we remove this comment?

Comment (JessicaMeixner-NOAA) [reply tests/rt_utils.sh]: Removed.

Comment (DusanJovic-NOAA) [reply tests/rt_utils.sh]: If it's not too late for this PR, `COMPILE_PREV_WW3_NR` can also be removed from `rt.sh` and `opnReqTest`

Comment (JessicaMeixner-NOAA) [reply tests/rt_utils.sh]: @DusanJovic-NOAA would these be the proper removals: 

```
Jessica.Meixner@hfe10:/scratch2/NCEPDEV/climate/Jessica.Meixner/PR_WW3/ufs-cmake$ git diff 
diff --git a/tests/opnReqTest b/tests/opnReqTest
index 78e47ac8..28f32f72 100755
--- a/tests/opnReqTest
+++ b/tests/opnReqTest
@@ -531,7 +531,6 @@ mkdir -p ${RUNDIR_ROOT}
 if [[ $ECFLOW == true ]]; then
   ECFLOW_RUN=${PATHRT}/ecflow_opnReqTest_run
   ECFLOW_SUITE=opnreqtest_$$
-  COMPILE_PREV_WW3_NR=
   rm -rf ${ECFLOW_RUN}
   mkdir -p ${ECFLOW_RUN}/${ECFLOW_SUITE}
   cp head.h tail.h ${ECFLOW_RUN}
diff --git a/tests/rt.sh b/tests/rt.sh
index c5ab9a74..aabdc9a3 100755
--- a/tests/rt.sh
+++ b/tests/rt.sh
@@ -522,7 +522,6 @@ source default_vars.sh
 JOB_NR=0
 TEST_NR=0
 COMPILE_NR=0
-COMPILE_PREV_WW3_NR=''
 rm -f fail_test* fail_compile*
 
 export LOG_DIR=${PATHRT}/log_$MACHINE_ID
@@ -741,10 +740,6 @@ EOF
       BL_SUFFIX=""
     fi
 
-    if [[ ${MAKE_OPT^^} =~ "-DAPP=ATMW" ]] || [[ ${MAKE_OPT^^} =~ "-DAPP=S2SW" ]] || [[ ${MAKE_OPT^^} =~ "-DAPP=HAFSW" ]] || [[ ${MAKE_OPT^^} =~ "-DAPP=HAFS-ALL" ]] ; then
-       COMPILE_PREV_WW3_NR=${COMPILE_NR}
-    fi
-
     continue
 
   elif [[ $line == RUN* ]] ; then
```

Comment (DusanJovic-NOAA) [reply tests/rt_utils.sh]: Yes.

**Comment by DusanJovic-NOAA** [comment]
Thank you @kgerheiser and @JessicaMeixner-NOAA. This is great. Adding CMake support to WW3 will allow us to run parallel builds in regression testing and, I hope, substantially speed up testing.

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA Can you run baselines on wcoss cray/dell?

**Comment by JessicaMeixner-NOAA** [comment]
> @JessicaMeixner-NOAA Can you run baselines on wcoss cray/dell?

I've already started both.

File: modulefiles/ufs_orion.intel (hunk 4 above)
Comment (kgerheiser) [reply modulefiles/ufs_orion.intel:11]: Just a thought, but it might be wise to update the `cmake_minimum_required` in UFS to 3.19.

File: .gitmodules [hunk 6]
```diff
@@ -4,8 +4,9 @@
   branch = develop
 [submodule "WW3"]
   path = WW3
-  url = https://github.com/NOAA-EMC/WW3
-  branch = dev/ufs-weather-model
+  #url = https://github.com/NOAA-EMC/WW3
+  #branch = dev/ufs-weather-model
+  url = https://github.com/JessicaMeixner-NOAA/WW3
```
Comment (junwang-noaa) [inline .gitmodules]: @JessicaMeixner-NOAA Even though your develop branch is same as your sync-dev-to-ufs-20200308 (also the same as noaa emc ww3 develop branch as shown in your ww3 PR). But it looks to me your develop branch does not have the same history as the dev/ufs-weather-model, in other words your ww3 is not based on the top of the dev/ufs-weather-model branch, which makes the github version check fail. Is it intended to change dev/ufs-weather-model branch history?

Comment (JessicaMeixner-NOAA) [reply .gitmodules]: Unfortunately at some point the history of the dev/ufs-weather-model branch got messed up.  @aliabdolali and I  always make sure that the content of the dev/ufs-weather-model is what it should be but unfortunately so that the history of the ufs-weather-model stays there we can't delete the branch and start over with a clean history.  The WW3 develop branch still has a clean history though and at some point if we can make more frequent commits to ufs-weather-model with WW3 updates maybe we can move back to using the develop branch in the future.

Comment (junwang-noaa) [reply .gitmodules]: OK, I think the dev/ufs-weather-model history will be changed with your PR. If this is what you want to do, we will ignore the github version check error message.

**Comment by JessicaMeixner-NOAA** [comment]
Please let me know when you are ready for the WW3 submodule to be merged.

**Comment by JessicaMeixner-NOAA** [comment]
The WW3 PR has been updated: https://github.com/NOAA-EMC/WW3/pull/638 if this is acceptable I will restart the dell and cray tests. Please note the contents of WW3 has not changed.

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA Thanks for making the changes, the code changes look good. The github action repo check passed. Please start dell/cray tests.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: RT
[RT] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/874662617/20220315171512/ufs-weather-model
Please make changes and add the following label back: jet-intel-RT

**Comment by BrianCurtis-NOAA** [comment]
@junwang-noaa
> The github action repo check passed.

It looks like it failed.

**Comment by BrianCurtis-NOAA** [comment]
> @junwang-noaa
> 
> > The github action repo check passed.
> 
> It looks like it failed.

Nevermind. Clicked the wrong item.

**Comment by junwang-noaa** [comment]
@BrianCurtis-NOAA Please see: https://github.com/ufs-community/ufs-weather-model/actions/runs/1988148405. The check repo job finished successfully.

**Comment by DeniseWorthen** [comment]
It looks like there is still an issue w/ auto-rt and jet. I will run manually.

**Review by junwang-noaa — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
Cheyenne.intel had two failures:
1) hafs_regional_docn_oisst test which failed with MPT: shepherd terminated: r12i6n25.ib0.cheyenne.ucar.edu - job aborting
2) cpld_bmark_p8 which doesn't seem to have launched, although the run directory is present (no out, err). I see in run_007_cpld_bmark_p8.log the message 
```
++ [[ pbs = \p\b\s ]]
++ echo 'run_util.sh: interrupt_job qsub_id = 3289762'
run_util.sh: interrupt_job qsub_id = 3289762
++ qdel 3289762
+++ echo 'run_test.sh terminated PID=61003'
run_test.sh terminated PID=61003
```

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA All tests are complete. Please merge your WW3 PR and update the submodules. Thanks.

**Review by DeniseWorthen — APPROVED** [review]

File: modulefiles/ufs_orion.intel (hunk 4 above)
Comment (DeniseWorthen) [reply modulefiles/ufs_orion.intel:11]: @DusanJovic-NOAA Could you make this change in your PR (3.18->3.19):
https://github.com/ufs-community/ufs-weather-model/blob/10a616d328356cf99b36961a392eac65a3359db2/CMakeLists.txt#L1

Comment (DusanJovic-NOAA) [reply modulefiles/ufs_orion.intel:11]: Done.
