### PR TITLE
Re-work testing verification, fail file naming consistency, remove lsf support, simplify RT logs.

### LINKED ISSUE #1821: regression test logs do not clearly indicate when a test fails to run
## Description

The regression test logs contain for each test for example:

```
001 cpld_control_p8_mixedmode_intel failed in check_result
cpld_control_p8_mixedmode_intel 001 failed in run_test
```

However, if multiple tests fail, and are expected to fail, tests which did not actually run are difficult to catch in a long list of test failures. For example

```
001 cpld_control_p8_mixedmode_intel failed in check_result
cpld_control_p8_mixedmode_intel 001 failed in run_test
002 cpld_control_gfsv17_intel failed in check_result
cpld_control_gfsv17_intel 002 failed in run_test
003 cpld_control_p8_intel failed in check_result
cpld_control_p8_intel 003 failed in run_test
005 cpld_control_qr_p8_intel failed in check_result
cpld_control_qr_p8_intel 005 failed in run_test
007 cpld_2threads_p8_intel failed in check_result
cpld_2threads_p8_intel 007 failed in run_test
008 cpld_decomp_p8_intel failed in check_result
cpld_decomp_p8_intel 008 failed in run_test
009 cpld_mpi_p8_intel failed in check_result
cpld_mpi_p8_intel 009 failed in run_test
010 cpld_control_ciceC_p8_intel failed in check_result
cpld_control_ciceC_p8_intel 010 failed in run_test
011 cpld_control_c192_p8_intel failed in check_result
cpld_control_c192_p8_intel 011 failed in run_test
013 cpld_bmark_p8_intel failed in check_result
cpld_bmark_p8_intel 013 failed in run_test
015 cpld_control_noaero_p8_intel failed in check_result
cpld_control_noaero_p8_intel 015 failed in run_test
016 cpld_control_nowave_noaero_p8_intel failed in check_result
cpld_control_nowave_noaero_p8_intel 016 failed in run_test
017 cpld_debug_p8_intel failed in check_result
cpld_debug_p8_intel 017 failed in run_test
018 cpld_debug_noaero_p8_intel failed in check_result
cpld_debug_noaero_p8_intel 018 failed in run_test
020 cpld_control_c48_intel failed in check_result
cpld_control_c48_intel 020 failed in run_test
cpld_warmstart_c48_intel 021 failed in run_test
023 cpld_control_p8_faster_intel failed in check_result
cpld_control_p8_faster_intel 023 failed in run_test
024 cpld_control_pdlib_p8_intel failed in check_result
cpld_control_pdlib_p8_intel 024 failed in run_test
027 cpld_debug_pdlib_p8_intel failed in check_result
cpld_debug_pdlib_p8_intel 027 failed in run_test
134 hafs_regional_atm_ocn_intel failed in check_result
hafs_regional_atm_ocn_intel 134 failed in run_test
136 hafs_regional_atm_ocn_wav_intel failed in check_result
hafs_regional_atm_ocn_wav_intel 136 failed in run_test
hafs_regional_storm_following_1nest_atm_qr_intel 146 failed in run_test
151 hafs_regional_docn_intel failed in check_result
hafs_regional_docn_intel 151 failed in run_test
152 hafs_regional_docn_oisst_intel failed in check_result
hafs_regional_docn_oisst_intel 152 failed in run_test
234 cpld_control_p8_gnu failed in check_result
cpld_control_p8_gnu 234 failed in run_test
235 cpld_control_nowave_noaero_p8_gnu failed in check_result
cpld_control_nowave_noaero_p8_gnu 235 failed in run_test
236 cpld_debug_p8_gnu failed in check_result
cpld_debug_p8_gnu 236 failed in run_test
237 cpld_control_pdlib_p8_gnu failed in check_result
cpld_control_pdlib_p8_gnu 237 failed in run_test
238 cpld_debug_pdlib_p8_gnu failed in check_result
cpld_debug_pdlib_p8_gnu 238 failed in run_test
```

In this case, a single test ``cpld_warmstart_c48_intel``, failed to run at all. 

## Solution

Update the regression test logging function to allow the developer to easily spot tests which failed to run at all vs just tests which ran and failed. For example, in the above case:

```
FAILED COMPARISON TESTS:
....

FAILED RUN TESTS:

cpld_warmstart_c48_intel 021 failed to run
```

### LINKED ISSUE #2058: Re-work test verification and add pre-test option in rt.sh for developers to use in PR process.
## Description
There are a lot of pieces to putting a pull request together and the information that code management needs isn't always readily available and can take developers a long time to gather. The logs are overly verbose and don't provide developers a quick way to find what went wrong with their code changes.

## Solution
The logs should be more succinct. Having information on all file comparisons kept in the history of the repository seems overkill. Simplify the logs to provide information that all tests are pass/fail and provide a log for failed tests for developers to easily find out what went wrong.

## Ideas

- Creates a synopsis that clarifies: 
  - number of tests ran to completion (double checking all tests are run)
    - Listing all failed comparisons.
  - number of compilations ran to completion (double checking all compiles are run).
    - Listing all failed compiles.
- Write synopsis to RegressionTests_<machine>.log
- fail_test uses number while fail_compile uses compile name, changing fail_test to use test name.

## Extras
- The resulting PR will also need to adjust the PR template.

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description

This PR updates the rt.sh script:
- Makes fail_test and fail_compile files consistent in naming
- Created a new generate_log() function in rt.sh to allow for better control over the information logged after the full RT suite is finished.
  - Log outputs minimized to information that's important to track, and easier to read for developers.
  - Adds test_changes.list file for repository tracking of what tests are changed due to the changes in the PR.
  - Adds test_changes.list file for easy creation of new baselines specific to the PR using `rt.sh -b test_changes.out`.
- Ends support for lsf (queue system from old WCOSS systems)

### Commit Message

```
* UFSWM
  * Re-work test verification in rt.sh for developers to use in PR process. (Closes #2058)
  * fail_<test_number> file name upgraded to use compile/test name instead of number.
  * Regression test logs do not clearly indicate when a test fails to run. (Closes #1821)
  * New test_changes.list file:
    * Verification of what tests change for each PR.
    * Used with './rt.sh -c -b test_changes.list` to help create new baselines for each PR.
```

### Priority

* Normal

### UFSWM

* Closes #2058 
* Closes #1821

### Sub component Pull Requests

* None

### UFSWM Blocking Dependencies

* None

---
### Regression Test Changes (Please commit test_changes.list):

* None Expected

### Input data Changes

* None.

### Library Changes/Upgrades

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- [x] CI
- [x] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
A successful log is pushed to the repositoy  (RegressionTests_hera.log).
Here is a failed log:
```
====START OF HERA REGRESSION TESTING LOG====

UFSWM hash used in testing:
3ff6b3f27cae02855235f5dd4143dab9100f3cac

Submodule hashes used in testing:
 37cbb7d6840ae7515a9a8f0dfd4d89461b3396d1 AQM (v0.2.0-37-g37cbb7d)
 78b9504c0f7c537d7f143ca02e5eef62fb88e80e CDEPS-interface/CDEPS (cdeps0.6.3-30-g78b9504)
 620e48fe75d92aa607af7e21f2d8691baddd2851 CICE-interface/CICE (CICE6.0.0-445-g620e48f)
 dadb082291ce3487d8b5a8e191a0abe45b69c8af CMEPS-interface/CMEPS (cmeps0.9.13-26-gdadb0822)
 cabd7753ae17f7bfcc6dad56daf10868aa51c3f4 CMakeModules (v1.0.0-28-gcabd775)
 f4cbc079d41d4c7933fec39c0f03ba8db2d14f9c FV3 (remotes/origin/feature/noahmp)
 041422934cae1570f2f0e67239d5d89f11c6e1b7 GOCART (sdr_v2.1.2.6-119-g0414229)
 35789c757766e07f688b4c0c7c5229816f224b09 HYCOM-interface/HYCOM (2.3.00-121-g35789c7)
 60c397b910c9f0c5d1b35f9fea2293ccebd27fc8 MOM6-interface/MOM6 (dev/master/repository_split_2014.10.10-9875-g60c397b91)
 5d8319df205b0dbe6716bc40bb8065b8ea79ce5f NOAHMP-interface/noahmp (v3.7.1-421-g5d8319d)
 02693d837f2cd99d20ed08515878c2b5e9525e64 WW3 (6.07.1-343-g02693d83)
 a5561802021d89a9a1e2b52cb69393efcdc6f71c stochastic_physics (ufs-v2.0.0-199-ga556180)


COMPILE 's2swa_32bit_intel': PASS | Times (RT/Compile): (00:13:08/00:11:33)
TEST 'cpld_control_p8_mixedmode_intel': PASS | Times (RT/Test): (00:08:16/00:05:31)

COMPILE 's2swa_32bit_pdlib_intel': PASS | Times (RT/Compile): (00:18:08/00:16:22)
TEST 'cpld_control_gfsv17_intel': PASS | Times (RT/Test): (00:44:28/00:18:07)
TEST 'cpld_control_gfsv17_iau_intel': PASS | Times (RT/Test): (00:14:46/00:11:49)
TEST 'cpld_restart_gfsv17_intel': PASS | Times (RT/Test): (00:11:57/00:08:51)
TEST 'cpld_mpi_gfsv17_intel': PASS | Times (RT/Test): (00:21:15/00:18:02)

COMPILE 's2swa_32bit_pdlib_debug_intel': PASS | Times (RT/Compile): (00:06:06/00:04:15)
TEST 'cpld_debug_gfsv17_intel': PASS | Times (RT/Test): (00:22:01/00:19:09)

COMPILE 's2swa_intel': PASS | Times (RT/Compile): (00:13:09/00:11:34)
TEST 'cpld_control_p8_intel': PASS | Times (RT/Test): (00:08:11/00:05:55)
TEST 'cpld_restart_p8_intel': PASS | Times (RT/Test): (00:06:29/00:03:23)
TEST 'cpld_control_qr_p8_intel': PASS | Times (RT/Test): (00:08:11/00:05:57)
TEST 'cpld_restart_qr_p8_intel': PASS | Times (RT/Test): (00:06:29/00:03:24)
TEST 'cpld_2threads_p8_intel': PASS | Times (RT/Test): (00:08:11/00:05:40)
TEST 'cpld_decomp_p8_intel': PASS | Times (RT/Test): (00:08:11/00:05:53)
TEST 'cpld_mpi_p8_intel': PASS | Times (RT/Test): (00:07:22/00:04:52)
TEST 'cpld_control_ciceC_p8_intel': PASS | Times (RT/Test): (00:08:21/00:05:56)
TEST 'cpld_control_c192_p8_intel': PASS | Times (RT/Test): (00:14:23/00:10:06)
TEST 'cpld_restart_c192_p8_intel': PASS | Times (RT/Test): (00:26:01/00:06:45)
TEST 'cpld_bmark_p8_intel': PASS | Times (RT/Test): (00:19:03/00:10:24)
TEST 'cpld_restart_bmark_p8_intel': PASS | Times (RT/Test): (00:17:28/00:06:39)
TEST 'cpld_s2sa_p8_intel': PASS | Times (RT/Test): (00:08:13/00:05:30)

COMPILE 's2sw_intel': PASS | Times (RT/Compile): (00:12:08/00:10:48)
TEST 'cpld_control_noaero_p8_intel': PASS | Times (RT/Test): (00:07:10/00:04:36)
TEST 'cpld_control_nowave_noaero_p8_intel': PASS | Times (RT/Test): (00:07:16/00:04:28)

COMPILE 's2swa_debug_intel': PASS | Times (RT/Compile): (00:06:06/00:04:08)
TEST 'cpld_debug_p8_intel': PASS | Times (RT/Test): (00:11:05/00:08:21)

COMPILE 's2sw_debug_intel': PASS | Times (RT/Compile): (00:05:06/00:04:02)
TEST 'cpld_debug_noaero_p8_intel': PASS | Times (RT/Test): (00:08:04/00:05:39)

COMPILE 's2s_aoflux_intel': PASS | Times (RT/Compile): (00:12:08/00:10:02)
TEST 'cpld_control_noaero_p8_agrid_intel': PASS | Times (RT/Test): (00:07:16/00:04:23)

COMPILE 's2s_intel': PASS | Times (RT/Compile): (00:12:08/00:10:06)
TEST 'cpld_control_c48_intel': PASS | Times (RT/Test): (00:11:46/00:09:22)

COMPILE 's2swa_faster_intel': PASS | Times (RT/Compile): (00:18:09/00:16:31)
TEST 'cpld_control_p8_faster_intel': PASS | Times (RT/Test): (00:09:23/00:05:36)

COMPILE 's2sw_pdlib_intel': PASS | Times (RT/Compile): (00:17:09/00:15:37)
TEST 'cpld_control_pdlib_p8_intel': PASS | Times (RT/Test): (00:19:03/00:16:15)
TEST 'cpld_restart_pdlib_p8_intel': PASS | Times (RT/Test): (00:11:19/00:07:42)
TEST 'cpld_mpi_pdlib_p8_intel': PASS | Times (RT/Test): (00:22:48/00:18:51)

COMPILE 's2sw_pdlib_debug_intel': PASS | Times (RT/Compile): (00:05:07/00:03:59)
TEST 'cpld_debug_pdlib_p8_intel': PASS | Times (RT/Test): (00:26:01/00:23:57)

COMPILE 'atm_dyn32_intel': PASS | Times (RT/Compile): (00:12:08/00:10:32)
TEST 'control_flake_intel': PASS | Times (RT/Test): (00:06:25/00:03:37)
TEST 'control_CubedSphereGrid_intel': PASS | Times (RT/Test): (00:05:25/00:02:32)
TEST 'control_CubedSphereGrid_parallel_intel': PASS | Times (RT/Test): (00:05:27/00:02:36)
TEST 'control_latlon_intel': PASS | Times (RT/Test): (00:05:22/00:02:33)
TEST 'control_wrtGauss_netcdf_parallel_intel': PASS | Times (RT/Test): (00:05:30/00:02:39)
TEST 'control_c48_intel': PASS | Times (RT/Test): (00:08:29/00:06:22)
TEST 'control_c192_intel': PASS | Times (RT/Test): (00:11:45/00:09:07)
TEST 'control_c384_intel': PASS | Times (RT/Test): (00:12:37/00:09:34)
TEST 'control_c384gdas_intel': PASS | Times (RT/Test): (00:14:08/00:08:13)
TEST 'control_stochy_intel': PASS | Times (RT/Test): (00:04:23/00:01:48)
TEST 'control_stochy_restart_intel': PASS | Times (RT/Test): (00:03:26/00:00:59)
TEST 'control_lndp_intel': PASS | Times (RT/Test): (00:04:23/00:01:47)
TEST 'control_iovr4_intel': PASS | Times (RT/Test): (00:04:31/00:02:31)
TEST 'control_iovr5_intel': PASS | Times (RT/Test): (00:04:24/00:02:29)
TEST 'control_p8_intel': PASS | Times (RT/Test): (00:05:59/00:03:07)
TEST 'control_p8_ugwpv1_intel': PASS | Times (RT/Test): (00:04:52/00:02:52)
TEST 'control_restart_p8_intel': PASS | Times (RT/Test): (00:03:48/00:01:40)
TEST 'control_noqr_p8_intel': PASS | Times (RT/Test): (00:04:55/00:02:54)
TEST 'control_restart_noqr_p8_intel': PASS | Times (RT/Test): (00:03:56/00:01:37)
TEST 'control_decomp_p8_intel': PASS | Times (RT/Test): (00:05:56/00:03:02)
TEST 'control_2threads_p8_intel': PASS | Times (RT/Test): (00:04:52/00:02:42)
TEST 'control_p8_lndp_intel': PASS | Times (RT/Test): (00:07:54/00:05:09)
TEST 'control_p8_rrtmgp_intel': PASS | Times (RT/Test): (00:05:59/00:03:48)
TEST 'control_p8_mynn_intel': PASS | Times (RT/Test): (00:05:03/00:02:56)
TEST 'merra2_thompson_intel': PASS | Times (RT/Test): (00:05:58/00:03:29)
TEST 'regional_control_intel': PASS | Times (RT/Test): (00:07:43/00:05:10)
TEST 'regional_restart_intel': PASS | Times (RT/Test): (00:04:46/00:02:53)
TEST 'regional_decomp_intel': PASS | Times (RT/Test): (00:07:41/00:05:35)
TEST 'regional_2threads_intel': PASS | Times (RT/Test): (00:05:41/00:03:14)
TEST 'regional_noquilt_intel': PASS | Times (RT/Test): (00:06:41/00:04:59)
TEST 'regional_netcdf_parallel_intel': PASS | Times (RT/Test): (00:07:43/00:05:03)
TEST 'regional_2dwrtdecomp_intel': PASS | Times (RT/Test): (00:07:36/00:05:07)
TEST 'regional_wofs_intel': PASS | Times (RT/Test): (00:08:48/00:06:46)

COMPILE 'ifi_intel': PASS | Times (RT/Compile): (00:12:08/00:10:32)
TEST 'regional_ifi_control_intel': PASS | Times (RT/Test): (00:08:48/00:06:46)
TEST 'regional_ifi_decomp_intel': PASS | Times (RT/Test): (00:08:48/00:06:46)
TEST 'regional_ifi_2threads_intel': PASS | Times (RT/Test): (00:08:48/00:06:46)

COMPILE 'rrfs_intel': PASS | Times (RT/Compile): (00:11:10/00:09:29)
TEST 'rap_control_intel': PASS | Times (RT/Test): (00:09:57/00:07:44)
TEST 'regional_spp_sppt_shum_skeb_intel': PASS | Times (RT/Test): (00:07:13/00:04:18)
TEST 'rap_decomp_intel': PASS | Times (RT/Test): (00:10:36/00:08:06)
TEST 'rap_2threads_intel': PASS | Times (RT/Test): (00:09:43/00:07:23)
TEST 'rap_restart_intel': PASS | Times (RT/Test): (00:06:52/00:04:13)
TEST 'rap_sfcdiff_intel': PASS | Times (RT/Test): (00:09:47/00:07:47)
TEST 'rap_sfcdiff_decomp_intel': PASS | Times (RT/Test): (00:10:37/00:08:13)
TEST 'rap_sfcdiff_restart_intel': PASS | Times (RT/Test): (00:07:52/00:05:49)
TEST 'hrrr_control_intel': PASS | Times (RT/Test): (00:07:07/00:04:03)
TEST 'hrrr_control_decomp_intel': PASS | Times (RT/Test): (00:07:07/00:04:09)
TEST 'hrrr_control_2threads_intel': PASS | Times (RT/Test): (00:06:56/00:03:42)
TEST 'hrrr_control_restart_intel': PASS | Times (RT/Test): (00:04:46/00:02:44)
TEST 'rrfs_v1beta_intel': PASS | Times (RT/Test): (00:10:47/00:07:38)
TEST 'rrfs_v1nssl_intel': PASS | Times (RT/Test): (00:11:31/00:09:10)
TEST 'rrfs_v1nssl_nohailnoccn_intel': PASS | Times (RT/Test): (00:10:30/00:09:02)

COMPILE 'csawmg_intel': PASS | Times (RT/Compile): (00:11:07/00:09:11)
TEST 'control_csawmg_intel': PASS | Times (RT/Test): (00:07:44/00:05:54)
TEST 'control_csawmgt_intel': PASS | Times (RT/Test): (00:07:45/00:05:48)
TEST 'control_ras_intel': PASS | Times (RT/Test): (00:05:24/00:03:22)

COMPILE 'wam_intel': PASS | Times (RT/Compile): (00:10:07/00:08:47)
TEST 'control_wam_intel': PASS | Times (RT/Test): (00:04:27/00:02:07)

COMPILE 'atm_faster_dyn32_intel': PASS | Times (RT/Compile): (00:11:07/00:09:19)
TEST 'control_p8_faster_intel': PASS | Times (RT/Test): (00:05:19/00:02:43)
TEST 'regional_control_faster_intel': PASS | Times (RT/Test): (00:06:46/00:04:46)

COMPILE 'atm_debug_dyn32_intel': PASS | Times (RT/Compile): (00:06:06/00:04:48)
TEST 'control_CubedSphereGrid_debug_intel': PASS | Times (RT/Test): (00:04:39/00:02:43)
TEST 'control_wrtGauss_netcdf_parallel_debug_intel': PASS | Times (RT/Test): (00:04:33/00:02:40)
TEST 'control_stochy_debug_intel': PASS | Times (RT/Test): (00:04:18/00:02:55)
TEST 'control_lndp_debug_intel': PASS | Times (RT/Test): (00:05:31/00:03:21)
TEST 'control_csawmg_debug_intel': PASS | Times (RT/Test): (00:06:59/00:04:31)
TEST 'control_csawmgt_debug_intel': PASS | Times (RT/Test): (00:06:54/00:04:15)
TEST 'control_ras_debug_intel': PASS | Times (RT/Test): (00:05:31/00:02:52)
TEST 'control_diag_debug_intel': PASS | Times (RT/Test): (00:05:40/00:03:17)
TEST 'control_debug_p8_intel': PASS | Times (RT/Test): (00:04:57/00:02:56)
TEST 'regional_debug_intel': PASS | Times (RT/Test): (00:18:52/00:16:41)
TEST 'rap_control_debug_intel': PASS | Times (RT/Test): (00:06:35/00:04:55)
TEST 'hrrr_control_debug_intel': PASS | Times (RT/Test): (00:06:26/00:04:55)
TEST 'hrrr_gf_debug_intel': PASS | Times (RT/Test): (00:06:25/00:04:49)
TEST 'hrrr_c3_debug_intel': PASS | Times (RT/Test): (00:06:25/00:04:50)
TEST 'rap_unified_drag_suite_debug_intel': PASS | Times (RT/Test): (00:06:19/00:04:50)
TEST 'rap_diag_debug_intel': PASS | Times (RT/Test): (00:07:40/00:05:01)
TEST 'rap_cires_ugwp_debug_intel': PASS | Times (RT/Test): (00:06:21/00:04:51)
TEST 'rap_unified_ugwp_debug_intel': PASS | Times (RT/Test): (00:07:26/00:05:00)
TEST 'rap_lndp_debug_intel': PASS | Times (RT/Test): (00:07:25/00:04:49)
TEST 'rap_progcld_thompson_debug_intel': PASS | Times (RT/Test): (00:06:21/00:04:49)
TEST 'rap_noah_debug_intel': PASS | Times (RT/Test): (00:06:22/00:04:48)
TEST 'rap_sfcdiff_debug_intel': PASS | Times (RT/Test): (00:06:22/00:04:54)
TEST 'rap_noah_sfcdiff_cires_ugwp_debug_intel': PASS | Times (RT/Test): (00:09:22/00:07:47)
TEST 'rrfs_v1beta_debug_intel': PASS | Times (RT/Test): (00:06:23/00:04:39)
TEST 'rap_clm_lake_debug_intel': PASS | Times (RT/Test): (00:08:22/00:06:05)
TEST 'rap_flake_debug_intel': PASS | Times (RT/Test): (00:06:24/00:04:53)
TEST 'gnv1_c96_no_nest_debug_intel': PASS | Times (RT/Test): (00:10:39/00:08:11)

COMPILE 'wam_debug_intel': PASS | Times (RT/Compile): (00:05:06/00:03:17)
TEST 'control_wam_debug_intel': PASS | Times (RT/Test): (00:06:16/00:04:45)

COMPILE 'rrfs_dyn32_phy32_intel': PASS | Times (RT/Compile): (00:10:08/00:08:55)
TEST 'regional_spp_sppt_shum_skeb_dyn32_phy32_intel': PASS | Times (RT/Test): (00:09:07/00:04:07)
TEST 'rap_control_dyn32_phy32_intel': PASS | Times (RT/Test): (00:08:43/00:06:24)
TEST 'hrrr_control_dyn32_phy32_intel': PASS | Times (RT/Test): (00:05:40/00:03:24)
TEST 'rap_2threads_dyn32_phy32_intel': PASS | Times (RT/Test): (00:08:37/00:06:13)
TEST 'hrrr_control_2threads_dyn32_phy32_intel': PASS | Times (RT/Test): (00:06:34/00:03:13)
TEST 'hrrr_control_decomp_dyn32_phy32_intel': PASS | Times (RT/Test): (00:05:32/00:03:41)
TEST 'rap_restart_dyn32_phy32_intel': PASS | Times (RT/Test): (00:06:45/00:04:56)
TEST 'hrrr_control_restart_dyn32_phy32_intel': PASS | Times (RT/Test): (00:04:26/00:01:54)

COMPILE 'rrfs_dyn32_phy32_faster_intel': PASS | Times (RT/Compile): (00:13:09/00:11:09)
TEST 'conus13km_control_intel': PASS | Times (RT/Test): (00:04:56/00:02:11)
TEST 'conus13km_2threads_intel': PASS | Times (RT/Test): (00:03:39/00:01:12)
TEST 'conus13km_restart_mismatch_intel': PASS | Times (RT/Test): (00:03:46/00:01:20)

COMPILE 'rrfs_dyn64_phy32_intel': PASS | Times (RT/Compile): (00:11:08/00:09:07)
TEST 'rap_control_dyn64_phy32_intel': PASS | Times (RT/Test): (00:06:48/00:04:21)

COMPILE 'rrfs_dyn32_phy32_debug_intel': PASS | Times (RT/Compile): (00:05:07/00:03:24)
TEST 'rap_control_debug_dyn32_phy32_intel': PASS | Times (RT/Test): (00:07:23/00:04:46)
TEST 'hrrr_control_debug_dyn32_phy32_intel': PASS | Times (RT/Test): (00:06:18/00:04:47)
TEST 'conus13km_debug_intel': PASS | Times (RT/Test): (00:16:02/00:13:59)
TEST 'conus13km_debug_qr_intel': PASS | Times (RT/Test): (00:15:44/00:14:00)
TEST 'conus13km_debug_2threads_intel': PASS | Times (RT/Test): (00:09:48/00:07:56)
TEST 'conus13km_radar_tten_debug_intel': PASS | Times (RT/Test): (00:16:53/00:13:58)

COMPILE 'rrfs_dyn64_phy32_debug_intel': PASS | Times (RT/Compile): (00:05:07/00:03:46)
TEST 'rap_control_dyn64_phy32_debug_intel': PASS | Times (RT/Test): (00:06:27/00:04:58)

COMPILE 'hafsw_intel': PASS | Times (RT/Compile): (00:12:07/00:10:19)
TEST 'hafs_regional_atm_intel': PASS | Times (RT/Test): (00:08:21/00:05:11)
TEST 'hafs_regional_atm_thompson_gfdlsf_intel': PASS | Times (RT/Test): (00:10:35/00:07:12)
TEST 'hafs_regional_atm_ocn_intel': PASS | Times (RT/Test): (00:10:29/00:07:11)
TEST 'hafs_regional_atm_wav_intel': PASS | Times (RT/Test): (00:17:17/00:13:15)
TEST 'hafs_regional_atm_ocn_wav_intel': PASS | Times (RT/Test): (00:18:47/00:14:58)
TEST 'hafs_regional_1nest_atm_intel': PASS | Times (RT/Test): (00:09:05/00:06:02)
TEST 'hafs_regional_telescopic_2nests_atm_intel': PASS | Times (RT/Test): (00:10:30/00:07:27)
TEST 'hafs_global_1nest_atm_intel': PASS | Times (RT/Test): (00:05:50/00:03:01)
TEST 'hafs_global_multiple_4nests_atm_intel': PASS | Times (RT/Test): (00:12:02/00:07:38)
TEST 'hafs_regional_specified_moving_1nest_atm_intel': PASS | Times (RT/Test): (00:05:48/00:03:58)
TEST 'hafs_regional_storm_following_1nest_atm_intel': PASS | Times (RT/Test): (00:05:51/00:03:50)
TEST 'hafs_regional_storm_following_1nest_atm_ocn_intel': PASS | Times (RT/Test): (00:06:54/00:04:20)
TEST 'hafs_global_storm_following_1nest_atm_intel': PASS | Times (RT/Test): (00:03:26/00:01:22)
TEST 'gnv1_nested_intel': PASS | Times (RT/Test): (00:06:48/00:04:28)

COMPILE 'hafsw_debug_intel': PASS | Times (RT/Compile): (00:05:05/00:03:29)
TEST 'hafs_regional_storm_following_1nest_atm_ocn_debug_intel': PASS | Times (RT/Test): (00:15:05/00:12:48)

COMPILE 'hafsw_faster_intel': PASS | Times (RT/Compile): (00:12:06/00:11:03)
TEST 'hafs_regional_storm_following_1nest_atm_ocn_wav_intel': PASS | Times (RT/Test): (00:10:56/00:08:48)

COMPILE 'hafs_all_intel': PASS | Times (RT/Compile): (00:12:07/00:10:27)
TEST 'hafs_regional_docn_intel': PASS | Times (RT/Test): (00:09:22/00:06:37)
TEST 'hafs_regional_docn_oisst_intel': PASS | Times (RT/Test): (00:09:19/00:06:37)
TEST 'hafs_regional_datm_cdeps_intel': PASS | Times (RT/Test): (00:18:00/00:16:05)

COMPILE 'datm_cdeps_intel': PASS | Times (RT/Compile): (00:07:06/00:05:53)
TEST 'datm_cdeps_control_cfsr_intel': PASS | Times (RT/Test): (00:04:15/00:02:40)
TEST 'datm_cdeps_restart_cfsr_intel': PASS | Times (RT/Test): (00:03:18/00:01:39)
TEST 'datm_cdeps_control_gefs_intel': PASS | Times (RT/Test): (00:04:13/00:02:33)
TEST 'datm_cdeps_iau_gefs_intel': PASS | Times (RT/Test): (00:04:14/00:02:34)
TEST 'datm_cdeps_stochy_gefs_intel': PASS | Times (RT/Test): (00:04:13/00:02:38)
TEST 'datm_cdeps_ciceC_cfsr_intel': PASS | Times (RT/Test): (00:04:13/00:02:38)
TEST 'datm_cdeps_bulk_cfsr_intel': PASS | Times (RT/Test): (00:04:13/00:02:38)
TEST 'datm_cdeps_bulk_gefs_intel': PASS | Times (RT/Test): (00:04:14/00:02:34)
TEST 'datm_cdeps_mx025_cfsr_intel': PASS | Times (RT/Test): (00:09:28/00:06:44)
TEST 'datm_cdeps_mx025_gefs_intel': PASS | Times (RT/Test): (00:09:34/00:06:34)
TEST 'datm_cdeps_multiple_files_cfsr_intel': PASS | Times (RT/Test): (00:04:10/00:02:40)
TEST 'datm_cdeps_3072x1536_cfsr_intel': PASS | Times (RT/Test): (00:05:14/00:03:56)
TEST 'datm_cdeps_gfs_intel': PASS | Times (RT/Test): (00:05:14/00:04:00)

COMPILE 'datm_cdeps_debug_intel': PASS | Times (RT/Compile): (00:04:05/00:02:55)
TEST 'datm_cdeps_debug_cfsr_intel': PASS | Times (RT/Test): (00:08:28/00:06:03)

COMPILE 'datm_cdeps_faster_intel': PASS | Times (RT/Compile): (00:07:06/00:05:56)
TEST 'datm_cdeps_control_cfsr_faster_intel': PASS | Times (RT/Test): (00:04:14/00:02:39)

COMPILE 'datm_cdeps_land_intel': PASS | Times (RT/Compile): (00:03:06/00:01:12)
TEST 'datm_cdeps_lnd_gswp3_intel': FAIL TO RUN | Times (RT/Test): (00:04:14/00:02:39)
-- LOG: /scratch1/NCEPDEV/nems/Brian.Curtis/git/uturuncoglu/ufs-weather-model/feature/noahmp/tests/logs/log_hera/run_datm_cdeps_lnd_gswp3_intel.log
TEST 'datm_cdeps_lnd_era5_intel': FAIL TO RUN | Times (RT/Test): (00:04:14/00:02:39)
-- LOG: /scratch1/NCEPDEV/nems/Brian.Curtis/git/uturuncoglu/ufs-weather-model/feature/noahmp/tests/logs/log_hera/run_datm_cdeps_lnd_era5_intel.log
TEST 'datm_cdeps_lnd_era5_rst_intel': MISSING | Times (RT/Test): (00:04:14/00:02:39)

COMPILE 'atml_intel': PASS | Times (RT/Compile): (00:12:07/00:10:22)
TEST 'control_p8_atmlnd_sbs_intel': FAIL TO COMPARE | Times (RT/Test): (00:04:14/00:02:39)
-- LOG: /scratch1/NCEPDEV/nems/Brian.Curtis/git/uturuncoglu/ufs-weather-model/feature/noahmp/tests/logs/log_hera/rt_control_p8_atmlnd_sbs_intel.log
TEST 'control_p8_atmlnd_intel': FAIL TO COMPARE | Times (RT/Test): (00:04:14/00:02:39)
-- LOG: /scratch1/NCEPDEV/nems/Brian.Curtis/git/uturuncoglu/ufs-weather-model/feature/noahmp/tests/logs/log_hera/rt_control_p8_atmlnd_intel.log
TEST 'control_restart_p8_atmlnd_intel': MISSING | Times (RT/Test): (00:04:14/00:02:39)

COMPILE 'atmw_intel': PASS | Times (RT/Compile): (00:12:07/00:10:34)
TEST 'atmwav_control_noaero_p8_intel': PASS | Times (RT/Test): (00:04:56/00:01:46)

COMPILE 'atmwm_intel': PASS | Times (RT/Compile): (00:12:08/00:10:38)
TEST 'control_atmwav_intel': PASS | Times (RT/Test): (00:03:34/00:01:42)

COMPILE 'atmaero_intel': PASS | Times (RT/Compile): (00:12:08/00:10:18)
TEST 'atmaero_control_p8_intel': PASS | Times (RT/Test): (00:08:40/00:04:03)
TEST 'atmaero_control_p8_rad_intel': PASS | Times (RT/Test): (00:08:36/00:04:47)
TEST 'atmaero_control_p8_rad_micro_intel': PASS | Times (RT/Test): (00:09:07/00:05:04)

COMPILE 'atmaq_intel': PASS | Times (RT/Compile): (00:11:08/00:09:20)
TEST 'regional_atmaq_intel': PASS | Times (RT/Test): (00:16:17/00:11:45)

COMPILE 'atmaq_debug_intel': PASS | Times (RT/Compile): (00:06:06/00:04:03)
TEST 'regional_atmaq_debug_intel': PASS | Times (RT/Test): (00:25:01/00:20:54)

COMPILE 'atm_gnu': PASS | Times (RT/Compile): (00:07:06/00:05:25)
TEST 'control_c48_gnu': PASS | Times (RT/Test): (00:13:38/00:11:36)
TEST 'control_stochy_gnu': PASS | Times (RT/Test): (00:06:55/00:04:09)
TEST 'control_ras_gnu': PASS | Times (RT/Test): (00:06:55/00:05:08)
TEST 'control_p8_gnu': PASS | Times (RT/Test): (00:08:00/00:05:04)
TEST 'control_p8_ugwpv1_gnu': PASS | Times (RT/Test): (00:07:41/00:04:54)
TEST 'control_flake_gnu': PASS | Times (RT/Test): (00:07:36/00:06:07)

COMPILE 'rrfs_gnu': PASS | Times (RT/Compile): (00:07:07/00:05:27)
TEST 'rap_control_gnu': PASS | Times (RT/Test): (00:13:51/00:11:46)
TEST 'rap_decomp_gnu': PASS | Times (RT/Test): (00:13:46/00:12:01)
TEST 'rap_2threads_gnu': PASS | Times (RT/Test): (00:12:54/00:10:49)
TEST 'rap_restart_gnu': PASS | Times (RT/Test): (00:08:43/00:06:04)
TEST 'rap_sfcdiff_gnu': PASS | Times (RT/Test): (00:14:03/00:12:00)
TEST 'rap_sfcdiff_decomp_gnu': PASS | Times (RT/Test): (00:13:56/00:12:05)
TEST 'rap_sfcdiff_restart_gnu': PASS | Times (RT/Test): (00:11:46/00:09:00)
TEST 'hrrr_control_gnu': PASS | Times (RT/Test): (00:07:50/00:06:10)
TEST 'hrrr_control_noqr_gnu': PASS | Times (RT/Test): (00:08:44/00:06:18)
TEST 'hrrr_control_2threads_gnu': PASS | Times (RT/Test): (00:07:45/00:05:26)
TEST 'hrrr_control_decomp_gnu': PASS | Times (RT/Test): (00:09:10/00:06:54)
TEST 'hrrr_control_restart_gnu': PASS | Times (RT/Test): (00:05:22/00:03:17)
TEST 'hrrr_control_restart_noqr_gnu': PASS | Times (RT/Test): (00:05:22/00:03:13)
TEST 'rrfs_v1beta_gnu': PASS | Times (RT/Test): (00:15:12/00:12:20)

COMPILE 'atm_dyn32_debug_gnu': PASS | Times (RT/Compile): (00:07:06/00:04:49)
TEST 'control_diag_debug_gnu': PASS | Times (RT/Test): (00:04:54/00:02:19)
TEST 'regional_debug_gnu': PASS | Times (RT/Test): (00:11:07/00:08:41)
TEST 'rap_control_debug_gnu': PASS | Times (RT/Test): (00:05:45/00:03:22)
TEST 'hrrr_control_debug_gnu': PASS | Times (RT/Test): (00:05:43/00:03:19)
TEST 'hrrr_gf_debug_gnu': PASS | Times (RT/Test): (00:05:44/00:03:23)
TEST 'hrrr_c3_debug_gnu': PASS | Times (RT/Test): (00:04:42/00:02:57)
TEST 'rap_diag_debug_gnu': PASS | Times (RT/Test): (00:05:59/00:03:23)
TEST 'rap_noah_sfcdiff_cires_ugwp_debug_gnu': PASS | Times (RT/Test): (00:06:37/00:04:21)
TEST 'rap_progcld_thompson_debug_gnu': PASS | Times (RT/Test): (00:04:39/00:02:42)
TEST 'rrfs_v1beta_debug_gnu': PASS | Times (RT/Test): (00:04:35/00:02:43)
TEST 'control_ras_debug_gnu': PASS | Times (RT/Test): (00:03:26/00:01:44)
TEST 'control_stochy_debug_gnu': PASS | Times (RT/Test): (00:04:26/00:02:03)
TEST 'control_debug_p8_gnu': PASS | Times (RT/Test): (00:03:37/00:01:41)
TEST 'rap_flake_debug_gnu': PASS | Times (RT/Test): (00:04:23/00:02:35)
TEST 'rap_clm_lake_debug_gnu': PASS | Times (RT/Test): (00:04:20/00:02:51)
TEST 'gnv1_c96_no_nest_debug_gnu': PASS | Times (RT/Test): (00:06:38/00:04:12)

COMPILE 'wam_debug_gnu': PASS | Times (RT/Compile): (00:04:07/00:01:59)
TEST 'control_wam_debug_gnu': PASS | Times (RT/Test): (00:04:18/00:02:27)

COMPILE 'rrfs_dyn32_phy32_gnu': PASS | Times (RT/Compile): (00:05:06/00:03:25)
TEST 'rap_control_dyn32_phy32_gnu': PASS | Times (RT/Test): (00:13:28/00:12:03)
TEST 'hrrr_control_dyn32_phy32_gnu': PASS | Times (RT/Test): (00:08:27/00:06:10)
TEST 'rap_2threads_dyn32_phy32_gnu': PASS | Times (RT/Test): (00:12:36/00:10:56)
TEST 'hrrr_control_2threads_dyn32_phy32_gnu': PASS | Times (RT/Test): (00:07:36/00:05:24)
TEST 'hrrr_control_decomp_dyn32_phy32_gnu': PASS | Times (RT/Test): (00:08:30/00:06:09)
TEST 'rap_restart_dyn32_phy32_gnu': PASS | Times (RT/Test): (00:11:36/00:08:52)
TEST 'hrrr_control_restart_dyn32_phy32_gnu': PASS | Times (RT/Test): (00:05:23/00:03:20)
TEST 'conus13km_control_gnu': PASS | Times (RT/Test): (00:06:56/00:04:18)
TEST 'conus13km_2threads_gnu': PASS | Times (RT/Test): (00:04:46/00:02:05)
TEST 'conus13km_restart_mismatch_gnu': PASS | Times (RT/Test): (00:04:43/00:02:24)

COMPILE 'atm_dyn64_phy32_gnu': PASS | Times (RT/Compile): (00:06:08/00:05:01)
TEST 'rap_control_dyn64_phy32_gnu': PASS | Times (RT/Test): (00:08:44/00:07:00)

COMPILE 'atm_dyn32_phy32_debug_gnu': PASS | Times (RT/Compile): (00:05:06/00:03:28)
TEST 'rap_control_debug_dyn32_phy32_gnu': PASS | Times (RT/Test): (00:04:20/00:02:31)
TEST 'hrrr_control_debug_dyn32_phy32_gnu': PASS | Times (RT/Test): (00:04:19/00:02:34)
TEST 'conus13km_debug_gnu': PASS | Times (RT/Test): (00:09:46/00:07:06)
TEST 'conus13km_debug_qr_gnu': PASS | Times (RT/Test): (00:09:43/00:07:15)
TEST 'conus13km_debug_2threads_gnu': PASS | Times (RT/Test): (00:06:42/00:04:29)
TEST 'conus13km_radar_tten_debug_gnu': PASS | Times (RT/Test): (00:09:40/00:07:18)

COMPILE 'atm_dyn64_phy32_debug_gnu': PASS | Times (RT/Compile): (00:05:06/00:03:23)
TEST 'rap_control_dyn64_phy32_debug_gnu': PASS | Times (RT/Test): (00:04:22/00:02:36)

COMPILE 's2swa_gnu': PASS | Times (RT/Compile): (00:15:07/00:13:58)
TEST 'cpld_control_p8_gnu': PASS | Times (RT/Test): (00:13:26/00:10:45)

COMPILE 's2s_gnu': PASS | Times (RT/Compile): (00:15:07/00:13:43)
TEST 'cpld_control_nowave_noaero_p8_gnu': PASS | Times (RT/Test): (00:09:15/00:06:37)

COMPILE 's2swa_debug_gnu': PASS | Times (RT/Compile): (00:04:07/00:02:24)
TEST 'cpld_debug_p8_gnu': PASS | Times (RT/Test): (00:09:07/00:06:30)

COMPILE 's2sw_pdlib_gnu': PASS | Times (RT/Compile): (00:15:08/00:13:48)
TEST 'cpld_control_pdlib_p8_gnu': PASS | Times (RT/Test): (00:24:01/00:21:55)

COMPILE 's2sw_pdlib_debug_gnu': PASS | Times (RT/Compile): (00:04:07/00:02:12)
TEST 'cpld_debug_pdlib_p8_gnu': PASS | Times (RT/Test): (00:14:57/00:12:56)

COMPILE 'datm_cdeps_gnu': PASS | Times (RT/Compile): (00:15:07/00:13:43)
TEST 'datm_cdeps_control_cfsr_gnu': PASS | Times (RT/Test): (00:04:13/00:02:58)

SYNOPSIS:
Starting Date/Time: 20240114 13:13:19
Ending Date/Time: 20240114 14:53:43
Total Time: 01h:40m:55s)
Compiles Completed: 52/52
Tests Completed: 235/239
Failed Tests:
-- TEST 'datm_cdeps_lnd_gswp3_intel': FAIL TO RUN
-- TEST 'datm_cdeps_lnd_era5_intel': FAIL TO RUN
-- TEST 'control_p8_atmlnd_sbs_intel': FAIL TO COMPARE
-- TEST 'control_p8_atmlnd_intel': FAIL TO COMPARE

NOTES:
A file 'test_changes.out' was generated with list of all failed tests.
You can use './rt.sh -b test_changes.out' to generate baselines for the failed tests.
If you are using this log as a pull request verification, please commit 'test_changes.out'.

Result: FAILURE

====END OF HERA REGRESSION TESTING LOG====
```

**Comment by BrianCurtis-NOAA** [comment]
Hmm, I want the times, I think it provides great information for EPIC to run statistics on, but it needs to be a little more simplified.

I think i'll move towards the PASS/FAIL being at the beginning:
```
PASS -- COMPILE 'atm_gnu' (07:06--05:25)
PASS -- TEST 'control_c48_gnu' (13:38--11:36)
PASS -- TEST 'control_stochy_gnu' (06:55--04:09)
PASS -- TEST 'control_ras_gnu' (06:55--05:08)
PASS -- TEST 'control_p8_gnu' (08:00--05:04)
PASS -- TEST 'control_p8_ugwpv1_gnu' (07:41--04:54)
PASS -- TEST 'control_flake_gnu' (07:36--06:07)
```

```
PASS -- COMPILE 'atml_intel' (12:07--10:22)
FAIL TO COMPARE -- TEST 'control_p8_atmlnd_sbs_intel' (--)
-- LOG: /scratch1/NCEPDEV/nems/Brian.Curtis/git/uturuncoglu/ufs-weather-model/feature/noahmp/tests/logs/log_hera/rt_control_p8_atmlnd_sbs_intel.log
FAIL TO COMPARE -- TEST 'control_p8_atmlnd_intel' (--)
-- LOG: /scratch1/NCEPDEV/nems/Brian.Curtis/git/uturuncoglu/ufs-weather-model/feature/noahmp/tests/logs/log_hera/rt_control_p8_atmlnd_intel.log
MISSING -- TEST 'control_restart_p8_atmlnd_intel' (--)
```

**Comment by BrianCurtis-NOAA** [comment]
I think this looks much better!
```
====START OF HERA REGRESSION TESTING LOG====

UFSWM hash used in testing:
3ff6b3f27cae02855235f5dd4143dab9100f3cac

Submodule hashes used in testing:
 37cbb7d6840ae7515a9a8f0dfd4d89461b3396d1 AQM (v0.2.0-37-g37cbb7d)
 78b9504c0f7c537d7f143ca02e5eef62fb88e80e CDEPS-interface/CDEPS (cdeps0.6.3-30-g78b9504)
 620e48fe75d92aa607af7e21f2d8691baddd2851 CICE-interface/CICE (CICE6.0.0-445-g620e48f)
 dadb082291ce3487d8b5a8e191a0abe45b69c8af CMEPS-interface/CMEPS (cmeps0.9.13-26-gdadb0822)
 cabd7753ae17f7bfcc6dad56daf10868aa51c3f4 CMakeModules (v1.0.0-28-gcabd775)
 f4cbc079d41d4c7933fec39c0f03ba8db2d14f9c FV3 (remotes/origin/feature/noahmp)
 041422934cae1570f2f0e67239d5d89f11c6e1b7 GOCART (sdr_v2.1.2.6-119-g0414229)
 35789c757766e07f688b4c0c7c5229816f224b09 HYCOM-interface/HYCOM (2.3.00-121-g35789c7)
 60c397b910c9f0c5d1b35f9fea2293ccebd27fc8 MOM6-interface/MOM6 (dev/master/repository_split_2014.10.10-9875-g60c397b91)
 5d8319df205b0dbe6716bc40bb8065b8ea79ce5f NOAHMP-interface/noahmp (v3.7.1-421-g5d8319d)
 02693d837f2cd99d20ed08515878c2b5e9525e64 WW3 (6.07.1-343-g02693d83)
 a5561802021d89a9a1e2b52cb69393efcdc6f71c stochastic_physics (ufs-v2.0.0-199-ga556180)

NOTES:
Times are at the end of each compile/test in format (MM:SS).
The first time is how long the scipt (prep+run+finalize) ran.
The second time is specifically how long the run phase ran.
Times will be empty for failed tests.

PASS -- COMPILE 's2swa_32bit_intel' (13:08--11:22)
PASS -- TEST 'cpld_control_p8_mixedmode_intel' (00:13:21--00:05:17)

PASS -- COMPILE 's2swa_32bit_pdlib_intel' (17:09--15:33)
PASS -- TEST 'cpld_control_gfsv17_intel' (00:25:58--00:16:01)
PASS -- TEST 'cpld_control_gfsv17_iau_intel' (00:24:56--00:10:34)
PASS -- TEST 'cpld_restart_gfsv17_intel' (00:21:06--00:07:42)
PASS -- TEST 'cpld_mpi_gfsv17_intel' (00:27:54--00:17:58)

PASS -- COMPILE 's2swa_32bit_pdlib_debug_intel' (06:07--04:02)
PASS -- TEST 'cpld_debug_gfsv17_intel' (00:22:17--00:18:56)

PASS -- COMPILE 's2swa_intel' (13:09--11:14)
PASS -- TEST 'cpld_control_p8_intel' (00:20:34--00:05:42)
PASS -- TEST 'cpld_restart_p8_intel' (00:14:30--00:03:18)
PASS -- TEST 'cpld_control_qr_p8_intel' (00:14:30--00:05:47)
PASS -- TEST 'cpld_restart_qr_p8_intel' (00:20:34--00:03:24)
PASS -- TEST 'cpld_2threads_p8_intel' (00:13:15--00:05:32)
PASS -- TEST 'cpld_decomp_p8_intel' (00:13:16--00:05:37)
PASS -- TEST 'cpld_mpi_p8_intel' (00:11:22--00:04:42)
PASS -- TEST 'cpld_control_ciceC_p8_intel' (00:14:35--00:05:40)
PASS -- TEST 'cpld_control_c192_p8_intel' (00:15:28--00:09:46)
PASS -- TEST 'cpld_restart_c192_p8_intel' (00:22:44--00:05:56)
PASS -- TEST 'cpld_bmark_p8_intel' (00:19:53--00:10:07)
PASS -- TEST 'cpld_restart_bmark_p8_intel' (00:19:28--00:06:23)
PASS -- TEST 'cpld_s2sa_p8_intel' (00:14:23--00:05:20)

PASS -- COMPILE 's2sw_intel' (13:08--10:46)
PASS -- TEST 'cpld_control_noaero_p8_intel' (00:11:15--00:04:35)
PASS -- TEST 'cpld_control_nowave_noaero_p8_intel' (00:12:23--00:04:35)

PASS -- COMPILE 's2swa_debug_intel' (06:06--04:02)
PASS -- TEST 'cpld_debug_p8_intel' (00:14:20--00:08:10)

PASS -- COMPILE 's2sw_debug_intel' (06:07--03:52)
PASS -- TEST 'cpld_debug_noaero_p8_intel' (00:08:15--00:05:44)

PASS -- COMPILE 's2s_aoflux_intel' (12:08--09:58)
PASS -- TEST 'cpld_control_noaero_p8_agrid_intel' (00:08:02--00:04:25)

PASS -- COMPILE 's2s_intel' (12:08--09:56)
PASS -- TEST 'cpld_control_c48_intel' (00:12:43--00:09:22)

PASS -- COMPILE 's2swa_faster_intel' (18:09--16:16)
PASS -- TEST 'cpld_control_p8_faster_intel' (00:15:05--00:05:23)

PASS -- COMPILE 's2sw_pdlib_intel' (17:09--14:33)
PASS -- TEST 'cpld_control_pdlib_p8_intel' (00:31:07--00:16:13)
PASS -- TEST 'cpld_restart_pdlib_p8_intel' (00:11:11--00:07:37)
PASS -- TEST 'cpld_mpi_pdlib_p8_intel' (00:22:01--00:18:35)

PASS -- COMPILE 's2sw_pdlib_debug_intel' (06:06--03:48)
PASS -- TEST 'cpld_debug_pdlib_p8_intel' (00:29:05--00:24:19)

PASS -- COMPILE 'atm_dyn32_intel' (13:07--10:10)
PASS -- TEST 'control_flake_intel' (00:22:25--00:03:21)
PASS -- TEST 'control_CubedSphereGrid_intel' (00:21:27--00:02:25)
PASS -- TEST 'control_CubedSphereGrid_parallel_intel' (00:22:30--00:02:35)
PASS -- TEST 'control_latlon_intel' (00:21:24--00:02:27)
PASS -- TEST 'control_wrtGauss_netcdf_parallel_intel' (00:21:32--00:02:32)
PASS -- TEST 'control_c48_intel' (00:25:26--00:06:17)
PASS -- TEST 'control_c192_intel' (00:21:39--00:09:01)
PASS -- TEST 'control_c384_intel' (00:29:40--00:09:09)
PASS -- TEST 'control_c384gdas_intel' (00:28:50--00:08:06)
PASS -- TEST 'control_stochy_intel' (00:21:25--00:01:45)
PASS -- TEST 'control_stochy_restart_intel' (00:03:22--00:00:59)
PASS -- TEST 'control_lndp_intel' (00:20:21--00:01:37)
PASS -- TEST 'control_iovr4_intel' (00:20:20--00:02:30)
PASS -- TEST 'control_iovr5_intel' (00:16:22--00:02:28)
PASS -- TEST 'control_p8_intel' (00:22:50--00:02:59)
PASS -- TEST 'control_p8_ugwpv1_intel' (00:22:09--00:02:54)
PASS -- TEST 'control_restart_p8_intel' (00:10:52--00:01:39)
PASS -- TEST 'control_noqr_p8_intel' (00:20:53--00:02:54)
PASS -- TEST 'control_restart_noqr_p8_intel' (00:11:51--00:01:37)
PASS -- TEST 'control_decomp_p8_intel' (00:20:51--00:03:01)
PASS -- TEST 'control_2threads_p8_intel' (00:18:51--00:02:45)
PASS -- TEST 'control_p8_lndp_intel' (00:20:55--00:05:11)
PASS -- TEST 'control_p8_rrtmgp_intel' (00:18:59--00:03:47)
PASS -- TEST 'control_p8_mynn_intel' (00:19:04--00:02:59)
PASS -- TEST 'merra2_thompson_intel' (00:12:54--00:03:27)
PASS -- TEST 'regional_control_intel' (00:11:42--00:05:08)
PASS -- TEST 'regional_restart_intel' (00:09:38--00:02:44)
PASS -- TEST 'regional_decomp_intel' (00:11:45--00:05:25)
PASS -- TEST 'regional_2threads_intel' (00:09:45--00:03:16)
PASS -- TEST 'regional_noquilt_intel' (00:11:47--00:05:06)
PASS -- TEST 'regional_netcdf_parallel_intel' (00:10:49--00:05:03)
PASS -- TEST 'regional_2dwrtdecomp_intel' (00:10:40--00:05:08)
PASS -- TEST 'regional_wofs_intel' (00:12:44--00:06:35)

PASS -- COMPILE 'ifi_intel' (13:07--10:10)
PASS -- TEST 'regional_ifi_control_intel' (00:12:44--00:06:35)
PASS -- TEST 'regional_ifi_decomp_intel' (00:12:44--00:06:35)
PASS -- TEST 'regional_ifi_2threads_intel' (00:12:44--00:06:35)

PASS -- COMPILE 'rrfs_intel' (11:07--09:16)
PASS -- TEST 'rap_control_intel' (00:10:39--00:07:41)
PASS -- TEST 'regional_spp_sppt_shum_skeb_intel' (00:07:01--00:04:07)
PASS -- TEST 'rap_decomp_intel' (00:13:30--00:08:06)
PASS -- TEST 'rap_2threads_intel' (00:09:29--00:07:14)
PASS -- TEST 'rap_restart_intel' (00:12:39--00:04:06)
PASS -- TEST 'rap_sfcdiff_intel' (00:20:40--00:07:44)
PASS -- TEST 'rap_sfcdiff_decomp_intel' (00:20:37--00:08:10)
PASS -- TEST 'rap_sfcdiff_restart_intel' (00:12:43--00:05:49)
PASS -- TEST 'hrrr_control_intel' (00:15:34--00:04:00)
PASS -- TEST 'hrrr_control_decomp_intel' (00:14:43--00:04:07)
PASS -- TEST 'hrrr_control_2threads_intel' (00:13:46--00:03:38)
PASS -- TEST 'hrrr_control_restart_intel' (00:12:26--00:02:09)
PASS -- TEST 'rrfs_v1beta_intel' (00:17:41--00:07:38)
PASS -- TEST 'rrfs_v1nssl_intel' (00:18:27--00:09:08)
PASS -- TEST 'rrfs_v1nssl_nohailnoccn_intel' (00:18:30--00:08:56)

PASS -- COMPILE 'csawmg_intel' (11:07--09:26)
PASS -- TEST 'control_csawmg_intel' (00:14:43--00:05:56)
PASS -- TEST 'control_csawmgt_intel' (00:14:42--00:05:53)
PASS -- TEST 'control_ras_intel' (00:12:22--00:03:21)

PASS -- COMPILE 'wam_intel' (10:07--08:34)
PASS -- TEST 'control_wam_intel' (00:12:19--00:02:06)

PASS -- COMPILE 'atm_faster_dyn32_intel' (14:08--09:05)
PASS -- TEST 'control_p8_faster_intel' (00:12:59--00:02:37)
PASS -- TEST 'regional_control_faster_intel' (00:06:39--00:04:42)

PASS -- COMPILE 'atm_debug_dyn32_intel' (10:07--04:07)
PASS -- TEST 'control_CubedSphereGrid_debug_intel' (00:10:27--00:02:37)
PASS -- TEST 'control_wrtGauss_netcdf_parallel_debug_intel' (00:10:27--00:02:36)
PASS -- TEST 'control_stochy_debug_intel' (00:11:17--00:03:00)
PASS -- TEST 'control_lndp_debug_intel' (00:10:19--00:02:39)
PASS -- TEST 'control_csawmg_debug_intel' (00:11:38--00:04:00)
PASS -- TEST 'control_csawmgt_debug_intel' (00:11:37--00:04:03)
PASS -- TEST 'control_ras_debug_intel' (00:09:17--00:02:42)
PASS -- TEST 'control_diag_debug_intel' (00:08:30--00:02:52)
PASS -- TEST 'control_debug_p8_intel' (00:07:37--00:02:49)
PASS -- TEST 'regional_debug_intel' (00:19:39--00:16:44)
PASS -- TEST 'rap_control_debug_intel' (00:07:19--00:04:43)
PASS -- TEST 'hrrr_control_debug_intel' (00:08:19--00:04:42)
PASS -- TEST 'hrrr_gf_debug_intel' (00:08:34--00:04:46)
PASS -- TEST 'hrrr_c3_debug_intel' (00:08:30--00:04:46)
PASS -- TEST 'rap_unified_drag_suite_debug_intel' (00:07:20--00:04:43)
PASS -- TEST 'rap_diag_debug_intel' (00:07:36--00:04:57)
PASS -- TEST 'rap_cires_ugwp_debug_intel' (00:15:21--00:04:46)
PASS -- TEST 'rap_unified_ugwp_debug_intel' (00:15:21--00:04:55)
PASS -- TEST 'rap_lndp_debug_intel' (00:15:21--00:04:44)
PASS -- TEST 'rap_progcld_thompson_debug_intel' (00:14:22--00:04:48)
PASS -- TEST 'rap_noah_debug_intel' (00:14:21--00:04:46)
PASS -- TEST 'rap_sfcdiff_debug_intel' (00:14:24--00:04:49)
PASS -- TEST 'rap_noah_sfcdiff_cires_ugwp_debug_intel' (00:17:26--00:07:45)
PASS -- TEST 'rrfs_v1beta_debug_intel' (00:14:24--00:04:47)
PASS -- TEST 'rap_clm_lake_debug_intel' (00:15:26--00:06:08)
PASS -- TEST 'rap_flake_debug_intel' (00:14:22--00:04:46)
PASS -- TEST 'gnv1_c96_no_nest_debug_intel' (00:16:35--00:08:13)

PASS -- COMPILE 'wam_debug_intel' (09:07--02:55)
PASS -- TEST 'control_wam_debug_intel' (00:13:24--00:04:49)

PASS -- COMPILE 'rrfs_dyn32_phy32_intel' (11:06--08:40)
PASS -- TEST 'regional_spp_sppt_shum_skeb_dyn32_phy32_intel' (00:11:57--00:03:53)
PASS -- TEST 'rap_control_dyn32_phy32_intel' (00:13:32--00:06:23)
PASS -- TEST 'hrrr_control_dyn32_phy32_intel' (00:10:32--00:03:24)
PASS -- TEST 'rap_2threads_dyn32_phy32_intel' (00:12:40--00:06:06)
PASS -- TEST 'hrrr_control_2threads_dyn32_phy32_intel' (00:09:32--00:03:09)
PASS -- TEST 'hrrr_control_decomp_dyn32_phy32_intel' (00:09:27--00:03:35)
PASS -- TEST 'rap_restart_dyn32_phy32_intel' (00:09:42--00:04:49)
PASS -- TEST 'hrrr_control_restart_dyn32_phy32_intel' (00:04:21--00:01:49)

PASS -- COMPILE 'rrfs_dyn32_phy32_faster_intel' (14:07--10:57)
PASS -- TEST 'conus13km_control_intel' (00:09:52--00:02:03)
PASS -- TEST 'conus13km_2threads_intel' (00:02:38--00:00:52)
PASS -- TEST 'conus13km_restart_mismatch_intel' (00:03:38--00:01:12)

PASS -- COMPILE 'rrfs_dyn64_phy32_intel' (28:10--08:54)
PASS -- TEST 'rap_control_dyn64_phy32_intel' (00:10:41--00:04:16)

PASS -- COMPILE 'rrfs_dyn32_phy32_debug_intel' (19:09--03:10)
PASS -- TEST 'rap_control_debug_dyn32_phy32_intel' (00:11:22--00:04:39)
PASS -- TEST 'hrrr_control_debug_dyn32_phy32_intel' (00:10:19--00:04:38)
PASS -- TEST 'conus13km_debug_intel' (00:19:47--00:13:53)
PASS -- TEST 'conus13km_debug_qr_intel' (00:18:48--00:13:51)
PASS -- TEST 'conus13km_debug_2threads_intel' (00:10:41--00:07:48)
PASS -- TEST 'conus13km_radar_tten_debug_intel' (00:18:44--00:13:44)

PASS -- COMPILE 'rrfs_dyn64_phy32_debug_intel' (19:07--03:11)
PASS -- TEST 'rap_control_dyn64_phy32_debug_intel' (00:06:19--00:04:46)

PASS -- COMPILE 'hafsw_intel' (25:09--10:17)
PASS -- TEST 'hafs_regional_atm_intel' (00:08:10--00:04:54)
PASS -- TEST 'hafs_regional_atm_thompson_gfdlsf_intel' (00:18:30--00:05:52)
PASS -- TEST 'hafs_regional_atm_ocn_intel' (00:10:26--00:06:49)
PASS -- TEST 'hafs_regional_atm_wav_intel' (00:16:14--00:13:08)
PASS -- TEST 'hafs_regional_atm_ocn_wav_intel' (00:30:34--00:14:48)
PASS -- TEST 'hafs_regional_1nest_atm_intel' (00:07:54--00:05:22)
PASS -- TEST 'hafs_regional_telescopic_2nests_atm_intel' (00:10:21--00:06:34)
PASS -- TEST 'hafs_global_1nest_atm_intel' (00:13:45--00:02:37)
PASS -- TEST 'hafs_global_multiple_4nests_atm_intel' (00:20:12--00:07:04)
PASS -- TEST 'hafs_regional_specified_moving_1nest_atm_intel' (00:06:43--00:03:36)
PASS -- TEST 'hafs_regional_storm_following_1nest_atm_intel' (00:20:55--00:03:26)
PASS -- TEST 'hafs_regional_storm_following_1nest_atm_ocn_intel' (00:20:50--00:04:10)
PASS -- TEST 'hafs_global_storm_following_1nest_atm_intel' (00:17:29--00:01:14)
PASS -- TEST 'gnv1_nested_intel' (00:20:42--00:03:58)

PASS -- COMPILE 'hafsw_debug_intel' (19:09--03:32)
PASS -- TEST 'hafs_regional_storm_following_1nest_atm_ocn_debug_intel' (00:28:55--00:12:26)

PASS -- COMPILE 'hafsw_faster_intel' (25:09--10:05)
PASS -- TEST 'hafs_regional_storm_following_1nest_atm_ocn_wav_intel' (00:24:55--00:08:34)

PASS -- COMPILE 'hafs_all_intel' (25:11--09:57)
PASS -- TEST 'hafs_regional_docn_intel' (00:23:23--00:06:09)
PASS -- TEST 'hafs_regional_docn_oisst_intel' (00:23:23--00:06:16)
PASS -- TEST 'hafs_regional_datm_cdeps_intel' (00:31:57--00:16:05)

PASS -- COMPILE 'datm_cdeps_intel' (20:08--05:58)
PASS -- TEST 'datm_cdeps_control_cfsr_intel' (00:06:16--00:02:38)
PASS -- TEST 'datm_cdeps_restart_cfsr_intel' (00:11:15--00:01:37)
PASS -- TEST 'datm_cdeps_control_gefs_intel' (00:07:14--00:02:36)
PASS -- TEST 'datm_cdeps_iau_gefs_intel' (00:10:16--00:02:34)
PASS -- TEST 'datm_cdeps_stochy_gefs_intel' (00:10:15--00:02:33)
PASS -- TEST 'datm_cdeps_ciceC_cfsr_intel' (00:11:16--00:02:41)
PASS -- TEST 'datm_cdeps_bulk_cfsr_intel' (00:14:16--00:02:36)
PASS -- TEST 'datm_cdeps_bulk_gefs_intel' (00:15:15--00:02:31)
PASS -- TEST 'datm_cdeps_mx025_cfsr_intel' (00:18:23--00:06:44)
PASS -- TEST 'datm_cdeps_mx025_gefs_intel' (00:18:22--00:06:38)
PASS -- TEST 'datm_cdeps_multiple_files_cfsr_intel' (00:12:14--00:02:38)
PASS -- TEST 'datm_cdeps_3072x1536_cfsr_intel' (00:12:17--00:03:54)
PASS -- TEST 'datm_cdeps_gfs_intel' (00:12:16--00:03:56)

PASS -- COMPILE 'datm_cdeps_debug_intel' (16:08--02:52)
PASS -- TEST 'datm_cdeps_debug_cfsr_intel' (00:14:17--00:06:08)

PASS -- COMPILE 'datm_cdeps_faster_intel' (18:07--06:03)
PASS -- TEST 'datm_cdeps_control_cfsr_faster_intel' (00:09:16--00:02:37)

PASS -- COMPILE 'datm_cdeps_land_intel' (06:07--00:57)
FAIL TO RUN -- TEST 'datm_cdeps_lnd_gswp3_intel' (--)
-- LOG: /scratch1/NCEPDEV/nems/Brian.Curtis/git/uturuncoglu/ufs-weather-model/feature/noahmp/tests/logs/log_hera/run_datm_cdeps_lnd_gswp3_intel.log
FAIL TO RUN -- TEST 'datm_cdeps_lnd_era5_intel' (--)
-- LOG: /scratch1/NCEPDEV/nems/Brian.Curtis/git/uturuncoglu/ufs-weather-model/feature/noahmp/tests/logs/log_hera/run_datm_cdeps_lnd_era5_intel.log
MISSING -- TEST 'datm_cdeps_lnd_era5_rst_intel' (--)

PASS -- COMPILE 'atml_intel' (15:09--10:07)
FAIL TO COMPARE -- TEST 'control_p8_atmlnd_sbs_intel' (--)
-- LOG: /scratch1/NCEPDEV/nems/Brian.Curtis/git/uturuncoglu/ufs-weather-model/feature/noahmp/tests/logs/log_hera/rt_control_p8_atmlnd_sbs_intel.log
FAIL TO COMPARE -- TEST 'control_p8_atmlnd_intel' (--)
-- LOG: /scratch1/NCEPDEV/nems/Brian.Curtis/git/uturuncoglu/ufs-weather-model/feature/noahmp/tests/logs/log_hera/rt_control_p8_atmlnd_intel.log
MISSING -- TEST 'control_restart_p8_atmlnd_intel' (--)

PASS -- COMPILE 'atmw_intel' (14:07--09:32)
PASS -- TEST 'atmwav_control_noaero_p8_intel' (00:08:52--00:01:45)

PASS -- COMPILE 'atmwm_intel' (12:08--09:35)
PASS -- TEST 'control_atmwav_intel' (00:06:28--00:01:41)

PASS -- COMPILE 'atmaero_intel' (19:10--09:10)
PASS -- TEST 'atmaero_control_p8_intel' (00:08:57--00:03:54)
PASS -- TEST 'atmaero_control_p8_rad_intel' (00:09:55--00:04:49)
PASS -- TEST 'atmaero_control_p8_rad_micro_intel' (00:09:40--00:04:58)

PASS -- COMPILE 'atmaq_intel' (11:06--08:47)
PASS -- TEST 'regional_atmaq_intel' (00:15:13--00:11:21)

PASS -- COMPILE 'atmaq_debug_intel' (13:07--03:07)
PASS -- TEST 'regional_atmaq_debug_intel' (00:25:10--00:20:09)

PASS -- COMPILE 'atm_gnu' (12:08--03:25)
PASS -- TEST 'control_c48_gnu' (00:13:22--00:11:39)
PASS -- TEST 'control_stochy_gnu' (00:06:19--00:04:04)
PASS -- TEST 'control_ras_gnu' (00:06:17--00:04:53)
PASS -- TEST 'control_p8_gnu' (00:07:59--00:04:57)
PASS -- TEST 'control_p8_ugwpv1_gnu' (00:07:57--00:04:36)
PASS -- TEST 'control_flake_gnu' (00:08:18--00:05:51)

PASS -- COMPILE 'rrfs_gnu' (12:07--03:27)
PASS -- TEST 'rap_control_gnu' (00:14:33--00:11:42)
PASS -- TEST 'rap_decomp_gnu' (00:14:31--00:11:47)
PASS -- TEST 'rap_2threads_gnu' (00:12:37--00:10:31)
PASS -- TEST 'rap_restart_gnu' (00:08:39--00:06:06)
PASS -- TEST 'rap_sfcdiff_gnu' (00:13:43--00:11:42)
PASS -- TEST 'rap_sfcdiff_decomp_gnu' (00:14:35--00:11:49)
PASS -- TEST 'rap_sfcdiff_restart_gnu' (00:10:38--00:08:53)
PASS -- TEST 'hrrr_control_gnu' (00:07:32--00:06:00)
PASS -- TEST 'hrrr_control_noqr_gnu' (00:07:29--00:05:58)
PASS -- TEST 'hrrr_control_2threads_gnu' (00:07:28--00:05:11)
PASS -- TEST 'hrrr_control_decomp_gnu' (00:07:30--00:05:53)
PASS -- TEST 'hrrr_control_restart_gnu' (00:05:25--00:03:33)
PASS -- TEST 'hrrr_control_restart_noqr_gnu' (00:05:25--00:03:12)
PASS -- TEST 'rrfs_v1beta_gnu' (00:13:41--00:11:28)

PASS -- COMPILE 'atm_dyn32_debug_gnu' (12:07--03:13)
PASS -- TEST 'control_diag_debug_gnu' (00:03:28--00:01:35)
PASS -- TEST 'regional_debug_gnu' (00:09:42--00:07:39)
PASS -- TEST 'rap_control_debug_gnu' (00:04:21--00:02:31)
PASS -- TEST 'hrrr_control_debug_gnu' (00:04:19--00:02:28)
PASS -- TEST 'hrrr_gf_debug_gnu' (00:04:18--00:02:29)
PASS -- TEST 'hrrr_c3_debug_gnu' (00:04:17--00:02:28)
PASS -- TEST 'rap_diag_debug_gnu' (00:04:32--00:02:43)
PASS -- TEST 'rap_noah_sfcdiff_cires_ugwp_debug_gnu' (00:05:20--00:03:51)
PASS -- TEST 'rap_progcld_thompson_debug_gnu' (00:04:22--00:02:32)
PASS -- TEST 'rrfs_v1beta_debug_gnu' (00:04:19--00:02:27)
PASS -- TEST 'control_ras_debug_gnu' (00:03:17--00:01:29)
PASS -- TEST 'control_stochy_debug_gnu' (00:04:16--00:02:10)
PASS -- TEST 'control_debug_p8_gnu' (00:04:39--00:01:41)
PASS -- TEST 'rap_flake_debug_gnu' (00:04:18--00:02:34)
PASS -- TEST 'rap_clm_lake_debug_gnu' (00:04:20--00:02:50)
PASS -- TEST 'gnv1_c96_no_nest_debug_gnu' (00:06:33--00:04:11)

PASS -- COMPILE 'wam_debug_gnu' (11:07--01:39)
PASS -- TEST 'control_wam_debug_gnu' (00:04:16--00:02:30)

PASS -- COMPILE 'rrfs_dyn32_phy32_gnu' (07:07--03:25)
PASS -- TEST 'rap_control_dyn32_phy32_gnu' (00:13:30--00:11:52)
PASS -- TEST 'hrrr_control_dyn32_phy32_gnu' (00:08:30--00:06:10)
PASS -- TEST 'rap_2threads_dyn32_phy32_gnu' (00:12:39--00:10:49)
PASS -- TEST 'hrrr_control_2threads_dyn32_phy32_gnu' (00:07:35--00:05:14)
PASS -- TEST 'hrrr_control_decomp_dyn32_phy32_gnu' (00:07:28--00:06:04)
PASS -- TEST 'rap_restart_dyn32_phy32_gnu' (00:15:36--00:08:58)
PASS -- TEST 'hrrr_control_restart_dyn32_phy32_gnu' (00:05:20--00:03:16)
PASS -- TEST 'conus13km_control_gnu' (00:06:56--00:04:17)
PASS -- TEST 'conus13km_2threads_gnu' (00:04:40--00:01:53)
PASS -- TEST 'conus13km_restart_mismatch_gnu' (00:04:40--00:02:17)

PASS -- COMPILE 'atm_dyn64_phy32_gnu' (08:08--04:52)
PASS -- TEST 'rap_control_dyn64_phy32_gnu' (00:08:38--00:06:56)

PASS -- COMPILE 'atm_dyn32_phy32_debug_gnu' (07:06--03:24)
PASS -- TEST 'rap_control_debug_dyn32_phy32_gnu' (00:04:21--00:02:35)
PASS -- TEST 'hrrr_control_debug_dyn32_phy32_gnu' (00:04:19--00:02:32)
PASS -- TEST 'conus13km_debug_gnu' (00:09:47--00:07:03)
PASS -- TEST 'conus13km_debug_qr_gnu' (00:09:43--00:07:11)
PASS -- TEST 'conus13km_debug_2threads_gnu' (00:06:38--00:04:24)
PASS -- TEST 'conus13km_radar_tten_debug_gnu' (00:09:38--00:07:00)

PASS -- COMPILE 'atm_dyn64_phy32_debug_gnu' (06:07--03:18)
PASS -- TEST 'rap_control_dyn64_phy32_debug_gnu' (00:04:20--00:02:35)

PASS -- COMPILE 's2swa_gnu' (16:10--13:59)
PASS -- TEST 'cpld_control_p8_gnu' (00:13:10--00:10:57)

PASS -- COMPILE 's2s_gnu' (16:09--13:45)
PASS -- TEST 'cpld_control_nowave_noaero_p8_gnu' (00:09:06--00:06:46)

PASS -- COMPILE 's2swa_debug_gnu' (05:07--02:19)
PASS -- TEST 'cpld_debug_p8_gnu' (00:09:04--00:06:12)

PASS -- COMPILE 's2sw_pdlib_gnu' (16:10--13:58)
PASS -- TEST 'cpld_control_pdlib_p8_gnu' (00:23:58--00:21:54)

PASS -- COMPILE 's2sw_pdlib_debug_gnu' (05:07--02:05)
PASS -- TEST 'cpld_debug_pdlib_p8_gnu' (00:14:51--00:12:59)

PASS -- COMPILE 'datm_cdeps_gnu' (16:08--13:41)
PASS -- TEST 'datm_cdeps_control_cfsr_gnu' (00:04:15--00:02:55)

SYNOPSIS:
Starting Date/Time: 20240114 16:22:40
Ending Date/Time: 20240114 18:40:11
Total Time: 02h:17m:54s)
Compiles Completed: 52/52
Tests Completed: 233/239
Failed Tests:
-- TEST 'datm_cdeps_lnd_gswp3_intel': FAIL TO RUN
-- TEST 'datm_cdeps_lnd_era5_intel': FAIL TO RUN
-- TEST 'datm_cdeps_lnd_era5_rst_intel': MISSING
-- TEST 'control_p8_atmlnd_sbs_intel': FAIL TO COMPARE
-- TEST 'control_p8_atmlnd_intel': FAIL TO COMPARE
-- TEST 'control_restart_p8_atmlnd_intel': MISSING

NOTES:
A file 'test_changes.out' was generated with list of all failed tests.
You can use './rt.sh -b test_changes.out' to generate baselines for the failed tests.
If you are using this log as a pull request verification, please commit 'test_changes.out'.

Result: FAILURE

====END OF HERA REGRESSION TESTING LOG====
```

**Comment by BrianCurtis-NOAA** [comment]
I think maybe we should save the fail log location and have it show at the Synopsis, that makes it easiest for devs to get to the location of the failed tests/compiles.

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA It's weird--in your comment above, the times show with a "--" . 

PASS -- COMPILE 's2swa_32bit_intel' (13:08--11:22)
PASS -- TEST 'cpld_control_p8_mixedmode_intel' (00:13:21--00:05:17)

I'm not sure what these are. But the actual files shows

COMPILE 's2swa_32bit_intel': PASS | Times (RT/Compile): (00:14:09/00:12:10)
TEST 'cpld_control_p8_mixedmode_intel': PASS | Times (RT/Test): (00:08:15/00:05:21)

What are the two times in "RT/Compile" or "RT/Test"?

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA It's weird--in your comment above, the times show with a "--" .
> 
> PASS -- COMPILE 's2swa_32bit_intel' (13:08--11:22) PASS -- TEST 'cpld_control_p8_mixedmode_intel' (00:13:21--00:05:17)
> 
> I'm not sure what these are. But the actual files shows
> 
> COMPILE 's2swa_32bit_intel': PASS | Times (RT/Compile): (00:14:09/00:12:10) TEST 'cpld_control_p8_mixedmode_intel': PASS | Times (RT/Test): (00:08:15/00:05:21)
> 
> What are the two times in "RT/Compile" or "RT/Test"?

Correct. I'm using ufuk's PR as a test with failures and adding them with their updates in comments. I have attached and older log format of a full passing suite. Once I finish tinkering with the layout, i'll get an updated full passing suite into the repo. The two times represent the time the script takes (initialize, run, finalize), and then the run phase of that.

**Comment by junwang-noaa** [comment]
@BrianCurtis-NOAA Can you also add memory change in the log? Thanks

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA Can you also add memory change in the log? Thanks

Yes, I don't recall where in the code that's calculated/stored. I'll see if i can find it.

**Comment by BrianCurtis-NOAA** [comment]
Testing the latest layout using ufuk's PR because it fails both in run and compare, so it's a good example of how the script will look:
```
====START OF HERA REGRESSION TESTING LOG====

UFSWM hash used in testing:
edf51800c484f2a762023b2aaad7761d571e1be9

Submodule hashes used in testing:
 37cbb7d6840ae7515a9a8f0dfd4d89461b3396d1 AQM (v0.2.0-37-g37cbb7d)
 78b9504c0f7c537d7f143ca02e5eef62fb88e80e CDEPS-interface/CDEPS (cdeps0.6.3-30-g78b9504)
 620e48fe75d92aa607af7e21f2d8691baddd2851 CICE-interface/CICE (CICE6.0.0-445-g620e48f)
 dadb082291ce3487d8b5a8e191a0abe45b69c8af CMEPS-interface/CMEPS (cmeps0.9.13-26-gdadb0822)
 cabd7753ae17f7bfcc6dad56daf10868aa51c3f4 CMakeModules (v1.0.0-28-gcabd775)
 f4cbc079d41d4c7933fec39c0f03ba8db2d14f9c FV3 (remotes/origin/feature/noahmp)
 041422934cae1570f2f0e67239d5d89f11c6e1b7 GOCART (sdr_v2.1.2.6-119-g0414229)
 35789c757766e07f688b4c0c7c5229816f224b09 HYCOM-interface/HYCOM (2.3.00-121-g35789c7)
 60c397b910c9f0c5d1b35f9fea2293ccebd27fc8 MOM6-interface/MOM6 (dev/master/repository_split_2014.10.10-9875-g60c397b91)
 5d8319df205b0dbe6716bc40bb8065b8ea79ce5f NOAHMP-interface/noahmp (v3.7.1-421-g5d8319d)
 02693d837f2cd99d20ed08515878c2b5e9525e64 WW3 (6.07.1-343-g02693d83)
 a5561802021d89a9a1e2b52cb69393efcdc6f71c stochastic_physics (ufs-v2.0.0-199-ga556180)


NOTES:
Times are at the end of each compile/test in format (MM:SS).
The first time is how long the scipt (prep+run+finalize) ran.
The second time is specifically how long the run phase ran.
Times will be empty for failed tests.

PASS -- COMPILE 'datm_cdeps_land_intel' (03:06--01:14)
FAIL TO RUN -- TEST 'datm_cdeps_lnd_gswp3_intel' (--)
FAIL TO RUN -- TEST 'datm_cdeps_lnd_era5_intel' (--)
MISSING -- TEST 'datm_cdeps_lnd_era5_rst_intel' (--)

PASS -- COMPILE 'atml_intel' (12:08--10:38)
FAIL TO COMPARE -- TEST 'control_p8_atmlnd_sbs_intel' (--)
FAIL TO COMPARE -- TEST 'control_p8_atmlnd_intel' (--)
MISSING -- TEST 'control_restart_p8_atmlnd_intel' (--)

SYNOPSIS:
Starting Date/Time: 20240115 15:12:53
Ending Date/Time: 20240115 15:42:13
Total Time: 00h:29m:26s)
Compiles Completed: 2/2
Tests Completed: 0/6
Failed Tests:
* TEST datm_cdeps_lnd_gswp3_intel: FAIL TO RUN
-- LOG: /scratch1/NCEPDEV/nems/Brian.Curtis/git/uturuncoglu/ufs-weather-model/feature/noahmp/tests/logs/log_hera/run_datm_cdeps_lnd_gswp3_intel.log
* TEST datm_cdeps_lnd_era5_intel: FAIL TO RUN
-- LOG: /scratch1/NCEPDEV/nems/Brian.Curtis/git/uturuncoglu/ufs-weather-model/feature/noahmp/tests/logs/log_hera/run_datm_cdeps_lnd_era5_intel.log
* TEST datm_cdeps_lnd_era5_rst_intel: MISSING
-- LOG: N/A
* TEST control_p8_atmlnd_sbs_intel: FAIL TO COMPARE
-- LOG: /scratch1/NCEPDEV/nems/Brian.Curtis/git/uturuncoglu/ufs-weather-model/feature/noahmp/tests/logs/log_hera/rt_control_p8_atmlnd_sbs_intel.log
* TEST control_p8_atmlnd_intel: FAIL TO COMPARE
-- LOG: /scratch1/NCEPDEV/nems/Brian.Curtis/git/uturuncoglu/ufs-weather-model/feature/noahmp/tests/logs/log_hera/rt_control_p8_atmlnd_intel.log
* TEST control_restart_p8_atmlnd_intel: MISSING
-- LOG: N/A

NOTES:
A file 'test_changes.out' was generated with list of all failed tests.
You can use './rt.sh -b test_changes.out' to generate baselines for the failed tests.
If you are using this log as a pull request verification, please commit 'test_changes.out'.

Result: FAILURE

====END OF HERA REGRESSION TESTING LOG====
```

**Comment by BrianCurtis-NOAA** [comment]
[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/14031986/RegressionTests_hera.log)
Here is a RT log with some failures from Ufuk's PR with the modifications for adding sizes to tests. Should help track size changes with each PR.

**Comment by DeniseWorthen** [comment]
So I like that it is more readable than previous versions and that all the failed stuff is in one place. I'm not a big fan of the time formats that you've used ``(05:18--02:26)``. This to me looks like a start/end time, but what it is two different elapsed times. I think a "," makes more sense than "--".

Also, why is the bmark test memory 04098968? Is there really a leading zero? Why?

**Comment by BrianCurtis-NOAA** [comment]
Marked as draft because I found another issue that needs to be addressed.

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA Did you mean to commit a log file w/ conflicts?

**Comment by BrianCurtis-NOAA** [comment]
No, i tried to keep the one i had a while ago, but i'm re-running Ufuk's to get the new updates and to verify my test_changes.out file works with `./rt.sh -c -b test_changes.out` without manually editing it.

**Comment by BrianCurtis-NOAA** [comment]
I've made a small change and addition:
- Options selected by the user will be in the logs
- Jobs that use -c, will show that a test was skipped as it does not generate a baseline

```
====START OF HERA REGRESSION TESTING LOG====

UFSWM hash used in testing:
11ad030eca21e0e9c06cccf750a8b6048ac37d21

Submodule hashes used in testing:
 37cbb7d6840ae7515a9a8f0dfd4d89461b3396d1 AQM (v0.2.0-37-g37cbb7d)
 89603d16f39675624fc8518da50d9515cd5f18c6 CDEPS-interface/CDEPS (cdeps0.4.17-39-g89603d1)
 620e48fe75d92aa607af7e21f2d8691baddd2851 CICE-interface/CICE (CICE6.0.0-445-g620e48f)
 13ed05982efc95c077efc3b9609688554e3a854c CMEPS-interface/CMEPS (cmeps_v0.4.1-1409-g13ed059)
 cabd7753ae17f7bfcc6dad56daf10868aa51c3f4 CMakeModules (v1.0.0-28-gcabd775)
 bd38c5676d99f350551f6b41cc1d9ffad020ce5c FV3 (remotes/origin/HEAD)
 041422934cae1570f2f0e67239d5d89f11c6e1b7 GOCART (sdr_v2.1.2.6-119-g0414229)
 35789c757766e07f688b4c0c7c5229816f224b09 HYCOM-interface/HYCOM (2.3.00-121-g35789c7)
 c8a7325c040b4cb1327c55c8248e8e66972239a5 MOM6-interface/MOM6 (dev/master/repository_split_2014.10.10-9878-gc8a7325c0)
 0cd3e23ae5d35ef93e205e4d0c3b13ccc0d851f5 NOAHMP-interface/noahmp (v3.7.1-423-g0cd3e23)
 4ffc47e10e3d3f3bbee50251aacb28b7e0165b92 WW3 (6.07.1-344-g4ffc47e1)
 a5561802021d89a9a1e2b52cb69393efcdc6f71c stochastic_physics (ufs-v2.0.0-199-ga556180)


NOTES:
(Times)[Memory] are at the end of each compile/test in format (MM:SS)[Size(KB)].
The first time is how long the scipt (prep+run+finalize) ran.
The second time is specifically how long the run phase ran.
Times/Memory will be empty for failed tests.

RT.SH OPTIONS USED:
* (-a) - HPC PROJECT ACCOUNT: nems
* (-b) - NEW BASELINES FROM FILE: test_changes.in
* (-c) - CREATE NEW BASELINES
* (-e) - USE ECFLOW

PASS -- COMPILE 's2swa_intel' [13:07, 11:38]
PASS -- TEST 'cpld_control_p8_intel' [07:53, 05:38](3180844)
SKIPPED (TEST DOES NOT GENERATE BASELINE) -- TEST 'cpld_restart_p8_intel' [, ]()

PASS -- COMPILE 'rrfs_gnu' [05:06, 03:30]
PASS -- TEST 'rap_control_gnu' [13:28, 11:37](896344)
SKIPPED (TEST DOES NOT GENERATE BASELINE) -- TEST 'rap_restart_gnu' [, ]()

SYNOPSIS:
Starting Date/Time: 20240131 02:39:30
Ending Date/Time: 20240131 03:01:44
Total Time: 00h:22m:23s
Compiles Completed: 2/2
Tests Completed: 4/4

NOTES:
A file 'test_changes.out' was generated but is empty.
If you are using this log as a pull request verification, please commit 'test_changes.out'.

Result: SUCCESS

====END OF HERA REGRESSION TESTING LOG====
```

**Comment by zach1221** [comment]
Hey @BrianCurtis-NOAA can you sync up your branch, please, so I can do some preliminary testing?

**Comment by BrianCurtis-NOAA** [comment]
> Hey @BrianCurtis-NOAA can you sync up your branch, please, so I can do some preliminary testing?

Done

File: tests/rt.sh [hunk 1]
```diff
@@ -30,77 +30,405 @@ usage() {
...
+                  DATE1=$(echo "$times" | cut -d ',' -f2 )
+                  DATE2=$(echo "$times" | cut -d ',' -f3 )
+                  DATE3=$(echo "$times" | cut -d ',' -f4 )
+                  DATE4=$(echo "$times" | cut -d ',' -f5 )
+
+                  COMPILE_TIME=$(date --date=@$((DATE3 - DATE2)) +'%M:%S')
+                  RT_COMPILE_TIME=$(date --date=@$((DATE4 - DATE1)) +'%M:%S')
+
+              done < "$TIME_FILE"
+            fi
```
Comment (BrianCurtis-NOAA) [inline tests/rt.sh:251]: @DusanJovic-NOAA I think you did work to create the timestamp files. I'm not sure I understand what time is for what in there. Could you double check I have it right, or what corrections I might need?

File: tests/rt.sh [hunk 2]
```diff
@@ -30,77 +30,405 @@ usage() {
...
+                  DATE1=$(echo "$times" | cut -d ',' -f2 )
+                  DATE2=$(echo "$times" | cut -d ',' -f3 )
+                  DATE3=$(echo "$times" | cut -d ',' -f4 )
+                  DATE4=$(echo "$times" | cut -d ',' -f5 )
+
+                  TEST_TIME=$(date --date=@$((DATE3 - DATE2)) +'%M:%S')
+                  RT_TEST_TIME=$(date --date=@$((DATE4 - DATE1)) +'%M:%S')
+
+              done < "$TIME_FILE"
+            fi
```
Comment (BrianCurtis-NOAA) [inline tests/rt.sh:323]: @DusanJovic-NOAA same here, I'm not sure I understand what time is for what in there. Could you double check I have it right, or what corrections I might need?

Comment (DusanJovic-NOAA) [reply tests/rt.sh:323]: Looks good. First and last timestamp are starting and ending time of the run_test script, while second and third are starting and ending time of the corresponding test job card script. Same for the run_compile script and the compile job.

**Comment by zach1221** [comment]
@BrianCurtis-NOAA getting command not found errors when trying to run ecflow with this branch. Issue seems to be coming from rt_utils.sh. I'm not certain yet what code may be causing the issue, so I'll keep you posted on that
+ ecflow_client --halt=yes
rt_utils.sh: line 683: ecflow_client: command not found
+ ecflow_client --check_pt
rt_utils.sh: line 684: ecflow_client: command not found
+ ecflow_client --terminate=yes
rt_utils.sh: line 685: ecflow_client: command not found

The other hpcs are running fine so far.

Looks like derecho doesn't like the "ecflow_client" in rt_utils.sh. Doesn't seem to recognize it all of a sudden.

PASSED:
Hercules: /work/noaa/nems/zshrader/hercules/rt-2061/tests/logs
Orion: /work2/noaa/stmp/zshrader/orion/rt-2061/tests/logs
Jet: /mnt/lfs4/HFIP/hfv3gfs/Zachary.Shrader/rt-2061/tests/logs
Hera: /scratch1/NCEPDEV/stmp2/Zachary.Shrader/rt-2061/tests/logs

**Comment by zach1221** [comment]
@BrianCurtis-NOAA I think we're planning to work this PR next. I'll continue looking through the rt scripts on derecho.

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA I think we're planning to work this PR next. I'll continue looking through the rt scripts on derecho.

I'm onto something with that, if you can hop onto slack we can discuss.

**Comment by BrianCurtis-NOAA** [comment]
@zach1221 it looks like the Derecho issue would block any PR at this point, should we proceed with testing? Have the ORT's been successful?

**Comment by zach1221** [comment]
> @zach1221 it looks like the Derecho issue would block any PR at this point, should we proceed with testing? Have the ORT's been successful?

I don't think there's another PR ready at the moment. We could continue testing against this PR today, on the other machines, while Derecho is worked on. I've got ORTs running on Hera now. @jkbk2004 do you want to wait until Derecho is ready?

**Comment by jkbk2004** [comment]
> > @zach1221 it looks like the Derecho issue would block any PR at this point, should we proceed with testing? Have the ORT's been successful?
> 
> I don't think there's another PR ready at the moment. We could continue testing against this PR today, on the other machines, while Derecho is worked on. I've got ORTs running on Hera now. @jkbk2004 do you want to wait until Derecho is ready?

@zach1221 can you submit jobs in sequential mode even if rocoto/eclfow are not functional ?

**Comment by BrianCurtis-NOAA** [comment]
> > > @zach1221 it looks like the Derecho issue would block any PR at this point, should we proceed with testing? Have the ORT's been successful?
> > 
> > 
> > I don't think there's another PR ready at the moment. We could continue testing against this PR today, on the other machines, while Derecho is worked on. I've got ORTs running on Hera now. @jkbk2004 do you want to wait until Derecho is ready?
> 
> @zach1221 can you submit jobs in sequential mode even if rocoto/eclfow are not functional ?

This would take an extremely long time.

**Comment by zach1221** [comment]
> > > > @zach1221 it looks like the Derecho issue would block any PR at this point, should we proceed with testing? Have the ORT's been successful?
> > > 
> > > 
> > > I don't think there's another PR ready at the moment. We could continue testing against this PR today, on the other machines, while Derecho is worked on. I've got ORTs running on Hera now. @jkbk2004 do you want to wait until Derecho is ready?
> > 
> > 
> > @zach1221 can you submit jobs in sequential mode even if rocoto/eclfow are not functional ?
> 
> This would take an extremely long time.

It's still running since last night. Hopefully not too much longer.

**Comment by zach1221** [comment]
Jet is mostly done. Just had one test timeout that I'm rerunning.

**Comment by BrianCurtis-NOAA** [comment]
What changes were made in Derecho to allow these tests to pass? I didn't see any Derecho changes in that regard.

**Comment by zach1221** [comment]
> What changes were made in Derecho to allow these tests to pass? I didn't see any Derecho changes in that regard.

I'm about to commit them.

**Comment by zach1221** [comment]
Ok we should be ready to proceed with final review here. @jkbk2004 fyi

**Comment by zach1221** [comment]
Hold off on approving actually. We want to make one additional template change.

**Comment by BrianCurtis-NOAA** [comment]
Should be good to go for review/merge.
@jkbk2004 @SadeghTabas-NOAA

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]
