### PR TITLE
Remove IPD (step 1)

### LINKED ISSUE #348: utest broken with WW3 update
## Description

The recent merge of https://github.com/ufs-community/ufs-weather-model/pull/334 broke the unit tests, because (at least) the newly introduced environment variable `INPUTDATA_ROOT_WW3` is undefined.

### To Reproduce:

Check out current head of develop on hera, run `./utest -n fv3_ccpp_control -e -k 2>&1 | tee utest_hera_intel.log`

### Fix

This will be fixed in https://github.com/ufs-community/ufs-weather-model/pull/331

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

Make `CCPP=Y` the default in `tests/compile.sh`. Remove `CCPP=Y` from `tests/rt*.conf` and adjust formatting.

Also:
- update submodule pointer for MOM6 to include PR https://github.com/ufs-community/ufs-weather-model/issues/341 ("Update MOM6 to GFDL's 20201218 commit")
- add `modulefiles/wcoss_cray/fv3_debug` (identical to `modulefiles/wcoss_cray/fv3`)
- fix broken `utest` (see https://github.com/ufs-community/ufs-weather-model/issues/348)

### Issue(s) addressed

This is step 1 of https://github.com/NOAA-EMC/fv3atm/issues/214 - minimal changes only, as previously agreed upon.

Fixes https://github.com/ufs-community/ufs-weather-model/issues/348

## Testing

Regression/manual testing will be done on all tier-1,2,3 platforms (tier-1 pre-commit, tier-2,3 as time permits).

Preliminary regression testing on hera 12/15/2020:
- all tests pass with hera.gnu against existing baseline (develop-20201215)
[rt_hera_gnu.log](https://github.com/ufs-community/ufs-weather-model/files/5703274/rt_hera_gnu.log)
- all tests pass with hera.gnu against existing baseline (develop-20201215)
[rt_hera_intel.log](https://github.com/ufs-community/ufs-weather-model/files/5703713/rt_hera_intel.log)

This preliminary regression testing will be repeated once it is time to commit these PRs, before removing the `_ccpp` or `_prod` suffices from the regression test baseline/run directories (this will require creating new baselines).

## Dependencies

https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/48
https://github.com/NOAA-EMC/fv3atm/pull/215
https://github.com/ufs-community/ufs-weather-model/pull/331

### CODE REVIEW

File: tests/rt.sh [hunk 1]
```diff
@@ -614,11 +614,11 @@ EOF
...
       # Set RT_SUFFIX (regression test run directories and log files) and BL_SUFFIX
-      # (regression test baseline directories) for REPRO (IPD, CCPP) or PROD (CCPP) runs
+      # (regression test baseline directories) for REPRO or PROD runs
       if [[ ${MAKE_OPT^^} =~ "REPRO=Y" ]]; then
         RT_SUFFIX="_repro"
         BL_SUFFIX="_repro"
-      elif [[ ${MAKE_OPT^^} =~ "CCPP=Y" ]]; then
+      else
         RT_SUFFIX="_prod"
         BL_SUFFIX="_ccpp"
```
Comment (DusanJovic-NOAA) [inline tests/rt.sh:625]: Can BL_SUFFIX be removed?

Comment (climbfuji) [reply tests/rt.sh:625]: I was thinking to do this, yes, if @junwang-noaa and you are ok. I made the change and will keep it until the last minute (before creating new baselines), however, so that I can test against the existing baselines first when it is time to commit. This way we know for sure that the PR doesn't change anything we don't expect it to change.

File: tests/rt.conf [hunk 2]
```diff
@@ -2,270 +2,271 @@
...
-RUN     | fv3_ccpp_iau                                                                                                                   | standard    | cheyenne.intel | fv3         |
-RUN     | fv3_ccpp_ca                                                                                                                    | standard    | hera.intel     | fv3         |
-RUN     | fv3_ccpp_ca                                                                                                                    | standard    | orion.intel    | fv3         |
-RUN     | fv3_ccpp_ca                                                                                                                    | standard    | cheyenne.intel | fv3         |
-RUN     | fv3_ccpp_lndp                                                                                                                  | standard    | hera.intel     | fv3         |
+RUN     | fv3_ccpp_control                                                                                                        | standard    |                | fv3         |
```
Comment (junwang-noaa) [inline tests/rt.conf:7]: I'd suggest to remove all the ccpp in the test names

File: tests/compile.sh [hunk 3]
```diff
@@ -100,46 +100,42 @@ else
...
 
-  # FIXME - create CCPP include directory before building FMS to avoid
-  # gfortran warnings of non-existent include directory (adding
-  # -Wno-missing-include-dirs) to the GNU compiler flags does not work,
-  # see also https://gcc.gnu.org/bugzilla/show_bug.cgi?id=55534);
-  # this line can be removed once FMS becomes a pre-installed library
-  mkdir -p $PATHTR/FV3/ccpp/include
-  # Similar for this directory, which apparently never gets populated
-  mkdir -p $PATHTR/FMS/fms2_io/include
+CMAKE_FLAGS="${CMAKE_FLAGS} -DCCPP=ON -DMPI=ON"
```
Comment (junwang-noaa) [inline tests/compile.sh:112]: Can we move all the CMAKE_FLAGS options down to build.sh? People report that  build.sh does not work any more without passing these CMAKE_FLAGS, so to avoid changes in downstream jobs, I think it's good to move the compile options down to build.sh

File: tests/rt.conf (hunk 2 above)
Comment (climbfuji) [reply tests/rt.conf:7]: Can do, but this means several changes in `fv3_conf` files, too (linking restart files from a previous coldstart run etc). 

Originally we wanted to make this commit as small as possible and it is growing and growing. There is a lot more cleanup work to be done (see also the different steps identified in my issue). I suggest to add this as another cleanup step to the issue instead of commingling everything in one commit.

File: tests/compile.sh (hunk 3 above)
Comment (climbfuji) [reply tests/compile.sh:112]: Not as part of this commit.

File: tests/rt.sh (hunk 1 above)
Comment (junwang-noaa) [reply tests/rt.sh:625]: I think it is good to remove all the ccpp in the test name including both prod and repro

Comment (climbfuji) [reply tests/rt.sh:625]: As I said, this will require several changes in `fv3_conf/*` files and I would really prefer to do this separately. It's ok to remove the `_ccpp` and `_prod` suffices as suggested by Dusan, because that is a change in this file only, but renaming all tests is too much for this commit in my opinion.

File: tests/compile.sh (hunk 3 above)
Comment (DusanJovic-NOAA) [reply tests/compile.sh:112]: Only the cmake options that we know must be always ON or OFF (but then, many option that must be always ON or OFF can be removed entirely from the build system).
All other options must remain in compile.sh

File: tests/rt.sh (hunk 1 above)
Comment (junwang-noaa) [reply tests/rt.sh:625]: If you want to have incremental commits, that is fine, please specify that in your PR. maybe we can call this IPD removal Part1.

Comment (climbfuji) [reply tests/rt.sh:625]: Sure, I updated the issue and the two PRs.

Comment (junwang-noaa) [reply tests/rt.sh:625]: Also if part 2 is renaming the test. Maybe we also need to have part3 to remove the "ifdef CCPP" in fv3 code and remove the -DCCPP=ON? So far from here it is not clear to me what the "Remove IPD" means

Comment (climbfuji) [reply tests/rt.sh:625]: Please read the issue.

File: tests/compile.sh (hunk 3 above)
Comment (junwang-noaa) [reply tests/compile.sh:112]: Yes, that is fine.

**Comment by junwang-noaa** [comment]
@climbfuji, Jiande updated MOM6 (see issue [#341](https://github.com/ufs-community/ufs-weather-model/issues/341), would you mind updating the MOM6 to point to the latest dev/emc version in this PR? The update will not change results. Thanks

**Comment by climbfuji** [comment]
> @climbfuji, Jiande updated MOM6 (see issue [#341](https://github.com/ufs-community/ufs-weather-model/issues/341), would you mind updating the MOM6 to point to the latest dev/emc version in this PR? The update will not change results. Thanks

I updated the MOM6 submodule pointer. Now waiting for the current commit (WW3 update) to be merged before pulling that one in and running the regression tests.

**Comment by climbfuji** [comment]
This PR is ready for testing.

**Comment by climbfuji** [comment]
@MinsukJi-NOAA same for this PR, the utests fail with a non-informative error message:
```
107 cases to compile: std
108 compiling std with compile option CCPP=Y SUITES=FV3_GFS_2017
109 Died with error code 2
110 The command '/bin/sh -c ./utest -n $test_name -c $build_case -z' returned a non-zero code: 2
111
112 Error: Process completed with exit code 2.
```
Could you take a look, please? Thanks.

**Comment by climbfuji** [comment]
The CI tests now pass, I am capturing a screenshot so that we can skip rerunning them if necessaary.

Screen Shot 2020-12-28 at 4 59 15 PM

File: tests/rt.sh (hunk 1 above)
Comment (climbfuji) [reply tests/rt.sh:625]: The removal will be part of one of the next steps when we rename all regression tests etc.

**Comment by climbfuji** [comment]
@DusanJovic-NOAA Ready to merge. Jun is on leave today, as far as I know. The CI tests did pass yesterday, up to you to wait for them to complete (and to see if Jun is approving the PR or not).

**Review by DusanJovic-NOAA — APPROVED** [review]
