### PR TITLE
Derecho updates: new spack-stack-1.9.2, rocoto, ecflow paths, TPN=128 default + Fix UFSATM CI github action #3035

### LINKED ISSUE #2177: inefficient use of resources on derecho
## Description

Derecho has TPN=128 but in most jobs we are vastly under-using these nodes. For example, the cpld_control_p8 test needs 200 tasks but the job card requests

```
#PBS -l select=3:ncpus=96:mpiprocs=96:ompthreads=1"
```

On Gaea, the same test uses 
```
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=128

srun --label -n 256 ./fv3.exe
```

See related discussions [here](https://github.com/ufs-community/ufs-weather-model/discussions/2135) and [here](https://github.com/ufs-community/ufs-srweather-app/discussions/1015)

### LINKED ISSUE #3034: UFASTM CI GitHub action needs to be updated
UFASTM CI fails while building spack stack in crtm with "No space left on device" error. https://github.com/NOAA-EMC/ufsatm/issues/1045

### PR DESCRIPTION
**Pull request by natalie-perlin**
## Commit Queue Requirements:

- [ ] Fill out all sections of this template.
- [ ] All sub component pull requests have been reviewed by their code managers.
- [ ] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [ ] Commit 'test_changes.list' from previous step
---
## Description:
Updates for Derecho:
- corrected spack-stack-1.9.2 environment
- rocoto modulefile location
- ecflow library from spack-stack-1.9.2 build
- add compile time on Derecho (01:00:00 instead of 00:30:00; compilation takes > 30 min)
- load nccmp/1.9.1.0 from the spack-stack built, not from the system. System-install nccmp produces errors due to missing source file. (Courtesy of Ratko Vasic)
- all GNU tests enabled for Derecho

A job_card for Derecho remains the same, being different from the way MPI jobs are launched on other systems. The way Derecho system is set up for the MPI jobs makes it much sensitive to the unbalanced MPI load. Attempts to use the same approach as for other systems, i.e., using the following entries in job_card:
```
#PBS -l select=@[NODES]:ncpus=@[TPN]:ompthreads=@[THRD]
mpiexec -n @[TASKS] --cpu-bind core - -depth @[THRD] ./fv3.exe
```
where [TASKS]= [TPN] * [NODES]
(for simplicity, assume THRD=1)

worked for some tests, but failed for others. Individual customization of RTs would then be required for many tests, and may also differe for rocoto vs ecflow submission.
Existing way of launching the RTs, when UFS_TASKS and TPN variables are computed for Derecho, make all the RTs pass except for two tests:
cpld_control_c192_p8_intel
cpld_control_p8_lnd_intel

These two tests were excluded from the RT in the commit [db392e91de](https://github.com/ufs-community/ufs-weather-model/pull/2863/commits/db392e91dee296b895b278562fa9cd9d431ed1f4)

Rocoto modulefile path and module loading:
```
     module use /glade/work/epicufsrt/contrib/derecho/modulefiles
     module load rocoto/1.3.7
```

Ecflow module used is from spack-stack-1.9.2:
 ```
     module use /glade/work/epicufsrt/contrib/spack-stack/derecho/spack-stack-1.9.2/envs/ue-oneapi-2024.2.1/install/modulefiles/oneapi/2024.2.1
      module load stack-python/3.11.7
      module load ecflow/5.11.4

```

The rocoto-submitted RTs finished successfully for all tests, 
i) first time through creating a baseline: 
 [RegressionTests_derecho.log_SUCCESS.txt](https://github.com/user-attachments/files/24034951/RegressionTests_derecho.log_SUCCESS.txt)
 
ii)  second time through testing against the baseline:
 [RegressionTests_derecho.log_SUCCESS2.txt](https://github.com/user-attachments/files/24034959/RegressionTests_derecho.log_SUCCESS2.txt)
 
RTs lauched with ecflow succeed all except the two tests
[test_changes.list_001.txt](https://github.com/user-attachments/files/24034919/test_changes.list_001.txt):
cpld_control_sfs intel
cpld_debug_sfs intel

When resubmitting by hand using "qsub < job_card", the test `cpld_control_sfs` intel finished successfully. 
See /glade/derecho/scratch/nperlin/FV3_RT/rt_62263/cpld_control_sfs_intel_RERUN

### Priority:

* Normal

### UFSWM:

* Addresses #https://github.com/ufs-community/ufs-weather-model/issues/2033 (not fully resolved)
* Closes https://github.com/ufs-community/ufs-weather-model/issues/2177 
* Addressed the issue: https://github.com/ufs-community/ufs-weather-model/issues/3017
* Addresses the issue: https://github.com/ufs-community/ufs-weather-model/issues/2860 (partially resolved; build works OK but not ifx-based)
* Closes #3034

### Sub component Pull Requests:

* UFSATM: https://github.com/NOAA-EMC/ufsatm/pull/1049

### UFSWM Blocking Dependencies:

* None

### Documentation:

* No documentation update is required for this PR

---
### Regression Test Changes (Please commit test_changes.list):

* PR Adds New Tests/Baselines.
* PR Updates/Changes Baselines.
* No Baseline Changes.

### Input data Changes:

* None.
* New input data.
* Updated input data.

### Library Changes/Upgrades:

Please delete what is not needed.
-->
* Addresses the issue:
  * Git Stack Issue https://github.com/JCSDA/spack-stack/pull/1726/files
  
  
 ## Testing Logs ##

 [RegressionTests_derecho.log_SUCCESS.txt](https://github.com/user-attachments/files/24034951/RegressionTests_derecho.log_SUCCESS.txt)
 
 [RegressionTests_derecho.log_SUCCESS2.txt](https://github.com/user-attachments/files/24034959/RegressionTests_derecho.log_SUCCESS2.txt)
 
 RT logs after enabling all GNU tests:
 First time through, creating a baseline:
[RegressionTests_derecho.log_GNU1.txt](https://github.com/user-attachments/files/24268743/RegressionTests_derecho.log_GNU1.txt)

Second time through, comparing against the baseline:
[RegressionTests_derecho.log_GNU2.txt](https://github.com/user-attachments/files/24268745/RegressionTests_derecho.log_GNU2.txt)
 
## CONTRIBUTORS:

* Ratko Vasic <Ratko.Vasic@noaa.gov>
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] GaeaC6
  - [ ] Derecho
  - [x] Ursa
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [x] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by natalie-perlin** [comment]
A spack-stack-1.9.2 on Derecho is being updated. Currently it is built in a user space, but will be be rebuilt in a common space as soon as the spack-stack PR is approved:
https://github.com/JCSDA/spack-stack/pull/1758 (a hot-fix for the previous [PR1756](https://github.com/JCSDA/spack-stack/pull/1756))

Selected  UFS RTs are currently being run on Derecho with the updated spack-stack-1.9.2 (user space-built).
/glade/derecho/scratch/nperlin/FV3_RT/rt_21274

**Comment by DusanJovic-NOAA** [comment]
Now that the derecho job card is (finally) fixed to use $TASKS variable, as all other job cards on all other platforms, we do not need $UFS_TASKS and $PPN in rt.sh an rt_utils.sh and run_tests.sh. Please double check, and remove them.

**Comment by natalie-perlin** [comment]
> Now that the derecho job card is (finally) fixed to use $TASKS variable, as all other job cards on all other platforms, we do not need $UFS_TASKS and $PPN in rt.sh an rt_utils.sh and run_tests.sh. Please double check, and remove them.

Are $UFS_TASKS  and $PPN only needed for Derecho?

**Comment by DusanJovic-NOAA** [comment]
> > Now that the derecho job card is (finally) fixed to use $TASKS variable, as all other job cards on all other platforms, we do not need $UFS_TASKS and $PPN in rt.sh an rt_utils.sh and run_tests.sh. Please double check, and remove them.
> 
> Are $UFS_TASKS and $PPN only needed for Derecho?

I think so.

```
$ grep -r UFS_TASKS .
./rt_utils.sh:  # TASKS is now set to UFS_TASKS
./rt_utils.sh:  # TASKS is now set to UFS_TASKS
./fv3_conf/fv3_qsub.IN_derecho:mpiexec -n @[UFS_TASKS] -ppn @[PPN] --hostfile $PBS_NODEFILE ./fv3.exe
./run_test.sh:UFS_TASKS=${TASKS}
./run_test.sh:PPN=$(( UFS_TASKS / NODES ))
./run_test.sh:if (( UFS_TASKS - ( PPN * NODES ) > 0 )); then
./run_test.sh:export UFS_TASKS
```

```
$ grep -r PPN .
./fv3_conf/fv3_qsub.IN_derecho:mpiexec -n @[UFS_TASKS] -ppn @[PPN] --hostfile $PBS_NODEFILE ./fv3.exe
./rt.sh:      PPN=$(( TASKS / NODES ))
./rt.sh:      if (( TASKS - ( PPN * NODES ) > 0 )); then
./rt.sh:          PPN=$((PPN + 1))
./run_test.sh:PPN=$(( UFS_TASKS / NODES ))
./run_test.sh:if (( UFS_TASKS - ( PPN * NODES ) > 0 )); then
./run_test.sh:  PPN=$((PPN + 1))
./run_test.sh:export PPN
./run_test.sh:  PPN=${TPN}
```
Only `./fv3_conf/fv3_qsub.IN_derecho` uses UFS_TASKS and PPN.

**Comment by gspetro-NOAA** [comment]
@natalie-perlin Thanks for your work on this! In general, only WM CMs should be updating the PR status in the PR board. You technically have access because you're an owner in ufs-community, but in the future, please just ping us on the PR itself or on Slack to update the status. It sounds like you still had a question--will the answer result in further changes for the PR? If so, it should stay in Evaluating until that gets resolved.

File: tests/tests/cpld_control_c192_p8 [hunk 1]
```diff
@@ -141,7 +141,7 @@ export FNABSC="'C192.maximum_snow_albedo.tileX.nc'"
 export FV3_RUN=cpld_control_run.IN
 
 if [[ $MACHINE_ID = derecho ]]; then
-  TPN=96
+  TPN=128
```
Comment (DeniseWorthen) [inline tests/tests/cpld_control_c192_p8]: Isn't 128 the actual cores/node on Derecho? Why does it need to be specified?

**Comment by DeniseWorthen** [comment]
I just ran ``cpld_debug_gfsv17_intel`` on derecho using this branch and I got a wall clock time
```
*****************RESOURCE STATISTICS*******************************
The total amount of wall time                        = 1122.732178
```

I don't think we need to specify a ``WLCLK=40`` for this test.

File: tests/tests/cpld_control_c192_p8 (hunk 1 above)
Comment (natalie-perlin) [reply tests/tests/cpld_control_c192_p8]: Yes, this could be removed, thank you

**Comment by natalie-perlin** [comment]
Notes after consulting with CISL/Derecho Helpdesk. 
Current issues remained:
job_card PBS directives need to be configured distinctly for different tests to work. 
Derecho's helpdeck/CISL team confirmed what is the expected/supported way for PBS directives. 

Currently,  a job_card for the test cpld_control_ciceC_p8_intel need to contain the following for the run to complete successfully:

```
#PBS -l select=2:ncpus=128:ompthreads=1
#PBS -l walltime=00:30:00zexport MPI_TYPE_DEPTH=20
export OMP_STACKSIZE=512M
export OMP_NUM_THREADS=1
export ESMF_RUNTIME_COMPLIANCECHECK=OFF:depth=4
export ESMF_RUNTIME_PROFILE=ON
export ESMF_RUNTIME_PROFILE_OUTPUT="SUMMARY"
export I_MPI_EXTRA_FILESYSTEM="ON"

mpiexec -n 256 --cpu-bind core -depth 1 ./fv3.exe
```

However, the test **cpld_control_c192_p8_intel** needs to have the following for the run to be successful (note the syntax change in PBS directive "-l select"):

```
#PBS -l select=7:ncpus=128:mpiprocs=128:ompthreads=1
#PBS -l walltime=00:30:00
export MPI_TYPE_DEPTH=20
export OMP_STACKSIZE=512M
export OMP_NUM_THREADS=1
export ESMF_RUNTIME_COMPLIANCECHECK=OFF:depth=4
export ESMF_RUNTIME_PROFILE=ON
export ESMF_RUNTIME_PROFILE_OUTPUT="SUMMARY"
export I_MPI_EXTRA_FILESYSTEM="ON"
mpiexec -n 896 --cpu-bind core -depth 1 ./fv3.exe
```

CISL/Derecho helpdesk confirms that the PBS directives syntax of
_#PBS -l select=[NODES]:ncpus=[TPN]:ompthreads=[THREADS]_
is the expected way to have it in the submission script.

Testing showed that the **cpld_control_c192_p8_intel** fails if the corresponding job_card has the following syntax:
_#PBS -l select=7:ncpus=128:ompthreads=1_

At the same time, the test **cpld_control_ciceC_p8_intel** fails if the job_card submission script has the following syntax:
_#PBS -l select=2:ncpus=128:mpiprocs=128:ompthreads=1_

**Comment by natalie-perlin** [comment]
Recent Derecho tests are under /glade/derecho/scratch/nperlin/FV3_RT/rt_113499

Regression tests submitted from /glade/derecho/scratch/nperlin/UFS-WM/ufs-wm-derecho/tests as following: 

`./rt.sh -a NRAL0032 -w -k -e -l rt.conf >& log.rt.sh.002 &`
[RegressionTests_weekly_derecho.log.txt](https://github.com/user-attachments/files/22974823/RegressionTests_weekly_derecho.log.txt) is attached

The tests that are currently failing:
```
cpld_mpi_gfsv17 intel
cpld_mpi_p8 intel
cpld_control_c192_p8 intel
cpld_restart_c192_p8 intel
cpld_mpi_pdlib_p8 intel
hafs_regional_atm_ocn intel
hafs_regional_atm_wav intel
hafs_regional_atm_ocn_wav intel
hafs_global_multiple_4nests_atm intel
hafs_regional_storm_following_1nest_atm_ocn_wav intel
hafs_regional_storm_following_1nest_atm_ocn_wav_inline intel
hafs_regional_storm_following_1nest_atm_ocn_wav_mom6 intel
hafs_regional_docn intel
hafs_regional_docn_oisst intel
```

The tests `cpld_control_c192_p8` intel and `cpld_restart_c192_p8` intel will succeed if job_card entry is changed to:
 _#PBS -l select=7:ncpus=128:mpiprocs=128:ompthreads=1_

I am yet to check if this fix would benefit other tests.

**Comment by natalie-perlin** [comment]
The rt.sh rerun with rocoto option, after pulling in updates from develop. 
Home directory for the tests are  `/glade/derecho/scratch/nperlin/UFS-WM/ufs-weather-model/tests/`, and tests directory is `/glade/derecho/scratch/nperlin/FV3_RT/rt_24522`
Tests status, as reported by `rocotostat -w rocoto_workflow.xml -d rocoto_workflow.db  -v 10` in current ufs-weather-model home directory is attached  [rocotostat.txt](https://github.com/user-attachments/files/23234324/rocotostat.txt), and list of failed tests is shown below.

The  cpld_control_p8_intel fails but would pass with no issues if resubmitted from the test directory using job_card. 
Note that there is an issue with Rocoto and the way Derecho is configured that currently will cause the rocoto-submitted test to fail. This is internal to Rocoto code and specific for Derecho. Reached out to CISL for help, but there is no other solution so far except changing the "#PBS -l select" submission entry manually when the job is submitted. See more details below, under the test summary. 

Tests (13) that failed:
```
cpld_control_p8_mixedmode_intel
cpld_control_p8_intel
cpld_control_p8.v2.sfc_intel
cpld_control_ciceC_p8_intel
cpld_control_p8_lnd_intel
cpld_s2sa_p8_intel
cpld_debug_p8_intel
cpld_control_p8_faster_intel
control_p8_ugwpv1_tempo_aerosol_hail_intel
hafs_regional_storm_following_1nest_atm_ocn_wav_mom6_intel
atmaero_control_p8_intel
atmaero_control_p8_rad_intel
atmaero_control_p8_rad_micro_intel
```

More notes on Rocoto:

Rocoto constructs its own submission script based on the entry in the rocoto database file. For example, when rocoto has the following entry in the rocoto_workflow.db: 
   `  <nodes>2:ppn=128</nodes>`
It constructs the directive in the job submission script as 
_#PBS -l select=2:mpiprocs=128:ncpus=128_
The submission prompt from rocoto is attached (rocoto_submit)
The job then fails with errors such as:

```
MPICH ERROR [Rank 16] [job id 3e48e3ff-2ab2-4e27-9dcf-e6491437510e] [Wed Oct 29 09:11:43 2025] [dec1509] - Abort(874135567) (rank 16 in comm 0): Fatal error in PMPI_Win_create: Other MPI error, error stack:
PMPI_Win_create(294)......: MPI_Win_create(base=0x7ffeb5dd7180, size=0, disp_unit=1, MPI_INFO_NULL, comm=0xc4000068, win=0x7ffeb5dd72e0) failed
MPID_Win_create(89).......:
MPIDIG_mpi_win_create(872):
win_allgather(246)........: OFI mr_enable failed (ofi_win.c:246:win_allgather:Address already in use)
```

(full log attached [err_orig.txt](https://github.com/user-attachments/files/23234402/err_orig.txt)).

When I create a submission script similar to the original one except removing the "mpiprocs=128" and changing the line to
_#PBS -l select=2:ncpus=128_
 , this run then finishes successfully, see [job_card.txt](https://github.com/user-attachments/files/23234474/job_card.txt) and [err.txt](https://github.com/user-attachments/files/23234482/err.txt) log files attached.

The ufs-weather-model job card ([job_card_wm.txt](https://github.com/user-attachments/files/23234491/job_card_wm.txt)) that is formed in the test directory during the submission has the syntax that works for resubmitting the test manually. 

Please let me know what else could be done on this PR!

**Comment by DeniseWorthen** [comment]
@natalie-perlin Do the RTs run w/ ecflow w/o issue?

**Comment by natalie-perlin** [comment]
> @natalie-perlin Do the RTs run w/ ecflow w/o issue?

Current fv3_conf/fv3_qsub.IN_derecho creates a job_card used by ecflow that has submission line as 
#PBS -l select=@[NODES]:ncpus=@[TPN]:ompthreads=@[THRD]

That would cause some of the test to fail. 
Unlike cpld_control_p8_intel, other tests, for example, cpld_control_c192_p8_intel, do _require_ to have a submission directive to include "mpiprocs" in the job_card, i.e., 
#PBS -l select=7:ncpus=128:ompthreads=1
and 
mpiexec -n 896 --cpu-bind core -depth 1 ./fv3.exe

Please see examples of this run in a rt.sh test directory lauched using ecflow workflow manager.
The run that fails (with the line `#PBS -l select=7:ncpus=128:ompthreads=1` in the job_card) is under
`/glade/derecho/scratch/nperlin/FV3_RT/rt_113499/cpld_control_c192_p8_intel`

The run that passes successfully after the job_card was edited to include  the line
    `#PBS -l select=7:ncpus=128:mpiprocs=128:ompthreads=1` :
`/glade/derecho/scratch/nperlin/FV3_RT/rt_113499/cpld_control_c192_p8_intel_RERUN`


CISL helpdesk responded that the including "mpiprocs=128" is the preferred/expected way, and they demonstrated on a small "Hello,world" test example that it is suboptimal for job placement to different cores/ranks to have it without "mpiprocs" specified. Having "mpiprocs in job_card would also be consistent with how rocoto submits the jobs to PBS. But it is not clear why it fails for cpld_control_p8_intel case.  Current `./tests/fv3_conf/fv3_qsub.IN_derecho` file has it without "mpiprocs"   so that the cpld_control_p8_intel test works if submitted via rt.sh using ecflow.

I may suggest that given the current rocoto code and a feedback from CISL, the `./tests/fv3_conf/fv3_qsub.IN_derecho` would be modified to 
#PBS -l select=@[NODES]:ncpus=@[TPN]:mpiprocs=@[TPN]:ompthreads=@[THRD]

but then we expect  cpld_control_p8_intel to fail in the rt.sh (unless job_card is edited by hand). 

I tested to include a hostfile argument in the mpiexec string for  cpld_control_p8_intel, i.e,
`mpiexec -n 256 --ppn 128 --hostfile $PBS_NODEFILE -depth 1 ./fv3.exe`, 
or even
`mpiexec -n 200 --ppn 128 --hostfile $PBS_NODEFILE -depth 1 ./fv3.exe` , 
where 200 would correspond to "UFS_TASKS" if calculated
but it did not help as the test still fails.
(See the last two attempts under /glade/derecho/scratch/nperlin/FV3_RT/rt_50523/cpld_control_p8_intel directory;
the first approach is job_card_bac, err_bac, out_bac, and the case with "-n 200" is in job_card, err, out log files)

**Comment by natalie-perlin** [comment]
An update of  a successful RT run cpld_control_p8_intel using rocoto, submitted as 
./rt.sh -a NRAL0032 -c -k -r -w -n "cpld_control_p8 intel" 
(/glade/derecho/scratch/nperlin/FV3_RT/rt_123132)
It completes with no issues if the job_card still uses the same approach as is currently in develop branch, i.e. uses "UFS_TASKS" and "PPN" variables in the mpiexec submission line:

`mpiexec -n @[UFS_TASKS] -ppn @[PPN] --hostfile $PBS_NODEFILE ./fv3.exe`
 
NB: the job_card in a successful cpld_control_p8_intel test has the following entries :
`#PBS -l select=2:ncpus=128:mpiprocs=128:ompthreads=1`
`mpiexec -n 200 -ppn 100 --hostfile $PBS_NODEFILE ./fv3.exe`

I'm going to revert my changes in the ./tests/fv3_conf/fv3_qsub.IN_derecho to keep it as in a current develop branch, and then re-running the rest of the RTs.

**Comment by natalie-perlin** [comment]
The rocoto-submitted RTs finished successfully all except two: 
 cpld_control_c192_p8_intel
 cpld_control_p8_lnd_intel
 The output from 
[rocoto.summary.txt](https://github.com/user-attachments/files/23265064/rocoto.summary.txt)
 Tests directories:
 /glade/derecho/scratch/nperlin/UFS-WM/ufs-wm/tests
 /glade/derecho/scratch/nperlin/FV3_RT/rt_28651
 
 The tests that failed - plan to test adding derecho-specific configurations  to ./tests/tests/control* files, similarly to what has proven to be working previously

**Comment by natalie-perlin** [comment]
RTs lauched with ecflow succeed all except the same two tests as for rocoto, 
cpld_control_c192_p8_intel
cpld_control_p8_lnd_intel

The directories for the ecflow-based tests:
/glade/derecho/scratch/nperlin/UFS-WM/ufs-wm-derecho/tests/
/glade/derecho/scratch/nperlin/FV3_RT/rt_62263

**Comment by jkbk2004** [comment]
@natalie-perlin can you sync up branch?

File: tests/rt.sh [hunk 2]
```diff
@@ -943,13 +943,12 @@ case ${MACHINE_ID} in
...
       module use /glade/work/epicufsrt/contrib/derecho/modulefiles
-      module load rocoto/1.3.7-fix
-    fi
-    module use /glade/work/epicufsrt/contrib/spack-stack/derecho/modulefiles
-    if [[ "${ECFLOW:-false}" == true ]] ; then
-      module load ecflow/5.8.4
+      module load rocoto/1.3.7
     fi
     if [[ "${ECFLOW:-false}" == true ]] ; then
+      module use /glade/work/epicufsrt/contrib/spack-stack/derecho/spack-stack-1.9.2/envs/ue-oneapi-2024.2.1/install/modulefiles/oneapi/2024.2.1
```
Comment (dpsarmie) [inline tests/rt.sh:949]: It looks like if ECFlow and Rocoto are both false, then no modules are loaded. I think we should add something as a default loadout when both flags are set to false.

**Comment by natalie-perlin** [comment]
Updated the PR description. 
After changes suggested by Ratko Vasic (ratko.vasic@noaa.gov) to use nccmp/1.9.0.1 from spack-stack, all the RTs successfully pass. The local install of nccmp on Derecho is not working properly due to a missing file, but the spack-stack-installed nccmp works well. The RT's used rocoto job scheduler.

i) first time through creating a baseline:
`./rt.sh -a NRAL0032 -c -k -r  -l rt.conf >& log.rt.sh.004 &`
[RegressionTests_derecho.log_SUCCESS.txt](https://github.com/user-attachments/files/24034951/RegressionTests_derecho.log_SUCCESS.txt)
[log.rt.sh.004.txt](https://github.com/user-attachments/files/24035696/log.rt.sh.004.txt)

ii) second time through testing against the baseline:
`./rt.sh -a NRAL0032 -m -k -r  -l rt.conf >& log.rt.sh.005 &`
[RegressionTests_derecho.log_SUCCESS2.txt](https://github.com/user-attachments/files/24034959/RegressionTests_derecho.log_SUCCESS2.txt)
[log.rt.sh.005.txt](https://github.com/user-attachments/files/24035692/log.rt.sh.005.txt)

RTs lauched with ecflow succeed all except the two tests
[test_changes.list_001.txt](https://github.com/user-attachments/files/24034919/test_changes.list_001.txt):
cpld_control_sfs intel
cpld_debug_sfs intel

When resubmitting by hand using "qsub < job_card", the test cpld_control_sfs intel finished successfully.
See /glade/derecho/scratch/nperlin/FV3_RT/rt_62263/cpld_control_sfs_intel_RERUN

**Comment by natalie-perlin** [comment]
@jkbk2004 - is there anything else that may need to be done for this PR?

**Comment by natalie-perlin** [comment]
Running the RTs using ecflow to verify against a baseline created earlier with rocoto:
./rt.sh -a NRAL0032 -m -k -e -l rt.conf >& log.rt.sh.006_ecflow &

Three sfs tests failed (in `test_changes.list`):
cpld_control_sfs intel
cpld_restart_sfs intel
cpld_debug_sfs intel

Info on these tests in ./logs/RegressionTests_derecho.log:
```

SYNOPSIS:
Starting Date/Time: 20251209 08:43:47
Ending Date/Time: 20251210 18:52:25
Total Time: 10h:09m:37s
Compiles Completed: 43/43
Tests Completed: 190/193
Failed Tests:
* TEST cpld_control_sfs_intel: FAILED: RUN DID NOT COMPLETE
-- LOG: /glade/derecho/scratch/nperlin/UFS-WM/ufs-weather-model/tests/logs/log_derecho/run_cpld_control_sfs_intel.log
* TEST cpld_restart_sfs_intel: FAILED: UNABLE TO START TEST
-- LOG: N/A
* TEST cpld_debug_sfs_intel: FAILED: RUN DID NOT COMPLETE
-- LOG: /glade/derecho/scratch/nperlin/UFS-WM/ufs-weather-model/tests/logs/log_derecho/run_cpld_debug_sfs_intel.log
```

The test `cpld_control_sfs intel` may (or may not) finish successfully when resubmitted using qsub < job_card from the test directory. The err file resulted from three consecutive launches, when messages added to the existing err file, show that two times the run failed and finished successfully for the third time:

/glade/derecho/scratch/nperlin/FV3_RT/rt_39461/cpld_control_sfs_intel_RERUN/err_3times

Not sure how to proceed with these three SFS tests.

**Comment by dustinswales** [comment]
@natalie-perlin I see that this PR updates the Intel on Derecho. Maybe this is the wrong place for my question, but is there any effort to get the UWM RTs working on Derecho w/ GNU compliers?

**Comment by natalie-perlin** [comment]
> @natalie-perlin I see that this PR updates the Intel on Derecho. Maybe this is the wrong place for my question, but is there any effort to get the UWM RTs working on Derecho w/ GNU compliers?

@dustinswales - I've run GNU tests for Derecho and having issues (MPI not found error) when CMEPS interface is turned on. 
Please let us know if there are any suggestions on how to resolve it:
https://github.com/ufs-community/ufs-weather-model/issues/3017#issuecomment-3658444606

**Comment by natalie-perlin** [comment]
All GNU tests pass on Derecho after the recent fix in `ufs_derecho.gnu.lua` (missing env. variables `CC`, `CXX`, `FC`).
Tests ran to completion in two sets, see comments under the discussion #3017 :

https://github.com/ufs-community/ufs-weather-model/issues/3017#issuecomment-3658444606
https://github.com/ufs-community/ufs-weather-model/issues/3017#issuecomment-3673468491

The fix for the modulefile has been committed successfully, but the GNU tests are not yet enabled in the currently used `rt.conf`.

Please let me know if it make sense to enable GNU tests for this PR... or it could be made a separate PR.

**Comment by gspetro-NOAA** [comment]
@natalie-perlin I think it makes sense to enable them on this PR because it's a closely related change as long as it won't delay this PR any further.

**Comment by natalie-perlin** [comment]
The rt.conf is updated in the recent commit 7143f10a97, running the the RTs at the moment as:
```
./rt.sh -a NRAL0032 -c -k -r  -l rt.conf >& log.rt.sh_all.001 &
```

All successful:
```
...

PASS -- COMPILE 'atm_dyn64_phy32_debug_gnu' [15:06, 15:05]
PASS -- TEST 'rap_control_dyn64_phy32_debug_gnu' [02:54, 02:41](848 MB)

PASS -- COMPILE 's2swa_gnu' [21:05, 21:05]
PASS -- TEST 'cpld_control_p8_gnu' [10:33, 09:40](1657 MB)

PASS -- COMPILE 's2s_gnu' [19:37, 19:36]
PASS -- TEST 'cpld_control_nowave_noaero_p8_gnu' [09:30, 08:44](1621 MB)

PASS -- COMPILE 's2swa_debug_gnu' [05:39, 05:39]
PASS -- TEST 'cpld_debug_p8_gnu' [07:33, 06:49](1677 MB)

PASS -- COMPILE 's2sw_pdlib_gnu' [19:50, 19:50]
PASS -- TEST 'cpld_control_pdlib_p8_gnu' [12:27, 11:41](1586 MB)

PASS -- COMPILE 's2sw_pdlib_debug_gnu' [04:56, 04:55]
PASS -- TEST 'cpld_debug_pdlib_p8_gnu' [09:23, 08:39](1586 MB)

PASS -- COMPILE 'datm_cdeps_gnu' [16:27, 16:26]
PASS -- TEST 'datm_cdeps_control_cfsr_gnu' [03:18, 03:11](1517 MB)

PASS -- COMPILE 'atm_mpas_dyn32_gnu' [03:02, 03:02]
PASS -- TEST 'control_gfs_mpas_gnu' [01:31, 01:08](6368 MB)

SYNOPSIS:
Starting Date/Time: 20251219 10:54:14
Ending Date/Time: 20251219 15:33:09
Total Time: 04h:39m:34s
Compiles Completed: 56/56
Tests Completed: 184/254

NOTES:
A file 'test_changes.list' was generated but is empty.
If you are using this log as a pull request verification, please commit 'test_changes.list'.

Result: SUCCESS

====END OF DERECHO REGRESSION TESTING LOG====
```

(Full log: [RegressionTests_derecho.log_GNU1.txt](https://github.com/user-attachments/files/24268743/RegressionTests_derecho.log_GNU1.txt) )

**Comment by natalie-perlin** [comment]
Full-list of RTs with Intel and GNU tests completes successfully ran for the second time comparing against the baseline:

```
...
SYNOPSIS:
Starting Date/Time: 20251219 15:51:50
Ending Date/Time: 20251219 21:48:28
Total Time: 05h:57m:25s
Compiles Completed: 56/56
Tests Completed: 254/254

NOTES:
A file 'test_changes.list' was generated but is empty.
If you are using this log as a pull request verification, please commit 'test_changes.list'.

Result: SUCCESS

====END OF DERECHO REGRESSION TESTING LOG====
```
Full log:
[RegressionTests_derecho.log_GNU2.txt](https://github.com/user-attachments/files/24268745/RegressionTests_derecho.log_GNU2.txt)

**Comment by jkbk2004** [comment]
@natalie-perlin tests on derecho consistently run ok and I pushed the log. keep syncing up branch. we will try to integrate this pr this week.

**Comment by FernandoAndrade-NOAA** [comment]
We are shifting over to this PR today, @natalie-perlin can you go ahead and resync with develop and bring in updates from #3035?

**Comment by BrianCurtis-NOAA** [comment]
WCOSS2 Compiles all were successful. I'm OK with this PR moving forward. UFSATM only touched build system so I only tested compiles. I assume with other machines being OK that Acorn should be fine as well (it uses a spack build on Acorn).

**Review by gspetro-NOAA — APPROVED** [review]

**Review by dpsarmie — CHANGES_REQUESTED** [review]
I don't think this was addressed. If others are ok with it, then I won't hold it up; but on other systems, modules are loaded if rocoto and ecflow options are both false.

**Comment by gspetro-NOAA** [comment]
> I don't think this was addressed. If others are ok with it, then I won't hold it up; but on other systems, modules are loaded if rocoto and ecflow options are both false.

@dpsarmie My only concern would be that if we make changes now, we have to retest the PR (tho probably just on Derecho?). Is that preferable, or do we create an issue and ask @natalie-perlin to open a small PR to address the issue promptly. It could be combined with another PR. I'm fine either way, with a preference for whatever will be quicker. 😜

**Comment by dpsarmie** [comment]
@gspetro-NOAA That's fine with me. It should be a simple fix but we can get this merged in to get Derecho up and running.

**Review by dpsarmie — APPROVED** [review]

**Comment by FernandoAndrade-NOAA** [comment]
Created https://github.com/ufs-community/ufs-weather-model/issues/3043 to cover adding default loads for Derecho within `rt.sh`, continuing with merge.

**Comment by jkbk2004** [comment]
@dpsarmie BTW, I was checking sequential run on Derecho. It runs ok. We will keep checking.
