### PR TITLE
FV3: Fix Prate_avg and UPP call freq + Fixing repo sync check with proper if...else block and re-instatiatin… #2859

### LINKED ISSUE #969: fix the output frequency for UPP when IAU is turned on
## Description
In GFSv17 IAU test, it is found that the UPP is called more frequently than it should be. This needs to be fixed.

### To Reproduce:
What compilers/machines are you seeing this with?
Give explicit steps to reproduce the behavior.
1. do this
2. then that
3. then, oops, look at the bug

## Additional context
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- needs to be fixed also in noaa-emc/nems/issues/<issue_number>
- needed for noaa-emc/fv3atm/pull/<pr_number>

## Output

**Screenshots**
If applicable, drag and drop screenshots to help explain your problem.

**output logs**
If applicable, include relevant output logs.
Either drag and drop the entire log file here (if a long log) or

```
paste the code here (if a short section of log)
```

## Testing:

1. Have you tested the code changes? On what platforms?

2. Have you run regression test in ufs-weather-model or ufs-s2s-model with code changes?
- Will the baseline results change? 
- If the baseline results change, is it expected? Please give brief explanation.

## Dependent PRs:

Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/GFDL_atmos_cubed_sphere/issues/<issue_number>
- ncar/ccpp-physics/pull/<pr_number>
- associated ufs-weather-model/pull/<pr_number>

### LINKED ISSUE #976: How is time averaged precipitation calculated?
I am confused how the time averaged precipitation calculated in the FV3. I know how precipitation is accumulated with time but don't have a clue how time averaging is done.

### PR DESCRIPTION
**Pull request by dpsarmie**
## Commit Queue Requirements:

- [X] Fill out all sections of this template.
- [X] All sub component pull requests have been reviewed by their code managers.
- [X] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [X] Commit 'test_changes.list' from previous step
---
## Description:
This PR will bring in FV3 changes that fix accumulated total precip (https://github.com/NOAA-EMC/fv3atm/pull/979) and fix the call frequency of UPP when restart and history frequencies are not the same (https://github.com/NOAA-EMC/fv3atm/pull/973). 

### Commit Message:
```
* UFSWM - repo_check.sh update
  * FV3 - Fixes Prate_avg, UPP call frequencies, and makes restart controls a single variable
```

### Priority:

* Normal - Needed for GFSv17 Retros

### UFSWM:
* Closes https://github.com/NOAA-EMC/fv3atm/issues/969
* Closes https://github.com/NOAA-EMC/fv3atm/issues/976

### Sub component Pull Requests:

* FV3: https://github.com/NOAA-EMC/fv3atm/pull/996

### UFSWM Blocking Dependencies:
* None

### Documentation:
* No documentation update is required for this PR

---
### Regression Test Changes (Please commit test_changes.list):

* PR Updates/Changes Baselines.

### Input data Changes:
* None.

### Library Changes/Upgrades:
* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] GaeaC6
  - [x] Derecho
  - [x] Ursa
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- [x] CI
- [x] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by dpsarmie** [comment]
@jkbk2004 Everything is updated and should be ready for testing.

**Comment by jkbk2004** [comment]
@dpsarmie Thanks! #2859 is minor update on repo check script and can be combined into this pr.

**Comment by dpsarmie** [comment]
Ok done, @kbooker79 can double check the changes.

File: tests/ci/repo_check.sh [hunk 1]
```diff
@@ -106,8 +106,7 @@ done
 if [[ ! $flag_sync ]]; then
     echo "** ${GITHUB_WORKSPACE} **NOT** up to date"
     exit 1
+else
+    echo "** ${GITHUB_WORKSPACE} up to date **"
+    exit 0
```
Comment (kbooker79) [inline tests/ci/repo_check.sh:111]: @dpsarmie, that looks good to me.

**Comment by BrianCurtis-NOAA** [comment]
There is a bug with -b option causing cpld_control_gfsv17 to be on the .conf twice. I'd recommend starting it with -b, letting it fail, editing the rt_temp.conf then running with -l to use rt_temp.conf that you edited.

**Comment by DeniseWorthen** [comment]
#2864

**Comment by jkbk2004** [comment]
all tests are done successfully. we can start merging process.

**Comment by jkbk2004** [comment]
@dpsarmie new fv3 hash is https://github.com/NOAA-EMC/fv3atm/commit/40187b2172e9cf3bbe1e09a2c5939dd6a10958d9

**Comment by dpsarmie** [comment]
@jkbk2004 Ok, everything should be updated and ready for final reviews.

**Review by jkbk2004 — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]
