### PR TITLE
Hpc stack update (Issue 1465)

### LINKED ISSUE #1465: Updating hpc-stack modules and  miniconda locations for Hera, Gaea, Cheyenne, Orion, Jet
## Description
Update the locations of the hpc-stack modules and miniconda3 for compiling and running the UFS-weather-model on NOAA HPC systems, such as Hera, Gaea, Cheyenne, Orion, Jet. The modules are installed under role.epic account and placed in a common EPIC-managed space on each system. Gaea also uses the Lmod installed locally in the same common location ([ufs-srweather-app/PR-352](https://github.com/ufs-community/ufs-srweather-app/pull/352), [ufs-weather-app/PR-353](https://github.com/ufs-community/ufs-srweather-app/pull/353)), and needs to run a script to initialize Lmod before loading a modulefile ufs_gaea.intel.lua. While ufs-weather model may use/require python to a lesser extent, the UFS-srweather-app relies heavily on conda environment.  

For ease of maintenance of the libraries on the NOAA HPC systems, transition to new location of the modules built for both ufs-weather-model and ufs-srweather-app is needed.  

## Solution
Repo of the ufs-weather-model to be updated with the new version of miniconda and hpc libraries. 

Udated installation locations have been used to load the modules listed in `/ufs-weather-model/modulefiles/ufs_common `and build the ufs model binaries. 
Hera gnu compilers includ
UPD. 10/20/2022: Modules for Hera and Jet have been build for the already tested compiler intel/2022.1.2. Modules for the compiler/impi intel/2022.2.0 also remained and could be used when the upgrade is needed. 

UPD. 10/24/2022: Modules for Hera gnu compilers (9.2.0, 10.2.0) and different mpich/openmpi combinations, and updated netcdf/4.9.0 have been prepared.
UPD. 12/07/2022: Added gnu/10.1.0-based hpc-stack on Cheyenne, by a request 
UPD. 12/07/2022: Added gnu/10.1.0-based hpc-stack on Cheyenne with mpt/2.22, by a request 

Cheyenne Lmod has been upgraded to v.8.7.13 systemwide after system maintenance on 10/21/2022.

## Alternatives
Alternative solutions could be to have the hpc libraries and modules built in separate locations for the ufs-weather-model and ufs-srweather-app. The request from EPIC management, however, was to use a common location for the all the libraries.

## Related to
A PR-419 in the ufs-srweather-model already exists, and a new PR will be made to the current repo. 
- needed by [https://github.com/ufs-community/ufs-srweather-app/pull/419](https://github.com/ufs-community/ufs-srweather-app/pull/419) - marked as `top priority`
- needed by https://github.com/ufs-community/ufs-weather-model/pull/???

Updated locations to load the conda/python and hpc-modules and how to load them on all the systems:

`Hera python/miniconda :`
module use /scratch1/NCEPDEV/nems/role.epic/miniconda3/modulefiles
module load miniconda3/4.12.0

`Hera intel/2022.1.2 + impi/2022.1.2 :`
module load intel/2022.1.2
module load impi/2022.1.2
 use /scratch1/NCEPDEV/nems/role.epic/hpc-stack/libs/intel-2022.1.2/modulefiles/stack
module load hpc/1.2.0
module load hpc-intel/2022.1.2
module load hpc-impi/2022.1.2

`Hera intel/2022.1.2 + impi/2022.1.2 + netcdf-c 4.9.0:`
module load intel/2022.1.2
module load impi/2022.1.2
 use /scratch1/NCEPDEV/nems/role.epic/hpc-stack/libs/intel-2022.1.2_ncdf49/modulefiles/stack
module load hpc/1.2.0
module load hpc-intel/2022.1.2
module load hpc-impi/2022.1.2

`Hera gnu/9.2 + mpich/3.3.2 :`
module load gnu/9.2
module use /scratch1/NCEPDEV/nems/role.epic/hpc-stack/libs/gnu-9.2/modulefiles/stack
module load hpc/1.2.0
module load hpc-gnu/9.2
module load mpich/3.3.2
module load hpc-mpich/3.3.2

`Hera gnu/10.2 + mpich/3.3.2 :`
module use /scratch1/NCEPDEV/nems/role.epic/gnu/modulefiles
module load gnu/10.2.0
module use /scratch1/NCEPDEV/nems/role.epic/hpc-stack/libs/gnu-10.2/modulefiles/stack
module load hpc/1.2.0
module load hpc-gnu/10.2
module load mpich/3.3.2
module load hpc-mpich/3.3.2

`Hera gnu/10.2 + openmpi/4.1.2 :`
module use /scratch1/NCEPDEV/nems/role.epic/gnu/modulefiles
module load gnu/10.2.0
module use /scratch1/NCEPDEV/nems/role.epic/hpc-stack/libs/gnu-10.2_openmpi/modulefiles/stack
module load hpc/1.2.0
module load hpc-gnu/10.2
module load openmpi/4.1.2
module load hpc-openmpi/4.1.2

`Hera gnu/9.2 + mpich/3.3.2 + netcdf-c 4.9.0:`
module load gnu/9.2
module use /scratch1/NCEPDEV/nems/role.epic/hpc-stack/libs/gnu-9.2_ncdf49/modulefiles/stack
module load hpc/1.2.0
module load hpc-gnu/9.2
module load mpich/3.3.2
module load hpc-mpich/3.3.2

`Hera gnu/10.2 + mpich/3.3.2 + netcdf-c/4.9.0:`
module use /scratch1/NCEPDEV/nems/role.epic/gnu/modulefiles
module load gnu/10.2.0
module use /scratch1/NCEPDEV/nems/role.epic/hpc-stack/libs/gnu-10.2_ncdf49/modulefiles/stack
module load hpc/1.2.0
module load hpc-gnu/10.2
module load mpich/3.3.2
module load hpc-mpich/3.3.2

`Gaea miniconda:`:
module use /lustre/f2/dev/role.epic/contrib/modulefiles
module load miniconda3/4.12.0

`Gaea intel:`
Lmod initialization on Gaea needs to be done first by sourcing the following script:
 /lustre/f2/dev/role.epic/contrib/Lmod_init.sh
   
module use /lustre/f2/dev/role.epic/contrib/modulefiles
module load miniconda3/4.12.0

module use /lustre/f2/dev/role.epic/contrib/hpc-stack/intel-2021.3.0/modulefiles/stack
module load hpc/1.2.0
module load intel/2021.3.0
module load hpc-intel/2021.3.0
module load hpc-cray-mpich/7.7.11

`Cheyenne miniconda:`
module use /glade/work/epicufsrt/contrib/miniconda3/modulefiles
module load miniconda3/4.12.0

`Cheyenne intel`: 
module use /glade/work/epicufsrt/contrib/miniconda3/modulefiles
module load miniconda3/4.12.0

module use /glade/work/epicufsrt/contrib/hpc-stack/intel2022.1/modulefiles/stack
module load hpc/1.2.0
module load hpc-intel/2022.1
module load hpc-mpt/2.25

`Cheyenne gnu/10.1.0_mpt2.22`:
module use /glade/work/epicufsrt/contrib/hpc-stack/gnu10.1.0_mpt2.22/modulefiles/stack
module load hpc/1.2.0
module load hpc-gnu/10.1.0
module load hpc-mpt/2.22

`Cheyenne gnu/10.1.0`:
module use /glade/work/epicufsrt/contrib/hpc-stack/gnu10.1.0/modulefiles/stack
module load hpc/1.2.0
module load hpc-gnu/10.1.0
module load hpc-mpt/2.25

`Cheyenne gnu/11.2.0`:
module use /glade/work/epicufsrt/contrib/hpc-stack/gnu11.2.0/modulefiles/stack
module load hpc/1.2.0
module load hpc-gnu/11.2.0
module load hpc-mpt/2.25

`Orion miniconda:`
module use /work/noaa/epic-ps/role-epic-ps/miniconda3/modulefiles
module load miniconda3/4.12.0

`Orion intel:`
module use /work/noaa/epic-ps/role-epic-ps/miniconda3/modulefiles
module load miniconda3/4.12.0

module use /work/noaa/epic-ps/role-epic-ps/hpc-stack/libs/intel-2022.1.2/modulefiles/stack
module load hpc/1.2.0
module load hpc-intel/2022.1.2
module load hpc-impi/2022.1.2

`Jet miniconda:`
module use /mnt/lfs4/HFIP/hfv3gfs/role.epic/miniconda3/modulefiles
module load miniconda3/4.12.0

`Jet intel`:
module use /mnt/lfs4/HFIP/hfv3gfs/role.epic/miniconda3/modulefiles
module load miniconda3/4.12.0

module use /mnt/lfs4/HFIP/hfv3gfs/role.epic/hpc-stack/libs/intel-2022.1.2/modulefiles/stack
module load hpc/1.2.0
module load hpc-intel/2022.1.2
module load hpc-impi/2022.1.2

`NB: ` There were comments in [ufs-weather-app/PR-419](https://github.com/ufs-community/ufs-srweather-app/pull/419) suggesting to roll back to lower compiler versions for Cheyenne gnu (to use 11.2.0 instead of 12.1.0), Hera intel (to use intel/2021.1.2 instead of 2022.2.0),  and Jet intel (to use intel/2021.1.2 instead of intel/2022.2.0)

Either way could be OK for the SRW, and the libraries would be built for the lower-version compilers as suggested

### LINKED ISSUE #1586: ORT script failure due to TASK-related variable changes
Description

On tier one HPCs Hera and Orion, the operational requirement script fails with the below error.
"/ufs-weather-model/tests/opnReqTests/std.sh: line 34: TASKS: unbound variable Died with error code 1"

Expected behavior is that ORT should run successfully and pass ORT tests.

To Reproduce:

1. Log into Hera or Orion 
2. cd into working directory 
3. run git clone of ufs-community/ufs-weather-model develop branch
4. cd into ufs-weather-model/tests
5. run ./opnReqTest -n control_p8 -c std

Additional context

This error was also produced by running cases regional_control and cpld_control_nowave_noaero_p8. As well as with all ORT tests std,thr, mpi, dcp, rst, bit, dbg

The issue was possibly created by PR #1523 as there were changes to TASK-related variables from 1523. ORT script update is needed to reflect the change introduced from #1523.

image

### PR DESCRIPTION
**Pull request by zach1221**
Description

Updated module paths added to modulefiles for new HPC-Stack locations created on tier-1 on-prem HPCs.
Testing of the new HPC-Stack locations has been conducted successfully on Hera, Jet, Orion, Cheyenne intel/gnu and Hera intel/gnu. Updates also made for autoRT baseline capability and ORT scripts.

Related issue to HPC-Stack updates [#1465](https://github.com/ufs-community/ufs-weather-model/issues/1465)

New features/additions being added through this PR.
New HPC-Stack module locations added to modulefiles for the below HPCs.
- Jet intel and intel debug
- Hera intel and intel debug
- Hera gnu and gnu debug
- Cheyenne intel and intel debug
- Cheyenne gnu and gnu debug
- Orion intel and intel debug

Updates to the below files for autoRT baseline capability. (Adding new workdir and blstore paths)
- bl.py

Updates to the below files to correct issues with ORT jenkins-ci pipeline. (Update ORT scripts to correct logic related to TASKS variables and cmp_proc_bind.sh)
- wrt_env.sh, dcp.sh, mpi.sh, rst.sh, std.sh, thr.sh
- opnReqTest, run_test.sh
- jenkinsfile

### Input data additions/changes
No changes are expected to input data.

### Anticipated changes to regression tests:
No Baseline Change

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [x] none

## Commit Queue Checklist:

- [ ] Link PR's from all sub-components involved
- [ ] Confirm reviews completed in sub-component PR's
- [ ] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne with both Intel/GNU compilers
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Testing Day Checklist:

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - Intel
    - [x] Hera
    - [x] Orion
    - [x] Jet
    - [ ] Gaea
    - [x] Cheyenne
  - GNU
    - [x] Hera
    - [x] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [ ] N/A
  - [x] Log attached to comment

### CODE REVIEW

**Comment by jkbk2004** [comment]
need to revert hera/gnu to 9.2 and cheyenne/gnu to 10.1

**Comment by zach1221** [comment]
@jkbk2004 I have reverted hera/gnu to 9.2 and cheyenne/gnu to 10.1.

**Comment by jkbk2004** [comment]
> @jkbk2004 I have reverted hera/gnu to 9.2 and cheyenne/gnu to 10.1.

@natalie-perlin @zach1221 can we make sure about these reverting cases?

**Comment by jkbk2004** [comment]
cheyenne.gnu has some issues. Build crashes:
`Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/REAL(8)).
/glade/scratch/jongkim/UFS-RT-tests/rt-1595-gnu/HYCOM-interface/HYCOM/mod_xc_mp.h:1196:25:

 1196 |           call mpi_bcast(ga(1,j0_pe(mpe_1(np),np)+1), &
      |                         1`

**Comment by jkbk2004** [comment]
Orion needs update fms/g2tmpl:
`Lmod has detected the following error: The following module(s) are unknown:
"fms/2022.04" "g2tmpl/1.10.2"`

**Comment by jkbk2004** [comment]
On gaea, some issues as well:
`Lmod has detected the following error:
/lustre/f2/pdata/ncep/Jong.Kim/rt-1595/modulefiles/ufs_gaea.intel:
(ufs_gaea.intel): invalid command name "export"`

**Comment by jkbk2004** [comment]
@natalie-perlin can you address the above issues?

**Comment by jkbk2004** [comment]
@natalie-perlin Build is not going thru on Orion. Please, take a look at:` /work/noaa/epic-ps/jongkim/rt-1595/stmp/jongkim/FV3_RT/rt_1450/compile_006`

**Comment by jkbk2004** [comment]
@natalie-perlin still same build trouble on gaea: `/lustre/f2/scratch/Jong.Kim/FV3_RT/rt_7709/compile_001`

**Comment by natalie-perlin** [comment]
Updated fms/2022.04 and g2tmpl/1.10.2 on Orion

**Comment by jkbk2004** [comment]
> Updated fms/2022.04 and g2tmpl/1.10.2 on Orion
It's still not working on orion.
`+ cmake /work/noaa/epic-ps/jongkim/UFS-RT-tests/rt-1595 -DAPP=S2S -DCCPP_SUITES=FV3_GFS_v17_coupled_p8_sfcocn -DCMEPS_AOFLUX=ON -DMPI=ON -DCMAKE_BUILD_TYPE=Release -DMOM6SOLO=ON
CMake Error at /apps/cmake-3.22.1/share/cmake-3.22/Modules/CMakeDetermineCCompiler.cmake:49 (message):
  Could not find compiler set in environment variable CC:`

**Comment by natalie-perlin** [comment]
On Orion: Cmake complains about the following env. variables not set:
(See /work/noaa/epic-ps/jongkim/rt-1595/stmp/jongkim/FV3_RT/rt_1450/compile_006/err)
```
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_Fortran_COMPILER not set, after EnableLanguage
```
Suggest to add the following to ./modulefiles/ufs_orion.intel.lua (after L29):
```
setenv("CMAKE_C_COMPILER", "mpiicc")
setenv("CMAKE_CXX_COMPILER", "mpiicpc")
setenv("CMAKE_Fortran_COMPILER", "mpiifort")
```
Similar env. variable settings to be added to ufs_orion.intel_debug.lua.

**Comment by natalie-perlin** [comment]
@jkbk2004, @zach1221  - regarding the issue on Gaea:
Please set the correct module environment for Gaea. Use the following  EPIC-managed Lmod installed on Gaea in` module-setup.sh` , following the line that states `elif [[ $MACHINE_ID = gaea* ]] ; then`
```
      
    if ( ! eval module help > /dev/null 2>&1 ) ; then
      # Use EPIC-managed Lmod installed on Gaea
      export BASH_ENV="/lustre/f2/dev/role.epic/contrib/apps/lmod/lmod/init/bash"
      source $BASH_ENV
      export LMOD_SYSTEM_DEFAULT_MODULES="modules/3.2.11.4"
      module --initial_load --no_redirect restore
    fi
```
The following lines need then to be **removed** from `compile.sh`, as they likely overwrite the module environment initialization done in `setup-modules.sh` 
  _# Activate lua environment for gaea
  if [[ $MACHINE_ID == gaea.* ]] ; then
    source /lustre/f2/pdata/esrl/gsd/contrib/lua-5.1.4.9/init/init_lmod.sh
  fi_

**Comment by natalie-perlin** [comment]
The module on Gaea needs to be converted to lua format. This is the `modulefile ufs_gaea.intel.lua` :

```
help([[
  This module loads libraries required for building and running UFS Weather Model 
  on the NOAA RDHPC machine Gaea using Intel-2022.1.2
]])

whatis([===[Loads libraries needed for building the UFS Weather Model on Gaea ]===])

prepend_path("MODULEPATH", "/lustre/f2/dev/role.epic/contrib/modulefiles")
load(pathJoin("miniconda3",os.getenv("miniconda_ver") or "4.12.0"))

load(pathJoin("cmake", os.getenv("cmake_ver") or "3.20.1"))

prepend_path("MODULEPATH","/lustre/f2/dev/role.epic/contrib/hpc-stack/intel-2021.3.0/modulefiles/stack")
load(pathJoin("hpc", os.getenv("hpc_ver") or "1.2.0"))
load(pathJoin("intel", os.getenv("intel_ver") or "2021.3.0"))
load(pathJoin("hpc-intel", os.getenv("hpc_intel_ver") or "2021.3.0"))
load(pathJoin("hpc-cray-mpich", os.getenv("hpc_cray_mpich_ver") or "7.7.11"))
load(pathJoin("gcc", os.getenv("gcc_ver") or "8.3.0"))
load(pathJoin("libpng", os.getenv("libpng_ver") or "1.6.37"))

-- needed for WW3 build
load(pathJoin("gcc", os.getenv("gcc_ver") or "8.3.0"))
-- Needed at runtime:
load("alps")
load("rocoto")

load("ufs_common")

setenv("CC","cc")
setenv("FC","ftn")
setenv("CXX","CC")
setenv("CMAKE_C_COMPILER","cc")
setenv("CMAKE_CXX_COMPILER","CC")
setenv("CMAKE_Fortran_COMPILER","ftn")
setenv("CMAKE_Platform","gaea.intel")
```

**Comment by natalie-perlin** [comment]
The modulefile `ufs_gaea.intel_debug.lua` is similar to `ufs_gaea.intel.lua`, except for this line:
```load("ufs_common_debug")```

**Comment by natalie-perlin** [comment]
@zach1221 , @jkbk2004 

> @jkbk2004 I have reverted hera/gnu to 9.2 and cheyenne/gnu to 10.1.

What were the questions or issues with higher order compilers on Hera and Cheyenne?

**Comment by zach1221** [comment]
@natalie-perlin I think it was just to recheck/confirm that there were no issues with the below compilers on these two HPCs.
image

**Comment by zach1221** [comment]
@natalie-perlin  I added the "setenv" variable for cmake compiler to the Orion module lua file but still failed with same "language not enabled error".

**Comment by jkbk2004** [comment]
> On Orion: Cmake complains about the following env. variables not set: (See /work/noaa/epic-ps/jongkim/rt-1595/stmp/jongkim/FV3_RT/rt_1450/compile_006/err)
> 
> ```
> CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
> CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
> CMake Error: CMAKE_Fortran_COMPILER not set, after EnableLanguage
> ```
> 
> Suggest to add the following to ./modulefiles/ufs_orion.intel.lua (after L29):
> 
> ```
> setenv("CMAKE_C_COMPILER", "mpiicc")
> setenv("CMAKE_CXX_COMPILER", "mpiicpc")
> setenv("CMAKE_Fortran_COMPILER", "mpiifort")
> ```
> 
> Similar env. variable settings to be added to ufs_orion.intel_debug.lua.

@natalie-perlin I tried but it still not working.

**Comment by jkbk2004** [comment]
> The module on Gaea needs to be converted to lua format. This is the `modulefile ufs_gaea.intel.lua` :
> 
> ```
> help([[
>   This module loads libraries required for building and running UFS Weather Model 
>   on the NOAA RDHPC machine Gaea using Intel-2022.1.2
> ]])
> 
> whatis([===[Loads libraries needed for building the UFS Weather Model on Gaea ]===])
> 
> prepend_path("MODULEPATH", "/lustre/f2/dev/role.epic/contrib/modulefiles")
> load(pathJoin("miniconda3",os.getenv("miniconda_ver") or "4.12.0"))
> 
> load(pathJoin("cmake", os.getenv("cmake_ver") or "3.20.1"))
> 
> prepend_path("MODULEPATH","/lustre/f2/dev/role.epic/contrib/hpc-stack/intel-2021.3.0/modulefiles/stack")
> load(pathJoin("hpc", os.getenv("hpc_ver") or "1.2.0"))
> load(pathJoin("intel", os.getenv("intel_ver") or "2021.3.0"))
> load(pathJoin("hpc-intel", os.getenv("hpc_intel_ver") or "2021.3.0"))
> load(pathJoin("hpc-cray-mpich", os.getenv("hpc_cray_mpich_ver") or "7.7.11"))
> load(pathJoin("gcc", os.getenv("gcc_ver") or "8.3.0"))
> load(pathJoin("libpng", os.getenv("libpng_ver") or "1.6.37"))
> 
> -- needed for WW3 build
> load(pathJoin("gcc", os.getenv("gcc_ver") or "8.3.0"))
> -- Needed at runtime:
> load("alps")
> load("rocoto")
> 
> load("ufs_common")
> 
> setenv("CC","cc")
> setenv("FC","ftn")
> setenv("CXX","CC")
> setenv("CMAKE_C_COMPILER","cc")
> setenv("CMAKE_CXX_COMPILER","CC")
> setenv("CMAKE_Fortran_COMPILER","ftn")
> setenv("CMAKE_Platform","gaea.intel")
> ```

This should be separate feature. We are not using lua on gaea yet. We need to confirm your hpc stack installation work first.

**Comment by natalie-perlin** [comment]
> > On Orion: Cmake complains about the following env. variables not set: (See /work/noaa/epic-ps/jongkim/rt-1595/stmp/jongkim/FV3_RT/rt_1450/compile_006/err)
> > ```
> > CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
> > CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
> > CMake Error: CMAKE_Fortran_COMPILER not set, after EnableLanguage
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Suggest to add the following to ./modulefiles/ufs_orion.intel.lua (after L29):
> > ```
> > setenv("CMAKE_C_COMPILER", "mpiicc")
> > setenv("CMAKE_CXX_COMPILER", "mpiicpc")
> > setenv("CMAKE_Fortran_COMPILER", "mpiifort")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Similar env. variable settings to be added to ufs_orion.intel_debug.lua.
> 
> @natalie-perlin I tried but it still not working.

@jkbk2004 - 
 regarding Orion, where is the directory with the WM code that is being built?

**Comment by natalie-perlin** [comment]
> @natalie-perlin I added the "setenv" variable for cmake compiler to the Orion module lua file but still failed with same "language not enabled error".

Let me know where is the modulefile is and the log with the error

**Comment by jkbk2004** [comment]
@natalie-perlin can you read the crashing errors and paths above?

**Comment by natalie-perlin** [comment]
> @natalie-perlin can you read the crashing errors and paths above?

@jkbk2004 @zach1221  - Not finding the log file with the  "language not enabled error" message on Orion

**Comment by jkbk2004** [comment]
Please, take a look /work/noaa/epic-ps/jongkim/rt-1595/stmp/jongkim/FV3_RT/rt_1450/compile_006/err

**Comment by natalie-perlin** [comment]
> @natalie-perlin I think it was just to recheck/confirm that there were no issues with the below compilers on these two HPCs. image

Cheyenne gnu/10.1.0 is verified. 

Hera gnu/9.2 in /scratch1/NCEPDEV/nems/role.epic/hpc-stack/libs/gnu-9.2/ is verified as well (with mpich/3.3.2)

**Comment by jkbk2004** [comment]
Cheyenne.gnu passes ok!

**Comment by natalie-perlin** [comment]
> Please, take a look /work/noaa/epic-ps/jongkim/rt-1595/stmp/jongkim/FV3_RT/rt_1450/compile_006/err

This log file with the error has a timestamp from earlier time today, before the modulefile `ufs_orion.intel.lua` changed. Are there any tests that have been run following the modulefile update?

UPD: ... Found new test locations, looking at them now

**Comment by natalie-perlin** [comment]
@jkbk2004 , @zach1221 - 
Please hold on for a couple of hours with the RTs for Orion. I'd like to rebuild the hpc-stack in the same location as listed in the RT-1465, with the vector instructions that fit older partitions vjet and sjet as well. (Note that old hpc-stack was built without special any special compiler options at all). Will update with my comment when done.

**Comment by zach1221** [comment]
@jkbk2004 I think I fixed the issue causing ORT to fail on on-prem HPCs (i.e hera/orion). I've tested with control_p8, cpld_control_nowave_noaero_p8 and regional_control, please feel free to check behind me. 

Additionally, jenkins-ci is working again except for the regional_control tests (thr,dcp) and one control_p8 test (thr). I believe I have isolated the issue to the cmp_proc_bind.sh file in opnReqTests directory. This would explain why ORT passes all tests on on-prem HPCs but not jenkins, because this file I think is only used for the jenkins-ci pipeline.

**Comment by natalie-perlin** [comment]
@jkbk2004 @zach1221 @MichaelLueken - 
Updated hpc-stack on JET is ready for further RT and Jenkins testing, and is at the same location as listed in RT-1465.
  
  * SRW test successfully ran on all four partitions (xjet,kjet,sjet,vjet)
  * Weather Model built OK.

**Comment by zach1221** [comment]
Thanks, @natalie-perlin . Testing on jet again now.
@jkbk2004

**Comment by jkbk2004** [comment]
@natalie-perlin @zach1221 what about gaea and orion?

**Comment by natalie-perlin** [comment]
@jkbk2004 @zach1221 -

1) Fixed the issue on Orion. Loading the modules for intel/2022.1.2 and impi/2022.1.2 by default was added to hpc meta-modules.

2) Gaea - fixed, similar issue, loading intel, mpich modules by default. 

SRW test successfully runs with the new hpc-stack build.
SRW main directory:
/lustre/f2/dev/wpo/role.epic/sandbox/SRW/ufs-srw-devExperiment directory:
/lustre/f2/dev/wpo/role.epic/sandbox/SRW/expt_dirs/grid_RRFS_CONUScompact_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16

**Comment by jkbk2004** [comment]
@zach1221 can you update orion and gaea lua files?

**Comment by zach1221** [comment]
@jkbk2004 Orion and Jet have been updated. I've spoken with @natalie-perlin and she is checking the WM build again with the TCL version of the Gaea modulefile and will update us here once complete.

**Comment by natalie-perlin** [comment]
@zach1221 @jkbk2004 
The TCL file for Gaea, **ufs_gaea.intel**:
  
```
#%Module
proc ModulesHelp {} {
  puts stderr "\tcit - loads modules required for building and running UFS Model on Gaea/Intel"
}

module-whatis "loads UFS Model prerequisites for Gaea/Intel"

module load cmake/3.20.1
# Needed at runtime:
module load alps

module use /lustre/f2/dev/role.epic/contrib/hpc-stack/intel-2021.3.0/modulefiles/stack
module load hpc/1.2.0
module load hpc-intel/2021.3.0
module load hpc-cray-mpich/7.7.11
module load cray-python/3.7.3.2

#needed for WW3 build
module load gcc/8.3.0
module load libpng/1.6.37

module load ufs_common

setenv CC cc
setenv CXX CC
setenv FC ftn
setenv CMAKE_Platform gaea.intel

```

**Comment by natalie-perlin** [comment]
The modulefile **ufs_gaea.intel_debug** would be similar, except for "`module load ufs_common_debug`"

**Comment by zach1221** [comment]
@natalie-perlin @jkbk2004 Working with Mike to retest Gaea and we're having issues in compile. Netcdf is in the list of loaded modules, however it appears it's unable to find the necessary NetCDFConfig.cmake or netcdf-config.cmake files. /lustre/f2/scratch/Michael.Lueken/FV3_RT/rt_5488/compile_001

image

**Comment by natalie-perlin** [comment]
@zach1221 - The /lustre/f2/scratch/Michael.Lueken/FV3_RT/rt_5488/compile_001/err file indicates that the Lmod initialization has not been done properly, from the list of the loaded modules given in this log file. 
I need to determine the location of the ufs-wm code that is used for this build, to see what has to be  corrected

**Comment by MichaelLueken** [comment]
@natalie-perlin The ufs-wm code associated with that PR can be found: `/lustre/f2/pdata/ncep/Michael.Lueken/ufs-weather-model`

**Comment by natalie-perlin** [comment]
**module-setup.sh** needs to have updated Lmod initialization (similar to the way it is done in **./ufs-srweather-app/etc/lmod-setup.sh**):

```
elif [[ $MACHINE_ID = gaea* ]] ; then
    # We are on GAEA.
    if ( ! eval module help > /dev/null 2>&1 ) ; then
        # We cannot simply load the module command.  The GAEA
        # /etc/profile modifies a number of module-related variables
        # before loading the module command.  Without those variables,
        # the module command fails.  Hence we actually have to source
        # /etc/profile here.
        source /etc/profile
        __ms_source_etc_profile=yes
    else
        __ms_source_etc_profile=no
    fi
    export BASH_ENV="/lustre/f2/dev/role.epic/contrib/apps/lmod/lmod/init/bash"
    source $BASH_ENV

    export LMOD_SYSTEM_DEFAULT_MODULES="modules/3.2.11.4"
    module --initial_load --no_redirect restore


```

**Comment by natalie-perlin** [comment]
... and for gaea, modification for `compile.sh`, instead of lines 59-62, you have the following Lmod initialization::

  ```
# Activate lua environment for gaea
  if [[ $MACHINE_ID == gaea.* ]] ; then
       export BASH_ENV="/lustre/f2/dev/role.epic/contrib/apps/lmod/lmod/init/bash"
       source $BASH_ENV

        export LMOD_SYSTEM_DEFAULT_MODULES="modules/3.2.11.4"
        module --initial_load --no_redirect restore

  fi
```

**Comment by MichaelLueken** [comment]
@natalie-perlin After modifying `module-setup.sh`, the compile was still failing.  Retrying now after updating `compile.sh`.

**Comment by MichaelLueken** [comment]
@natalie-perlin Changing compile.sh with the following:
```
   if [[ $MACHINE_ID == gaea.* ]] ; then
-    source /lustre/f2/pdata/esrl/gsd/contrib/lua-5.1.4.9/init/init_lmod.sh
+    export BASH_ENV="/lustre/f2/dev/role.epic/contrib/apps/lmod/lmod/init/bash"
+    source $BASH_ENV
+
+    export LMOD_SYSTEM_DEFAULT_MODULES="modules/3.2.11.4"
+    module --initial_load --no_redirect restore
   fi
```
and module-setup.sh with:
```
-    module purge
-    # clean up after purge
-    unset _LMFILES_
-    unset _LMFILES_000
-    unset _LMFILES_001
-    unset LOADEDMODULES
-    module load modules
-    if [[ -d /opt/cray/ari/modulefiles ]] ; then
-        module use -a /opt/cray/ari/modulefiles
-    fi
-    if [[ -d /opt/cray/pe/ari/modulefiles ]] ; then
-        module use -a /opt/cray/pe/ari/modulefiles
-    fi
-    if [[ -d /opt/cray/pe/craype/default/modulefiles ]] ; then
-        module use -a /opt/cray/pe/craype/default/modulefiles
-    fi
-    if [[ -s /etc/opt/cray/pe/admin-pe/site-config ]] ; then
-        source /etc/opt/cray/pe/admin-pe/site-config
-    fi
-    if [[ "$__ms_source_etc_profile" == yes ]] ; then
-        source /etc/profile
-        unset __ms_source_etc_profile
-    fi
+    export BASH_ENV="/lustre/f2/dev/role.epic/contrib/apps/lmod/lmod/init/bash"
+    source $BASH_ENV
+
+    export LMOD_SYSTEM_DEFAULT_MODULES="modules/3.2.11.4"
+    module --initial_load --no_redirect restore
```
the compile is still failing with the same NetCDF issue:
```
CMake Error at CMakeLists.txt:121 (find_package):
  By not providing "FindNetCDF.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "NetCDF", but
  CMake did not find one.

  Could not find a package configuration file provided by "NetCDF" (requested
  version 4.7.4) with any of the following names:

    NetCDFConfig.cmake
    netcdf-config.cmake

  Add the installation prefix of "NetCDF" to CMAKE_PREFIX_PATH or set
  "NetCDF_DIR" to a directory containing one of the above files.  If "NetCDF"
  provides a separate development package or SDK, be sure it has been
  installed.
```
Is there any other location that needs to be updated to properly load ufs-wm modulefiles on Gaea?

**Comment by natalie-perlin** [comment]
@MichaelLueken - 
 I do see another file that appears to have Lmod initialization done, it's
`./tests/fv3_conf/fv3_slurm.IN_gaea`:

```
MACHINE_ID=gaea
source ./module-setup.sh
source /lustre/f2/pdata/esrl/gsd/contrib/lua-5.1.4.9/init/init_lmod.sh
```

Because it invokes ./module-setup.sh, the subsequent line could simply be removed, if module-setup.sh has been corrected.

**Comment by MichaelLueken** [comment]
@natalie-perlin Removing `source /lustre/f2/pdata/esrl/gsd/contrib/lua-5.1.4.9/init/init_lmod.sh` from `fv3_slurm.IN_gaea` doesn't seem to help either, unfortunately.  This is strange, because the SRW App is able to build the WM without issue using the same HPC-Stack.  I don't understand why the RT compile is failing due to NetCDF.

**Comment by zach1221** [comment]
@jkbk2004 The new hpc-stack on jet ran through the regression test suite without issue. Waiting for Orion to finish now.

**Comment by zach1221** [comment]
The RT suite also completes on Orion without issue, using the new stack.

**Comment by natalie-perlin** [comment]
@MichaelLueken - 
  What is the script/sequence are you running? Is it **./build.sh** or **./tests/rt.sh**?

**Comment by MichaelLueken** [comment]
@natalie-perlin - I'm using `nohup ./rt.sh -l rt.conf` to try and compile on Gaea (using `tests/rt.sh`).

**Comment by natalie-perlin** [comment]
@MichaelLueken  -
  There is a typo in the **/lustre/f2/pdata/ncep/Michael.Lueken/ufs-weather-model/tests/compile.sh** in line 61, it should be as follows:
`  export BASH_ENV="/lustre/f2/dev/role.epic/contrib/apps/lmod/lmod/init/bash"`

(currently it says "export _ENV_=...")

**Comment by MichaelLueken** [comment]
@natalie-perlin Thanks for pointing that out.  I have gone back in and corrected this issue.  Unfortunately, it is continuing to fail to compile with the same NetCDF error message.

**Comment by natalie-perlin** [comment]
@jkbk2004 -

My RT tests got compiled, run, but fail the baseline comparison, and report something like: 
...
```
Comparing RESTART/sfc_data.tile5.nc ............ALT CHECK......NOT OK
 Comparing RESTART/sfc_data.tile6.nc ............ALT CHECK......NOT OK
 Comparing RESTART/MOM.res.nc ............ALT CHECK......NOT OK
 Comparing RESTART/iced.2021-03-23-21600.nc ............ALT CHECK......NOT OK
 Comparing RESTART/ufs.cpld.cpl.r.2021-03-23-21600.nc ............ALT CHECK......NOT OK
  Comparing 20210323.060000.out_pnt.ww3 .........NOT OK
 Comparing 20210323.060000.out_grd.ww3 .........NOT OK

  0: The total amount of wall time                        = 335.113111
  0: The maximum resident set size (KB)                   = 1534764

Test 001 cpld_control_p8_mixedmode FAIL

```
Please take a look at:
`/lustre/f2/dev/role.epic/sandbox/UFS-WM/ufs-wm-hpctest2/tests/log_gaea.intel_old/rt_001_cpld_control_p8_mixedmode.log`, or
`rt_002_cpld_control_gfsv17.log`

**Comment by natalie-perlin** [comment]
I would like to try building the stack with no specific arch instructions, and to test whether this may improve testing results.

**Comment by natalie-perlin** [comment]
@MichaelLueken - 
  I attempted to copy your directory, and have got the same error as you did complaining about NETCDF.
  We seem to use different repositories, however. Your code come from 	https://github.com/zach1221/ufs-weather-model, while I clone the develop branch from https://github.com/ufs-community/ufs-weather-model.git .
  
 I made a fresh clone from the ufs-community repo, and modified only  the following: 
`modulefiles/ufs_gaea.intel`
`tests/compile.sh`
`tests/module-setup.sh`
`tests/fv3_conf/fv3_slurm.IN_gaea`
( plus rt.sh and rt.conf )

It builds successfully, as could be seen in
/lustre/f2/scratch/role.epic/FV3_RT/rt_31419/compile_001/
Main WM directory is /lustre/f2/dev/role.epic/sandbox/UFS-WM/ufs-wm-dev/

I will try to clone a code from 
https://github.com/zach1221/ufs-weather-model/  repo, and attempt to do build it with the similar modifications.

UPD.: Cloning from  **https://github.com/zach1221/ufs-weather-model**, branch **HPC-Stack-Update** - seem to build successfully, after the modifications to the 4 files  + 2 rt.* files, as mentioned above. 
Code directory: `/lustre/f2/dev/role.epic/sandbox/UFS-WM/ufs-wm-zach `
RT compile: `/lustre/f2/scratch/role.epic/FV3_RT/rt_31419/compile_001`

**Comment by jkbk2004** [comment]
@zach1221 if no progress on gaea, can you revert the chnage eon gaea? we need to commit the pr ASAP.

**Comment by zach1221** [comment]
@jkbk2004 gaea modulefiles are reverted.

**Comment by zach1221** [comment]
Jenkins-ci logs attached.
[ufs-weather-model » ort-docker-pipeline » PR-1596 #9 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/10698897/ufs-weather-model.ort-docker-pipeline.PR-1596.9.Console.Jenkins.pdf)

File: modulefiles/ufs_hera.gnu_debug.lua [hunk 1]
```diff
@@ -1,9 +1,9 @@
 help([[
-loads UFS Model prerequisites for Hera/GNU Debugging
+loads UFS Model prerequisites for Hera/GNU
```
Comment (BrianCurtis-NOAA) [inline modulefiles/ufs_hera.gnu_debug.lua]: Please add here that it's a debug build.

File: tests/opnReqTests/dcp.sh [hunk 2]
```diff
@@ -38,5 +39,5 @@ elif [[ $application == 'cpld' ]]; then
   fi
 fi
 
-(test $CI_TEST == 'true') && source $PATHRT/opnReqTests/cmp_proc_bind.sh
+#outdated (test $CI_TEST == 'true') && source $PATHRT/opnReqTests/cmp_proc_bind.sh
```
Comment (BrianCurtis-NOAA) [inline tests/opnReqTests/dcp.sh]: Do you need to keep this line? If its not needed, just remove them from all files.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Comment by natalie-perlin** [comment]
@jkbk2004  - Gaea transition has not been done yet.
