### PR TITLE
Regression test bug fixes for running on Jet or with Rocoto

### LINKED ISSUE #979: Jet rt.sh is hard-coded to ACCNR=h-nems
## Description
Jet rt.sh is hard-coded to ACCNR=h-nems

### To Reproduce:
Set `export ACCNR=hfv3gfs` (or anything other than h-nems). Notice the script still uses h-nems.

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
# PR Checklist

- [x] Ths PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] ~~New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.~~

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Jet was hard-coded to `ACCNR=h-nems` and Rocoto support was broken (especially on Jet). No impact to baseline from these udpates.

This PR also contains fv3/ccpp physics (CCPP PR#812) updates that implements a vertically-integrated formula to properly compute tracer column mass and ensure mass conservation for all tracers except TKE. See issue https://github.com/NCAR/ccpp-physics/issues/811 for details.  This update will change the baseline for all regression tests using Scale-Aware Mass-Flux (SAMF) shallow or deep convective schemes, as well as the Scale-aware TKE-based Moist Eddy-Diffusivity Mass-Flux (SATMEDMF) PBL scheme. for tracer column mass conservation in TVD schemes. 

### Issue(s) addressed

Resolves #979 and #980
Resolves https://github.com/NCAR/ccpp-physics/issues/811

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

Regression tests passed on Jet and Hera, using Rocoto.

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [x] CI: https://github.com/ufs-community/ufs-weather-model/actions/runs/1651831979

## Dependency:
- fv3atm: https://github.com/noaa-emc/fv3atm/pull/453
- CCPP physics: https://github.com/NCAR/ccpp-physics/pull/819

### CODE REVIEW

File: tests/run_compile.sh [hunk 1]
```diff
@@ -75,7 +75,10 @@ if [[ $ROCOTO = 'false' ]]; then
   submit_and_wait job_card
 else
   chmod u+x job_card
-  ./job_card
+  ( ./job_card 2>&1 1>&3 3>&- | tee err ) 3>&1 1>&2 | tee out
```
Comment (MinsukJi-NOAA) [inline tests/run_compile.sh:78]: Is this and the similar change in `run_test.sh` necessary? I ran RT with and without these changes and did not notice any difference in any of the log files.

Comment (SamuelTrahanNOAA) [reply tests/run_compile.sh:78]: Unless I'm mistaken, you need to redirect via tee to see logs in the job's own log file. Otherwise it only goes to the out and err files. There is similar code (but less reliable) in the non-Rocoto portions of the script.

**Review by MinsukJi-NOAA — APPROVED** [review]

File: tests/run_compile.sh (hunk 1 above)
Comment (DusanJovic-NOAA) [reply tests/run_compile.sh:78]: At some point we should remove all rocoto code, we do not use it and do not test it. For parallel execution we use ecflow.

Comment (SamuelTrahanNOAA) [reply tests/run_compile.sh:78]: I'll retest this. I know I added this change in two locations. Let me check if I really need them in both locations. This may take a whole day due to queue wait times.

Comment (SamuelTrahanNOAA) [reply tests/run_compile.sh:78]: @DusanJovic-NOAA  - It is premature to remove Rocoto support since most people outside EMC and NCO have no experience with ecFlow. I can keep it working on Jet and Hera until that interferes with my official duties.

Edit: I meant to say no experience with ecFlow.

**Comment by junwang-noaa** [comment]
@SamuelTrahanNOAA Are jet tests finished? Also do you have access to wcoss? If not, I can run RT on wcoss when the code is ready.

**Comment by SamuelTrahanNOAA** [comment]
The Jet and Hera tests passed. Although I have access to WCOSS, I lack project access to run the regression test. (I could use an unrelated project, but I'm not sure I'm allowed to.)

Baselines:

Hera Intel: /scratch1/NCEPDEV/stmp4/Samuel.Trahan/FV3_RT/REGRESSION_TEST_INTEL/
Hera GNU: /scratch1/NCEPDEV/stmp4/Samuel.Trahan/FV3_RT/REGRESSION_TEST_GNU/
Jet Intel: /lfs4/HFIP/hfv3gfs/s/rt/t/Samuel.Trahan/FV3_RT/REGRESSION_TEST_INTEL

Edit: Jet path was wrong.

**Comment by junwang-noaa** [comment]
@SamuelTrahanNOAA would you please change "BL_DATE=20211230" in rt.sh to "BL_DATE=20220103"?

also jet baseline is at: /lfs4/HFIP/hfv3gfs/s/rt/t/Samuel.Trahan/FV3_RT/REGRESSION_TEST_INTEL, correct?

File: tests/run_compile.sh (hunk 1 above)
Comment (SamuelTrahanNOAA) [reply tests/run_compile.sh:78]: @MinsukJi-NOAA I retested. Yes, the changes are necessary.  This is half of the bug fix for the critical bug in the workflow: the job deleted the out and err files Rocoto created in its `#SBATCH` lines, causing the rt_test.sh to conclude the test failed (because its grep failed). Now, Rocoto and the job_card each have their own log files, and this line ensures the logging goes to both.

**Comment by SamuelTrahanNOAA** [comment]
> @SamuelTrahanNOAA would you please change "BL_DATE=20211230" in rt.sh to "BL_DATE=20220103"?

Done.

> also jet baseline is at: /lfs4/HFIP/hfv3gfs/s/rt/t/Samuel.Trahan/FV3_RT/REGRESSION_TEST_INTEL, correct?

Yes.

**Comment by DeniseWorthen** [comment]
@SamuelTrahanNOAA Logs for Cheyenne are at /scratch2/NCEPDEV/stmp1/Denise.Worthen/ForSam

**Comment by junwang-noaa** [comment]
@grantfirl This PR is ready for commit, would you please commit CCPP PR#819?

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by SamuelTrahanNOAA** [comment]
> @grantfirl This PR is ready for commit, would you please commit CCPP PR#819?

I just approved and merged Grant's CCPP PR.

**Comment by grantfirl** [comment]
@SamuelTrahanNOAA @junwang-noaa Thanks Sam. I'll update the fv3atm PR branch with the newly merged main and push.

**Comment by junwang-noaa** [comment]
@SamuelTrahanNOAA fv3 PR was committed (fv3 revision: 8198cee ), please update your ufs-weather-model branch. Thanks

**Comment by SamuelTrahanNOAA** [comment]
> @SamuelTrahanNOAA fv3 PR was committed (fv3 revision: 8198cee ), please update your ufs-weather-model branch. Thanks

Done.
