### PR TITLE
p8b (with aerosols) 

### LINKED ISSUE #478: Add SDF for p8b coupled and standalone
## Description
Add SDF for p8b settings for coupled and uncoupled. 

## Solution
Add SDFs originally made by @yangfanglin  

Files are here: https://github.com/jessicameixner-noaa/fv3atm/tree/feature/p8b

## Testing:

1. Have you tested the code changes? On what platforms? In progress. 
2. Have you run regression test in ufs-weather-model or ufs-s2s-model with code changes?
- Will the baseline results change? Yes 
- If yes, please give brief explanation of your code updates on the regression test.
The results will change because the tests will be updated to use these PRs.  

## Dependent PRs:

None

### LINKED ISSUE #677: UFS-Aerosols component (GOCART) platform / compiler / prod-debug limitations
## Description

PR https://github.com/ufs-community/ufs-weather-model/pull/591 adds the UFS-Aeorosols component (GOCART) to the ufs-weather-model. The regression tests are run on Hera with Intel in PROD mode only. Issues/limitations:

1. Hera / Intel / DEBUG regression test fails with
```
  0:  af create fcst fieldbundle, name=sfc_nearest_stodrc=           0
  0:  af create fcst fieldbundle, name=sfc_bilinearrc=           0
  0:  in fcst,init total time:    66.0327100753784
  0:  in fcst run phase 2, na=           0
144:  in readxml,bf readxml,size(post_avblflds%param)=           0
144:  xml_perl_data read Post flat file
144:  allocate paramset to :           2
144:  allocate param to :          45
144:  sum num_post_afld :          45
144:  allocate param to :         149
144:  sum num_post_afld :         194
144:  in readxml, aft read flat file.xml,num_post_afld=         149
144:  in readxml, aft read flat file.xml,num_pset=           2
144:  Size of pset is:          149
144:  datset is: GFSPRS
144:  MXFLD is:          999
144:  size of lvlsxml:        97000
144:  size of post_avblflds param         149
144:  in readxml. nfld=         149 nrecout=         994
144:  post_fname=GFSPRS.GrbF00
144: forrtl: error (65): floating invalid
144: Image              PC                Routine            Line        Source
144: fv3.exe            000000000969D7DE  Unknown               Unknown  Unknown
144: libpthread-2.17.s  00002B96987D2630  Unknown               Unknown  Unknown
144: fv3.exe            0000000009290762  bndlyr_                   311  BNDLYR.f
144: libiomp5.so        00002B9696EE2A43  __kmp_invoke_micr     Unknown  Unknown
144: libiomp5.so        00002B9696EA62C6  __kmp_fork_call       Unknown  Unknown
144: libiomp5.so        00002B9696E65BB0  __kmpc_fork_call      Unknown  Unknown
144: fv3.exe            0000000009295D5E  bndlyr_                   272  BNDLYR.f
144: fv3.exe            00000000091FB669  miscln_                  1712  MISCLN.f
144: fv3.exe            0000000008F49327  process_                  116  PROCESS.f
144: fv3.exe            0000000003E9D321  post_gfs_mp_post_         201  post_gfs.F90
144: fv3.exe            0000000003E98BDA  inline_post_mp_in          43  inline_post.F90
144: fv3.exe            0000000003E36DE0  module_wrt_grid_c        1489  module_wrt_grid_comp.F90
144: fv3.exe            000000000132E79B  _ZN5ESMCI6FTable1        2036  ESMCI_FTable.C
144: fv3.exe            000000000132A15C  ESMCI_FTableCallE         765  ESMCI_FTable.C
144: fv3.exe            0000000001FF2A42  _ZN5ESMCI3VMK5ent        2204  ESMCI_VMKernel.C
144: fv3.exe            0000000001F758D0  _ZN5ESMCI2VM5ente        1211  ESMCI_VM.C
144: fv3.exe            000000000132A845  c_esmc_ftablecall         922  ESMCI_FTable.C
144: fv3.exe            00000000010C162C  esmf_compmod_mp_e        1214  ESMF_Comp.F90
144: fv3.exe            00000000017797AD  esmf_gridcompmod_        1889  ESMF_GridComp.F90
144: fv3.exe            0000000003AF9513  fv3gfs_cap_mod_mp        1263  fv3_cap.F90
144: fv3.exe            0000000001E2CB8C  _ZNK5ESMCI13Metho         333  ESMCI_MethodTable.C
144: fv3.exe            0000000001E2DFF0  _ZN5ESMCI11Method         519  ESMCI_MethodTable.C
144: fv3.exe            0000000001E2C9A0  c_esmc_methodtabl         303  ESMCI_MethodTable.C
```

2. `APP=ATMAERO` doesn't compile with GNU 9.2.0 on Hera (not tried: GNU 10.1.0 on Cheyenne):
```
/scratch1/BMC/gmtb/Dom.Heinzeller/ufs-weather-model/ufs-weather-model-feature-gocart/gnu/GOCART/ESMF/UFS/Aerosol_Comp_Mod.F90:38:33:

   38 |   character(len=*), dimension(*,2), parameter :: &
      |                                 1
Error: Bad specification for assumed size array at (1)
/apps/cmake/3.20.1/bin/cmake -E cmake_copy_f90_mod include/UFS_Aerosols/aerosol_diag_mod.mod GOCART/ESMF/UFS/CMakeFiles/UFS_Aerosols.dir/aerosol_diag_mod.mod.stamp GNU
/apps/cmake/3.20.1/bin/cmake -E touch GOCART/ESMF/UFS/CMakeFiles/UFS_Aerosols.dir/Aerosol_Diag_Mod.F90.o.provides.build
/scratch1/BMC/gmtb/Dom.Heinzeller/ufs-weather-model/ufs-weather-model-feature-gocart/gnu/GOCART/ESMF/UFS/Aerosol_Comp_Mod.F90:201:34:

  201 |       fieldMapSize = size(fieldMap, 1)
      |                                  1
```
3. `APP=ATMAERO` not tested on other R&D tie 1 platforms (orion, jet, gaea, cheyenne) / with other compilers due to issues with compiler versions, dependencies, ...

### LINKED ISSUE #1042: Update to use p8b settings in regression tests
## Description
Update p8 (coupled and standalone atm) regression tests to use p8b settings. Including a test for aerosols.  The benchmark tests will point to the p8b ICs (which are the same as p8a/p7.2). 

## Solution
Update the regtests 

## Alternatives
None

## Related to
https://github.com/NOAA-EMC/fv3atm/issues/478

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# PR Checklist

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [x] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [x] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [x] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [x] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

This PR updates all p8 tests to the p8b settings, which includes GOCART.   New baselines are required due to these settings updates.  New input is also required for the BM ICs and additional GOCART inputs for p8. 

Co-author: @rmontuoro 

Physics settings were given by the physics group and can be confirmed by @yangfanglin @RuiyuSun @JongilHan66 and others 

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues must always be created before starting work on a PR branch!) 
- fixes #1042 
- fixes https://github.com/NOAA-EMC/fv3atm/issues/478 

## Testing

These changes were tested on hera and orion

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [x] hera.intel
- [x] hera.gnu
- [x] orion.intel
- [x] cheyenne.intel 
- [x] cheyenne.gnu
- [x] gaea.intel 
- [x] jet.intel
- [x] wcoss_cray
- [x] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

## Dependencies

If testing this branch requires non-default branches in other repositories, list them. Those branches should have matching names (ideally).

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/491 
- waiting on https://github.com/NOAA-EMC/fv3atm/pull/489 
- waiting on https://github.com/ufs-community/ufs-weather-model/pull/1065 (or needs to be combined with this PR as this builds on those changes)

### CODE REVIEW

File: tests/default_vars.sh [hunk 1]
```diff
@@ -33,47 +33,52 @@ elif [[ $MACHINE_ID = wcoss_dell_p3 ]]; then
...
+  CHM_cpl_c384="0 287"; OPB_cpl_c384="312 431"; IPB_cpl_c384="432 479"
   NPROC_ICE_cpl_c384=48
 
   TASKS_cpl_bmrk=560; TPN_cpl_bmrk=28; INPES_cpl_bmrk=6; JNPES_cpl_bmrk=8
   THRD_cpl_bmrk=1; WPG_cpl_bmrk=24; MPB_cpl_bmrk="0 287"; APB_cpl_bmrk="0 311"
-  OPB_cpl_bmrk="312 431"; IPB_cpl_bmrk="432 479"; WPB_cpl_bmrk="480 559"
+  MPB_cpl_bmrk="0 287"; OPB_cpl_bmrk="312 431"; IPB_cpl_bmrk="432 479"; WPB_cpl_bmrk="480 559"
   NPROC_ICE_cpl_bmrk=48
 
+  TASKS_cpl_bmrk_aero=560; TPN_cpl_bmrk_aero=14; INPES_cpl_bmrk_aero=6; JNPES_cpl_bmrk_aero=8
```
Comment (DeniseWorthen) [inline tests/default_vars.sh:69]: Can all the bmrk_aero task settings be deleted? I don't see them being used anymore.

File: tests/default_vars.sh [hunk 2]
```diff
@@ -33,47 +33,52 @@ elif [[ $MACHINE_ID = wcoss_dell_p3 ]]; then
...
-  OPB_cpl_c384="312 431"; IPB_cpl_c384="432 479"
+  TASKS_cpl_c384=480; TPN_cpl_c384=14; INPES_cpl_c384=6; JNPES_cpl_c384=8
+  THRD_cpl_c384=2; WPG_cpl_c384=24; MPB_cpl_c384="0 287"; APB_cpl_c384="0 311"
+  CHM_cpl_c384="0 287"; OPB_cpl_c384="312 431"; IPB_cpl_c384="432 479"
   NPROC_ICE_cpl_c384=48
 
   TASKS_cpl_bmrk=560; TPN_cpl_bmrk=28; INPES_cpl_bmrk=6; JNPES_cpl_bmrk=8
   THRD_cpl_bmrk=1; WPG_cpl_bmrk=24; MPB_cpl_bmrk="0 287"; APB_cpl_bmrk="0 311"
-  OPB_cpl_bmrk="312 431"; IPB_cpl_bmrk="432 479"; WPB_cpl_bmrk="480 559"
+  MPB_cpl_bmrk="0 287"; OPB_cpl_bmrk="312 431"; IPB_cpl_bmrk="432 479"; WPB_cpl_bmrk="480 559"
```
Comment (DeniseWorthen) [inline tests/default_vars.sh]: Should this be ``CHM_cpl_bmrk="0 287"``, not ``MPB_cpl_bmrk``?

File: tests/default_vars.sh [hunk 3]
```diff
@@ -826,8 +879,15 @@ export CDMBWD_c192='0.23,1.5,1.0,1.0'
 export CDMBWD_c384='1.1,0.72,1.0,1.0'
 export CDMBWD_c768='4.0,0.15,1.0,1.0'
 
+#DT_INNER=(Time step)/2
+export DT_INNER_c96='350'
+export DT_INNER_c192='300'
+export DT_INNER_c384='150'
+export DT_INNER_c768='75'
```
Comment (DeniseWorthen) [inline tests/default_vars.sh]: Are quotes required here?

File: tests/default_vars.sh (hunk 2 above)
Comment (JessicaMeixner-NOAA) [reply tests/default_vars.sh]: Yes! Great catch! I'll fix this ASAP.

File: tests/default_vars.sh (hunk 1 above)
Comment (JessicaMeixner-NOAA) [reply tests/default_vars.sh:69]: The _aero was added because you need different memory requirements and more threads.  Tests such as cpld_bmark_p7 still use the non _aero settings.

File: tests/default_vars.sh (hunk 3 above)
Comment (JessicaMeixner-NOAA) [reply tests/default_vars.sh]: No, just updated.

File: tests/tests/cpld_bmark_p8 [hunk 4]
```diff
@@ -140,3 +151,5 @@ export RST_END=$RUN_END
 export RST_2_END=$RUN_END
 
 export FV3_RUN=cpld_control_run.IN
+export FIELD_TABLE=field_table_thompson_noaero_tke_GOCART
+export DIAG_TABLE=diag_table_p7.2_template
```
Comment (DeniseWorthen) [inline tests/tests/cpld_bmark_p8]: Is this the default DIAG_TABLE for all cpld_*p8 tests? If only the remaining P7 tests are using the older diag_table_template, maybe the p7.2_template should be made the default.

File: tests/default_vars.sh [hunk 5]
```diff
@@ -826,8 +879,15 @@ export CDMBWD_c192='0.23,1.5,1.0,1.0'
 export CDMBWD_c384='1.1,0.72,1.0,1.0'
 export CDMBWD_c768='4.0,0.15,1.0,1.0'
 
+#DT_INNER=(Time step)/2
+export DT_INNER_c96=350
```
Comment (junwang-noaa) [inline tests/default_vars.sh]: Should this be 360? If the time step is 700s, we won't get hourly output if the time step is 700.

File: tests/default_vars.sh [hunk 6]
```diff
@@ -1243,6 +1322,7 @@ export FHMAX=24
 export THRD=1
 export FHROT=0
 export WARM_START=.false.
+export WRITE_NSFLIP=.false.
```
Comment (junwang-noaa) [inline tests/default_vars.sh]: Please set the WRITE_NSFLIP default to .true.

File: tests/rt.conf [hunk 7]
```diff
@@ -2,35 +2,36 @@
 # S2S tests                                                                                                                                                                    #
 ###################################################################################################################################################################################
 
-COMPILE | -DAPP=S2SW -DCCPP_SUITES=FV3_GFS_v16_coupled_nsstNoahmpUGWPv1,FV3_GFS_v16_coupled_p7_rrtmgp,FV3_GFS_v16_coupled_p8      | - wcoss_cray                            | fv3 |
+COMPILE | -DAPP=S2SW -DUFS_GOCART=ON -DCCPP_SUITES=FV3_GFS_v16_coupled_nsstNoahmpUGWPv1,FV3_GFS_v16_coupled_p7_rrtmgp,FV3_GFS_v17_coupled_p8b     | - wcoss_cray                            | fv3 |
```
Comment (junwang-noaa) [inline tests/rt.conf]: Can we call this FV3_GFS_v17_coupled_p8? And update this suite file for future P8 prototypes?

Comment (JessicaMeixner-NOAA) [reply tests/rt.conf]: I'm following the naming convention from @yangfanglin, so I'll let him weigh in on if he would be okay with this change or not or if there's a need for being able to run the multiple options.

File: tests/default_vars.sh (hunk 6 above)
Comment (JessicaMeixner-NOAA) [reply tests/default_vars.sh]: done.

File: tests/rt.conf (hunk 7 above)
Comment (yangfanglin) [reply tests/rt.conf]: it is fine to call it FV3_GFS_v17_coupled_p8

File: tests/default_vars.sh (hunk 5 above)
Comment (JessicaMeixner-NOAA) [reply tests/default_vars.sh]: Actually it looks like the time step is 720 (https://github.com/JessicaMeixner-NOAA/ufs-weather-model/blob/feature/p8b_aero/tests/default_vars.sh#L1101) so I did not do 720/2 correctly and this should be 360 (or I found a dt=700 somewhere and now am not seeing it).  Eitherway, I'm updating this to 360.

File: tests/rt.sh [hunk 8]
```diff
@@ -494,7 +494,7 @@ fi
 
 INPUTDATA_ROOT=${INPUTDATA_ROOT:-$DISKNM/NEMSfv3gfs/input-data-20211210}
 INPUTDATA_ROOT_WW3=${INPUTDATA_ROOT}/WW3_input_data_20211113
-INPUTDATA_ROOT_BMIC=${INPUTDATA_ROOT_BMIC:-$DISKNM/NEMSfv3gfs/BM_IC-20210717}
+INPUTDATA_ROOT_BMIC=${INPUTDATA_ROOT_BMIC:-$DISKNM/NEMSfv3gfs/BM_IC-20220207}
```
Comment (junwang-noaa) [inline tests/rt.sh:497]: I saw data directories cpc,gfs_p7, mom6_da besides gfs_p8a and wav_p7.2 under BM_IC-20220207, are they same data sets as those under BM_IC-20210717? If yes, could we add gfs_p8a and wav_p7.2 under BM_IC-20210717 to avoid the duplications?

Comment (JessicaMeixner-NOAA) [reply tests/rt.sh:497]: That works for me.

File: tests/tests/cpld_bmark_p7 [hunk 9]
```diff
@@ -131,6 +131,19 @@ export MOM6_RESTART_SETTING=r
...
 export MIN_SEAICE=1.0e-11
 export IOPT_SFC=1
+export DNATS=1
+export IMP_PHYSICS=11
+export CCPP_SUITE=FV3_GFS_v16_coupled_nsstNoahmpUGWPv1
+export FIELD_TABLE=field_table_gfsv16
+export LGFDLMPRAD=.true.
+export KNOB_UGWP_VERSION=1
+export DO_UGWP_V0=.false.
+export DO_UGWP_V1=.true.
```
Comment (junwang-noaa) [inline tests/tests/cpld_bmark_p7:141]: So we are not running ugwpv1 in p8 test? Is there a plan to add a ugwpv1 test in p8 configuration?

File: tests/tests/cpld_bmark_p8 (hunk 4 above)
Comment (JessicaMeixner-NOAA) [reply tests/tests/cpld_bmark_p8]: done

File: tests/rt.conf (hunk 7 above)
Comment (JessicaMeixner-NOAA) [reply tests/rt.conf]: File name has been updated.

File: tests/tests/cpld_bmark_p7 (hunk 9 above)
Comment (JessicaMeixner-NOAA) [reply tests/tests/cpld_bmark_p7:141]: This test is maintained which tests DO_UGWP_V1=true.  The p8 tests are all updated to the full set of p8b settings.  I do not know of any additional planned tests.

File: tests/tests/cpld_bmark_p8 [hunk 10]
```diff
@@ -63,18 +64,23 @@ export FHMAX=6
 export RESTART_N=`expr ${FHMAX} - ${FHROT}`
 export RESTART_INTERVAL="${RESTART_N} -1"
 
-export TASKS=$TASKS_cpl_bmrk
-export TPN=$TPN_cpl_bmrk
-export INPES=$INPES_cpl_bmrk
-export JNPES=$JNPES_cpl_bmrk
-export THRD=$THRD_cpl_bmrk
-export WRTTASK_PER_GROUP=$WPG_cpl_bmrk
+export WLCLK=45
```
Comment (DeniseWorthen) [inline tests/tests/cpld_bmark_p8:67]: Does this test require 45 minutes?

Comment (JessicaMeixner-NOAA) [reply tests/tests/cpld_bmark_p8:67]: It was consistently running out of time during testing.  I can check to see what the time is now though.

File: tests/tests/cpld_bmark_mpi_p8 [hunk 11]
```diff
@@ -1,142 +0,0 @@
-#
-#  cpld_bmark_p8 test WW3 mpi
```
Comment (junwang-noaa) [inline tests/tests/cpld_bmark_mpi_p8:2]: Why is this test deleted?

Comment (JessicaMeixner-NOAA) [reply tests/tests/cpld_bmark_mpi_p8:2]: It was never intended to be a long term test and it was one less test to add aerosols to.  I can add it back if it's desired.

File: tests/tests/cpld_bmark_p7 (hunk 9 above)
Comment (junwang-noaa) [reply tests/tests/cpld_bmark_p7:141]: Since now the P8 tests are available, do we still need to maintain the cpld_bmark_p7 test? Can we have P8+ugwdv1 test?

File: tests/tests/cpld_control_c96_noaero_p8 [hunk 12]
```diff
@@ -0,0 +1,103 @@
+#
+#  cpld_control C96 P8 test
```
Comment (junwang-noaa) [inline tests/tests/cpld_control_c96_noaero_p8]: Can we change it to cpld_control C96 no aero P8 test?

File: tests/tests/cpld_control_c96_p8 [hunk 13]
```diff
@@ -1,8 +1,8 @@
 #
-#  cpld_control C96 P8 test
+#  cpld_control C96 P8 aero test
```
Comment (junwang-noaa) [inline tests/tests/cpld_control_c96_p8]: Maybe just to keep it as "cpld_control C96 P8 test" as P8 will run with aerosol?

File: tests/tests/cpld_control_p8 [hunk 14]
```diff
@@ -1,8 +1,8 @@
 #
-#  cpld_control P8 test
+#  cpld_control P8 aero test
```
Comment (junwang-noaa) [inline tests/tests/cpld_control_p8]: same here

File: tests/tests/cpld_debug_noaero_p8 [hunk 15]
```diff
@@ -0,0 +1,92 @@
+#
+#  cpld_debug_p8 test
```
Comment (junwang-noaa) [inline tests/tests/cpld_debug_noaero_p8]: maybe change it to cpld_debug_p8 no aero test to keep consistent with the test name.

File: tests/tests/cpld_debug_p8 [hunk 16]
```diff
@@ -1,8 +1,8 @@
 #
-#  cpld_debug_p8 test
+#  cpld_debug_p8 aero test
```
Comment (junwang-noaa) [inline tests/tests/cpld_debug_p8]: same here

File: tests/tests/cpld_bmark_p7 (hunk 9 above)
Comment (JessicaMeixner-NOAA) [reply tests/tests/cpld_bmark_p7:141]: I have maintained this test so it would get the same results as before.  Any P8+ugwdv1 test seems out of the scope of the current PR.

File: tests/tests/cpld_decomp_p8 [hunk 17]
```diff
@@ -1,8 +1,8 @@
 #
-#  cpld_decomp P8 test
+#  cpld_decomp P8 aero test
```
Comment (junwang-noaa) [inline tests/tests/cpld_decomp_p8]: Here too and the rest of tests

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA Since the input data are available on other platforms, would you please run the RT test on those platforms? Thanks

**Comment by JessicaMeixner-NOAA** [comment]
> @JessicaMeixner-NOAA Since the input data are available on other platforms, would you please run the RT test on those platforms? Thanks

I can run on orion, wcoss-dell, wcoss-cray and gaea.  Someone else will have to run on jet and Cheyenne.

**Comment by DeniseWorthen** [comment]
I tried to compile on Cheyenne---I believe you still need to change the "p8b" to "p8" in the suite files themselves
```
<suite name="FV3_GFS_v17_coupled_p8b" version="1">
```

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen thanks for finding this.  I pushed the fix.

**Comment by JessicaMeixner-NOAA** [comment]
I have run into the following issue on wcoss-dell, see /gpfs/dell2/ptmp/Jessica.Meixner/FV3_RT/rt_46221/compile_001/err: 
```
CMake Error at GOCART/CMakeLists.txt:68 (find_package):
  By not providing "FindMAPL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "MAPL", but
  CMake did not find one.

  Could not find a package configuration file provided by "MAPL" with any of
  the following names:

    MAPLConfig.cmake
    mapl-config.cmake

  Add the installation prefix of "MAPL" to CMAKE_PREFIX_PATH or set
  "MAPL_DIR" to a directory containing one of the above files.  If "MAPL"
  provides a separate development package or SDK, be sure it has been
  installed.

```
I assumed MAPL was installed on all platforms since it was included in the ufs_common module file?

**Comment by junwang-noaa** [comment]
@kgerheiser @Hang-Lei-NOAA Do we have MAPL/yafyaml/gftl-shared installed on dell/jet/gaea/orion?

File: tests/tests/cpld_bmark_p8 (hunk 10 above)
Comment (JessicaMeixner-NOAA) [reply tests/tests/cpld_bmark_p8:67]: Orion wall time is:  1098.278576 
I'll make sure the other machines have similar timing and then we can remove the WLCLCK.

**Comment by kgerheiser** [comment]
Yes, we've been keeping the MAPL installations up-to-date as new versions of ESMF come out.

**Comment by Hang-Lei-NOAA** [comment]
Yes.

**Comment by JessicaMeixner-NOAA** [comment]
I've done a module spider on maple on mars and Venus, and neither have  mapl/2.11.0-esmf-8.2.1b04 (also I get an issue trying to load jasper/2.0.22) as well.  Am I doing something wrong? I'm basically just loading on the login node after a module purge: https://github.com/JessicaMeixner-NOAA/ufs-weather-model/blob/feature/p8b_aero/modulefiles/ufs_wcoss_dell_p3#L9-L19 and then https://github.com/JessicaMeixner-NOAA/ufs-weather-model/blob/feature/p8b_aero/modulefiles/ufs_common#L3-L23 ?

**Comment by JessicaMeixner-NOAA** [comment]
I do have the correct modules on hera, orion and gaea it's just WCOSS-dell that I'm having the MAPL issues.

**Comment by Hang-Lei-NOAA** [comment]
I will check this. Thanks

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA On cheyenne.intel, all p8 jobs compiled. 

The ``cpld_control_c384_p8`` fails at startup with ``MPT: shepherd terminated: r14i1n25.ib0.cheyenne.ucar.edu - job aborting``. This can really be almost anything in my experience but it is usually memory related. 

The ``cpld_bmark_p8`` also failed, though I can't find any error message.

The ``cpld_bmark_p7`` did not reproduce the baseline. Shouldn't this test still reproduce? Has it reproduced in your tests?

The ``cpld_control_p7_rrtmgp`` did reproduce.

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen thanks for reporting these issues.  I forgot about cpld_bmark_p7, it reproduced except that you can't actually point to either old or new ICs.  So if you un-did the changes in 
tests/fv3_conf/cpld_control_run.IN 
  FV3_IC=@[INPUTDATA_ROOT_BMIC]/${SYEAR}${SMONTH}${SDAY}${SHOUR}/gfs_p8a/@[ATMRES]_L@[NPZ]/INPUT
to the old line, then it should still reproduce. That being said, it has been a minute since I ran that so I can double check that on orion.    

Likely both the cpld_control_c384_p8 and cpld_bmark_p8 are memory issues.  I'll check the Cheyenne settings and see if I can push a change to the resources that might help. 

Comparing with a new baseline on (gaea, wcoss-*, orion, I did realize I didn't update the control_p8 with a recent settings change so I'll soon push an update for that as well).

**Comment by JessicaMeixner-NOAA** [comment]
For the FV3_IC and the p7 test reproducing, I can make that a variable but I guess decided that wasn't necessary.  If others think it is, I can add in a variable.

**Comment by DeniseWorthen** [comment]
I suspect the issue w/ the p7 test is also from ``#export DZ_MIN=2`` in default_vars. It is not re-set to 2 in the p7 test.

**Comment by JessicaMeixner-NOAA** [comment]
Thanks for the heads up, it seems it was longer than I remember from when I checked this test.  I'll add confirming this to my to-do list.

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen I pushed a recommended change for memory for Cheyenne  - let me know if that doesn't work and we'll try something else.

**Comment by DeniseWorthen** [comment]
I think setting dz_min back to 2 for ``cpld_bmark_p7`` does allow the baseline to reproduce. I tested by just changing the input.nml and then comparing the mediator restart file against the baseline.

**Comment by JessicaMeixner-NOAA** [comment]
@Hang-Lei-NOAA @kgerheiser  -- I was able to load the MAPL module on WCOSS-Dell today and am assuming it's ready to use.   Thank you!

@DeniseWorthen @junwang-noaa to get the cpld_bmark_p7 I need to add as Denise mentioned above DZ_MIN=2.  Also I needed to add WRITE_NSFLIP=.false. (this is the default value, if I'm not mistaken) and change in the input directory to use the p7 atm input files.  Please let me know what of these changes you'd like me to maintain other than of course adding DZ_MIN=2.  The log file and changes can be seen locally on orion here: /work/noaa/marine/jmeixner/p8b/ufs-p7test

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA We do want to maintain the current bmark_p7 test reproducing the current baseline. Once the P8 prototype is finalized we will drop the test. 

It think the simplest solution would be to add a variable such as ``P7IC = .false.`` as a default, use that variable in the fv3_conf/cpld_control_run.IN to control the source directory and then set it true for the cpld_bmark_p7 test.

For Cheyenne.intel, the c384 test was able to run with the changed resources but not the bmark_p8. From experience I'm not sure that the c384 working this time means it will work a second time. I will test again after you push the dz_min and the IC fix.

**Comment by JessicaMeixner-NOAA** [comment]
I pushed changes for the p7 test  and an update to the p8 Cheyenne settings

**Comment by JessicaMeixner-NOAA** [comment]
I'm creating the baseline on wcoss-dell and running the full set after the updates on orion against the existing baselines so we'll have all that information.

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA I've tested with the latest changes. The p7 bmark test now reproduces, so thanks for that fix. 

The bmark_p8 test runs but it takes almost 26 minutes, which is probably cutting it too fine for our 30min test limit. The c384_p8 test also runs, but clocks in at about 28 minutes. 

However, now the c192 p8 test failed w/ the MPT shepherd error. I went back and confirmed that one had previously run. I think this shows a case that when we're close to some limit, it sometimes works and sometimes doesn't.

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen would increasing the time limits for those two tests be acceptable?  Alternatively, I can increase the threads again for additional memory to be available and could attempt to further balance the test if there is a machine I have access to has similar performance to Cheyenne.    Does Cheyenne provide any memory usage when running that you could share?

**Comment by DeniseWorthen** [comment]
We'll need to discuss at the morning tag-up. We may need to turn the tests off on Cheyenne. 

I'm not sure what sort of memory usage report you might be referring to. Is there something I should look for---information that can be retrieved on other platforms?

**Comment by JessicaMeixner-NOAA** [comment]
I know for example that WCOSS-DELL in the out file you can get things like: 
```
Resource usage summary:

    CPU time :                                   24514.00 sec.
    Max Memory :                                 89629 MB
    Average Memory :                             60212.12 MB
```
but not all machines have this type of information.

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen I have worked on other platforms to see if I can figure out other combinations to make the model a little faster.  I can bump up to 8x8 (from 6x8) for the atm model and take a few cores away from the other components but you don't see a huge speed up (although it does in fact speed up a little).  
On hera for example: 
Current 6x8 settings (28 nodes): 
```
  0: The total amount of wall time                        = 999.551893
  0: The total amount of time in user mode                = 1450.440496
```

  8x8 reducing other components (28 nodes): 
```
  TASKS_cpl_bmrk_aero=560; TPN_cpl_bmrk_aero=20; INPES_cpl_bmrk_aero=8; JNPES_cpl_bmrk_aero=8
  THRD_cpl_bmrk_aero=2; WPG_cpl_bmrk_aero=24; MPB_cpl_bmrk_aero="0 383"; APB_cpl_bmrk_aero="0 407"
  CHM_cpl_bmrk_aero="0 383"; OPB_cpl_bmrk_aero="384 483"; IPB_cpl_bmrk_aero="484 507"; WPB_cpl_bmrk_aero="508 559"
  NPROC_ICE_cpl_bmrk_aero=24
```

Timing: 
```
  0: The total amount of wall time                        = 952.125671
  0: The total amount of time in user mode                = 1287.446964
```

8x12, reducing other components (39 nodes): 
```
  TASKS_cpl_bmrk_aero=780; TPN_cpl_bmrk_aero=20; INPES_cpl_bmrk_aero=12; JNPES_cpl_bmrk_aero=8
  THRD_cpl_bmrk_aero=2; WPG_cpl_bmrk_aero=24; MPB_cpl_bmrk_aero="0 575"; APB_cpl_bmrk_aero="0 599"
  CHM_cpl_bmrk_aero="0 575"; OPB_cpl_bmrk_aero="600 699"; IPB_cpl_bmrk_aero="700 719"; WPB_cpl_bmrk_aero="720 779"
  NPROC_ICE_cpl_bmrk_aero=20
```
Timing: 

```
  0: The total amount of wall time                        = 754.271854
  0: The total amount of time in user mode                = 983.948570
```

On Cheyenne since you need to use 3-4 threads for memory, the node count will get very high very quickly, but thought this might be helpful as decisions are made on the best paths forward. 


The dell logs were added, note I had issues with Dell the past several days not just for this PR where a different test or compile would fail each time although I had no troubles creating the baseline.  All the tests do however pass. 

Please let me know if there are other outstanding issues I can help address.

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA Thanks for those tests. We have been having various compile issues w/ Dell which we believe we now have a solution for. That may be the cause of your variable test results. 

For Cheyenne, @jkbk2004 was going to try to do some testing on Cheyenne for your PR.

**Comment by jkbk2004** [comment]
@JessicaMeixner-NOAA @DeniseWorthen Yeah, submitted RT-intel runs on Cheyenne. will keep you posted.

**Comment by jkbk2004** [comment]
@JessicaMeixner-NOAA @DeniseWorthen @junwang-noaa on cheyenne/intel: some check failures. most expensive ones are around 20 minutes.
rt-1071-fails
rt-1071-timings

**Comment by JessicaMeixner-NOAA** [comment]
@jkbk2004 these tests are expected to have different answers than the existing baselines.  Is this compared against the existing baseline or a new one?

**Comment by jkbk2004** [comment]
@JessicaMeixner-NOAA do I need to test with develop-20220228? I tested with develop-20220224.

**Comment by JessicaMeixner-NOAA** [comment]
This PR will change baselines for the tests that failed, so if you're testing against the existing baseline, your results are as expected.

**Comment by junwang-noaa** [comment]
Please merge to the top of develop branches, and change the BL_DATE to 20220304 in rt.sh. Thanks

**Comment by JessicaMeixner-NOAA** [comment]
> 20220304

Done!

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA Please create new baseline and run RT on wcoss. Please let me know if you have issue copying new baseline. Thanks.

**Comment by JessicaMeixner-NOAA** [comment]
@junwang-noaa are we anticipating more updates or should I start creating baselines/running things on wcoss?

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
[BL] Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/867250832/20220304133011/ufs-weather-model
[BL] Error: Test cpld_control_c192_p8 006 failed in run_test failed 
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by junwang-noaa** [comment]
> @junwang-noaa are we anticipating more updates or should I start creating baselines/running things on wcoss?

No. We have all the code changes. You can start creating baselines on wcoss.

**Comment by junwang-noaa** [comment]
@jkbk2004 Jong, would you please take a look at the cpld_control_c192_p8 RT test  on Cheyenne? Thanks

**Comment by jkbk2004** [comment]
@junwang-noaa I am checking.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
[BL] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/867250832/20220304201513/ufs-weather-model
[BL] Error: Test compile_001 failed in run_compile failed 
[BL] Error: Test compile_002 failed in run_compile failed 
Please make changes and add the following label back: jet-intel-BL

**Comment by junwang-noaa** [comment]
@kgerheiser Do we have MAPL installed on jet? I saw error:

Force 32-bit build for GOCART
CMake Error at GOCART/CMakeLists.txt:69 (include):
  include could not find requested file:

    mapl_acg


CMake Error at GOCART/ESMF/Aerosol_GridComp/CMakeLists.txt:9 (mapl_acg):
  Unknown CMake command "mapl_acg".

**Comment by kgerheiser** [comment]
Yep, it's there.

```
module load esmf/8.2.1b04
module load mapl/2.11.0-esmf-8.2.1b04
```

**Comment by junwang-noaa** [comment]
@rmontuoro Do you know if the mapl_acg is included in mapl/2.11.0?

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: orion
Compiler: intel
Job: BL
[BL] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/867250832/20220304141534/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /work/noaa/nems/emc.nemspara/autort/pr/867250832/20220304164615/ufs-weather-model
[RT] Error: Test hafs_regional_telescopic_2nests_atm 104 failed in run_test failed 
Please make changes and add the following label back: orion-intel-BL

**Comment by junwang-noaa** [comment]
@rmontuoro @JessicaMeixner-NOAA would you please confirm the mapl_acg is in mapl/2.11.0? According to @kgerheiser The MAPL/2.11.0 is installed on jet.

**Comment by jkbk2004** [comment]
@JessicaMeixner-NOAA @junwang-noaa cpld_control_c192_p8 crashes on cheyenne. MPT: shepherd terminated: r1i5n7.ib0.cheyenne.ucar.edu - job aborting

**Comment by JessicaMeixner-NOAA** [comment]
Can someone help me move baselines on WCOSS to the official area? 
On WCOSS-cray the baseline is here: /gpfs/hps3/stmp/Jessica.Meixner/FV3_RT/REGRESSION_TEST
On WCOSS-Dell the baseline is here: /gpfs/dell2/stmp/Jessica.Meixner/FV3_RT/REGRESSION_TEST 

I've emailed the WCOSS Helpdesk to reset my password, but I do not know how long that will take.  Note, it took me about 3+ tries over the weekend to finally get the WCOSS-DELL baseline to generate w/out issues. (It was a different issue each time and unrelated to the updates made here from what I could tell).

**Comment by junwang-noaa** [comment]
I am copying the data on venus. On surge, I got:

SURGE-slogin1 > ls /gpfs/hps3/stmp/Jessica.Meixner/FV3_RT/REGRESSION_TEST
ls: cannot access /gpfs/hps3/stmp/Jessica.Meixner/FV3_RT/REGRESSION_TEST: No such file or directory

**Comment by JessicaMeixner-NOAA** [comment]
@junwang-noaa thank you.  It looks like my cray baseline was scrubbed (I thought it was 5 days not 2?), I'm resubmitting that job now.

**Comment by JessicaMeixner-NOAA** [comment]
> @rmontuoro @JessicaMeixner-NOAA would you please confirm the mapl_acg is in mapl/2.11.0? According to @kgerheiser The MAPL/2.11.0 is installed on jet.

On hera, in /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/impi-2018.0.4/mapl/2.11.0-esmf-8.2.1b04 there are the following: 

etc/mapl_acg.pl
lib64/cmake/MAPL/mapl-import.cmake
share/MAPL/cmake/mapl_acg.cmake

So looks like mapl_acg is something in MAPL/2.11.0 ?

**Comment by JessicaMeixner-NOAA** [comment]
> @JessicaMeixner-NOAA @junwang-noaa cpld_control_c192_p8 crashes on cheyenne. MPT: shepherd terminated: r1i5n7.ib0.cheyenne.ucar.edu - job aborting

@jkbk2004  - @DeniseWorthen replied with a similar issue before in this PR and mentioned that this is typically a memory issue.  Does a simple re-run fix the issue?  Otherwise, for Cheyenne, we could update (line 612-615) from: 
```
  TASKS_cpl_c192=288; TPN_cpl_c192=36; INPES_cpl_c192=4; JNPES_cpl_c192=8
  THRD_cpl_c192=1; WPG_cpl_c192=12;  MPB_cpl_c192="0 191"; APB_cpl_c192="0 203"
  CHM_cpl_c192="0 191"; OPB_cpl_c192="204 263"; IPB_cpl_c192="264 287"
  NPROC_ICE_cpl_c192=24
```
to
```
  TASKS_cpl_c192=288; TPN_cpl_c192=18; INPES_cpl_c192=4; JNPES_cpl_c192=8
  THRD_cpl_c192=2; WPG_cpl_c192=12;  MPB_cpl_c192="0 191"; APB_cpl_c192="0 203"
  CHM_cpl_c192="0 191"; OPB_cpl_c192="204 263"; IPB_cpl_c192="264 287"
  NPROC_ICE_cpl_c192=24
```

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA Thanks for confirming.

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA When you created baseline from dell, what are the issues (error messages) for the failed runs?
I created new baseline on dell for Grant's PR 1#032 after the compile issue was fixed, I did not have any problem when creating new baseline.

**Comment by kgerheiser** [comment]
MAPL is installed properly, but the `lib` directory is `lib64`. It's possible MAPL changed their install directory to `CMAKE_INSTALL_LIBDIR` in this newer version.

`ls /lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/intel-18.0.5.274/impi-2018.4.274/mapl/2.11.0-esmf-8.2.1b04/lib64/`

```
cmake		   libMAPL.a	   libMAPL.cap.a	libMAPL.generic.a    libMAPL.griddedio.a  libMAPL.oomph.a  libMAPL.pfio.a      libMAPL.shared.a   libMAPL_cfio_r8.a
libMAPL.ExtData.a  libMAPL.base.a  libMAPL.constants.a	libMAPL.gridcomps.a  libMAPL.history.a	  libMAPL.orbit.a  libMAPL.profiler.a  libMAPL_cfio_r4.a  libpflogger.a
```

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA I will try the changed resources for the C192 test. 

We still have issues w/ wall clock on the two c384 tests however. For the BL creation, we had the following results, so we're still going to need to adjust the configurations.

```
cpld_bmark_p8
0:The total amount of wall time                        = 1656.513562

cpld_control_c384_p8
0:The total amount of wall time                        = 1751.353799
```

Since the c384 test is running 12 hours, we could reduce the FHMAX to 6 hours, but that will require new baselines for this test everywhere. The bmark case is already only running for 6 hours.

**Comment by DusanJovic-NOAA** [comment]
> MAPL is installed properly, but the `lib` directory is `lib64`. It's possible MAPL changed their install directory to `CMAKE_INSTALL_LIBDIR` in this newer version.
> 
> `ls /lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/intel-18.0.5.274/impi-2018.4.274/mapl/2.11.0-esmf-8.2.1b04/lib64/`
> 
> ```
> cmake		   libMAPL.a	   libMAPL.cap.a	libMAPL.generic.a    libMAPL.griddedio.a  libMAPL.oomph.a  libMAPL.pfio.a      libMAPL.shared.a   libMAPL_cfio_r8.a
> libMAPL.ExtData.a  libMAPL.base.a  libMAPL.constants.a	libMAPL.gridcomps.a  libMAPL.history.a	  libMAPL.orbit.a  libMAPL.profiler.a  libMAPL_cfio_r4.a  libpflogger.a
> ```

I think all libraries should be installed in lib. This lib vs. lib64 just creates confusion and inconsistency.

**Comment by junwang-noaa** [comment]
@kgerheiser I saw mapl-import.cmake is missing on jet and mapl_acg is included in mapl-import.cmake

on jet
[14:21:39]emc.nemspara@fe8:/lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/intel-18.0.5.274/impi-2018.4.274/mapl/2.11.0-esmf-8.2.1b04
-->ls lib64/cmake/MAPL
MAPL-targets-release.cmake  MAPL-targets.cmake  mapl-config-version.cmake  mapl-config.cmake

on hera:
[Jun.Wang@hfe09 2.11.0-esmf-8.2.1b04]$ ls lib64/cmake/MAPL
MAPL-targets-release.cmake  MAPL-targets.cmake  mapl-config-version.cmake  mapl-config.cmake  mapl-import.cmake

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA The baseline develop-20220304 is available on dell.

**Comment by rmontuoro** [comment]
> @kgerheiser Do we have MAPL installed on jet? I saw error:
> 
> Force 32-bit build for GOCART CMake Error at GOCART/CMakeLists.txt:69 (include): include could not find requested file:
> 
> ```
> mapl_acg
> ```
> 
> CMake Error at GOCART/ESMF/Aerosol_GridComp/CMakeLists.txt:9 (mapl_acg): Unknown CMake command "mapl_acg".

@junwang-noaa - `mapl_acg` is a CMake function defined in `${MAPL_ROOT}/etc/share/MAPL/cmake/mapl_acg.cmake` and included through `GOCART/CMakeLists.txt`  if `UFS_GOCART` is `ON`:
```
if (UFS_GOCART)
  find_package (MAPL REQUIRED)
  include(mapl_acg)
elseif (IS_DIRECTORY "${PROJECT_SOURCE_DIR}/ESMF/Shared/MAPL@")
  message (STATUS "Using local MAPL source tree: ${PROJECT_SOURCE_DIR}/ESMF/Shared/MAPL@")
endif ()
```
This issue arises from incorrect `CMAKE_MODULE_PATH` settings, and I agree that the missing `mapl-import.cmake` file on Jet may be the culprit.

**Comment by JessicaMeixner-NOAA** [comment]
@junwang-noaa  I didn't save the logs but one was compile and one was a test failure that was not a coupled test. Given that it was the weekend, I just hit resubmit.  The wcoss-dell regtests are now running and the WCOSS-cray baseline was recreated and can be found here: /gpfs/hps3/stmp/Jessica.Meixner/FV3_RT/REGRESSION_TEST Thanks for moving these to the official area.

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA The changes you listed for the c192 test do allow the model to run. The test runs out of wall clock time however before completion.

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen good to hear the memory was resolved, for speed, we could try: 

```
  TASKS_cpl_c192=384; TPN_cpl_c192=18; INPES_cpl_c192=6; JNPES_cpl_c192=8
  THRD_cpl_c192=2; WPG_cpl_c192=12;  MPB_cpl_c192="0 287"; APB_cpl_c192="0 299"
  CHM_cpl_c192="0 287"; OPB_cpl_c192="300 359" ; IPB_cpl_c192="360 383"
  NPROC_ICE_cpl_c192=24
```

Sometimes you can also reduce the ocean/ice pet counts and keep the same timings as well although someone would need to run with ESMF profiling to confirm.  I'd say probably 12 for ice and 20-40 for ocean could be something to try even without that, although that will not completely offset the timing differences.  It's expected that with Thompson MP  and with the GOCART component that the resources and/or timings will increase.

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA I can try this for the C192 but we still have the timing issue w/ the two c384 tests. See the above posted timings---one was just shy of timing out.

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen Here are the existing C384 resources on Cheyenne: 

```
  TASKS_cpl_c384=480; TPN_cpl_c384=12; INPES_cpl_c384=6; JNPES_cpl_c384=8
  THRD_cpl_c384=3; WPG_cpl_c384=24; MPB_cpl_c384="0 287"; APB_cpl_c384="0 311"
  CHM_cpl_c384="0 287"; OPB_cpl_c384="312 431"; IPB_cpl_c384="432 479"
  NPROC_ICE_cpl_c384=48

  TASKS_cpl_bmrk_aero=576; TPN_cpl_bmrk_aero=12; INPES_cpl_bmrk_aero=6; JNPES_cpl_bmrk_aero=8
  THRD_cpl_bmrk_aero=3; WPG_cpl_bmrk_aero=24; MPB_cpl_bmrk_aero="0 287"; APB_cpl_bmrk_aero="0 311"
  CHM_cpl_bmrk_aero="0 287"; OPB_cpl_bmrk_aero="312 431"; IPB_cpl_bmrk_aero="432 479"; WPB_cpl_bmrk_aero="480 575"
  NPROC_ICE_cpl_bmrk_aero=48
```

possible solution:  

```
  TASKS_cpl_c384=576; TPN_cpl_c384=12; INPES_cpl_c384=8; JNPES_cpl_c384=8
  THRD_cpl_c384=3; WPG_cpl_c384=24; MPB_cpl_c384="0 383"; APB_cpl_c384="0 407"
  CHM_cpl_c384="0 383"; OPB_cpl_c384="408 527"; IPB_cpl_c384="528 575"
  NPROC_ICE_cpl_c384=48

  TASKS_cpl_bmrk_aero=672; TPN_cpl_bmrk_aero=12; INPES_cpl_bmrk_aero=8; JNPES_cpl_bmrk_aero=8
  THRD_cpl_bmrk_aero=3; WPG_cpl_bmrk_aero=24; MPB_cpl_bmrk_aero="0 383"; APB_cpl_bmrk_aero="0 407"
  CHM_cpl_bmrk_aero="0 383"; OPB_cpl_bmrk_aero="408 527"; IPB_cpl_bmrk_aero="528 575"; WPB_cpl_bmrk_aero="576  671"
  NPROC_ICE_cpl_bmrk_aero=48
```

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA The develop-20220304 baseline is available on cray

**Comment by junwang-noaa** [comment]
@kgerheiser would you please update the MAPL lib on jet to include the mapl-import.cmake? We need it for jet RT. Thanks

**Comment by kgerheiser** [comment]
i don't know why that file is missing in an otherwise successful install. 

This appears to be a bug in MAPL. The file is installed with:

```
install (
   DIRECTORY cmake
   DESTINATION ${INSTALL_DATA_DIR}
   FILES_MATCHING PATTERN "mapl_*.cmake"
   )
```

Notice, `"mapl_*.cmake"`, but the name of the file is `mapl-import.cmake.in` (`-`, instead of `_`), and I don't see a `configure_file` anywhere that would process the `.in` to `.cmake`. 

@rmontuoro

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA With your latest changes, I am getting:

```
cpld_bmark_p8/out:0:The total amount of wall time                        = 1560.349721
cpld_control_c192_p8/out:0:The total amount of wall time                        = 1607.353175
cpld_control_c384_p8/out:0:The total amount of wall time                        = 1701.056845
```

Note that I had to reduce the mediator tasks in all the settings below 300. With your original changes, all tests were running extremely slowly. I believe Moorthi has noted this extreme slow-down when using more than 300 MED tasks. The CHM tasks were running on the full FV3 tasks - write component.

**Comment by kgerheiser** [comment]
@junwang-noaa I have manually fixed the mapl-import.cmake issue

**Comment by junwang-noaa** [comment]
@kgerheiser Thanks, the cpld test compile job is now running on jet, The modules were loaded without complaining.

**Comment by junwang-noaa** [comment]
@rmontuoro @JessicaMeixner-NOAA I ran cpld_control_p8 test on jet, the run failed with "seg fault" with MAPL, any idea what happened?

  0: forrtl: severe (174): SIGSEGV, segmentation fault occurred
  0: Image              PC                Routine            Line        Source
  0: fv3.exe            000000000807C42C  Unknown               Unknown  Unknown
  0: libpthread-2.17.s  00002AC2813BA630  Unknown               Unknown  Unknown
  0: libmpi.so.12.0     00002AC28095E364  Unknown               Unknown  Unknown
  0: libmpi.so.12.0     00002AC28086C193  Unknown               Unknown  Unknown
  0: libmpi.so.12.0     00002AC2808CD2D7  Unknown               Unknown  Unknown
  0: libmpi.so.12.0     00002AC280912C69  Unknown               Unknown  Unknown
  0: libmpi.so.12.0     00002AC2809144FD  Unknown               Unknown  Unknown
  0: libmpi.so.12.0     00002AC280A90BD0  Unknown               Unknown  Unknown
  0: libmpi.so.12       00002AC280854BC8  PMPIDI_CH3I_Progr     Unknown  Unknown
  0: libmpi.so.12.0     00002AC2808981C0  Unknown               Unknown  Unknown
  0: libmpi.so.12       00002AC280C0A677  MPI_Win_fence         Unknown  Unknown
  0: libmpifort.so.12.  00002AC2804BC69D  pmpi_win_fence_       Unknown  Unknown
  0: fv3.exe            00000000026C7FA7  pfio_rdmareferenc         163  RDMAReference.F90
  0: fv3.exe            00000000025D289F  pfio_baseservermo          75  BaseServer.F90
  0: fv3.exe            00000000026334D6  pfio_serverthread         980  ServerThread.F90
  0: fv3.exe            00000000025B8FEE  pfio_messagevisit          93  MessageVisitor.F90
  0: fv3.exe            00000000026CC12E  pfio_abstractmess         112  AbstractMessage.F90
  0: fv3.exe            00000000025C9F88  pfio_simplesocket         105  SimpleSocket.F90
  0: fv3.exe            0000000002645B29  pfio_clientthread         429  ClientThread.F90
  0: fv3.exe            000000000264EF62  pfio_clientmanage         381  ClientManager.F90
  0: fv3.exe            0000000001FF0958  mapl_historygridc        3655  MAPL_HistoryGridComp.F90

**Comment by rmontuoro** [comment]
@junwang-noaa - The following setting should be added to `ufs_jet.intel`:
```
setenv I_MPI_DAPL_UD 1
```
This should be added anytime Intel MPI 2018 is used.

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen do you want the times of those runs to be shorter still or is that okay? 

@junwang-noaa let me know if you'd like me to push the I_MI_DAPL_UD change to this branch for Jet.

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA let me test with that first.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Compiler: intel
Job: BL
[BL] Repo location: /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/867250832/20220307190012/ufs-weather-model
[BL] Error: Test cpld_control_p8 001 failed in run_test failed 
[BL] Error: Test cpld_control_c96_p8 005 failed in run_test failed 
[BL] Error: Test cpld_control_c192_p8 006 failed in run_test failed 
[BL] Error: Test cpld_control_c384_p8 007 failed in run_test failed 
[BL] Error: Test cpld_debug_p8 008 failed in run_test failed 
Please make changes and add the following label back: jet-intel-BL

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA We really need the tests to come in at about 20mins. It doesn't need to be under 20mins, but these three are all >26 mins. Our concern is that w/ variations in the system load, we will continually have these tests time-out.

It seems though that we're making only marginal improvements in how long the tests take. @junwang-noaa I think we have three options: one more round at trying to reducing the time, turn the tests off for now on Cheyenne or commit as is and risk time-outs.

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA The test works with "setenv I_MPI_DAPL_UD 1". Since we are using Intel 18 on dell, hera, jet, gaea, orion, maybe we should add it to the module files on all these platforms.

Also I noticed on jet, the cpld_bmark_p8 is taking 2100s, we need to reduce the time within 25mins.

-->tail  /lfs4/HFIP/h-nems/emc.nemspara/autort/pr/867250832/20220307190012/ufs-weather-model/tests/log_jet.intel/rt_004_cpld_bmark_p8.log
 Moving RESTART/MOM.res_2.nc .........OK
 Moving RESTART/MOM.res_3.nc .........OK
 Moving RESTART/iced.2013-04-01-21600.nc .........OK
 Moving RESTART/ufs.cpld.cpl.r.2013-04-01-21600.nc .........OK

  0: The total amount of wall time                        = 2132.180950
  0: The maximum resident set size (KB)                   = 2943636

Test 004 cpld_bmark_p8 PASS

The cpld_bmark_p8 in current develop branch takes 1200s.

https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/RegressionTests_jet.intel.log#L369

**Comment by JessicaMeixner-NOAA** [comment]
Switching the atm physics and adding GOCART, it's not surprising that the tests are taking longer.  There has also been a desire in the past to use as few as resources as possible, therefore I did not increase the resource usage unless there was a memory issue, etc.  We could likely double the atm resources and get much better timings, but I don't know what balance is desired to implement those changes.

I think it would be a great idea to add the "setenv I_MPI_DAPL_UD 1" to all 2018 platforms, I believe this will solve an issue I ran into on wcoss-dell.    If you agree I'll go ahead and add that to all 2018 platforms now.

**Comment by JessicaMeixner-NOAA** [comment]
I added "setenv I_MPI_DAPL_UD 1" to wcoss-dell and jet platforms.  Will wait for word on wether to update gaea (hera and orion already have it I believe).

**Comment by junwang-noaa** [comment]
Yes, please add it gaea module files. I will resubmit RT test.

**Comment by junwang-noaa** [comment]
> @JessicaMeixner-NOAA With your latest changes, I am getting:
> 
> ```
> cpld_bmark_p8/out:0:The total amount of wall time                        = 1560.349721
> cpld_control_c192_p8/out:0:The total amount of wall time                        = 1607.353175
> cpld_control_c384_p8/out:0:The total amount of wall time                        = 1701.056845
> ```
> 
> Note that I had to reduce the mediator tasks in all the settings below 300. With your original changes, all tests were running extremely slowly. I believe Moorthi has noted this extreme slow-down when using more than 300 MED tasks. The CHM tasks were running on the full FV3 tasks - write component.

@JessicaMeixner-NOAA Could we make the similar changes on jet? We asked to get all the tests finished within 30mins since we have about 120 RT tests. 
Also I noticed the cpld_bmark_p8 test running time is increased about 30% on hera, orion and gaea ((900s->1200s). But it increased about 80% on jet (1200s->2130s).

**Comment by JessicaMeixner-NOAA** [comment]
WCOSS-dell is continuing to have issues.  Last night compile 006 failed, then the re-submit over night had the following issues: 

Test rap_cires_ugwp_debug 087 failed in run_test failed
Test rap_progcld_thompson_debug 095 failed in run_test failed
Test rrfs_v1beta_debug 096 failed in run_test failed
Test hafs_regional_atm_thompson_gfdlsf 099 failed in run_test failed 

output is here: /gpfs/dell2/ptmp/Jessica.Meixner/FV3_RT/rt_53256 

I'm resubmitting on wcoss-dell again and will update the Jet resources, it's unclear what the final Cheyenne resources are or if more changes are needed, etc.

**Comment by DeniseWorthen** [comment]
The diff below shows the tasking I have set up for Cheyenne. Using this, I am able to obtain the following timings on Cheyenne.intel:

rt_001_cpld_bmark_p8.log:0:The total amount of wall time                        = 1541.331088
rt_002_cpld_control_c192_p8.log:0:The total amount of wall time                        = 1605.464318
rt_004_cpld_control_c384_p8.log:0:The total amount of wall time                        = 1600.595492

I also ran the c384 case with the runtime esmf profiling turned on. A copy of the profile summary and the default_vars is located at /scratch2/NCEPDEV/stmp3/Denise.Worthen/P8b

We do need the tests to run under 25 mins at a minimum. Let me know what I can do to help.

```
diff --git a/tests/default_vars.sh b/tests/default_vars.sh
index 48cfaff7..d617c362 100755
--- a/tests/default_vars.sh
+++ b/tests/default_vars.sh
@@ -589,9 +589,9 @@ elif [[ $MACHINE_ID = cheyenne.* ]]; then
   CHM_cpl_mpi="0 191"; OPB_cpl_mpi="198 231"; IPB_cpl_mpi="232 251"; WPB_cpl_mpi="252 279"
   NPROC_ICE_cpl_mpi=20

-  TASKS_cpl_c384=480; TPN_cpl_c384=12; INPES_cpl_c384=6; JNPES_cpl_c384=8
-  THRD_cpl_c384=3; WPG_cpl_c384=24; MPB_cpl_c384="0 287"; APB_cpl_c384="0 311"
-  CHM_cpl_c384="0 287"; OPB_cpl_c384="312 431"; IPB_cpl_c384="432 479"
+  TASKS_cpl_c384=576; TPN_cpl_c384=12; INPES_cpl_c384=8; JNPES_cpl_c384=8
+  THRD_cpl_c384=3; WPG_cpl_c384=24; MPB_cpl_c384="0 287"; APB_cpl_c384="0 407"
+  CHM_cpl_c384="0 383"; OPB_cpl_c384="408 527"; IPB_cpl_c384="528 575"
   NPROC_ICE_cpl_c384=48

   TASKS_cpl_bmrk=560; TPN_cpl_bmrk=36; INPES_cpl_bmrk=6; JNPES_cpl_bmrk=8
@@ -599,9 +599,9 @@ elif [[ $MACHINE_ID = cheyenne.* ]]; then
   CHM_cpl_bmrk="0 287"; OPB_cpl_bmrk="312 431"; IPB_cpl_bmrk="432 479"; WPB_cpl_bmrk="480 559"
   NPROC_ICE_cpl_bmrk=48

-  TASKS_cpl_bmrk_aero=576; TPN_cpl_bmrk_aero=12; INPES_cpl_bmrk_aero=6; JNPES_cpl_bmrk_aero=8
-  THRD_cpl_bmrk_aero=3; WPG_cpl_bmrk_aero=24; MPB_cpl_bmrk_aero="0 287"; APB_cpl_bmrk_aero="0 311"
-  CHM_cpl_bmrk_aero="0 287"; OPB_cpl_bmrk_aero="312 431"; IPB_cpl_bmrk_aero="432 479"; WPB_cpl_bmrk_aero="480 575"
+  TASKS_cpl_bmrk_aero=672; TPN_cpl_bmrk_aero=12; INPES_cpl_bmrk_aero=8; JNPES_cpl_bmrk_aero=8
+  THRD_cpl_bmrk_aero=3; WPG_cpl_bmrk_aero=24; MPB_cpl_bmrk_aero="0 287"; APB_cpl_bmrk_aero="0 407"
+  CHM_cpl_bmrk_aero="0 383"; OPB_cpl_bmrk_aero="408 527"; IPB_cpl_bmrk_aero="528 575"; WPB_cpl_bmrk_aero="576  671"
   NPROC_ICE_cpl_bmrk_aero=48

   TASKS_cpl_bmrk_mpi=600; TPN_cpl_bmrk_mpi=36; INPES_cpl_bmrk_mpi=6; JNPES_cpl_bmrk_mpi=8
@@ -609,9 +609,9 @@ elif [[ $MACHINE_ID = cheyenne.* ]]; then
   CHM_cpl_bmrk_mpi="0 287"; OPB_cpl_bmrk_mpi="312 431"; IPB_cpl_bmrk_mpi="432 479"; WPB_cpl_bmrk_mpi="480 599"
   NPROC_ICE_cpl_bmrk_mpi=48

-  TASKS_cpl_c192=288; TPN_cpl_c192=36; INPES_cpl_c192=4; JNPES_cpl_c192=8
-  THRD_cpl_c192=1; WPG_cpl_c192=12;  MPB_cpl_c192="0 191"; APB_cpl_c192="0 203"
-  CHM_cpl_c192="0 191"; OPB_cpl_c192="204 263"; IPB_cpl_c192="264 287"
+  TASKS_cpl_c192=384; TPN_cpl_c192=18; INPES_cpl_c192=6; JNPES_cpl_c192=8
+  THRD_cpl_c192=2; WPG_cpl_c192=12;  MPB_cpl_c192="0 287"; APB_cpl_c192="0 299"
+  CHM_cpl_c192="0 287"; OPB_cpl_c192="300 359" ; IPB_cpl_c192="360 383"
   NPROC_ICE_cpl_c192=24

   TASKS_cdeps_100=40; TPN_cdeps_100=36
```

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA I split the compile job 8 (rap debug) to two compile jobs and rerun the RT on dell from your branch. So far the cpld_2threads_p8 failed with seg fault as I do not have the I_MPI change.  All the compile jobs finished successfully. Would you please copy /gpfs/dell1/ptmp/Jun.Wang/ufs-weather-model/tests/rt.conf to your branch and run RT again on dell. Please let us know if you still get any failure.

**Comment by JessicaMeixner-NOAA** [comment]
> @JessicaMeixner-NOAA I split the compile job 8 (rap debug) to two compile jobs and rerun the RT on dell from your branch. So far the cpld_2threads_p8 failed with seg fault as I do not have the I_MPI change. All the compile jobs finished successfully. Would you please copy /gpfs/dell1/ptmp/Jun.Wang/ufs-weather-model/tests/rt.conf to your branch and run RT again on dell. Please let us know if you still get any failure.

I reran the tests again this morning after reporting that the compiles failed, and the compiles all ran fine, but now instead of the rap tests failing, I got a failure in: hafs_regional_atm, see: 
/gpfs/dell2/ptmp/Jessica.Meixner/FV3_RT/rt_9675/hafs_regional_atm

It seems like it's something different every time but the I_MPI change does resolve the 2threads test issue.

**Comment by JessicaMeixner-NOAA** [comment]
I'm re-running on dell now.

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA FYI. With the rt.conf change, all the RT tests passed except the cpld_2threads_p8 due to the I_MPI setting on dell.

**Comment by JessicaMeixner-NOAA** [comment]
I've had that scenario happen where it's just the cpld_2threads_p8 test that fails.  I don't think things consistently pass on WCOSS-DELL given my experience in the past 5 days, but I really hope I am wrong.  I've resubmitted the tests and they are running on wcoss-dell.

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen I'm looking at the ESMF profiles from Cheyenne and hope to have an updated suggestion within the hour, just wanted you to know I saw your comment and am looking into it.

**Comment by junwang-noaa** [comment]
@rmontuoro @JessicaMeixner-NOAA I saw the error message of the failed tests on dell: 

Test rap_cires_ugwp_debug 087 failed in run_test failed
Test rap_progcld_thompson_debug 095 failed in run_test failed
Test rrfs_v1beta_debug 096 failed in run_test failed
Test hafs_regional_atm_thompson_gfdlsf 099 failed in run_test failed

output is here: /gpfs/dell2/ptmp/Jessica.Meixner/FV3_RT/rt_53256

The first three showed the same error: 

[23] Assertion failed in file ../../src/mpid/ch3/channels/nemesis/netmod/dapl/dapl_send_ud.c at line 2143: vc_reserve_area->RNDV_SEND_STATUS == RNDV_SEND_WAITING_FIN_REPLY
[23] internal ABORT - process 23

The error seems related to the new setting "setenv I_MPI_DAPL_UD 1", would you please take a look? The hafs_regional_atm_thompson_gfdlsf runs out of time (30mins), while the test usually takes 280s as shown in current develop branch:
https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/RegressionTests_wcoss_dell_p3.log#L2726

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA Do you have access to jet? We need to reduce the running time for the coupled tests there too.

**Comment by JessicaMeixner-NOAA** [comment]
@junwang-noaa no, I do not have access to Jet. I'll make a suggested update for Jet as well.  Is it just C384 tests or 192 tests as well?

**Comment by junwang-noaa** [comment]
and cpld_bmark_p8

**Comment by JessicaMeixner-NOAA** [comment]
> @rmontuoro @JessicaMeixner-NOAA I saw the error message of the failed tests on dell:
> 
> Test rap_cires_ugwp_debug 087 failed in run_test failed Test rap_progcld_thompson_debug 095 failed in run_test failed Test rrfs_v1beta_debug 096 failed in run_test failed Test hafs_regional_atm_thompson_gfdlsf 099 failed in run_test failed
> 
> output is here: /gpfs/dell2/ptmp/Jessica.Meixner/FV3_RT/rt_53256
> 
> The first three showed the same error:
> 
> [23] Assertion failed in file ../../src/mpid/ch3/channels/nemesis/netmod/dapl/dapl_send_ud.c at line 2143: vc_reserve_area->RNDV_SEND_STATUS == RNDV_SEND_WAITING_FIN_REPLY [23] internal ABORT - process 23
> 
> The error seems related to the new setting "setenv I_MPI_DAPL_UD 1", would you please take a look? The hafs_regional_atm_thompson_gfdlsf runs out of time (30mins), while the test usually takes 280s as shown in current develop branch: https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/RegressionTests_wcoss_dell_p3.log#L2726

@junwang-noaa These tests passed the next time I ran the tests though, and it passes on jet, gaea, orion and hera with the "setenv I_MPI_DAPL_UD 1",

**Comment by junwang-noaa** [comment]
Your test /gpfs/dell2/ptmp/Jessica.Meixner/FV3_RT/rt_9675/hafs_regional_atm also failed with out of time. It seems to me this is a new issue on dell. Before this PR we had compile job issue or disk quota issue. But not the dapl error or HAFS tests hang. Also are you saying the cpld_2threads_p8 sometimes passed and sometimes failed too?

**Comment by JessicaMeixner-NOAA** [comment]
> Your test /gpfs/dell2/ptmp/Jessica.Meixner/FV3_RT/rt_9675/hafs_regional_atm also failed with out of time. It seems to me this is a new issue on dell. Before this PR we had compile job issue or disk quota issue. But not the dapl error or HAFS tests hang. Also are you saying the cpld_2threads_p8 sometimes passed and sometimes failed too?

Before the setenv I_MPI_DAPL_UD 1 setting was added yesterday, over the weekend it took multiple attempts to create the baseline, with random tests or compiles failing (I didn't write down which tests as it was the weekend, so I was doing the bare minimum which included "resubmit").  So that's why I don't think it's the I_MPI_DAPL_UD setting. The regression tests update after the last update of the rt.conf are still running I'll report back how that goes. Still have 21 jobs left.

**Comment by junwang-noaa** [comment]
Please write down the error message for the failed cases so that people can track and fix the issues for the random failure. The goal is to have stable run without any failure. So far with your branch I am able to create new baseline without error and the cpld_2threads_p8 failed for the full RT without the I_MPI setting. I am running full RT again with your latest branch to check if  there is any random failure.

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen @junwang-noaa the defaults were update for jet/Cheyenne 

There are 2 more tasks to go on wcoss-dell.

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA jet is on PM. will test it when it's back.

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA Would you please check the consistency of the nproc_ice w/ your most recent changes? For the c384 and bmark_aero settings, nproc_ice is 48 but the PE limits are for 24. The c192 setting has the PE limits for 48 but nprocs is 24.

**Comment by junwang-noaa** [comment]
@rmontuoro The hafs_regional_1nest_atm test hang in my full RT test on dell with  I_MPI_DAPL_UD=1. The same error message was shown in /gpfs/dell2/ptmp/Jessica.Meixner/FV3_RT/rt_9675/hafs_regional_atm. It looks to me it is similar to the hanging issue we had on hera with the old I_MPI_FABRICS setting on hera. Would you please take a look? Thanks

**Comment by JessicaMeixner-NOAA** [comment]
> @rmontuoro The hafs_regional_1nest_atm test hang in my full RT test on dell with I_MPI_DAPL_UD=1. The same error message was shown in /gpfs/dell2/ptmp/Jessica.Meixner/FV3_RT/rt_9675/hafs_regional_atm. It looks to me it is similar to the hanging issue we had on hera with the old I_MPI_FABRICS setting on hera. Would you please take a look? Thanks

@junwang-noaa after your update for rt.conf the regtest passed without issue or re-run.

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA I ran the full RT test from your latest branch, the  hafs_regional_1nest_atm test hang. I suspect there is still some random hanging issue as we saw on hera with I_MPI setting before. We didn't have hanging job issue on dell in the develop branch before.

**Comment by JessicaMeixner-NOAA** [comment]
@junwang-noaa I got these types of errors before the I_MPI setting was updated.   I haven't had any of these types of errors when @rmontuoro and I were running on hera preparing this PR which has always had the I_MPI setting there.

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA Thanks for the information. Would you please confirm the hang jobs on dell by providing the error message or a test case?  We have been tracking the RT issues on dell, we haven't seen any hang jobs. This will help us debug the issue.

File: tests/default_vars.sh [hunk 18]
```diff
@@ -589,29 +589,29 @@ elif [[ $MACHINE_ID = cheyenne.* ]]; then
...
 
   TASKS_cpl_bmrk=560; TPN_cpl_bmrk=36; INPES_cpl_bmrk=6; JNPES_cpl_bmrk=8
   THRD_cpl_bmrk=1; WPG_cpl_bmrk=24; MPB_cpl_bmrk="0 287"; APB_cpl_bmrk="0 311"
   CHM_cpl_bmrk="0 287"; OPB_cpl_bmrk="312 431"; IPB_cpl_bmrk="432 479"; WPB_cpl_bmrk="480 559"
   NPROC_ICE_cpl_bmrk=48
 
-  TASKS_cpl_bmrk_aero=672; TPN_cpl_bmrk_aero=12; INPES_cpl_bmrk_aero=8; JNPES_cpl_bmrk_aero=8
-  THRD_cpl_bmrk_aero=3; WPG_cpl_bmrk_aero=24; MPB_cpl_bmrk_aero="0 287"; APB_cpl_bmrk_aero="0 407"
-  CHM_cpl_bmrk_aero="0 383"; OPB_cpl_bmrk_aero="408 527"; IPB_cpl_bmrk_aero="528 575"; WPB_cpl_bmrk_aero="576  671"
+  TASKS_cpl_bmrk_aero=804; TPN_cpl_bmrk_aero=12; INPES_cpl_bmrk_aero=8; JNPES_cpl_bmrk_aero=23
```
Comment (DeniseWorthen) [inline tests/default_vars.sh]: @JessicaMeixner-NOAA Could you please check these values that you changed for Cheyenne (and maybe jet also)? I think there are some typos (jnpes=23?) and the nproc ice doesn't match with the actual pe bounds for the bmark/c384/c192 cases.

File: tests/default_vars.sh [hunk 19]
```diff
@@ -327,47 +347,52 @@ elif [[ $MACHINE_ID = jet.* ]]; then
...
+  CHM_cpl_c384="0 575"; OPB_cpl_c384="600 679"; IPB_cpl_c384="680 703"
   NPROC_ICE_cpl_c384=48
 
   TASKS_cpl_bmrk=560; TPN_cpl_bmrk=24; INPES_cpl_bmrk=6; JNPES_cpl_bmrk=8
   THRD_cpl_bmrk=1; WPG_cpl_bmrk=24; MPB_cpl_bmrk="0 287"; APB_cpl_bmrk="0 311"
-  OPB_cpl_bmrk="312 431"; IPB_cpl_bmrk="432 479"; WPB_cpl_bmrk="480 559"
+  CHM_cpl_bmrk="0 287"; OPB_cpl_bmrk="312 431"; IPB_cpl_bmrk="432 479"; WPB_cpl_bmrk="480 559"
   NPROC_ICE_cpl_bmrk=48
 
+  TASKS_cpl_bmrk_aero=804; TPN_cpl_bmrk_aero=12; INPES_cpl_bmrk_aero=8; JNPES_cpl_bmrk_aero=23
```
Comment (junwang-noaa) [inline tests/default_vars.sh]: May I ask why we set JNPES_cpl_bmrk_aero=23? We had the reproducibility issue with non divisible layout. Can we set it to JNPES_cpl_bmrk_aero=24?

Comment (JessicaMeixner-NOAA) [reply tests/default_vars.sh]: This was a typo.  I'll fix this and the ice PET inconsistencies @DeniseWorthen  mentioned ASAP.

File: tests/default_vars.sh (hunk 18 above)
Comment (JessicaMeixner-NOAA) [reply tests/default_vars.sh]: Definitely a typo! Thanks for catching this.  I think it's all fixed now.

**Comment by JessicaMeixner-NOAA** [comment]
> @JessicaMeixner-NOAA Would you please check the consistency of the nproc_ice w/ your most recent changes? For the c384 and bmark_aero settings, nproc_ice is 48 but the PE limits are for 24. The c192 setting has the PE limits for 48 but nprocs is 24.

@DeniseWorthen I believe these are all now fixed.  Thanks for helping catch this.  Hopefully this is fixed correctly now.

**Comment by JessicaMeixner-NOAA** [comment]
@junwang-noaa @rmontuoro I ran the develop branch 3 times on wcoss-dell.  2 of the 3 succeeded.  The third failed on Compile 009, see /gpfs/dell2/ptmp/Jessica.Meixner/FV3_RT/rt_20607 

Again, I think these are machine related issues and not issues related to any code updates in this branch.  We do have a successful run log showing that all regression tests can pass.  I know there is a desire to have stable code, but I don't think the updates here are the cause of the instability I have seen on wcoss-dell.

File: tests/default_vars.sh [hunk 20]
```diff
@@ -531,47 +566,52 @@ elif [[ $MACHINE_ID = cheyenne.* ]]; then
...
+  CHM_cpl_bmrk_mpi="0 287"; OPB_cpl_bmrk_mpi="312 431"; IPB_cpl_bmrk_mpi="432 479"; WPB_cpl_bmrk_mpi="480 599"
   NPROC_ICE_cpl_bmrk_mpi=48
 
-  TASKS_cpl_c192=288; TPN_cpl_c192=36; INPES_cpl_c192=4; JNPES_cpl_c192=8
-  THRD_cpl_c192=1; WPG_cpl_c192=12;  MPB_cpl_c192="0 191"; APB_cpl_c192="0 203"
-  OPB_cpl_c192="204 263"; IPB_cpl_c192="264 287"
+  TASKS_cpl_c192=576; TPN_cpl_c192=18; INPES_cpl_c192=8; JNPES_cpl_c192=8
+  THRD_cpl_c192=2; WPG_cpl_c192=12;  MPB_cpl_c192="0 287"; APB_cpl_c192="0 407"
+  CHM_cpl_c192="0 383"; OPB_cpl_c192="408 527" ; IPB_cpl_c192="528 575"
   NPROC_ICE_cpl_c192=24
```
Comment (DeniseWorthen) [inline tests/default_vars.sh]: This still needs to be updated for nproc_ice = 48 to match the 528:575 values

**Comment by junwang-noaa** [comment]
> @junwang-noaa @rmontuoro I ran the develop branch 3 times on wcoss-dell. 2 of the 3 succeeded. The third failed on Compile 009, see /gpfs/dell2/ptmp/Jessica.Meixner/FV3_RT/rt_20607
> 
> Again, I think these are machine related issues and not issues related to any code updates in this branch. We do have a successful run log showing that all regression tests can pass. I know there is a desire to have stable code, but I don't think the updates here are the cause of the instability I have seen on wcoss-dell.

@JessicaMeixner-NOAA Thanks for running those tests. Your results confirmed what we have so far. In the develop branch, there is a random compile job failure with compile job 9 (wam test) with internal compiler error, but there are no hanging jobs. Can you run with your branch a couple of times on dell and confirm you have the similar results?

File: tests/default_vars.sh (hunk 20 above)
Comment (JessicaMeixner-NOAA) [reply tests/default_vars.sh]: Fixed.  Thanks for pointing out the issue.

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA The tasking for the c192 is still not correct. I am getting 

``0:FATAL from PE     0: mpp_domains_define.inc: not all the pe_end are in the pelist``

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA on jet, cpld_control_c192_p8 and cpld_control_c384_p8 ran out of time, and cpld_bmark_p8 takes 1691s.

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen @junwang-noaa the resources for jet and Cheyenne have been updated.

**Comment by DeniseWorthen** [comment]
Thanks for the Cheyenne fixes. Here are the latest values which all look reasonable. 

```
cpld_bmark_p8/out:0:The total amount of wall time                        = 1162.499743
cpld_control_c192_p8/out:0:The total amount of wall time                        = 1331.810947
cpld_control_c384_p8/out:0:The total amount of wall time                        = 1425.730147
```

I did not ice the cpld_debug_p8 currently has ``WLCLK=180``? And there is also a ``cpld_debug_noaero_p8`` that is not being used I think.

File: tests/tests/cpld_debug_noaero_p8 [hunk 21]
```diff
@@ -0,0 +1,92 @@
...
+                   RESTART/phy_data.tile3.nc \
+                   RESTART/phy_data.tile4.nc \
+                   RESTART/phy_data.tile5.nc \
+                   RESTART/phy_data.tile6.nc \
+                   RESTART/sfc_data.tile1.nc \
+                   RESTART/sfc_data.tile2.nc \
+                   RESTART/sfc_data.tile3.nc \
+                   RESTART/sfc_data.tile4.nc \
+                   RESTART/sfc_data.tile5.nc \
+                   RESTART/sfc_data.tile6.nc \
```
Comment (DusanJovic-NOAA) [inline tests/tests/cpld_debug_noaero_p8:52]: Are these restart files required to actually restart some other tests?

Comment (JessicaMeixner-NOAA) [reply tests/tests/cpld_debug_noaero_p8:52]: No, just copying the format from the other tests.

**Comment by junwang-noaa** [comment]
@JessicaMeixner-NOAA Please turn off the C192, C384 coupled tests on jet. I submitted RT for coupled tests this morning with your updated resources, but they are still waiting in the queue.

**Comment by JessicaMeixner-NOAA** [comment]
> @JessicaMeixner-NOAA Please turn off the C192, C384 coupled tests on jet. I submitted RT for coupled tests this morning with your updated resources, but they are still waiting in the queue.

@junwang-noaa done 


> I did not ice the cpld_debug_p8 currently has `WLCLK=180`? And there is also a `cpld_debug_noaero_p8` that is not being used I think.

@DeniseWorthen I have no recollection of why that was added, it's been removed. The cpld_debug_noaero_p8 is used in the gnu tests.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: BL
[BL] Repo location: /glade/scratch/dtcufsrt/autort/tests/auto/pr/867250832/20220309101509/ufs-weather-model
[BL] ERROR: Baseline location exists before creation:
/glade/p/ral/jntp/GMTB/ufs-weather-model/RT/NEMSfv3gfs/develop-20220304/GNU
Please make changes and add the following label back: cheyenne-gnu-BL

**Comment by DeniseWorthen** [comment]
I didn't realize a baseline for cheyenne.gnu was already created.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA sounds like gnu-cheyenne runs ok? When I tried with develop branch, I saw a compilation failure.

**Comment by DeniseWorthen** [comment]
@jkbk2004 We don't compile the cpld wave model with gnu.

**Comment by jkbk2004** [comment]
@DeniseWorthen so the gnu issue is with the wave model only. Then we can create issue to wave repo. thanks!

**Comment by DeniseWorthen** [comment]
@jkbk2004 The other components already have the GNU 10+ compile work-around in their build.

**Comment by DeniseWorthen** [comment]
I believe all RTs are now complete.

**Review by junwang-noaa — APPROVED** [review]

**Comment by junwang-noaa** [comment]
@DeniseWorthen @JessicaMeixner-NOAA the fv3atm PR is committed, revision [3bcba51](https://github.com/NOAA-EMC/fv3atm/commit/3bcba5162232745cd0d500c2da0bd5e5c09d814e).

**Review by DeniseWorthen — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA I've created a P8b tag.

**Comment by JessicaMeixner-NOAA** [comment]
Thank you for making the tag @DeniseWorthen and for all of the help to get this merged!

**Comment by DusanJovic-NOAA** [comment]
> @JessicaMeixner-NOAA I've created a P8b tag.

@DeniseWorthen looks like you created a release, not just a tag. Do we really need a release? Is tag not sufficient?

**Comment by DeniseWorthen** [comment]
I was a little confused. I saw release/p8a as tag; but it doesn't show as a release. But when I tried to repeat that w/ p8b, it shows up as a tag and as a release. I can delete it if there is a better way (probably should have done it on the command line).

**Comment by DusanJovic-NOAA** [comment]
I think having a release, which is not a 'real' release is confusing. In my opinion having all these P7, P8 'release' branches named release/P?? is little misleading. Are they real releases like release/public-v1, v2 etc?
