### PR TITLE
GW-RT global_control.nml modifications

### LINKED ISSUE #2424: Modify global_control.nml to work with GW scripts
## Description
There are namelist options that are used by Global Workflow that are either not present or set as constant in the global_control.nml in the UFS branch.

## Solution
These options should be changed in the global_control.nml so both the regression tests and Global workflow can use the same namelist template. 

## Related to
Required to support https://github.com/NOAA-EMC/global-workflow/pull/2733, which closes https://github.com/NOAA-EMC/global-workflow/issues/2731 and https://github.com/ufs-community/ufs-weather-model/issues/1664

### LINKED ISSUE #2443: ATMRES getting reset in export_cpl()
## Description
There is an export call in default_vars.sh export_cpl() that resets ATMRES. Most of the regression tests still reset relevant parameters so they are unchanged but this should be changed since it will have unforeseen consequences in future tests.

### To Reproduce/Fix:
default_vars.sh will be changed to keep ATMRES/ICERES/OCNRES unchanged if it is already set. ATMRES check will be done in export_fv3() while the ICERES and OCNRES checks will be in export_cpl().

### LINKED ISSUE #2470: Add check for coupling timing between components
## Description
There should be a check added to make sure that the following two conditions are met:
1) The atmosphere and CICE timesteps are equal
2) The ocean timestep is divisible by the coupling timestep

There was an issue that arose from these criteria not being true, so a check can be added to alert the user when these conditions are not being satisfied.

## Solution
A check can be added to run_test.sh to make sure that all regression tests satisfy these conditions.

### PR DESCRIPTION
**Pull request by dpsarmie**
## Commit Queue Requirements:
- [x] Fill out all sections of this template.
- [ ] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
There is now an option to allow default_vars.sh to set variables that are dependent on `DT_ATMOS` and `ATMRES`. If you wish to use a non-default value for either variable and have the script set all dependent variables automatically (ex. DT_INNER, CDMBGWD, namsfc filenames, etc.), then `DT_ATMOS` and `ATMRES` **_must be defined before calling the export functions_**.

If the user does not define the variable, then the defaults of C96 (ATMRES) and 1800 (DT_ATMOS for atm only) or 720 (DT_ATMOS for cpld cases) will be set.

**_Example:_**
Your RT uses C48 resolution and you want a timestep of 720:
In your test configuration:
```
export ATMRES=C48
export DT_ATMOS=720
export_fv3
export_ugwpv1
export_cpl
<the rest of the config>
```
This will now be able to use the user defined timestep and resolution to populate the other variables needed to run this case. _**As always, the order of the export function calls should go export_fv3, export_ugwpv1, then export_cpl.**_ You can remove export function calls as needed for your particular case.

You are still able to use the old methodology of defining all variables manually. This feature just allows users to streamline that process.

### Non-standard RT configurations
It should be noted that many of the RTs have changes to variables from what is being set in **default_vars.sh** (mainly N_SPLIT, K_SPLIT, and DT_ATMOS). This was done because the runtime of the default settings was too long for the regression test suite. The RTs are made to provide a fidelity check on future UFS updates, so these checks are still valid even if some of the variables that affect runtime have been changed.
The runs using the default values were checked for stability and passed; however, there are no plans to regularly check the RTs using the default values on a regular basis. 

## Description:
This PR will modify the global_control.nml to add variables that are present in the Global Workflow scripts but not currently present in the RTs. Some variables will also be changed from constants to variable placeholders. This will allow Global Workflow to use the global_control.nml as a template for their operations. 
```Variable values that were hard-coded in global_control.nml.IN were replaced with an @ tag and the values were moved to default_vars.sh.```

This PR is now also going to include a fix for #2443. This will add baseline changes that are unrelated to the initial global_control.nml modifications or the sfs configuration fix.
```Default values for DT_ATMOS and ATMRES are now being set as intended. If the user defines either of these variables before the export_ function calls, then the appropriate dependent variables will be auto-configured. This removes the need to redefine these variables in the test configs.```

This PR now includes a feature mentioned in #2470. The checks have been added to run_test.sh.
```Changes in run_test.sh now have checks for the fast and slow coupling frequencies and a check on the CICE to ATM timesteps.```

### Commit Message:
```
* UFSWM - Modify global_control.nml to add compatibility with Global Workflow
```

### Priority:
* Normal

### UFSWM:
* Closes #2424 
* Closes #2443 
* Closes #2470

### Sub component Pull Requests:
* None

### UFSWM Blocking Dependencies:
* None

---
### Regression Test Changes (Please commit test_changes.list):

- cpld_control_p8_mixedmode intel
- cpld_control_gfsv17 intel
- cpld_control_gfsv17_iau intel
- cpld_restart_gfsv17 intel
- cpld_mpi_gfsv17 intel
- cpld_control_sfs intel
- cpld_debug_gfsv17 intel
- cpld_control_p8 intel
- cpld_control_p8.v2.sfc intel
- cpld_restart_p8 intel
- cpld_control_qr_p8 intel
- cpld_restart_qr_p8 intel
- cpld_2threads_p8 intel
- cpld_decomp_p8 intel
- cpld_mpi_p8 intel
- cpld_control_ciceC_p8 intel
- cpld_control_c192_p8 intel
- cpld_restart_c192_p8 intel
- cpld_bmark_p8 intel
- cpld_restart_bmark_p8 intel
- cpld_s2sa_p8 intel
- cpld_control_noaero_p8 intel
- cpld_control_nowave_noaero_p8 intel
- cpld_debug_p8 intel
- cpld_debug_noaero_p8 intel
- cpld_control_c48 intel
- cpld_warmstart_c48 intel
- cpld_restart_c48 intel
- cpld_control_p8_faster intel
- cpld_control_pdlib_p8 intel
- cpld_restart_pdlib_p8 intel
- cpld_mpi_pdlib_p8 intel
- cpld_debug_pdlib_p8 intel
- atm_ds2s_docn_dice intel
- cpld_control_nowave_noaero_p8 gnu
- cpld_control_pdlib_p8 gnu
- cpld_debug_pdlib_p8 gnu

### Input data Changes:
* None.

### Library Changes/Upgrades:
* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [ ] Derecho
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Review by BrianCurtis-NOAA — DISMISSED** [review]

File: tests/default_vars.sh [hunk 1]
```diff
@@ -787,12 +908,37 @@ export LNDP_MODEL_TYPE=0
...
+export USE_ZMTNBLCK=.true.
+export PBL_TAPER=0,0,0,0.125,0.25,0.5,0.75
+export OCNSPPT=0.8,0.4,0.2,0.08,0.04
+export OCNSPPT_LSCALE=500.E3,1000.E3,2000.E3,2000.E3,2000.E3
+export OCNSPPT_TAU=2.16E4,2.592E5,2.592E6,7.776E6,3.1536E7
+export ISEED_OCNSPPT=20210325000108,20210325000109,20210325000110,20210325000111,20210325000112
+export EPBL=0.8,0.4,0.2,0.08,0.04
+export EPBL_LSCALE=500.E3,1000.E3,2000.E3,2000.E3,2000.E3
+export EPBL_TAU=2.16E4,2.592E5,2.592E6,7.776E6,3.1536E7
+export ISEED_EPBL=20210325000113,20210325000114,20210325000115,20210325000116,20210325000117
```
Comment (NickSzapiro-NOAA) [inline tests/default_vars.sh:945]: I think SKEB, SPPT, SHUM are missing default values (like EPBL).

If I understand, are you wanting these to default to what is being used in GEFS prototype? Maybe @pjpegion can confirm?

File: tests/tests/cpld_control_sfs
Comment (NeilBarton-NOAA) [inline tests/tests/cpld_control_sfs:1]: Please add the update damping parameters for C96 SFS test to the same as g-w

 export K_SPLIT=1
 export N_SPLIT=4
 export TAU=8.0
 export NUDGE_QV=.false.
 export RF_CUTOFF=100
 export FV_SG_ADJ=1800
 export VTDM4=0.05

see https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/gefs/config.ufs

Comment (dpsarmie) [reply tests/tests/cpld_control_sfs:1]: Hey Neil,

Most of those changes are going to be a part of this PR: https://github.com/ufs-community/ufs-weather-model/pull/2363

I'll switch the NUDGE_QV to false and I'll have to change the VTDM4 value for the sfs case. The other values will be imported under the new export_ugwpv1 function.

For the RT themselves, I did have to change some of the timesteps and/or remappings for certain tests to get them under the preset time limit. All tests were checked with the updated parameter values on Hera and worked, but some tests were taking anywhere from 45 mins - 2 hours of run-time.

Extending the time limits would put more demand on the RTs, so that's the solution I went with.

If there's an issue with that solution, let me know and we can think of others ways around the problem.

Thanks.

File: tests/default_vars.sh (hunk 1 above)
Comment (NickSzapiro-NOAA) [reply tests/default_vars.sh:945]: Maybe we default to what's in global workflow (?):
https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/gefs/config.efcs

File: tests/tests/cpld_control_sfs
Comment (NeilBarton-NOAA) [reply tests/tests/cpld_control_sfs:1]: Thanks @dpsarmie I see the updates in the other PR

Comment (dpsarmie) [reply tests/tests/cpld_control_sfs:1]: These sfs specific changes will be officially rolled into this PR (nudge_qv and vtdm4).

**Comment by NickSzapiro-NOAA** [comment]
@dpsarmie I also hit a problem with DT_ATMOS. For gfsv17 tests for example:
1. export_fv3 sets a default DT_ATMOS
2. export_cpl sets a different default DT_ATMOS that is used in export_{cice,cmeps,...} for DT_CICE, coupling_interval_fast_sec,.. 
3. Then export_ugwpv1 sets a different DT_ATMOS based on ATMRES
4. But cice, cmeps,... never see changes from step 3

Maybe export_cpl should not touch DT_ATMOS either. 

It may also be better in these tests to call export_fv3, then export_ugwpv1, then export_cpl so atmosphere is configured properly before setting other components

**Comment by dpsarmie** [comment]
Thanks @NickSzapiro-NOAA for bringing that up. I'll have to do some more testing to see what makes sense. I think the simplest solution would be to make the atm only and cpld default DT_ATMOS the same, but I want to make sure that the runtime isn't greatly affected for the atm only cases. 
If not, then there needs to be a straightforward way to differentiate between the possible combinations and what needs to be defined. 
Although I agree that the ugwpv1 call should come before the cpld call to resolve your issue 4.

**Comment by NickSzapiro-NOAA** [comment]
I think it is better if DT_ATMOS is thought of as input to export_cpl (and not modified in export_cpl). The issue I'm focusing on is (coupling) timesteps for gfsv17 test, where ufs.configure is the same before and after 2363:
```
# CMEPS warm run sequence
runSeq::
@3600
   MED med_phases_prep_wav_avg
   MED med_phases_prep_ocn_avg
   MED -> WAV :remapMethod=redist
   MED -> OCN :remapMethod=redist
   WAV
   OCN
   @720
     MED med_phases_prep_atm
     MED med_phases_prep_ice
     MED -> ATM :remapMethod=redist
     MED -> ICE :remapMethod=redist
     ATM
     ICE
     ATM -> MED :remapMethod=redist
     MED med_phases_post_atm
     ICE -> MED :remapMethod=redist
     MED med_phases_post_ice
     MED med_phases_ocnalb_run
     MED med_phases_prep_ocn_accum
     MED med_phases_prep_wav_accum
   @
   OCN -> MED :remapMethod=redist
   WAV -> MED :remapMethod=redist
   MED med_phases_post_ocn
   MED med_phases_post_wav
   MED med_phases_restart_write
@
::
```

But, dt_atmos in model_configure is 360s in current develop vs 720s before 2363. Was it intended for 2363 to reduce timestep for this test? Either way, now FV3<-->CMEPS no longer couple every ATM timestep, ATM timestep is different than ICE timestep,... I'm not sure this is intentional and may need hot fix if not intended.

**Comment by dpsarmie** [comment]
Ok I see what you mean. 

#2363 was intended to change the timesteps to have the more optimized set of parameter values to allow for more stability at longer timesteps: https://github.com/NOAA-EMC/global-workflow/issues/2574

I'm going to move forward with your idea of having _DT_ATMOS_ set in `export_fv3` and changed in `export_ugwpv1` (if needed) before calling `export_cpl`.

That should allow _DT_CICE_ and _coupling_interval_fast_sec_ to be set correctly when the other export calls are run from within `export_cpl`.

Line 1302 will also be removed in **default_vars.sh** since _DT_INNER_ will have been set by then. 

Let me know if that logic makes sense. That should resolve the issues of not having the timing in sync between the models, correct?

**Comment by NickSzapiro-NOAA** [comment]
That makes sense to me. Maybe can ask Denise to review solution too

**Comment by dpsarmie** [comment]
Latest changes do the following:

To fix the timing issue it CMEPS, default_vars.sh has been reworked. If you export DT_ATMOS and/or ATMRES before the export_fv3 (and other export functions), then all dependent variables will be auto-populated. If these variables are not set, then defaults will be set. You can still manually set these parameters after the function calls but you need to make sure that all variables that depend on DT_ATMOS and ATMRES are also set unless you intended to do so otherwise. 

Either way, the timing with CMEPS should be functioning as intended.

File: tests/tests/atm_ds2s_docn_dice [hunk 2]
```diff
@@ -90,6 +90,25 @@ export WRTTASK_PER_GROUP=$WPG_cpl_dflt
...
+export LDIAG_UGWP=.false.
+
+export DO_GSL_DRAG_TOFD=.false.
+export CDMBWD=${CDMBWD_c96}
+
+# UGWD
+export DO_UGWP_V0=.true.
+export DO_UGWP_V1=.false.
+export DO_GSL_DRAG_LS_BL=.false.
+export KNOB_UGWP_VERSION=0
```
Comment (NickSzapiro-NOAA) [inline tests/tests/atm_ds2s_docn_dice]: Why is this different than the cpld_control_nowave_noaero_p8 test it depends on?

**Comment by NickSzapiro-NOAA** [comment]
@dpsarmie In the PR description, can you add how the logic/flow in default_vars works and should be used?

**Comment by dpsarmie** [comment]
@NickSzapiro-NOAA I added a snippet to the description on how it should be used. I'm actually currently working on a more detailed document for how to use the new features, so let me know if anything is unclear or if anything else should be added to the description for the PR.

File: tests/default_vars.sh [hunk 3]
```diff
@@ -1029,7 +1179,8 @@ export_ugwpv1() {
   if [[ ${DO_GSL_DRAG_SS} = .true. ]]; then export CDMBGWD=${CDMBGWD_GSL}; fi
   if [[ ${SEDI_SEMI} = .true. ]]; then export DT_ATMOS=$((DT_ATMOS/2)); fi
   export DT_INNER=${DT_ATMOS}
-
+  export default_dt_atmos=0
```
Comment (NickSzapiro-NOAA) [inline tests/default_vars.sh:1180]: Is DT_INNER always equal to DT_ATMOS?

Why is the value of default_dt_atmos changing here? Is it used somewhere else?

**Comment by DeniseWorthen** [comment]
@dpsarmie I'm getting confused about where the B4B differences are arising. It seems you're combining what is a bug-fix (the issue w/ dt_atmos), with updates of various namelist settings to match GW. Both of these tasks create non-B4B changes, is that right? Should we really be combining a bug fix w/ what is actually a new feature (consistency w/ G-W)?

**Comment by dpsarmie** [comment]
@DeniseWorthen Yes, the changes to the namelist and the associated changes to default_vars (just adding variables) were changes that were still B4B comparable. 
There was a discussion a few weeks ago with EPIC to roll these other bug fixes into the PR since they are touching related files.

I've opened individual issues for documentation purposes since it is getting a bit complex. I'll add something to the description to try and detail the changes and which issue was addressed by which change in the code.  There won't be anything else added to this PR.

**Comment by DeniseWorthen** [comment]
@dpsarmie Thanks for adding the information. Did either 


_Variable values that were hard-coded in global_control.nml.IN were replaced with an @ tag and the values were moved to default_vars.sh.
Another issue will also be merged into this PR. The cpld_control_sfs configuration will be changed to bring it in-line with the GW configuration. cpld_control_sfs settings were changed in the test configuration file._

change baselines?

I'm confused because the next change is described with _This will add **additional** baseline changes_. (emphasis added).

If either of the first two items changed baselines, then I believe it is poor CM practice to combine issues which both change a set of tests. Rolling them together makes it much harder to un-roll/debug in the future, if required.

**Comment by dpsarmie** [comment]
@DeniseWorthen Yes, the cpld_control_sfs test underwent two baseline changes. The GW settings change (second item under **Description**) and the DT_ATMOS fix (third item) had two distinct changes in that baseline.

I can untangle those easily and create an independent PR so there's only one baseline change per PR.

**Review by NickSzapiro-NOAA — CHANGES_REQUESTED** [review]

**Comment by dpsarmie** [comment]
> @dpsarmie I also hit a problem with DT_ATMOS. For gfsv17 tests for example:
> 
> 1. export_fv3 sets a default DT_ATMOS
> 2. export_cpl sets a different default DT_ATMOS that is used in export_{cice,cmeps,...} for DT_CICE, coupling_interval_fast_sec,..
> 3. Then export_ugwpv1 sets a different DT_ATMOS based on ATMRES
> 4. But cice, cmeps,... never see changes from step 3
> 
> Maybe export_cpl should not touch DT_ATMOS either.
> 
> It may also be better in these tests to call `export_fv3`, then `export_ugwpv1`, then `export_cpl` so atmosphere is configured properly before setting other components

This was resolved by adding a **default_dt_atmos** variable. If **DT_ATMOS** is not defined before the `export_fv3` is called, then it will be set to its default value. Since the coupled cases and the ugwpv1 cases all have their unique **DT_ATMOS** settings, they will also change **DT_ATMOS** if it was set to default.

The new ordering of the function calls should be `export_fv3`, `export_ugwpv1`, `export_cpl`.  If **default_dt_atmos** is 1, `export_fv3` will set **DT_ATMOS** to the default value (default for uncoupled cases), `export_ugwpv1` will then set **DT_ATMOS** to the compatible value for gwpv1 based on grid resolution. The final `export_cpl` call will not change **DT_ATMOS** and then cice and cmeps will get the final **DT_ATMOS** value.

All other model configuration combinations should also work. ATM only (export_fv3), coupled using gwpv0 (export_fv3, export_cpl), ATM gwpv1 only, (export_fv3, export_ugwpv1), and coupled gwpv1 (export_fv3, export_ugwpv1, export_cpl) are all working as intended.

File: tests/default_vars.sh (hunk 3 above)
Comment (dpsarmie) [reply tests/default_vars.sh:1180]: If the test is running the ugwpv1, then yes DT_INNER will be set to DT_ATMOS. If we set DT_INNER to half of DT_ATMOS (which is what GW is doing), then a handful of tests run over the allotted wall clock time. I did this to keep the RTs under the wall clock, but I did test the RTs using the GW parameters that were discussed here: https://github.com/ufs-community/ufs-weather-model/pull/2363 to make sure that they were stable on our end. 

default_dt_atmos changes here to make sure that it does not change in export_cpl(). I'm allowing export_cpl() to change DT_ATMOS for now to keep functionality with ugwpv0. When the time comes to deprecate version 0, then L1403 - 1407 should be removed.

File: tests/default_vars.sh (hunk 1 above)
Comment (dpsarmie) [reply tests/default_vars.sh:945]: Yes, I'm was setting defaults based off of GW. There are some missing entries that are not here that will be added.
I'm scheduling a meeting soon with GW to talk about some discrepancies in the RT and GW namelist and what they would prefer.
The missing defaults are here on a branch I created for the GW PR: https://github.com/dpsarmie/global-workflow/blob/feature/GW-RT_GlobalNML/global_control.nml.IN#L393

File: tests/tests/atm_ds2s_docn_dice (hunk 2 above)
Comment (dpsarmie) [reply tests/tests/atm_ds2s_docn_dice]: atm_ds2s_docn_dice settings should now reflect the cpld_control_nowave_noaero_p8 settings.

**Review by NickSzapiro-NOAA — APPROVED** [review]

**Comment by jkbk2004** [comment]
@dpsarmie I am updating bl_date: 20241028.

**Comment by jkbk2004** [comment]
@dpsarmie I pushed hera log. But I noticed computational time increases for quite some cases. Can you review and confirm? @NickSzapiro-NOAA @junwang-noaa @BrianCurtis-NOAA FYI

**Review by junwang-noaa — DISMISSED** [review]

**Comment by dpsarmie** [comment]
Yes I see. I'm going to go through the tests and see if we can get them all back down (future PR). Most of the increases were from ugwpv1 and fixing the CICE/coupling timestep, I believe.

**Comment by jkbk2004** [comment]
OK! we can merge this pr. any final comment?

**Review by jkbk2004 — APPROVED** [review]

**Review by zach1221 — APPROVED** [review]
