### PR TITLE
Remove unnecessary SIMD instruction sets for Jet, first round of cleanup in rt.conf, initialize cld_amt to zero for regional runs (dycore)

### LINKED ISSUE #310: Update of jet regression testing environment
## Description
Several updates are required for the regression testing on jet using `rt.sh`:

- Currently jet is configured to run regression tests on the xjet partition, same for the compile jobs when using ecflow.
- This may lead to different results when not using ecflow (because the login nodes may have a different chipset than the xjet nodes).
- We are also using the `SIMDMULTIARCH` cmake option, which replaces `-xCORE-AVX2` with `-axSSE4.2,AVX,CORE-AVX2,CORE-AVX512`. This leads to significantly longer compile times (about four times as long!), and I have reason to believe that the `CORE-AVX512` flags are detrimental to at least one of the regression tests (`fv3_ccpp_rrfs_v1beta`).

## Solution
- Improve the `SIMDMULTIARCH` handling
- Check if we can get b4b identical results across chipsets at some optimization level

## Alternatives
Looking forward to hearing from you.

### LINKED ISSUE #352: Simplify rt.conf
## Description

Right now we have a lot of special treatments in `rt.conf` to run certain tests on some systems but not on others. For many of these tests, the exceptions were introduced in the past when something didn't run on certain systems (because it was currently developed, was missing input data, or the system had problems).

We need to check if these exceptions are still required or if we can remove some of them to cleanup `rt.conf` and facilitate the overall regression test cleanup that we are planning to do in the near future.

## Solution

On a case-by-case basis, remove exceptions to run certain tests only on some platforms or to exclude certain platforms. Create new baselines and verify against them to make sure that the tests not only complete but also reproduce.

## Alternatives

Deal with these exceptions later when doing the general overhaul of the global model regression tests.

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

**1. Remove unnecessary SIMD instruction sets for Jet**

When option `SIMDMULTIARCH` is used at compile time (currently only on Jet), four SIMD instruction sets are compiled into the executable. The cmake config `cmake/Intel.cmake` defines these flags for the build. By reducing the instruction sets from
```
-axSSE4.2,AVX,CORE-AVX2,CORE-AVX512
```
to
```
-axSSE4.2,CORE-AVX2
```
we are reducing the compile time by about 50%. Further, nobody has looked at the results (in terms of performance and accuracy) when `CORE-AVX512` is used. With the two flags `-axSSE4.2,CORE-AVX2` we can run the same high performance code on the newer jet partitions that we run on other Intel systems (NOAA RDHPC, NCAR, ...), and we have a fallback option for the older Jet platforms that do not understand AVX2 SIMD instruction sets.

**2. First round of cleanup in rt.conf**

See https://github.com/ufs-community/ufs-weather-model/issues/352 for a detailed description. This work is in preparation and to facilitate the upcoming overhaul of the global model regression tests.

Also included:
- delete `rt_stampede.conf` (we are not running regression tests there, no need to maintain that file)
- update submodule pointer for GFDL_atmos_cubed_sphere for the change described in NOAA-EMC/GFDL_atmos_cubed_sphere#49 (initialize cld_amt to zero for regional runs)

### Issue(s) addressed

- fixes https://github.com/ufs-community/ufs-weather-model/issues/310
- fixes https://github.com/ufs-community/ufs-weather-model/issues/352

## Testing

Regression tests will be run on all tier-1 platforms. For systems for which the baseline is not expected to change (see below), the existing baseline will be copied to the new date tag and used to verify against. For systems for which the baseline is expected to change, a new baseline will be created and used to verify against.

No changes are expected on the following systems:
- cheyenne.gnu (confirmed by running `rt.sh` against existing baseline on 12/31/2020)
- hera.intel (confirmed by running `rt.sh` against existing baseline on 12/31/2020)
- hera.gnu (confirmed by running `rt.sh` against existing baseline on 12/31/2020)

Changes are expected on the following systems (because additional tests are run and, for jet only, the compiler flags have changed):
- jet.intel (creating new baseline and verifying against it successful, confirmed 1/4/2021)
- gaea.intel (creating new baseline and verifying against it successful, confirmed 12/31/2020)
- cheyenne.intel (creating new baseline and verifying against it successful, confirmed 12/31/2020)
- orion.intel (creating new baseline and verifying against it successful, confirmed 1/4/2021)
- wcoss_cray (no access)
- wcoss_dell_p3 (no access)

Final regression testing on 01/06/2021: all tests passed, logs updated in the PR.

## Dependencies

https://github.com/NCAR/ccpp-physics/pull/539
https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/49
https://github.com/NOAA-EMC/fv3atm/pull/220
https://github.com/ufs-community/ufs-weather-model/pull/353

### CODE REVIEW

**Comment by junwang-noaa** [comment]
Can we have a detailed plan what the future rt.conf will look like? I thought we are going to reduce the total number of rt.conf files, but now we have rt_gnu.conf, rt_acorn.conf, rt_ccpp_dev.conf. Also why do we remove the "-f" option which may allow us integrate rt_35d.conf into rt.conf. Also we worked with other research collaborators to port the code to stampede, before we have a formal plan on supporting a wide range developers including people using stampede, please do not remove the file. I think we need to write a document for the rt.conf development.

**Comment by climbfuji** [comment]
> Can we have a detailed plan what the future rt.conf will look like? I thought we are going to reduce the total number of rt.conf files, but now we have rt_gnu.conf, rt_acorn.conf, rt_ccpp_dev.conf.

That's why I started reducing it by removing `rt_stampede.conf`, which a few lines below you ask me to put it back. Leaving this file there when it is not tested doesn't make any sense. If needed we can simply pull out the two most standard tests of `rt.conf` when we identify a team that maintains and run `rt.sh` on stampede, and that the full `rt.conf` doesn't run for some reason.

**EDIT** For the same reason, we should delete `rt_acorn.conf` in my opinion. `rt_gnu.conf` is needed because the differences between Intel and GNU regression test sets are still to big to incorporate them in one file, unless we add another column that specifies the compiler(s) in the same way the machines can be specified.

`rt_ccpp_dev.conf` is required and maintained by DTC+GSL, but if that one file is offending some we can think about whether it makes sense to maintain it only in their fork. I am note sure it is, though, because the file provides a reference for the develop users what kind of tests are run routinely by the CCPP and RAP/HRRR physics developers

> Also why do we remove the "-f" option which may allow us integrate rt_35d.conf into rt.conf.

Because @DusanJovic-NOAA asked me to do so, and because it is not needed? `-l xyz.conf` exists, and without `-l` it goes to `rt.conf` automatically, what does `-f` do on top of it?

> Also we worked with other research collaborators to port the code to stampede, before we have a formal plan on supporting a wide range developers including people using stampede, please do not remove the file.

See above.

> I think we need to write a document for the rt.conf development.

Yes.

**Comment by junwang-noaa** [comment]
Let's discuss this at ufs infrastructure development, we do have tier2 or
tier3 platforms. We may not have enough resources to test it on certain
platforms, it does not mean " Leaving this file there when it is not
tested", I do think corresponding parties can have test them. In general we
need to provide a way to allow other collaborators to run ufs. Again I just
don't know where the code changes lead us to, we need a development plan
for it.

**Comment by climbfuji** [comment]
> Let's discuss this at ufs infrastructure development, we do have tier2 or tier3 platforms. We may not have enough resources to test it on certain platforms, it does not mean " Leaving this file there when it is not tested", I do think corresponding parties can have test them. In general we need to provide a way to allow other collaborators to run ufs. Again I just don't know where the code changes lead us to, we need a development plan for it.
> […](#)

Based on today's discussion it seems to be appropriate to remove `rt_stampede.conf`, since `rt.sh` is only run on tier-1 platforms (which stampede is not). For tier-2 platforms, we maintain the module files and (try to, time and access permitting) make sure that the model compiles, but we do not maintain running the regression tests.

We will retain `rt_acorn.conf` as an exception until that system has been adopted by NOAA, at which time it will be using `rt.conf` as all other tier-1 platforms. We should also keep `rt_ccpp_dev.conf`, and we must keep `rt_gnu.conf` unless we can and want to run all tests in `rt.conf` with GNU (several tests will take much longer with GNU).

We did not discuss the `-f` flag. Is there any reason why this flag is needed? I can't see it, but I may be missing something.

**Comment by climbfuji** [comment]
@junwang-noaa @DusanJovic-NOAA please take a look at the modified `rt.conf`. Once Denise's current PR is merged, I will update this one and then we are ready to create new baselines. If the `rt.conf` changes are agreed upon by then, we don't have to do any more back and forth. Thanks!

**Comment by climbfuji** [comment]
This PR is ready for review. The new regression test baseline date tag is 20210106.

File: tests/rt.sh [hunk 1]
```diff
@@ -9,18 +9,16 @@ die() { echo "$@" >&2; exit 1; }
 usage() {
   set +x
   echo
-  echo "Usage: $0 -c | -e | -f | -h | -k | -l <file> | -m | -n <name> | -r | -s"
+  echo "Usage: $0 -c | -e | -h | -k | -l <file> | -m | -n <name> | -r "
```
Comment (junwang-noaa) [inline tests/rt.sh:12]: we did not get to discuss about the full test feature. We may want to bring "-f" feature back when we do full tests with several rt.conf files if we decided to combine them together, or we can set up a script to run those configurations separately.

Comment (climbfuji) [reply tests/rt.sh:12]: It's really a question about complexity in `rt.sh` versus running two steps manually, first `rt.sh` without `-l ...`, then `rt.sh -l rt_35d.conf`. I am leaning towards keeping `rt.sh` (as) simple (as possible), but I would like to hear other opinions.

File: tests/rt_acorn.conf [hunk 2]
```diff
@@ -1,52 +1,52 @@
...
-################################################################################################################################################################################
-
-COMPILE | SUITES=FV3_GFS_2017_coupled,FV3_GFS_2017_satmedmf_coupled,FV3_GFS_v15p2_coupled S2S=Y                                   | standard    |                | fv3         |
-RUN     | cpld_control                                                                                                            | standard    |                | fv3         |
-RUN     | cpld_2threads                                                                                                           | standard    |                |             |
-RUN     | cpld_decomp                                                                                                             | standard    |                |             |
+##################################################################################################################################################################
```
Comment (junwang-noaa) [inline tests/rt_acorn.conf]: Do we need this to be in the repo? Do we run the test in this commit? I feel this is the same kind file as rt_stampede.conf

File: tests/rt.sh (hunk 1 above)
Comment (DusanJovic-NOAA) [reply tests/rt.sh:12]: I agree. We should try to keep rt.sh as simple as possible, without adding (or maintaining) unnecessary logic.

File: tests/rt_acorn.conf (hunk 2 above)
Comment (climbfuji) [reply tests/rt_acorn.conf]: I am ok to delete it, @DusanJovic-NOAA mentioned last time that acorn was somewhat special. But one can always just run a single test using `-n` or copy `rt.conf` to something else.

Comment (DusanJovic-NOAA) [reply tests/rt_acorn.conf]: We do not run any test on acorn before each commit.
Acorn (or however they call the real WCOSS2) is not the same as stampede. It will (soon?) become Tier-1 platform. Moreover it will be the NCEP's production machine.

File: tests/rt.conf [hunk 3]
```diff
@@ -1,188 +1,188 @@
...
-RUN     | cpld_satmedmf                                                                                                           | standard | - wcoss_cray gaea.intel jet.intel | fv3 |
-RUN     | cpld_ca                                                                                                                 | standard | - wcoss_cray gaea.intel jet.intel | fv3 |
+COMPILE | DEBUG=Y                                                                                                                 | + wcoss_dell_p3                         | fv3 |
+COMPILE | DEBUG=Y                                                                                                                 | + wcoss_cray                            | fv3 |
+COMPILE | DEBUG=Y                                                                                                                 | + hera.intel                            | fv3 |
+COMPILE | SUITES=FV3_GFS_v15p2,FV3_GFS_v16beta,FV3_GFS_v15p2_RRTMGP,FV3_GFS_v16beta_RRTMGP DEBUG=Y                                | + orion.intel                           | fv3 |
```
Comment (DusanJovic-NOAA) [inline tests/rt.conf]: I think I tested the compilation on Orion using just "DEBUG=Y' and it worked.

Comment (climbfuji) [reply tests/rt.conf]: Ok, I will make this change.

File: tests/rt_acorn.conf (hunk 2 above)
Comment (DusanJovic-NOAA) [reply tests/rt_acorn.conf]: > I am ok to delete it, @DusanJovic-NOAA mentioned last time that acorn was somewhat special. But one can always just run a single test using `-n` or copy `rt.conf` to something else.

Ok. Delete it.

Comment (climbfuji) [reply tests/rt_acorn.conf]: Deleted.

**Comment by junwang-noaa** [comment]
Sorry, maybe I misunderstand, I thought we would have a different machine
for wcoss2, not acorn which is a small test machine. If acorn is the wcoss2
machine, we need to add it to rt.conf like dell and cray.

**Comment by junwang-noaa** [comment]
Let's add wcoss2 to rt.conf when it is accepted as NCEP's production
machine.

**Comment by junwang-noaa** [comment]
@climbfuji would you please give a short summary what additional tests have been added on orion, jet, cheyenne, and wcoss?

**Comment by climbfuji** [comment]
It's best to look at https://docs.google.com/spreadsheets/d/1tf7ufYW2umLXQQ2G43h64ESGw5jYb67MAqEbvGPNAm4/edit?ts=5feca219#gid=1397536520 and the updated `rt.conf`. The following tests have changed:
- fv3_ccpp_ca, fv3_ccpp_lndp, fv3_ccpp_iau, fv3_ccpp_lheatstrg, fv3_ccpp_satmedmfq, fv3_ccpp_gfdlmprad_32bit_post now run on all platforms
- fv3_ccpp_rap and fv3_ccpp_hrrr now run on all platforms except jet (known issue, will be fixed when the next round of updates from gsl/develop are merged into the authoritative repositories)
- all v15p2 and v16beta tests are now run on all platforms (in both DEBUG and PROD mode)
- fv3_ccpp_gfsv16_csawmg and fv3_ccpp_gfsv16_csawmgt not run on cheyenne (crashes with a bus error, as before), but they do now run on gaea and jet

That's it.

**Comment by climbfuji** [comment]
@DusanJovic-NOAA I think you can start creating baselines on wcoss and orion (if possible). I am cruising along on jet, gaea, cheyenne, hera.

**Comment by climbfuji** [comment]
> It's best to look at https://docs.google.com/spreadsheets/d/1tf7ufYW2umLXQQ2G43h64ESGw5jYb67MAqEbvGPNAm4/edit?ts=5feca219#gid=1397536520 and the updated `rt.conf`. The following tests have changed:
> 
> * fv3_ccpp_ca, fv3_ccpp_lndp, fv3_ccpp_iau, fv3_ccpp_lheatstrg, fv3_ccpp_satmedmfq, fv3_ccpp_gfdlmprad_32bit_post now run on all platforms
> * fv3_ccpp_rap and fv3_ccpp_hrrr now run on all platforms except jet (known issue, will be fixed when the next round of updates from gsl/develop are merged into the authoritative repositories)
> * all v15p2 and v16beta tests are now run on all platforms (in both DEBUG and PROD mode)
> * fv3_ccpp_gfsv16_csawmg and fv3_ccpp_gfsv16_csawmgt not run on cheyenne (crashes with a bus error, as before), but they do now run on gaea and jet
> 
> That's it.

I will update the spreadsheet that Dusan put together after the PR is merged.

**Comment by climbfuji** [comment]
@junwang-noaa @DusanJovic-NOAA This PR is ready to merge. The CI tests just kicked off, they'll be done by tomorrow morning easily. Thanks @DusanJovic-NOAA for your help with running the regression tests today.

**Review by junwang-noaa — APPROVED** [review]

File: modulefiles/jet.intel/fv3_debug [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+module load hpc-impi/2018.4.274
+
+module load jasper/2.0.22
+module load zlib/1.2.11
+module load png/1.6.35
+
+module load hdf5/1.10.6
+module load netcdf/4.7.4
+module load pio/2.5.1
+module load esmf/8_1_0_beta_snapshot_27
```
Comment (DeniseWorthen) [inline modulefiles/jet.intel/fv3_debug:31]: Is there no esmf debug module on jet ?

**Review by MinsukJi-NOAA — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

File: modulefiles/jet.intel/fv3_debug (hunk 4 above)
Comment (climbfuji) [reply modulefiles/jet.intel/fv3_debug:31]: For all the platforms where we haven't compiled the debug module yet we simply had to copy the existing module over so that the code would still run. This is because somebody removed the logic (or it is not working as intended) that says "only if a debug module exists, use it; otherwise use the standard module".

Yes, when the next HPC stack release is rolled out we should create debug modules for all platforms.

Comment (climbfuji) [reply modulefiles/jet.intel/fv3_debug:31]: FYI, it's the same for wcoss_cray, for example.

**Comment by climbfuji** [comment]
CI tests passed; @DeniseWorthen once you approve we are ready to merge. Thanks everyone for your review.

**Review by DeniseWorthen — APPROVED** [review]
