### PR TITLE
Regression Testing Updates: GNU/Intel into one RT. New logs/ dir in tests/

### LINKED ISSUE #1363: Update documentation on readthedocs for ORTs to include information on what ORT's to run for specific types of tests.
The wiki has information on what we currently call ORT's (Operational Requirements Tests), previously called unit tests at https://github.com/ufs-community/ufs-weather-model/wiki/Running-unit-tests-using-utest .

If there's anything new about ORT's that the component devs need to know, it needs to be updated on that wiki. With all of the EPIC work and their current or upcoming methodologies, if there are any changes that needs to be updated/added it should be done as well.

A section for what ORT's need to be run for which tests should also be added. i.e. coupled, global, regional. Not all ORT's work for all types of tests (yet i think) and this needs to be documented.

### LINKED ISSUE #1682: Combine Intel/GNU tests && hard code compile number in rt.conf
## Description

As intel/gnu logs need to be attached to PR's as proof of testing and what tests fail, it would be helpful to combine the Intel and GNU tests into one file to be run at the same time. As an added benefit this should reduce the number of files that need to be maintained.

As compiles fail on machines, they give a compile number that depends on where that compile is in rt.conf and is unique to each machine. This leads to counting compiles in rt.conf to identify which compile fails and can lead to errors and delays. 

## Solution

Update the RT system to allow the tests in rt_gnu.conf to be added to rt.conf.

It would be beneficial to hard code compile numbers such that identifying it upon a failure is easy.

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
## Description

rt.conf updates:
- Combine Intel and GNU tests into one conf file.
- Added section to COMPILE line to hard-code compile numbers.
- Added section to COMPILE line to specify compiler.
- Ordered RUN lines globally for easier GREP view.
- Changed fv3 in RUN lines to "baseline" for easier understanding of what it does.

rt.sh updates:
- -a option added, need to use -a unless ACCNR is set in environment
- Fixes for some identified potential issues in scripts. Output text should be less repetative.
- Removal of INTEL/GNU baseline develop dirs.
- Test Run Dir's names updated with which compiler is being used.
- Logs will now contain the hashes of the UFSWM and its submodules.
- moved BL_DATE outside rt.sh into bl_date.conf

bl_date.conf:
- moved BL_DATE into here for easier code management, identify actual rt.sh changes vs BL_DATE change each PR.

Log updates:
- RegressionTests_*.log and opnReqTest_*.log now go into log directory.
- Log files now RegressionTests_\<machine\>.log instead of RegressionTests_\<machine\>.\<compiler\>.log.

Baseline storage updates:
  - develop-2023XXXX/INTEL|GNU/\<test_dir\> now are just develop-2023XXXX/\<test_dir\>.
  - Run/Test Dir's now have RT_COMPILER appended to them (i.e. control_c48_intel and control_c48_gnu).
  - STMP/PTMP baseline storage now REGRESSION_TEST instead of REGRESSION_TEST_INTEL or REGRESSION_TEST_GNU.

opnReqTest updates:
- -a option added to force users to specify account to use on HPC
- Tests that are not compatible yet with ORT tests like dcmp, thrd, fhzero etc, will now auto skip themselves instead of failing the whole suite. So running ORT should be as easy as `./opnReqTest -e -n regional_control`

PR template update:
- The PR template was updated to what is shown here. Removed the Intel/GNU sections from Testing Log.

### What I have tested:
- Full RT Suite on hera
- ORT with regional_control
- rt_weekly (./rt.sh -e -w -l rt_weekly.conf)
- AutoRT on Hera/Cheyenne
- Jenkins-CI
- new -a option in rt.sh and opnReqTest

### What I need to test:
- all testing completed

### Input data additions/changes
- [x] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Anticipated changes to regression tests:
- [ ] No changes are expected to any regression test.
- [x] Changes are expected to the following tests:

This should not change answers to any test, but the whole regression testing system is getting name changes, so all baselines will need to be regenerated with the new code changes and new baseline-dirs will need to be created.

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [X] none

## Commit Queue Checklist:

- [x] Link PR's from all sub-components involved in section below
- [x] Confirm reviews completed in ALL sub-component PR's
- [x] Add all appropriate labels to this PR.
- [x] Run full RT suite on either Hera/Cheyenne AND attach log to a PR comment.
- [x] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Linked PR's and Issues:

- closes #1682 
- closes #1363 

## Testing Day Checklist:

- [x] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [x] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Jet
  - [x] Gaea
  - [x] Cheyenne
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- CI
  - [x] Completed
- opnReqTest
  - [x] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
To prove tests don't change baselines for this PR will be manual due to the fact that the baselines directory is changing a bit. I have used the following script to compare baselines:
```bash
#! /bin/bash

TESTDIR=/scratch1/NCEPDEV/stmp4/Brian.Curtis/FV3_RT/REGRESSION_TEST_GOOD/
TESTS=`ls ${TESTDIR}`
BLDIR=/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20230413/

#echo $TESTDIRS

for i in $TESTS
do
  TEST=${i%_*}
  CMPLR=${i##*_}
  CMPDIR=${BLDIR}${CMPLR^^}/${TEST}
  echo "Comparing files for ${CMPLR^^} test: ${TEST}"
  for j in `ls ${CMPDIR}`
  do
    if [[ ${j} == "RESTART" ]]; then
      for k in `ls ${CMPDIR}/$j`
      do
        if  [[ ${k##*.} =~ nc* ]]; then
          echo "--> USING NCCMP ON FILE: ${j}/${k} "
          nccmp -d -f -g -B --Attribute=checksum --warn=format ${TESTDIR}/$i/$j/$k ${CMPDIR}/$j/$k || echo -e "\n"
        else
          echo "--> USING CMP ON FILE: ${j}/${k}"
          cmp ${TESTDIR}/$i/$j/$k ${CMPDIR}/$j/$k || echo -e "\n"
        fi
        
      done
      
    elif  [[ ${j##*.} =~ nc* ]]; then
      echo "--> USING NCCMP ON FILE: ${j}"
      nccmp -d -f -g -B --Attribute=checksum --warn=format ${TESTDIR}/$i/$j ${CMPDIR}/$j || echo -e "\n"
    else
      echo "--> USING CMP ON FILE: ${j}"
      cmp ${TESTDIR}/$i/$j ${CMPDIR}/$j || echo -e "\n"
    fi

  done
done
```
And here is it's results:
[comparisons.txt](https://github.com/ufs-community/ufs-weather-model/files/11289935/comparisons.txt)

**Comment by FernandoAndrade-NOAA** [comment]
@BrianCurtis-NOAA I'm going to get started with jenkins-ci on this PR

File: tests/rt.sh [hunk 1]
```diff
@@ -123,14 +123,14 @@ fi
 readonly RT_SINGLE_CONF='rt_single.conf'
 
 # Default compiler "intel"
-export RT_COMPILER=${RT_COMPILER:-intel}
+#export RT_COMPILER=${RT_COMPILER:-intel}
```
Comment (DusanJovic-NOAA) [inline tests/rt.sh]: Delete these two lines

File: tests/run_test.sh [hunk 2]
```diff
@@ -84,13 +80,13 @@ cd $RUNDIR
 ###############################################################################
 # Make configure and run files
 ###############################################################################
-MACHINE_ID=${MACHINE_ID:-false}
+# MACHINE_ID=${MACHINE_ID:-false}
```
Comment (DusanJovic-NOAA) [inline tests/run_test.sh]: Delete if not needed anymore

File: tests/run_test.sh [hunk 3]
```diff
@@ -109,22 +105,37 @@ SRCD="${PATHTR}"
...
+else
+  echo "Cannot find file ${MODEL_CONFIGURE} set by variable MODEL_CONFIGURE"
+  exit 1
+fi
 
 compute_petbounds_and_tasks
 
-atparse < ${PATHRT}/parm/${NEMS_CONFIGURE:-nems.configure} > nems.configure
+if [[ -f ${PATHRT}/parm/${NEMS_CONFIGURE} ]]; then
+  atparse < ${PATHRT}/parm/${NEMS_CONFIGURE:-nems.configure.atm.IN} > nems.configure
```
Comment (DusanJovic-NOAA) [inline tests/run_test.sh]: If ${NEMS_CONFIGURE} is always required to be set remove the default value

File: tests/run_test.sh [hunk 4]
```diff
@@ -109,22 +105,37 @@ SRCD="${PATHTR}"
...
 
 if [[ $DATM_CDEPS = 'true' ]] || [[ $FV3 = 'true' ]] || [[ $S2S = 'true' ]]; then
   if [[ $HAFS = 'false' ]] || [[ $FV3 = 'true' && $HAFS = 'true' ]]; then
     atparse < ${PATHRT}/parm/${INPUT_NML:-input.nml.IN} > input.nml
   fi
 fi
 
-atparse < ${PATHRT}/parm/${MODEL_CONFIGURE:-model_configure.IN} > model_configure
+if [[ -f ${PATHRT}/parm/${MODEL_CONFIGURE} ]]; then
+  atparse < ${PATHRT}/parm/${MODEL_CONFIGURE:-model_configure.IN} > model_configure
```
Comment (DusanJovic-NOAA) [inline tests/run_test.sh]: If ${MODEL_CONFIGURE} is always required to be set remove the default value

**Comment by FernandoAndrade-NOAA** [comment]
Attached are the jenkins ci logs; the tests failed and we're looking into this.
[ufs-weather-model » ort-docker-pipeline » PR-1718 #1 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/11297374/ufs-weather-model.ort-docker-pipeline.PR-1718.1.Console.Jenkins.pdf)

**Comment by BrianCurtis-NOAA** [comment]
@FernandoAndrade-NOAA 

- The BL_DIR was (develop-YYYYMMDD/<compiler>/<test_names>) is now just (develop-YYYYMMDD/<test_names>).
- Test dirs were <test_name>/files are now <test_name>_${RT_COMPILER}/files where ${RT_COMPILER} is either intel or gnu (you probably don't need to worry about GNU, since it's unsupported for WCOSS2 operations.)

If you need me to look through what you're doing, i'd be happy to.

**Comment by zach1221** [comment]
I'm trying to test ORT manually against this PR on Hera, and receiving unbound variable error for "TEST_NAME". I get this error with both intel and gnu. 
image

Edit* (I should add this occurs on the std_base)

**Comment by zach1221** [comment]
@FernandoAndrade-NOAA ORTs passed when I ran them manually against this PR, following Brian's changes. I think you can try jenkins-ci again, when you're able.

**Comment by BrianCurtis-NOAA** [comment]
[RegressionTests_hera.log](https://github.com/ufs-community/ufs-weather-model/files/11324810/RegressionTests_hera.log)

**Comment by zach1221** [comment]
@BrianCurtis-NOAA jenkins-ci sandbox pipeline passed when I added " export OMP_ENV=${OMP_ENV:-""} " to line 295 in run_test.sh of tests/ directory and line 5 in cmp_proc_bind.sh of tests/opnReqTests/.  Once you make the updates I'll run the production pipeline again.

**Comment by zach1221** [comment]
@BrianCurtis-NOAA could you please update the jenkinsfile, in tests/ci/, on line 80?

Let's update the shm-size to 8gb. Currently it is set to 1.
image

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA could you please update the jenkinsfile, in tests/ci/, on line 80?
> 
> Let's update the shm-size to 8gb. Currently it is set to 1. image

@zach1221 done

**Comment by zach1221** [comment]
@BrianCurtis-NOAA Apologies, can you please update the jenkinsfile once more to 16gb? Thank you.

**Comment by zach1221** [comment]
@BrianCurtis-NOAA can you make another additional change in the opnReqTest script? I want to try temporarily hashing out the 2>&1 error redirect for the test run, on line 271. It could be helpful to see the specific error the script throws.

**Comment by BrianCurtis-NOAA** [comment]
@zach1221 done

**Comment by zach1221** [comment]
Jenkins-ci attached. We're planning to start testing the autoRT portion first thing tomorrow A.M.
[ufs-weather-model » ort-docker-pipeline » PR-1718 #10 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/11434995/ufs-weather-model.ort-docker-pipeline.PR-1718.10.Console.Jenkins.pdf)

File: tests/rt.conf [hunk 5]
```diff
@@ -2,10 +2,10 @@
 # S2S tests                                                                                                                                                                       #
```
Comment (DeniseWorthen) [inline tests/rt.conf]: Are you able to realign the columns in rt.conf? It's easy to do in emacs, but I don't know if that is what you use

Comment (BrianCurtis-NOAA) [reply tests/rt.conf]: I am going to completely update rt.conf once this gets to its merge/testing day. Make it look much better than it currently does.

**Comment by DeniseWorthen** [comment]
@BrianCurtis-NOAA 

6:forrtl: Disk quota exceeded

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Job: BL
Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1321449518/20230515105802/ufs-weather-model
Please manually delete: /glade/scratch/epicufsrt/FV3_RT/rt_17819
Please make changes and add the following label back: cheyenne-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Job: BL
Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1321449518/20230515151519/ufs-weather-model
Please manually delete: /glade/scratch/epicufsrt/FV3_RT/rt_69235
Baseline creation and move successful
[RT] Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1321449518/20230515164016/ufs-weather-model
Please make changes and add the following label back: cheyenne-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1321449518/20230517182826/ufs-weather-model
Please make changes and add the following label back: cheyenne-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Job: BL
Repo location: /scratch1/NCEPDEV/nems/role.epic/autort/pr/1321449518/20230518124911/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/Brian.Curtis/FV3_RT/rt_29838
Please make changes and add the following label back: hera-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1321449518/20230518092144/ufs-weather-model
Please make changes and add the following label back: cheyenne-RT

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Job: BL
Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1321449518/20230518121957/ufs-weather-model
Please make changes and add the following label back: cheyenne-BL

**Comment by zach1221** [comment]
Trying once more with the BL on Cheyenne. I think I forgot a step in the jenkins trigger and just want to make sure.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Job: BL
Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1321449518/20230518131116/ufs-weather-model
Please make changes and add the following label back: cheyenne-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Job: BL
Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1321449518/20230518150322/ufs-weather-model
Please make changes and add the following label back: cheyenne-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Job: BL
Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1321449518/20230522084928/ufs-weather-model
Please make changes and add the following label back: cheyenne-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Job: BL
Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1321449518/20230522094451/ufs-weather-model
Please make changes and add the following label back: cheyenne-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Job: BL
Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1321449518/20230522102918/ufs-weather-model
Please make changes and add the following label back: cheyenne-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Job: BL
Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1321449518/20230522113548/ufs-weather-model
Please manually delete: /glade/scratch/epicufsrt/FV3_RT/rt_54119
Please make changes and add the following label back: cheyenne-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Job: BL
Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1321449518/20230524075510/ufs-weather-model
Please make changes and add the following label back: cheyenne-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Job: BL
Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1321449518/20230524093152/ufs-weather-model
Please make changes and add the following label back: cheyenne-BL

File: tests/rt.conf [hunk 6]
```diff
@@ -204,122 +204,233 @@ RUN     | hrrr_control_decomp_dyn32_phy32
...
+
+COMPILE | 46 | gnu | -DAPP=S2SWA -DCCPP_SUITES=FV3_GFS_v17_coupled_p8,FV3_GFS_cpld_rasmgshocnsstnoahmp_ugwp                                   | + cheyenne hera | fv3         |
+RUN     | cpld_control_p8                                                                                                          | + cheyenne hera | fv3         |
+
+COMPILE | 47 | gnu | -DAPP=S2S -DCCPP_SUITES=FV3_GFS_v17_coupled_p8,FV3_GFS_cpld_rasmgshocnsstnoahmp_ugwp                                     | + cheyenne hera | fv3         |
+RUN     | cpld_control_nowave_noaero_p8                                                                                            | + cheyenne hera | fv3         |
+
+COMPILE | 48 | gnu | -DAPP=S2SWA -DDEBUG=ON -DCCPP_SUITES=FV3_GFS_v17_coupled_p8,FV3_GFS_cpld_rasmgshocnsstnoahmp_ugwp                        | + cheyenne hera | fv3         |
+RUN     | cpld_debug_p8                                                                                                            | + cheyenne hera | fv3         |
+
```
Comment (DeniseWorthen) [inline tests/rt.conf:390]: You are missing the new unstruc WW3 tests here.

Comment (BrianCurtis-NOAA) [reply tests/rt.conf:390]: Thanks. I was afraid of that already, so since I know the PRs before this one do not change rt.conf i'm currently using develop's rt.conf and rt_gnu.conf to create an rt.conf for this PR, which should address this.

Comment (DeniseWorthen) [reply tests/rt.conf:390]: I'm testing my cmeps PR now for hera.gnu and I'm having timeouts each time. I know this is a known issue, but I don't understand why we can't take my earlier suggestion and modify the wall clock for hera.gnu w/in the cpld test. 

I know eventually we hope to update GNU on hera, but we need something to bridge between now and then. It isn't tenable to have to keep running the cpld hera.gnu tests 3 or 4 times when we know the timeout issue.

Comment (DusanJovic-NOAA) [reply tests/rt.conf:390]: We should stop running gnu tests on hera and cheyenne. Hera is very busy, we have issues with disk apace and hera uses old gnu compiler. Cheyenne has its own issues with compiler, mpi etc and most people do not have access to cheyenne. Instead we should build all required libraries on Orion or even better on Hercules with gcc/12 and start running gnu tests there.

Comment (DeniseWorthen) [reply tests/rt.conf:390]: I think being able to test a more modern GNU on Cheyenne has been an advantage. If Orion can support a new GNU, then I agree this would make sense. What I don't like is the idea to stop testing GNU until that is in place.

And I won't even mention the "too many tests"....

Comment (BrianCurtis-NOAA) [reply tests/rt.conf:390]: Resolving with latest commits!

File: tests/opnReqTest [hunk 7]
```diff
@@ -332,7 +338,7 @@ if [[ $MACHINE_ID = hera.* ]]; then
   PARTITION=
   QUEUE=batch
   COMPILE_QUEUE=batch
-  ACCNR="${ACCNR:-nems}"
+  #ACCNR="${ACCNR:-nems}"
```
Comment (DeniseWorthen) [inline tests/opnReqTest]: Is there a reason you're retaining the commented out ACCNR lines?

Comment (BrianCurtis-NOAA) [reply tests/opnReqTest]: No

File: tests/rt.conf [hunk 8]
```diff
@@ -1,325 +1,395 @@
...
+## NOTE: The build resulting from the COMPILE line above the RUN line will be used to run the test 
+# Item 1: RUN - This tells rt.conf the following information is to be used in setting up a model run
+# Item 2: Test name - Which test in the tests/tests directory should be sourced?
+# Item 3: Machines to run on (- is used to ignore specified machines, + is used to only run on specified machines) 
+## reference example above
+# Item 4: Controls whether the run creates its own baseline or it uses the baseline from a different (control) test
+
+### Intel Tests ###
+### S2S tests ###
+COMPILE | 1 | intel | -DAPP=S2SWA -D32BIT=ON -DCCPP_SUITES=FV3_GFS_v17_coupled_p8,FV3_GFS_cpld_rasmgshocnsstnoahmp_ugwp | | fv3 |
```
Comment (DeniseWorthen) [inline tests/rt.conf:23]: I find the non-alignment of the vertical bars (|) much more difficult to read.

Comment (BrianCurtis-NOAA) [reply tests/rt.conf:23]: I did not feel it was important for COMPILE lines to match their following RUN lines columns because the data for each line is drastically different and creates an unnecessary large line of blank spaces.

The new changes bring what you mention to the RUN lines, they are much easier to follow.

I will leave this open for opinions, happy to make changes if I am in the minority! @junwang-noaa @jkbk2004 @DusanJovic-NOAA what do you feel?

Comment (DeniseWorthen) [reply tests/rt.conf:23]: I didn't mean to comment on the compile line specifically (it was just the first line in the file). My comment was more about the alignment of | in the actual run lines. They don't run down the file all in the same column.

Comment (BrianCurtis-NOAA) [reply tests/rt.conf:23]: Thats fine. It's still a similar answer, though. I didn't feel the RUN lines needed to share the same shape as other RUN lines that followed different COMPILE lines, as the test names all vary in length, and the different machines to ignore or only run on varied as well.

Comment (DusanJovic-NOAA) [reply tests/rt.conf:23]: I personally prefer that all RUN lines are aligned. For example if I want to see the status of all restart tests I can grep for RUN lines with string restart and see :

```
$ grep "^RUN" rt.conf | grep restart
RUN | cpld_restart_p8       |                            |     | cpld_control_p8
RUN | cpld_restart_qr_p8    |                            |     | cpld_control_qr_p8
RUN | cpld_restart_c192_p8  | - wcoss2 jet acorn gaea s4 |     | cpld_control_c192_p8
RUN | cpld_restart_bmark_p8 | - s4 jet cheyenne acorn    |     | cpld_bmark_p8
RUN | cpld_restart_c48   | |     | cpld_warmstart_c48
RUN | cpld_restart_pdlib_p8 | + hera orion cheyenne  |     | cpld_control_pdlib_p8
RUN | control_stochy_restart           |                |     | control_stochy
RUN | control_restart_p8               |                |     | control_p8
RUN | control_restart_qr_p8            |                |     | control_qr_p8
RUN | regional_restart                 |                |     | regional_control
RUN | regional_restart_qr              |                |     | regional_control_qr
RUN | rap_restart                               | |     | rap_control
RUN | rap_sfcdiff_restart                       | |     | rap_sfcdiff
RUN | hrrr_control_restart                      | |     | hrrr_control
RUN | rrfs_conus13km_hrrr_warm_restart_mismatch | | fv3 | rrfs_conus13km_hrrr_warm
RUN | rap_restart_dyn32_phy32                 | |     | rap_control_dyn32_phy32
RUN | hrrr_control_restart_dyn32_phy32        | |     | hrrr_control_dyn32_phy32
RUN | datm_cdeps_restart_cfsr        | - wcoss2 |     | datm_cdeps_control_cfsr
RUN | rap_restart                             | + hera cheyenne |     | rap_control
RUN | rap_sfcdiff_restart                     | + hera cheyenne |     | rap_sfcdiff
RUN | hrrr_control_restart                    | + hera cheyenne |     | hrrr_control
RUN | rrfs_conus13km_hrrr_warm_restart_mismatch | + hera cheyenne | fv3 | rrfs_conus13km_hrrr_warm
RUN | rap_restart_dyn32_phy32           | + hera cheyenne |     | rap_control_dyn32_phy32
RUN | hrrr_control_restart_dyn32_phy32  | + hera cheyenne |     | hrrr_control_dyn32_phy32
```
Which is not as readable as, for example:

```
$ grep "^RUN" rt_aligned.conf | grep restart
RUN | cpld_restart_p8                           |                            |     | cpld_control_p8
RUN | cpld_restart_qr_p8                        |                            |     | cpld_control_qr_p8
RUN | cpld_restart_c192_p8                      | - wcoss2 jet acorn gaea s4 |     | cpld_control_c192_p8
RUN | cpld_restart_bmark_p8                     | - s4 jet cheyenne acorn    |     | cpld_bmark_p8
RUN | cpld_restart_c48                          |                            |     | cpld_warmstart_c48
RUN | cpld_restart_pdlib_p8                     | + hera orion cheyenne      |     | cpld_control_pdlib_p8
RUN | control_stochy_restart                    |                            |     | control_stochy
RUN | control_restart_p8                        |                            |     | control_p8
RUN | control_restart_qr_p8                     |                            |     | control_qr_p8
RUN | regional_restart                          |                            |     | regional_control
RUN | regional_restart_qr                       |                            |     | regional_control_qr
RUN | rap_restart                               |                            |     | rap_control
RUN | rap_sfcdiff_restart                       |                            |     | rap_sfcdiff
RUN | hrrr_control_restart                      |                            |     | hrrr_control
RUN | rrfs_conus13km_hrrr_warm_restart_mismatch |                            | fv3 | rrfs_conus13km_hrrr_warm
RUN | rap_restart_dyn32_phy32                   |                            |     | rap_control_dyn32_phy32
RUN | hrrr_control_restart_dyn32_phy32          |                            |     | hrrr_control_dyn32_phy32
RUN | datm_cdeps_restart_cfsr                   | - wcoss2                   |     | datm_cdeps_control_cfsr
RUN | rap_restart                               | + hera cheyenne            |     | rap_control
RUN | rap_sfcdiff_restart                       | + hera cheyenne            |     | rap_sfcdiff
RUN | hrrr_control_restart                      | + hera cheyenne            |     | hrrr_control
RUN | rrfs_conus13km_hrrr_warm_restart_mismatch | + hera cheyenne            | fv3 | rrfs_conus13km_hrrr_warm
RUN | rap_restart_dyn32_phy32                   | + hera cheyenne            |     | rap_control_dyn32_phy32
RUN | hrrr_control_restart_dyn32_phy32          | + hera cheyenne            |     | hrrr_control_dyn32_phy32
```
where I can immediately see that there are two 'restart' tests that generate new baselines and I can reason why and whether that's intended or not. Or see the status of restart tests on various machines. Or I can verify that all restart tests have it's dependent test specified in the last column. Etc.

Comment (DusanJovic-NOAA) [reply tests/rt.conf:23]: Maybe this PR is good opportunity to finally replace that 'fv3' in the 4th column, that means 'generate new baselines' to some other string. 'baseline' or 'base' maybe? Or something else other than 'fv3'.

File: tests/rt.conf [hunk 9]
```diff
@@ -1,325 +1,395 @@
...
+## -> EX: - wcoss2 acorn = compile will NOT be run on wcoss2 or acorn
+# Item 6:
+#
+# RUN Line ( Items separated by a | )
+## NOTE: The build resulting from the COMPILE line above the RUN line will be used to run the test 
+# Item 1: RUN - This tells rt.conf the following information is to be used in setting up a model run
+# Item 2: Test name - Which test in the tests/tests directory should be sourced?
+# Item 3: Machines to run on (- is used to ignore specified machines, + is used to only run on specified machines) 
+## reference example above
+# Item 4: Controls whether the run creates its own baseline or it uses the baseline from a different (control) test
```
Comment (DusanJovic-NOAA) [inline tests/rt.conf]: Add Item 5 which specifies the name of the test this test depends on.

File: tests/rt.conf (hunk 8 above)
Comment (DeniseWorthen) [reply tests/rt.conf:23]: @DusanJovic-NOAA Great idea. I think "baseline" is clearest thing we could use instead. We only save 4 chars making it "base".

File: tests/rt.conf (hunk 9 above)
Comment (DeniseWorthen) [reply tests/rt.conf]: How do you describe the 5th column? When the 4th column is blank, then it compares against a control baseline, right? The 5th column is really where the test "depends" on another test.

Comment (DusanJovic-NOAA) [reply tests/rt.conf]: Yes. The 5th column is the name of the (previous) test that must be completed before this one starts, that's all . It is typically used for restart tests which depend on the output of the previous (cold start) test to be available. Whether the 4th column is blank or not does not matter, for restart cases this is mostly true, because restart test compare against it's 'dependent' test baselines, but conceivably one can decide to have some baseline files saved even for restart cases. So, basically this column is only used to specify the execution order of tests nothing else.

**Comment by DusanJovic-NOAA** [comment]
Currently we specify `BL_DATE` in rt.sh. How about we introduce separate file `bl_date.conf` or `bl_date.txt`  or whatever, which will only have single line:

```
BL_DATE=YYYYMMDD
```
and we just source it in rt.sh at the place where BL_DATE is currently set. 
Most of the PRs do not need to touch rt.sh, and such PRs will only update this little file instead of changing rt.sh, which will indicate that no other changes are made in regression testing other than updating baseline date. What do you think?

**Comment by BrianCurtis-NOAA** [comment]
> Currently we specify `BL_DATE` in rt.sh. How about we introduce separate file `bl_date.conf` or `bl_date.txt` or whatever, which will only have single line:
> 
> ```
> BL_DATE=YYYYMMDD
> ```
> 
> and we just source it in rt.sh at the place where BL_DATE is currently set. Most of the PRs do not need to touch rt.sh, and such PRs will only update this little file instead of changing rt.sh, which will indicate that no other changes are made in regression testing other than updating baseline date. What do you think?

I like this idea.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA #1761 was merged. You can go ahead to sync up. We will start working on this pr.

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA #1761 was merged. You can go ahead to sync up. We will start working on this pr.

I have some final changes to be made, i'll get them done ASAP.

File: tests/rt.conf (hunk 9 above)
Comment (BrianCurtis-NOAA) [reply tests/rt.conf]: Addressed in recent commit

File: tests/rt.conf (hunk 8 above)
Comment (BrianCurtis-NOAA) [reply tests/rt.conf:23]: i've changed them to baseline and addressed where i think it matters in rt.sh

File: tests/rt_35d.conf [hunk 10]
```diff
@@ -2,12 +2,12 @@
...
-RUN     | cpld_bmark_p8_35d                                                                                               |                             | fv3 |  | 2012070100
-RUN     | cpld_bmark_p8_35d                                                                                               |                             | fv3 |  | 2012100100
-RUN     | cpld_bmark_p8_35d                                                                                               |                             | fv3 |  | 2013010100
-RUN     | cpld_bmark_p8_35d                                                                                               |                             | fv3 |  | 2013040100
-RUN     | cpld_bmark_p8_35d                                                                                               |                             | fv3 |  | 2013070100
-RUN     | cpld_bmark_p8_35d                                                                                               |                             | fv3 |  | 2013100100
+COMPILE | 1 | intel | -DAPP=S2SW -DCCPP_SUITES=FV3_GFS_v17_coupled_p8 | + hera.intel | fv3 |  |
```
Comment (DeniseWorthen) [inline tests/rt_35d.conf]: What should we do (if anything) about the fv3 in the compile line? Does this just name the executable? I really don't know what it does @DusanJovic-NOAA

Comment (BrianCurtis-NOAA) [reply tests/rt_35d.conf]: I agree, im still not sure what it does, i think we used it long ago so we didn't have to redo compile? We can address this in a later PR.

**Comment by BrianCurtis-NOAA** [comment]
I'm running a 2 compile 4 test, RT suite to make sure these recent changes are not breaking anything. I'll let @zach1221 know when to start hera RT, so we can at least confirm all the autoRT changes are working after these last minute changes.

File: tests/rt_35d.conf (hunk 10 above)
Comment (DeniseWorthen) [reply tests/rt_35d.conf]: That sounds fine. There is a catch-all issue #1756 it could be part of.

**Comment by DeniseWorthen** [comment]
I always use this type of command to create new compiles when debugging and running in sandboxes

```
./compile.sh hera.intel '-DAPP=S2SW -DDEBUG=ON -DCCPP_SUITES=FV3_GFS_v17_coupled_p8' '' YES NO 2>&1 | tee compile.log
```

This now gives me

```
Lmod has detected the following error: The following module(s) are unknown: "ufs_hera.intel.YES"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "ufs_hera.intel.YES"

Also make sure that all modulefiles written in TCL start with the string #%Module
```

What would be the new format?

**Comment by BrianCurtis-NOAA** [comment]
> What would be the new format?

MACHINE_ID=$1
MAKE_OPT=${2:-}
COMPILE_NR=${3:+_$3}
RT_COMPILER=${4:-intel}
clean_before=${5:-YES}
clean_after=${6:-YES}

so `./compile.sh hera '-DAPP=S2SW -DDEBUG=ON -DCCPP_SUITES=FV3_GFS_v17_coupled_p8' 1 intel YES NO`

**Comment by DeniseWorthen** [comment]
Ok, so I often also name the executable so I can have multiple compiles for different tests. To do that I can 

```
./compile.sh hera '-DAPP=S2SW -DDEBUG=ON -DCCPP_SUITES=FV3_GFS_v17_coupled_p8' s2sw.db intel YES NO 2>&1 | tee compile.s2sw.db.log
```

**Comment by BrianCurtis-NOAA** [comment]
I ran comparisons on Acorn between the previous baseline and the current (new) baselines using the script previously posted in this PR, with the same results. All tests identical to old baselines.
[comparisons.txt](https://github.com/ufs-community/ufs-weather-model/files/11574628/comparisons.txt)

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Job: RT
[RT] Repo location: /scratch1/NCEPDEV/nems/role.epic/autort/pr/1321449518/20230526124216/ufs-weather-model
Please make changes and add the following label back: hera-RT

File: tests/rt_35d.conf (hunk 10 above)
Comment (DusanJovic-NOAA) [reply tests/rt_35d.conf]: > What should we do (if anything) about the fv3 in the compile line? Does this just name the executable? I really don't know what it does @DusanJovic-NOAA

No, it does not name the executable. It has the same meaning as the string in the 4th column in RUN entries. If rt.sh is running in create baselines mode, and if the 4th column is (currently) 'fv3' it will run the COMPILE step. That's all, nothing to do with the executable name.

The reason this exists is when we implemented rt.sh originally NEMS had multiple models, gfs, nmm, fim etc. These were completely different models, so very often code changes will be local to one particular model and if new baselines are required it made sense to create them only for that model only. Back then the '-c' flag had an additional option which would specify the model. For example:

```
./rt.sh -c nmm
```
would create new baselines only for the NMM model and copy current baselines for other two models.

Now that we have only one model that option is redundant and we run all COMPILE steps all the time, and that's why each COMPILE line has that 'fv3' in the 4th column. We can keep it for consistency with RUN entries, but the 'fv3' string can be changed. Or we can simply remove it.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Job: BL
Repo location: /scratch1/NCEPDEV/nems/role.epic/autort/pr/1321449518/20230526134812/ufs-weather-model
BL_DATE not found in rt.sh.Please manually edit rt.sh with BL_DATE={bldate}
Please make changes and add the following label back: hera-BL

**Comment by BrianCurtis-NOAA** [comment]
moving BL_DATE to bl_date.conf is needing fixes in autort, we're hashing them out right now. Expect maybe one or two more failures while we iron that out.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Job: BL
Repo location: /scratch1/NCEPDEV/nems/role.epic/autort/pr/1321449518/20230526144551/ufs-weather-model
BL_DATE not found in rt.sh.Please manually edit rt.sh with BL_DATE={bldate}
Please make changes and add the following label back: hera-BL

**Comment by zach1221** [comment]
@BrianCurtis-NOAA so below are the changes I made to the Dockerfile. 
Added "ENV ACCNR=$accnr"  to line 18
and "-a $accnr" to the end of line 21
image

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: hera
Job: BL
Repo location: /scratch1/NCEPDEV/nems/role.epic/autort/pr/1321449518/20230526172842/ufs-weather-model
Please manually delete: /scratch1/NCEPDEV/stmp2/role.epic/FV3_RT/rt_119418
Please make changes and add the following label back: hera-BL

**Comment by zach1221** [comment]
@BrianCurtis-NOAA please edit line 18 in the Dockerfile to the below.
ENV ACCNR=nems

Everything else can stay as is.

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Job: BL
Repo location: /glade/scratch/epicufsrt/autort/jenkins/autort/pr/1321449518/20230526140614/ufs-weather-model
BL_DATE not found in rt.sh.Please manually edit rt.sh with BL_DATE={bldate}
Please make changes and add the following label back: cheyenne-BL

**Comment by zach1221** [comment]
Jenkins pipeline logs attached. ORTs passed.
[ORT Pipeline #194 Console [Jenkins].pdf](https://github.com/ufs-community/ufs-weather-model/files/11580983/ORT.Pipeline.194.Console.Jenkins.pdf)

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Job: BL
Repo location: /lfs4/HFIP/hfv3gfs/role.epic/autort/pr/1321449518/20230530164534/ufs-weather-model
BL_DATE not found in rt.sh.Please manually edit rt.sh with BL_DATE={bldate}
Please make changes and add the following label back: jet-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Job: BL
Repo location: /lfs4/HFIP/hfv3gfs/role.epic/autort/pr/1321449518/20230530174535/ufs-weather-model
Please manually delete: /lfs4/HFIP/hfv3gfs/role.epic/RT_RUNDIRS/role.epic/FV3_RT/rt_237047
/lfs4/HFIP/hfv3gfs/role.epic/RT/NEMSfv3gfs/develop-20230525
 Exists already. It should not yet. Please delete.
Please make changes and add the following label back: jet-BL

**Comment by BrianCurtis-NOAA** [comment]
***Automated RT Failure Notification***
Machine: jet
Job: BL
Repo location: /lfs4/HFIP/hfv3gfs/role.epic/autort/pr/1321449518/20230530211034/ufs-weather-model
Please manually delete: /lfs4/HFIP/hfv3gfs/role.epic/RT_RUNDIRS/role.epic/FV3_RT/rt_251514
Please make changes and add the following label back: jet-BL

File: tests/compile.sh [hunk 11]
```diff
@@ -24,16 +24,17 @@ fi
...
   echo Valid MACHINE_IDs:
   echo $( ls -1 ../cmake/configure_* | sed s:.*configure_::g | sed s:\.cmake:: ) | fold -sw72
   exit 1
 else
   MACHINE_ID=$1
   MAKE_OPT=${2:-}
   COMPILE_NR=${3:+_$3}
-  clean_before=${4:-YES}
-  clean_after=${5:-YES}
+  RT_COMPILER=${4:-intel}
```
Comment (junwang-noaa) [inline tests/compile.sh:35]: RT_COMPILER is ${5:-YES}? Please see line 27.

Comment (BrianCurtis-NOAA) [reply tests/compile.sh:35]: Thanks! Addressed with https://github.com/ufs-community/ufs-weather-model/pull/1718/commits/e7e3ec23cb1619450c4e361cf099787bceac5166

**Comment by zach1221** [comment]
@BrianCurtis-NOAA update on Orion. All the RTs are complete except for a failure with regional_atmaq_faster case. The rest are good. However, it looks like Orion is down currently so I'm unable to troubleshoot the failed case at the moment. The baselines were created and copied over fine on Orion, so it may be a good idea to skip the logs on for this HPC, if Orion remains down the rest of the day. @jkbk2004 fyi.

**Comment by jkbk2004** [comment]
> @BrianCurtis-NOAA update on Orion. All the RTs are complete except for a failure with regional_atmaq_faster case. The rest are good. However, it looks like Orion is down currently so I'm unable to troubleshoot the failed case at the moment. The baselines were created and copied over fine on Orion, so it may be a good idea to skip the logs on for this HPC, if Orion remains down the rest of the day. @jkbk2004 fyi.

@zach1221 Sounds like unexpected orion network issue. all orion baselines were created ok, right? I agree we may move on to merge unless orion is back online next a few hours.

**Comment by zach1221** [comment]
Yes, the baselines created fine. I'm not certain why that last regional_atmaq case failed in the RT/matching. As soon as I started to dig through the logs I was kicked out.

**Comment by BrianCurtis-NOAA** [comment]
I think its justified to skip Orion, but I recommend creating an issue to check why once Orion is back and addressing anything in that issue.

**Comment by zach1221** [comment]
@BrianCurtis-NOAA I agree. I'll get the issue created now, so that when Orion is back up I can ensure everything is tracked and cleaned up.

**Review by jkbk2004 — DISMISSED** [review]

**Review by sadeghitabas — DISMISSED** [review]

**Comment by zach1221** [comment]
Ok, we have approvals. I'm proceeding with merging.

**Comment by zach1221** [comment]
Looks like Orion just came back up. Checking that last atmaq test.

**Comment by zach1221** [comment]
regional_atmaq_faster passed on Orion, after extending the wallclock, so looks like it was just timing out. I'll push the orion RT logs and then merge.

**Review by jkbk2004 — APPROVED** [review]

**Review by FernandoAndrade-NOAA — APPROVED** [review]
