### PR TITLE
Fix ugwpv1 timing / remove some extended WLCLK cases & PR#2491 Updates from the jedi model convention

### LINKED ISSUE #2496: SEDI_SEMI incorrectly halves DT_ATMOS in tests/default_vars.sh
## Description

Currently in [default_vars.sh#L1178](https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/default_vars.sh#L1178):
`if [[ ${SEDI_SEMI} = .true. ]]; then export DT_ATMOS=$((DT_ATMOS/2)); fi`

Presumably, semi-Lagrangian method should have a longer timestep, not shorter. 
This also conflicts with what's in global-workflow [config.fcst#L210-L212](https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/gfs/config.fcst#L210-L212)
```
export dt_inner=$((DELTIM/2))
export sedi_semi=.true.
if [[ "${sedi_semi}" == .true. ]]; then export dt_inner=${DELTIM} ; fi
```
In default_vars, maybe the corresponding implementation is:
`if [[ ${SEDI_SEMI} = .false. ]]; then export DT_INNER=$((DT_ATMOS/2)); fi`

This bug would increase test wallclock for tests calling export_ugwpv1() @dpsarmie @BrianCurtis-NOAA @DeniseWorthen @junwang-noaa @jkbk2004
Any adjusted k_split, n_split we're running should be revisited too

### PR DESCRIPTION
**Pull request by dpsarmie**
## Commit Queue Requirements:
- [X] Fill out all sections of this template.
- [ ] All sub component pull requests have been reviewed by their code managers.
- [X] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:
This PR will fix an issue with the `export_ugwpv1()` function in **default_vars.sh**. The `sedi_semi` check was inverted. This should now align with the GW spec.
Changing this timestep also required some changes in the `K_SPILT` and `N_SPLIT` variables for select regression tests.
These fixes also reduced the runtime of some regression tests. Those tests had the custom changes to `WLCLK` removed since they are running under the 30 min limit.
A new namelist variable was also added (`XR_CNVCLD`) to more closely align with the GW namelist needs.

### Commit Message:

```
* UFSWM - Fix sedi_semi logic issue in export_ugwpv1() and change affected RTs for more stable and quicker runtimes.
* UFSWM - Alias update JEDI-related variables inside the fd_ufs.yaml file.
```

### Priority:
* Normal

### UFSWM:
* Closes #2496 
* Closes #2491 

### Sub component Pull Requests:
* None

### UFSWM Blocking Dependencies:
* None

---
### Regression Test Changes (Please commit test_changes.list):
* PR Updates/Changes Baselines.

### Input data Changes:
* None.

### Library Changes/Upgrades:
* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] GaeaC6
  - [x] GaeaC6
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- [ ] CI
- [x] opnReqTest (complete task if unnecessary)

### CODE REVIEW

File: tests/default_vars.sh [hunk 1]
```diff
@@ -1187,7 +1188,7 @@ export_ugwpv1() {
   esac
 
   if [[ ${DO_GSL_DRAG_SS} = .true. ]]; then export CDMBGWD=${CDMBGWD_GSL}; fi
-  if [[ ${SEDI_SEMI} = .true. ]]; then export DT_ATMOS=$((DT_ATMOS/2)); fi
+  if [[ ${SEDI_SEMI} = .false. ]]; then export DT_ATMOS=$((DT_ATMOS/2)); fi
```
Comment (NickSzapiro-NOAA) [inline tests/default_vars.sh]: I think DT_ATMOS stays the same and DT_INNER changes:
`if [[ ${SEDI_SEMI} = .false. ]]; then export DT_INNER=$((DT_ATMOS/2)); fi`

dt_inner in ccpp is for subcycling in the Thompson MP scheme

Comment (NickSzapiro-NOAA) [reply tests/default_vars.sh]: I think SEDI_SEMI=.true. for all RTs that get here so there's no need to re-test anything you've done

Comment (dpsarmie) [reply tests/default_vars.sh]: You're right, got it fixed and it doesn't affect any of the RTs. Leaving the check in even if it doesn't get triggered for GW fidelity and reference.

**Comment by dpsarmie** [comment]
Changes from PR #2491 have been added

File: tests/logs/RegressionTests_hera.log [hunk 2]
```diff
@@ -26,391 +26,446 @@ The first time is for the full script (prep+run+finalize).
...
+PASS -- TEST 'rrfs_v1beta_intel' [09:45, 07:44](1080 MB)
+PASS -- TEST 'rrfs_v1nssl_intel' [11:31, 09:39](1961 MB)
+PASS -- TEST 'rrfs_v1nssl_nohailnoccn_intel' [11:30, 09:21](2048 MB)
+
+PASS -- COMPILE 'csawmg_intel' [11:12, 10:06]
+PASS -- TEST 'control_csawmg_intel' [08:40, 06:11](1000 MB)
+PASS -- TEST 'control_ras_intel' [05:24, 03:19](721 MB)
+
+PASS -- COMPILE 'wam_intel' [11:12, 10:01] ( 1 remarks )
+FAILED: TEST TIMED OUT -- TEST 'control_wam_intel' [, ]( MB)
```
Comment (dpsarmie) [inline tests/logs/RegressionTests_hera.log:156]: control_wam still timing out? I've run this branch a couple of times on Hera and it's running in under 12 minutes.  Baselines for this test haven't changed so I don't know what could be the problem. Do you have the logs somewhere for this test?

Comment (jkbk2004) [reply tests/logs/RegressionTests_hera.log:156]: I bumped up WLCLK to 45 on hera. It looks like random behavior with busy queue. We are fine once actual core hour runtime is ok.

**Comment by jkbk2004** [comment]
Hera disk quota issue is encountered on epic workspace. We will skip ORT runs.

**Review by FernandoAndrade-NOAA — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]
